### ISSUE TITLE
Anonymous figure and default-image-extensions don't work together

### ISSUE THREAD

**Issue by lcnhb** [quarto-dev/quarto-cli#2877] opened 2022-10-16 16:32 UTC
### Bug description

When I include an anonymous figure without extension i.e. `![](test)`, and I have the default extensions set for pdf and html output in a book I get the following error 

```
Error running filter /opt/quarto/share/filters/quarto-post/quarto-post.lua:
/opt/quarto/share/filters/quarto-post/quarto-post.lua:2277: attempt to index a nil value (field 'attr')
stack traceback:
        /opt/quarto/share/filters/quarto-post/quarto-post.lua:1119: in function </opt/quarto/share/filters/quarto-post/quarto-post.lua:1113>
```

my _quarto.yml has the following shape:

```
project:
  type: book

book:
  title: "mwebib"
  author: "Jane Doe"
  date: "10/10/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    cite-method: citeproc
    default-image-extension:  svg
  pdf:
    documentclass: scrreprt
    cite-method: biblatex
    default-image-extension:  tex
```

**Comment by lcnhb** [comment] 2022-10-16 16:51
It seems it is specific to tex as pdf extensions..

**Comment by cscheid** [comment] 2022-10-18 16:54
Can you share a minimal full example we can test ourselves?

**Comment by julianmatthewman** [comment] 2022-10-20 11:43
Hi,

I encountered a very similar error, where I was able to render to HTML but not Word or PDF:

> Error running filter /Applications/quarto/share/filters/quarto-init/quarto-init.lua:
> ...cations/quarto/share/filters/quarto-init/quarto-init.lua:240: attempt to index a nil value (global 'text')
> stack traceback:
> 	...cations/quarto/share/filters/quarto-init/quarto-init.lua:10: in local 'fn'
> 	...cations/quarto/share/filters/quarto-init/quarto-init.lua:548: in function <...cations/quarto/share/filters/quarto-init/quarto-init.lua:542>

It also related to figure paths, however not to whether the figure was named or not; in my case I was referring to a figure in a subfolder in a .qmd file that was itsself in a different subfolder. Below a minimal example:

Folder structure:
```
├ quarto.yml
├ index.qmd
├ figures/
├── image.png
├ documents/
├── doc_with_figure.qmd
```

quarto.yml:
```
project:
  type: book
  execute-dir: project

book:
  chapters:
    - index.qmd
    - documents/doc_with_figure.qmd

format:
  html:
    theme: cosmo
  docx:
    toc: true
  pdf:
    toc: true

```

In doc_with_figure.qmd:
`![](/figures/image.png)` renders correctly to HTML but not to PDF or Word.
`![](../figures/image.png)` renders correctly to all formats.

So the `execute-dir: project` option only seems to be working for the HTML format but not PDF or Word.

**Comment by cscheid** [comment] 2022-10-20 15:31
@julianmatthewman We need the contents of those files in order to be able to attempt to reproduce the issue. Can you share the repository on github or a zip archive? Thanks.

**Comment by julianmatthewman** [comment] 2022-10-20 15:34
Sure, here is a zip archive
[lua_filter_error_reprex.zip](https://github.com/quarto-dev/quarto-cli/files/9831638/lua_filter_error_reprex.zip)

**Comment by deckold** [comment] 2022-10-26 15:36
I seem to be getting the original (`attempt to index a nil value (field 'attr')`) error for any .tex figure.

MWE:
example.qmd:
```
---
title: this is a test
format:
  pdf: default
---

figure should go below here

![](fig.tex)
```
fig.tex:
```
\begin{tikzpicture}
\draw (0,0) -- (1,1);
\end{tikzpicture}
```

```
$ quarto render example.qmd --to pdf
pandoc 
  to: latex
  output-file: example.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: this is a test
  
Error running filter /opt/quarto/quarto-1.2.242/share/filters/quarto-post/quarto-post.lua:
...quarto-1.2.242/share/filters/quarto-post/quarto-post.lua:2486: attempt to index a nil value (field 'attr')
stack traceback:
        ...quarto-1.2.242/share/filters/quarto-post/quarto-post.lua:1293: in function <...quarto-1.2.242/share/filters/quarto-post/quarto-post.lua:1287>
```

If I manually compile the tikz figure first and use the resulting pdf in `![](fig.pdf)` it works, and if I directly use the LaTeX in the .qmd file like `\input{fig.tex}`, it also works.
Am I missing something on how to include tikz figures in Quarto?

**Comment by cscheid** [comment] 2023-03-07 23:51
I can't reproduce this error on the latest prerelease version (unzipping the repro and rendering worked without a problem). I'm going to go ahead and close this one, but if the error persists, please comment and reopen.

**Closed by cscheid** 2023-03-07 23:51 UTC
Labels: bug, need-repro
