### ISSUE TITLE
Julia Engine Book Project Scope Fail

### ISSUE THREAD

**Issue by stefanbringuier** [quarto-dev/quarto-cli#9499] opened 2024-04-26 19:58 UTC
### Bug description

In my book project with folders containing `.qmd` files, even when I set

```yml
engine: julia
execute:
  cache: true
  freeze: auto
  eval: true
  echo: true
  output: true
```

in the `_quarto.yml` file, It appears the project ignores the the `engine` setting and trys to use `Jupyter` throught `IJulia`.

```
Starting julia-1.10 kernel...ERROR: LoadError: ArgumentError: Package IJulia not found in current path.
- Run `import Pkg; Pkg.add("IJulia")` to install the IJulia package.
```

I've also tried to add a `_metadata.yml` file to my folders with:

```yml
engine: julia
execute: 
  exeflags: ["--project=@."]
```

but still get the same error.

The only think that works is if for each `.qmd` document file I include:

```
---
engine: julia
---
```

But this is cumbersome.

### Expected behavior

Should use `julia` engine via [QuartoNotebookRunner.jl](https://github.com/PumasAI/QuartoNotebookRunner.jl)

### Actual behavior

Uses `IJulia` and because my `Project.toml` doesn't include `IJulia` quarto fails.

### Your environment

- IDE: VSCode 1.86.2
- OS: Ubuntu 22.04.3 LTS
- Quarto: 1.5.30
- Julia: 1.10.2

### Quarto check output

```bash
Quarto 1.5.30
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.13: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.30
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/stefanbringuier/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /bin/python3
      Jupyter: 5.7.2
      Kernels: python3, julia-1.10, julia-1.9

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
      
```

**Comment by mcanouil** [comment] 2024-04-26 20:17
Duplicate of https://github.com/quarto-dev/quarto-cli/issues/3157

**Comment by mcanouil** [comment] 2024-04-26 20:17
Thanks for the report.
Currently, engine cannot be set globally.

- https://github.com/quarto-dev/quarto-cli/issues/3157

**Closed** 2024-04-26 20:17 UTC
Labels: duplicate

**Comment by stefanbringuier** [comment] 2024-04-26 20:22
Thanks, for the related issue link. Hope #3157 gets addressed.
