### ISSUE TITLE
Unable to resolve crossref in docx tables (works for html/pdf)

### ISSUE THREAD

**Issue by dmenne** [quarto-dev/quarto-cli#3719] opened 2022-12-20 15:11 UTC
### Bug description

quarto 1.3.26, Windows

Cross-referencing tables works for html/docx/pdf when I use `knitr::kable`

It fails for docx (only) for `flextable` and `gt`. `flextable` cross-referencing works in `rmarkdown/knitr` 

```
WARNING: Unable to resolve crossref @tbl-mtcars
WARNING: Unable to resolve crossref @tbl-gtcars
```

Similar issues: #1710, #3340

As far I understand #1556, this should work with gh?

````

---
title: "Flextable"
format: 
  docx
---

## Page references with flextable 

```{r}
#| echo: FALSE
#| message:  FALSE
#| label: tbl-mtcars
#| tbl-cap: "Motorcars flextable"

mt_head = head(head(mtcars))[,1:5]
flextable::flextable(mt_head)
```


For example, see @tbl-mtcars (does not work for docx, ok for html/pdf)

## Page references with kable

```{r}
#| echo: FALSE
#| message:  FALSE
#| label: tbl-kablecars
#| tbl-cap: "Motorcars kable"
knitr::kable(mt_head)
```

For example, see @tbl-kablecars (works for all)

Yihui can do it....

## Page references with gt

```{r}
#| echo: FALSE
#| message:  FALSE
#| label: tbl-gtcars
#| tbl-cap: "Motorcars gt chunk captions"
library(gt)

mt_head %>% 
  gt() %>% 
  tab_caption(caption = "Motorcars gt code captions")# also ok for html/pdf
  
```


For example, see @tbl-gtcars (does not work for docx, ok for html/pdf)

````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2022-12-21 05:02
Thanks for the report. This is effectively a duplicate of those issues you pointed out. I'll be working on this starting Jan 2023.

**Closed by cscheid** 2022-12-21 05:02 UTC
Labels: duplicate
