### ISSUE TITLE
Issue wtih table numbering between pdf and html / issue when table has empty cells

### ISSUE THREAD

**Issue by Xinenomine** [quarto-dev/quarto-cli#10438] opened 2024-07-31 20:58 UTC
### Bug description

Hello, 

I still have the exact same problem when using subtables… I have the right numbering a) and b) in html but a) and c) in pdf. 
Thank you very much for the help. I searched on the web for similar issues and I couldn’t solve it.  I also have issues when I have empty cells, all the cells are shifted in html and pdf as well (see below). Thank you very much !!!!
````qmd 

---
format:
  html: default
  typst: default
---


The @tbl-connectors summarizes the different information developped in the previous section in a more concise way for reference. 

see @tbl-connectors1 and @tbl-connectors2

::: {#tbl-connectors layout-ncol=1}

 Pin # | Instrumentation  | Instr. # | Pin pairs | R ($\Omega$) |
 ----- | :--------------- | -------- | --------- | ------------ |
 1,2   | Heater HTR1      | 9        | 1-2       | 7.3          |
 3,4   | Heater HTR2      | 10       | 3-4       | 4.1          |

: Summary of the pins available and the associated instruments {#tbl-connectors1 tbl-colwidths="[20,35, 25, 25, 25]"}
 
 Pin # | Instrumentation  | Instr. # | Pin pairs | R ($\Omega$) |
 ----- | :--------------- | -------- | --------- | ------------ |
 1,4   | Bottom CLTS      | 12       | -         | -            |
 5,8   | CLTS top sample  | 6        | 5-6       | 111.9        |

: Summary of the pins available and the associated instruments {#tbl-connectors2 tbl-colwidths="[20,35, 25, 25, 25]"}


Summary of the pins available for each instrumentation connected to the connector TC1 (top) and TC2 (bottom)
:::

![image](https://github.com/user-attachments/assets/404b5ed9-edaa-4df5-b40f-bca7a95d7baf)

 Pin # | Instrumentation  | Instr. # | Pin pairs | R ($\Omega$) |
 ----- | :--------------- | -------- | --------- | ------------ |
 1,4   | Bottom CLTS      | 12       | -         | -            |
 5,8   | CLTS top sample  | 6        | 5-6       | 111.9        |
       |                  | 6        | 6-7       | 111.9        |
````

### Expected behavior

in pdf : table (a) and table (b)
in html: table (a) and table (b)

### Actual behavior

![image](https://github.com/user-attachments/assets/e65eb935-ffed-4333-ae6d-cde89e2997b0)

![image](https://github.com/user-attachments/assets/77d07dde-cfa3-4664-945b-af2ad66b8f53)

![image](https://github.com/user-attachments/assets/e86563aa-0558-4553-8345-61a40e6218db)

### Your environment

vscode
quarto 1.5.52

### Quarto check output

Quarto 1.5.52
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.52
      Path: C:\Users\mynane\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.4
      Path: C:/Users/myname/AppData/Local/Programs/Python/Python312/python.exe
      Jupyter: 5.7.2
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.4.1
      Path: C:/PROGRA~1/R/R-44~1.1
      LibPaths:
        - C:/Users/myname/AppData/Local/R/win-library/4.4
        - C:/Program Files/R/R-4.4.1/library
      knitr: 1.47
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment] 2024-07-31 21:12
Are all the options you set really needed to reproduce the issue?

**Comment by Xinenomine** [comment] 2024-07-31 21:38
Hello, 

I corrected my bug report, sorry and thanks !

**Comment by mcanouil** [comment] 2024-07-31 21:44
It has nothing to do with empty cells.

<table>
<tr><th>Input</th><th>Output</th></tr>
<tr><td>

````qmd
---
format: typst
---

::: {#tbl-main layout-ncol=1}

| A | B |
|---|---|
| 1 | 2 |
| 3 | 4 |

: Caption 1 {#tbl-one}
 
| 1 | 2 |
|---|---|
| A | B |
| C | D |

: Caption 1 {#tbl-two}

Main caption
:::
````

</td><td>

<img width="303" alt="image" src="https://github.com/user-attachments/assets/a434741b-3a62-4fe2-ac4d-877ec9f769c1">

</td></tr>
</table>

**Comment by mcanouil** [comment] 2024-07-31 21:56
That's a regression compared to v1.4.450.

v1.5.38 is the first faulty release.

**Comment by Xinenomine** [comment] 2024-07-31 21:58
Hello,

Yes indeed sorry if I made myself unclear. I have an issue with numbering
the reference when using subtables AND when I have empty cells, the columns
are shifted.

I hope it helps

Thank you
Julien

**Comment by mcanouil** [comment] 2024-07-31 22:04
Please file a different issue or open a different discussion.
it makes it hard to track down efficiently several unrelated issues at the same time.

**Comment by mcanouil** [comment] 2024-07-31 22:13
I bisected this regression to 4b185d0c936a82a0888d6d31e288bffe889c4ede

**Comment by cscheid** [comment] 2024-08-16 18:16
This is at least in part a Pandoc bug; it's impossible to have Pandoc emit tables without it wrapping it in a separate crossref environment:

```
$ pandoc -f markdown -t typst
| A | B |
|---|---|
| 1 | 2 |
| 3 | 4 |

: Caption 1
^D
#figure(
  align(center)[#table(
    columns: 2,
    align: (auto,auto,),
    table.header([A], [B],),
    table.hline(),
    [1], [2],
    [3], [4],
  )]
  , caption: [Caption 1]
  , kind: table
  )
```

**Comment by cscheid** [comment] 2024-08-16 18:17
I think we're getting multiple counter bumps from this:

````
#quarto_super(
kind: 
"quarto-float-tbl"
, 
caption: 
[
Main caption
]
, 
label: 
<tbl-main>
, 
position: 
top
, 
supplement: 
"Table"
, 
subrefnumbering: 
"1a"
, 
subcapnumbering: 
"(a)"
, 
[
#grid(columns: 1, gutter: 2em,
  [
#block[
#figure([
#figure(
  align(center)[#table(
    columns: 2,
    align: (auto,auto,),
    table.header([A], [B],),
    table.hline(),
    [1], [2],
    [3], [4],
  )]
  , kind: table
  )

], caption: figure.caption(
position: top, 
[
Caption 1
]), 
kind: "quarto-float-tbl", 
supplement: "Table", 
)
<tbl-one>


]
],
  [
#block[
#figure([
#figure(
  align(center)[#table(
    columns: 2,
    align: (auto,auto,),
    table.header([1], [2],),
    table.hline(),
    [A], [B],
    [C], [D],
  )]
  , kind: table
  )

], caption: figure.caption(
position: top, 
[
Caption 2
]), 
kind: "quarto-float-tbl", 
supplement: "Table", 
)
<tbl-two>


]
],
)
]
)
````

**Comment by cscheid** [comment] 2024-08-16 18:19
This has been merged in Pandoc now, though (look who made the PR 🤣) so we have a chance to fix it here.

**Comment by cscheid** [comment] 2024-08-16 18:21
That fix is in Pandoc 3.3. So when we upgrade Quarto's Pandoc, we'll come back to this.

**Comment by TomBener** [comment] 2024-08-28 08:37
> That fix is in Pandoc 3.3. So when we upgrade Quarto's Pandoc, we'll come back to this.

I wonder do you have a timeline to upgrade Quarto's built-in Pandoc to 3.3? It would be great if I can use the OpenXML template for docx writer since [Pandoc 3.2.1](https://github.com/jgm/pandoc/releases/tag/3.2.1).

**Comment by mcanouil** [comment] 2024-08-28 09:54
Pandoc updates usually happen at the beginning of a new version because, it can break many things.
It might be a bit late in 1.6 development but for now since this issue is marked for 1.6 there is a chance it happens in the next few weeks but no guarantee there.

**Comment by cscheid** [comment] 2024-10-08 18:54
We can fix this now:

```
$ cat nofig.lua
function Table(t)
    t.classes:insert("typst:no-figure")
    return t
end
$ quarto pandoc -f markdown -t typst -L nofig.lua
| A | B |
|---|---|
| 1 | 2 |
| 3 | 4 |

: Caption 1
#table(
  columns: 2,
  align: (auto,auto,),
  table.header([A], [B],),
  table.hline(),
  [1], [2],
  [3], [4],
)
```

**Closed** 2024-10-08 19:48 UTC
Labels: bug, crossref, tables, typst
