### ISSUE TITLE
theorem-title not in its own HTML paragraph

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1926] opened 2022-08-16 16:13 UTC
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1925

<div type='discussions-op-text'>

<sup>Originally posted by **zeileis** August 16, 2022</sup>
When using one of the [theorem divs](https://quarto.org/docs/authoring/cross-references.html#theorems-and-proofs), then in the HTML output the corresponding "theorem-title" is sometimes in its own paragraph and sometimes not. Specifically, if the div just consists of a single paragraph, then the title is in a separate paragraph. Otherwise it is merged into the first paragraph.

As a concrete example consider:

```
::: {#exr-1}
Compute: 25 + 17.
:::

::: {#exr-2}
Let a = 25 and b = 17.

Compute: a + b.
:::
```

I have simply inserted the snippet above into the `intro.qmd` from the `mybook` demo (`quarto create-project mybook --type book`). This yields the following HTML output using quarto 1.0.38 with pandoc 2.17.1.1 on Debian GNU/Linux.

```
<div id="exr-1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 1.1 </strong></span></p>
<p>Compute: 25 + 17.</p>
</div>
<div id="exr-2" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 1.2 </strong></span>Let a = 25 and b = 17.</p>
<p>Compute: a + b.</p>
</div>
```

Rendered in a browser it looks like this:

![browser screenshot](https://i.imgur.com/GJWj8k8.png)

Note that the text of the first exercise starts in a new paragraph while the second exercise starts in the same paragraph as the title.

Is this difference by design? Can I somehow switch between these layouts? I would like a consistent layout, preferably with the theorem-title in its own paragraph.</div>

**Comment by jjallaire** [comment] 2022-08-16 16:14
I think we are automatically assuming that the first paragraph is the `name` of the theorem when we shouldn't be (we should really be looking for a header not a plain paragraph). Will investigate and hopefully resolve shortly.

**Comment by mcanouil** [comment] 2022-08-16 16:45
I think the issue is not about the name/label (if we are talking about the same thing), which in my understanding is a level 2 header.
The beahaviour is the same with/without the level 2 header.
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/8896044/184933963-1555dcb7-0c8f-438b-bb55-1ded3bf4def3.png">
See <https://github.com/quarto-dev/quarto-cli/discussions/1925#discussioncomment-3408096>

**Comment by cscheid** [comment] 2022-08-18 19:22
# Context

Let me first document the current state of affairs:

## Source

````
---
title: github-issue-1926
keep-md: true
---

::: {#exr-1}

Compute: 25 + 17.

:::

::: {#exr-2}

Let a = 25 and b = 17.

Compute: a + b.

:::

::: {#exr-3}

## A title

Compute: 25 + 17.

:::

::: {#exr-4}

## Another title

Let a = 25 and b = 17.

Compute: a + b.

:::
````

## HTML output

<img width="599" alt="image" src="https://user-images.githubusercontent.com/285675/185475852-6f8e06aa-2f99-4881-95a6-b903fd54cf3d.png">

## PDF output

<img width="858" alt="image" src="https://user-images.githubusercontent.com/285675/185475919-7a03a849-8f36-401c-b8a1-89790fb8c1ab.png">

## Docx output

<img width="457" alt="image" src="https://user-images.githubusercontent.com/285675/185475977-9489198e-8adf-4818-8095-6508fc7a7728.png">

# Discussion

There are two factors: whether or not we have titles, and whether or not we have multiple paragraphs. The output we're generating is consistent between HTML and Docx, but inconsistent with PDF. PDF output, specifically, always uses the exercise number and title as the beginning of the exercise description. If my understanding is correct, @jjallaire, you'd like to make it so that the HTML and Docx we emit follows the PDF output. This behavior would be consistent with cs/mathy textbooks and material I used in my previous academic life.

I agree with that goal, except that it also means changing the HTML behavior when there's a single paragraph and no title, which I think wasn't a source of complaints so far. I'm going to go ahead and do this, but I'm posting the discussion here just so we're all on the same page.

**Comment by jjallaire** [comment] 2022-08-18 19:31
If we are requiring a title, could we just have it not resolve and/or print  warning if there is a single paragraph and no title?

Also, should we require the using of a heading element to denote the title?

**Comment by cscheid** [comment] 2022-08-18 19:34
Do we want to require a title? The PDF version does not.

**Comment by cscheid** [comment] 2022-08-18 19:36
My proposal would simply make sure that the first paragraph is always merged to the paragraph that starts with "Exercise ...". If there's a title, that gets a typographically-distinct treatment, but also on the same paragraph. This would make all formats emit more-or-less consistent output.

**Comment by jjallaire** [comment] 2022-08-18 19:51
Okay that sounds right to me

**Closed** 2022-08-18 20:26 UTC
Labels: bug, open-pr
