### ISSUE TITLE
plotly plot does not show on a quarto pub

### ISSUE THREAD

**Issue by hbowley** [quarto-dev/quarto-cli#5989] opened 2023-06-21 02:35 UTC
### Bug description

I have a document that will show a plot when rendered to html but when I publish the document to quarto pub it disapears. I also noticed this issue is occurring on the quarto [website](https://quarto.org/docs/interactive/widgets/jupyter.html).  Is this just a browser issue (google chrome) with my computer or is the plot properly rendering on other browsers/computers. As seen in the photo there is a blank space where the plot should be. Any help would be appreciated. thanks.

![quarto](https://github.com/quarto-dev/quarto-cli/assets/54179736/5f88f92b-54d1-4137-a699-d93ee5815505)

**Comment by nomadiq** [comment] 2023-06-21 03:26
Problem you have is almost certainly because of problem with CDN that plotly.js is being served from right now. Hopefully fixed soon.

**Comment by cscheid** [comment] 2023-06-21 03:55
Yes - either what @nomadiq suggested or perhaps your network is blocking the request. I can't reproduce locally:

<img width="931" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/20db28f4-fe58-4515-b7bb-6f8bacfbed03">

I'm going to go ahead and close this one.

**Closed by cscheid** 2023-06-21 03:55 UTC
