### ISSUE TITLE
revealjs export pdf changes code block font

### ISSUE THREAD

**Issue by bcm0** [quarto-dev/quarto-cli#9699] opened 2024-05-16 15:48 UTC
### Bug description

Fonts in code blocks change and line highlighting is deleted

### Steps to reproduce

Visit https://quarto.org/docs/presentations/revealjs/demo/#/line-highlighting look at the font, press e key and scroll down again to see the changed font

### Expected behavior

The font should stay the same

### Actual behavior

The font changes

**Comment by mcanouil** [comment] 2024-05-16 19:06
I cannot reproduce any font change.

I don't thing there is a bug here even with the "different animation".

<img width="1512" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/c3c43e92-cc96-43a9-a80a-1f20ebe4f579">

<img width="1512" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/9eeb0482-65c0-4015-8df3-9b9a0ccf8f30">

**Comment by cderv** [comment] 2024-05-17 13:56
About the overwrite, this is an issue in Revealjs, fixed in 4.6 
* https://github.com/hakimel/reveal.js/issues/2867 	(https://github.com/hakimel/reveal.js/commit/edf6638065bf8c10a73e8823d437cc1de356b6aa)

We'll update to v5 for next release, so it should fix it. 

For the highlighting, Quarto does not use the same tool that reveal, so maybe we need to add some specific CSS rules to the print version. We'll see that after v5 update.

**Comment by cderv** [comment] 2024-08-29 15:15
This is now working with Quarto 1.6.9 which has Revealjs 5.1.0 update

**Closed by cderv** 2024-08-29 15:15 UTC
Labels: bug, upstream, revealjs
