### ISSUE TITLE
Margin content and margin page menu are mixed

### ISSUE THREAD

**Issue by wilcar** [quarto-dev/quarto-cli#5359] opened 2023-04-30 05:54 UTC
### Bug description

I am using version 1.4 of quarto (pre-release) to build a website.  I want to place different contents in the margin using the block :
   
     ::: {.column-margin}
    content
     :::

The content placed in the margin mixes with the menu of the page. Are the two compatible? If not, how do I deactivate the page menu (I don't see any indication in the documentation).

![image](https://user-images.githubusercontent.com/18226229/235337924-9c45b115-f713-4912-8fb2-e45922e3ade2.png)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment] 2023-04-30 10:50
Thank you for reporting! This was caused by an unrelated JS error that should be fixed in the latest build of Quarto 1.4 (the TOC is intended to 'collapse' when content would occlude it). Please feel free to re-open if you don't see this fixed after updating and I'll take another look!

**Closed by dragonstyle** 2023-04-30 10:50 UTC
Labels: bug
