### ISSUE TITLE
`quarto use` not documented in help

### ISSUE THREAD

**Issue by andrewpbray** [quarto-dev/quarto-cli#6678] opened 2023-09-01 16:35 UTC
### Bug description

All quarto CLI commands that I've seen documented at quarto.org have a (minimal) entry when you run `quarto --help`. The exception is `quarto use`, which I can't find. Note `quarto use template` is also found in the boilerplate `README.md` when you run `quarto create extension format:pdf` or the like. This was also raised on the discussion board #6306 .

### Steps to reproduce

Run `quarto --help`

### Expected behavior

The output of `quarto --help` would show `use` as an available command.

### Actual behavior

It is absent.

### Your environment

- IDE: RStudio 2023.09.0-daily+306
- OS: MacOS Monterey 12.6.8

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /Users/andrewbray/miniconda3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2023-09-01 16:40
Thanks for the report!

Closing as duplicate of:
- #5421

**Closed by mcanouil** 2023-09-01 16:40 UTC
Labels: bug
