### ISSUE TITLE
same source different hashes in _freeze/ files from different OS machines

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#3599] opened 2022-12-08 15:14 UTC
@cderv, can you check if the hashes are computed differently on windows and unix? I suspect something is doing newline normalization on our code.

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3597

<div type='discussions-op-text'>

<sup>Originally posted by **espinielli** December  8, 2022</sup>
Hi all,
I have set a CI workflow where Netlify published a quarto book as per [1] (we specifically use this for automatic preview on development branch [2][3]).
I am using the `freeze` option to get the code chunks pre-computed as required by the Netlify setup.
The issue is that pushes from the same source from different machine (mac and Windows) produce different hashes for the same qmd sources...and this means git merge clashes and difficulties to collaborate...
We use the same quarto version on the two OSs...

Here is an example of the clash:

```json
{
<<<<<<< HEAD
  "hash": "3575a3f572f6cd1d1124f5223cdfb566",
=======
  "hash": "ada4b65f5349f9aad31f8f739195a811",
>>>>>>> 67c67552f0aba0e2ab86d751957e6d3384296cc6
  "result": {
    "markdown": "\n# Welcome {-}\n\nThis is the website for __\"{{< meta title  >}}\"__.\n\n\nThe EUROCONTROL Business Cases team regularly refreshes the content and the underlying data\nin order to provide up-to-date information for the interested users.\n\n\n# About us\n\nEUROCONTROL Business Cases team is a dedicated team of experts supporting stakeholders to choose among different solutions and alternatives making use of the best available data. For more than 15 years, EUROCONTROL has been providing ATM decision makers with a wide range of  information enabling them to take rational long-term investment decisions.\n\n# Notice and Disclaimer {-}\n\nThe EUROCONTROL Business Cases team has made every effort to ensure that the information and analysis contained in this document are as accurate as possible. Only information from quoted sources has been used\nand information relating to named parties has been checked with the parties concerned. Despite these\nprecautions, should you find any errors or inconsistencies we would be grateful if you could please bring them to\nour attention. Our email address is [economics.business-cases@eurocontrol.int](mailto:economics.business-cases@eurocontrol.int)\n\nThis document is published by the EUROCONTROL Business Cases team in the interest of the exchange of\ninformation.\n\nInformation contained in this document may not be modified without prior written permission from the\nEUROCONTROL Business Cases team.\n\nThe views expressed herein do not necessarily respect the official views or policy of EUROCONTROL, which\nmakes no warranty, either implied or express, for the information contained in this document, neither does it\nassume any legal liability or responsibility for the accuracy, completeness or usefulness of this information.\n\n\n\n\n## Publications {-}\n\n| EUROCONTROL Headquarters\n| 96 Rue de la Fusée\n| B-1130 BRUSSELS\n| Tel: +32 (0)2 729 1152\n| Fax: +32 (0)2 729 5149\n| E-mail: publications@eurocontrol.int",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}
```

In a way it would be great to generate same hash from same source...

I initially thought this was due to line termination differences in the two OS architectures, so I forced line termination via `.gitattributes` to no avail unfortunately.

Has anybody had same/similar issues?

[1] <https://quarto.org/docs/publishing/netlify.html#rendering-on-netlify>
[2] <https://github.com/euctrl-pru/standard_inputs/pull/4>
[3] <https://deploy-preview-4--standard-inputs.netlify.app/></div>

**Comment by cderv** [comment] 2022-12-10 14:20
I did a quick test by creating a new quarto project and using `freeze: auto`. I did that with same content on Windows and on Linux WSL ubuntu 20. In both case I got the same hash in the freeze metadata. 

No difference in hash on windows. Not sure if line ending is changing some thing here. 


I'll try with the project from @espinielli

**Comment by mcanouil** [comment] 2022-12-13 22:31
Maybe of help, {targets} has (or had) a hash issue. The hash was not the same when computed on Windows or on Unix-based platform.
I don't have the discussion but I will find it back it case the issue is the same.

**Comment by espinielli** [comment] 2022-12-14 08:53
> I did a quick test by creating a new quarto project and using `freeze: auto`. I did that with same content on Windows and on Linux WSL ubuntu 20. In both case I got the same hash in the freeze metadata.
> 
> No difference in hash on windows. Not sure if line ending is changing some thing here.
> 
> I'll try with the project from @espinielli

I think it boils down to git having stored the files in, say, LF, then pulling on MS Windows.
When you render you get differences in the _freeze files maybe because now qmd are seen with CRLF, then re-rendered with CRLF, with the hash based then on different char totals?
(NOTE: pure guessing)

**Comment by cderv** [comment] 2022-12-15 11:21
> I initially thought this was due to line termination differences in the two OS architectures, so I forced line termination via .gitattributes to no avail unfortunately.

@espinielli did this worked for you ? 

I believe line ending will indeed change the MD5 hash used. 

@cscheid I can reproduce this when I am having file in Windows with CRLF endings, and on Linux with LF. The behavior on Windows with files shared on git repo will depend on some config like [`core.autocrlf true`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf)
For example, with our quarto-web project, if I explicitly render a file to recompute the freeze (example : `quarto render .\docs\authoring\article-layout.qmd --to html`), I'll get a change in HASH in `_freeze` even if I don't change the file. However, when doing `quarto render`, the freezed state is correctly used as not computation is done when rendering the all project because we have `freeze: true`. Switching to `quarto: auto` will indeed see the hash differently and recompute the files. 

if we want to be cross plateform, I think we need to handle this case and ignore the line ending maybe. Probably ignoring line ending somehow before computing the hash ? 
https://github.com/quarto-dev/quarto-cli/blob/60b919d2390097df027e739fb062fbd048dafe76/src/command/render/freeze.ts#L277-L279

> I suspect something is doing newline normalization on our code.

What did you mean by that by the way ? not sure to have grasp the full meaning. 

Some notes also : With same line ending (using LF on windows), the hash won't change in the freeze file but the `result` field in the JSON file will still have some difference, because of  `\r\n` introduced instead of `\n` only in fields like `include-in-header` that we save. 

This kind of line ending differences between Windows and Linux is hard to deal with. Freezing with Quarto is something stable on the same OS. This is like caching on github action, best to invalidate the cache on different OS usually.

**Comment by espinielli** [comment] 2022-12-24 19:48
An eventual solution to this issue is paramount for wider quarto adoption IMHO.

FYI I had quite some worries to introduce quarto & version control to my colleagues: they are not too used to resolve merge conflicts...so reducing "spurious" merge conflicts would greatly help

**Comment by kdheepak** [comment] 2023-04-18 17:25
I ran into this issue as well. One more thing that would help is when adding a .gitattributes file with the following content:

```
* text=auto eol=lf
```

I think when `quarto create` is run it should generate such a file. This will at the very least ensure that when collaborators clone the repo, they get `lf` line endings instead of `crlf`.

**Comment by mcanouil** [comment] 2023-04-18 17:59
I personally disagree with the fact that a tool has to handle/standardise user input.
If a user is using Git, he/she is able to ensure the committed files are using the right encoded, line sequence ending, etc., see <https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings>.

For instance, RStudio always force write things to `.gitignore` which is fine more most users but really annoying, especially when you have an "exclude everything but" kind of `.gitignore`.

**Comment by mcanouil** [comment] 2023-06-12 11:19
Thank you for using Quarto and reporting an issue!

Unfortunately, this issue is now considered stale because it has been opened since 14 days without providing a "working" reproducible example to help us investigate.
If you are still facing the issue, please review the ["Bug Reports" guide](https://quarto.org/bug-reports.html) on how to provide a fully reproducible example as a self-contained Quarto document or a link to a Git repository.
Without a reproducible example, it is unlikely that the issue will be addressed and thus will be closed.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

_Remove `stale` / `needs-repro` labels or this will be closed in 14 days._

**Comment by mcanouil** [comment] 2023-06-12 12:40
@kdheepak Thanks for the feedback, removing "needs-repro" and "stale".

**Closed** 2023-10-10 11:25 UTC
Labels: bug, windows
