### ISSUE TITLE
Proof Remark and Solution environment does not work when name provided anymore

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#7265] opened 2023-10-18 12:23 UTC
````markdown
---
title: "failing solution env"
format: 
  pdf: default
keep-md: true
---

### Solution

::: {.solution name="The solution"}
The solution
:::

````

````
Error running filter C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/resources/filters/main.lua:
...R/QUARTO~2/src/resources/filters/./crossref/theorems.lua:65: bad argument #2 to 'concat' (table expected, got string)
stack traceback:
	...R/QUARTO~2/src/resources/filters/./crossref/theorems.lua:65: in function <...R/QUARTO~2/src/resources/filters/./crossref/theorems.lua:35>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:78: in function <...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:68>
	(...tail calls...)
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:40: in local 'callback'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:54: in upvalue 'run_emulated_filter_chain'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:89: in function <..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:86>
stack traceback:
	...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:78: in function <...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:68>
	(...tail calls...)
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:40: in local 'callback'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:54: in upvalue 'run_emulated_filter_chain'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:89: in function <..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:86>
`````

This syntax is documented at https://quarto.org/docs/authoring/cross-references.html#theorems-and-proofs

> As with theorems you can optionally include a heading as the first element of the div (or a name attribute) to give the environment a caption for typesetting (this typically appears in parentheses after the environment title).

Same with other syntax which is adding a header inside 
````markdown
---
title: "failing solution env"
format: 
  pdf: default
keep-md: true
---

### Solution

::: {.solution}

# The solution

The solution
:::
````

This is with Quarto 1.4 latest pre-release on Windows.

**Comment by mcanouil** [comment] 2023-10-18 12:25
Duplicate of:
- #7259

**Comment by cderv** [comment] 2023-10-18 12:33
@cscheid this is failing at 
https://github.com/quarto-dev/quarto-cli/blob/4941bff8b441543ac5dd4324ae39f8657ede95f3/src/resources/filters/crossref/theorems.lua#L65C18-L65C18

I could try fix it, but I don't really this what this line means. `env` does not seem to exist and be used. `name` is a table so would require `stringify` to be added like this. However, it is already handle later with 
https://github.com/quarto-dev/quarto-cli/blob/4941bff8b441543ac5dd4324ae39f8657ede95f3/src/resources/filters/crossref/theorems.lua#L66-L68

So I guess it is not needed and creating the issue.

**Closed** 2023-10-19 15:43 UTC
Labels: bug, crossref, triaged-to, regression
