### ISSUE TITLE
Could not load translations for pl

### ISSUE THREAD

**Issue by jakub-jedrusiak** [quarto-dev/quarto-cli#5447] opened 2023-05-07 21:41 UTC
### Bug description

Using `lang: pl` causes Quarto to show this error:

```
[WARNING] Could not load translations for pl
  translations/pl.yaml: YAML parse exception at line 3, column 9:
  mapping values are not allowed in this context
[WARNING] The term Abstract has no translation defined.
```

Other languages work. `_language_pl.yml` seems fine.

```md
---
title: "Polish translation"
format: html
lang: pl
---
Zażółć gęsią jaźń.
```

`quarto check` output:
```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.1: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.36
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/lib64/R
      LibPaths:
        - /home/jakub/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/lib/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.1.25-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × 11th Gen Intel® Core™ i5-11300H @ 3.10GHz
Memory: 31.1 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics
Manufacturer: HP
Product Name: HP Pavilion Gaming Laptop 17-cd2xxx
System Version: Type1ProductConfigId

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment] 2023-05-07 22:12
I am closing this as a duplicate of #5197.
Note that the issue is an upstream issue with Pandoc itself.

Also note that this has been fixed in Pandoc (https://github.com/jgm/pandoc/issues/8787), thus the fix should propagate in Quarto 1.4.

**Closed by mcanouil** 2023-05-07 22:12 UTC
Labels: bug
