### ISSUE TITLE
quarto throws away traceback info stored in ipynb

### ISSUE THREAD

**Issue by jkrumbiegel** [quarto-dev/quarto-cli#9536] opened 2024-04-30 11:23 UTC
### Bug description

In qmd files using the jupyter backends for python or Julia, or using the new Julia engine, cells that error only display the `ename` and `evalue` fields from the data stored in the ipynb json.

For example

````
---
keep-ipynb: true
---

```{python}
#| error: true
"a" * "b"
```
````

gives, among other things, this json:

```json
{
   "cell_type": "code",
   "execution_count": 1,
   "id": "358bd35c",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "can't multiply sequence by non-int of type 'str'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124ma\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m*\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mb\u001b[39m\u001b[38;5;124m\"\u001b[39m\n",
      "\u001b[0;31mTypeError\u001b[0m: can't multiply sequence by non-int of type 'str'"
     ]
    }
   ],
   "source": [
    "#| error: true\n",
    "\"a\" * \"b\""
   ]
  }
```

The output that quarto generates looks like this:

<img width="845" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/22495855/9f61c1dc-49c4-4475-ab89-194d12deebf4">

On the other hand, converting the intermediate ipynb file to html with `jupyter-nbconvert python.quarto_ipynb --to html` gives this html, which uses the `traceback` field:

<img width="723" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/22495855/bf7473b7-e373-4b49-a780-3bbb5b244ca2">

Especially in Julia, while tracebacks can be long they are also very useful to understand what's going on. So I'd prefer that quarto used the `traceback` field and not just `ename` and `evalue` here.

### Your environment

MacOS 12.3

### Quarto check output

Quarto 1.5.31
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.13: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.31
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.03
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/krumbiegel/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2 (Conda)
      Path: /Users/krumbiegel/miniconda3/bin/python
      Jupyter: 5.5.0
      Kernels: julia-1.10, julia-1.8, julia-1.7, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment] 2024-04-30 12:21
> or using the new Julia engine

As far as I know, it does not use Jupyter. It is Julia native.

**Comment by jkrumbiegel** [comment] 2024-04-30 12:41
The native Julia backend uses ipynb as an intermediate format, it doesn't use a Jupyter kernel, that's correct.

**Comment by mcanouil** [comment] 2024-04-30 12:50
Thanks for the clarification!

**Comment by cscheid** [comment] 2024-04-30 15:53
@jkrumbiegel Thanks! We should improve this. Is there a place that gives the spec for error reporting fields so that when I do fix it, it's actually done right?

**Comment by MichaelHatherly** [comment] 2024-04-30 16:07
> Is there a place that gives the spec for error reporting fields so that when I do fix it, it's actually done right?

https://github.com/jupyter/nbformat/blob/60b6151fedcbdc9f137fb2d223eeb10c935a8378/nbformat/v4/nbformat.v4.schema.json#L367-L391 is what we followed when implementing it in QuartoNotebookRunner.jl.

**Comment by cscheid** [comment] 2024-04-30 20:00
I think I'm willing to live with the bad line numbering for now. Another small thing we'll need to do in the future is fix our ANSI code interpretations, because they play badly with theming.

This is good, default theme:

<img width="835" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/2fa86263-7cdf-49f4-bac0-20fe0bffc1f8">

This is _okay_, theme `darkly`:

<img width="832" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/d08c857b-d11d-4a65-81e0-3ce230784156">

This is less okay, theme `cyborg` (note the bad yellow highlighting):

<img width="848" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/563c346f-1ce3-4905-a3fd-11829029c07f">

**Comment by cscheid** [comment] 2024-04-30 20:02
We can't fix all of these, because Jupyter emits ANSI codes that have raw RGB values instead of "semantic" old-school ANSI colors that `ansiup` converts to classes (and so stand a chance of being appropriately themed).

God, I'm going to have to patch `ansiup`, aren't I.

**Comment by cscheid** [comment] 2024-04-30 21:34
Fixed on `main` now. We'll handle the theming challenges later.

**Closed** 2024-04-30 21:33 UTC
Labels: bug, jupyter

**Comment by tvatter** [comment] 2024-08-15 16:40
Oh shoot, I actually preferred the old behavior. Is there any way to make this change optional? When preparing slides for students, I find it useful to just show the final message :/

**Comment by tvatter** [comment] 2024-08-20 07:50
Hi and thanks a lot for your answer @cscheid. Editing the code cells in the intermediate output as appropriate seems like a lot of manual labor and kind of defeat the "reproducible" purpose, or am I missing something?

For the Lua filter, I didn't know that it was possible. It seems like exactly what I need. However, I've never used it, would you have a code pointer to select this specific type of code output that produces an error? It doesn't seem like there's anything specifically identifying such blocks.

**Comment by tvatter** [comment] 2024-08-20 07:58
Apologies, I just noticed the `.cell-output-error`. Alright, I'm going to give it a crack.

**Comment by tvatter** [comment] 2024-08-20 10:26
Alright, the following seems to work.

```lua
-- A Pandoc Lua filter to process .cell-output-error blocks and extract error name and value
function Div(el)
  -- Check if the div has the class 'cell-output-error'
  if el.classes:includes("cell-output-error") then 
    -- Iterate over the elements within the block
    for i, innerEl in ipairs(el.content) do
      -- Check if the element is a div with the class 'ansi-escaped-output'
      if innerEl.t == "Div" and innerEl.classes:includes("ansi-escaped-output") then
        -- Iterate over the elements within the 'ansi-escaped-output' div
        for j, block in ipairs(innerEl.content) do
            
            -- Extract the content of the block
            local content = block.text

            -- Reverse the content and extract the error message
            -- This is because there is no way to match the last occurence of a pattern in Lua
            local reversed_content = content:reverse()
            local reversed_match = reversed_content:match('>(.-)>"gf%-der%-isna"=ssalc naps<')
            if reversed_match then
                local modified_content = reversed_match:reverse()
                block.text = string.format('<pre><span class="ansi-red-fg">%s>', modified_content)
                -- print("Modified content: ", block.text)
            end
          end
      end
    end
  end
  return el
end
```

**Comment by cscheid** [comment] 2024-08-20 19:09
> ```lua
>             -- Reverse the content and extract the error message
>             -- This is because there is no way to match the last occurence of a pattern in Lua
>             local reversed_content = content:reverse()
>             local reversed_match = reversed_content:match('>(.-)>"gf%-der%-isna"=ssalc naps<')
> ```

This is an incredible hack 😂

**Comment by tvatter** [comment] 2024-09-02 09:33
Thank ChatGPT for this ;)
