### ISSUE TITLE
Repo Action URLs not compatible with Codeberg

### ISSUE THREAD

**Issue by jdcarls2** [quarto-dev/quarto-cli#7155] opened 2023-10-06 15:00 UTC
Recently discovered the `repo-actions`, and I'd like to use them. My site is on Codeberg, and the links are a bit different. Edit links are formatted `/_edit/<branch>/<file>` instead of `/edit/<branch>/<file>`, and source links are `/src/<branch>/<file>` instead of `/blob/<branch>/<file>`.

Most users are probably on GitHub or something like that, so it's fine as a default, but I'd like to be able to override those parts of the repo URLs by providing a template URL or some additional setting in the `_quarto.yml` file or something. I can see *where* the URLs are being hard-coded with the GitHub URL elements, but I'm out of my depth attempting to implement a change.

I imagine it would just be a couple new settings, and then the URL would be like this?

```ts
`${repoInfo.baseUrl}${some-new-setting}/${branch}/${repoInfo.path}${source}`
```

https://github.com/quarto-dev/quarto-cli/blob/59621bde94a34a238be9d6130b3edd7850f8cb38/src/project/types/website/website-navigation.ts#L740

also

https://github.com/quarto-dev/quarto-cli/blob/59621bde94a34a238be9d6130b3edd7850f8cb38/src/project/types/website/website-navigation.ts#L757

**Comment by mcanouil** [comment] 2023-10-06 17:40
This is a duplicate of:
- #5301

**Closed** 2023-10-06 17:40 UTC
Labels: duplicate, enhancement

**Comment by jdcarls2** [comment] 2023-10-06 18:08
Ah, thank you! I searched the issues for this first, but evidently didn't use the right terms.

**Comment by mcanouil** [comment] 2023-10-06 18:10
No worries.
Don't hesitate to upvote by adding a reaction on the first post 😉
