### ISSUE TITLE
Code annotation numbers are gradually indented

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#11185] opened 2024-10-24 09:45 UTC
### Bug description

Consider this example:
````
---
format: html
---

```{r}
#| echo: true
2 + # <1>
  2 + # <2>
  2 # <3>
```
1. Annotation 1.
2. Annotation 2.
3. Annotation 3.
````

In the code block, the code annotation numbers are gradually indented from the right border:

![Image](https://github.com/user-attachments/assets/d2bbec25-530f-4fb9-b8e8-c7746d47bf9c)

### Quarto check output

```
Quarto 1.6.28
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.6.28
      Path: C:\Users\au234616\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: C:/Users/au234616/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.2.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.4.1
      Path: C:/Users/au234616/AppData/Local/Programs/R/R-4.4.1
      LibPaths:
        - C:/Users/au234616/AppData/Local/R/win-library/4.4
        - C:/Users/au234616/AppData/Local/Programs/R/R-4.4.1/library
      knitr: 1.48.3
      rmarkdown: 2.28
```

**Comment by mcanouil** [comment] 2024-10-24 09:52
Thanks for the report.
Did you try the other formats? i.e., is it specific to `html`?

**Comment by snhansen** [comment] 2024-10-24 09:56
> Thanks for the report. Did you try the other formats? i.e., is it specific to `html`?

Just tested `format: pdf` and it shows fine, so seems specific to `html``.

**Comment by cderv** [comment] 2024-10-25 14:36
So I found what caused the problem. This is a side effect of some changes for brand support. These changes
https://github.com/quarto-dev/quarto-cli/compare/e51b07e680ab9de6608167c36bbf304296864c75...4702f46893915294acc4d4542f48ad77010462bf from 
- https://github.com/quarto-dev/quarto-cli/pull/11028

I'll find the problematic rule. Just making you aware @cscheid as you worked on those changes

**Comment by cderv** [comment] 2024-10-25 14:49
This is an effect of the font size change for code block 
https://github.com/quarto-dev/quarto-cli/blob/c96fe72cd714bd553f4eaa1b2b4cb6378c089584/src/resources/formats/html/bootstrap/_bootstrap-rules.scss#L2156

which previous was `inherit` from
https://github.com/quarto-dev/quarto-cli/blob/c96fe72cd714bd553f4eaa1b2b4cb6378c089584/src/resources/formats/html/bootstrap/dist/scss/_reboot.scss#L316

So this may be an issue in the way we are setting the rounded number, as no matter the font-size, they should be fixed on the right. 

This reproduce the issue with Quarto 1.5 
````markdown
---
format: 
  html: 
    theme: custom.scss
---

```{.r}
2 + # <1>
  2 + # <2>
  2 # <3>
```
1. Annotation 1.
2. Annotation 2.
3. Annotation 3.

````
with `custom.scss`
````scss
/*-- scss:defaults --*/

/*-- scss:rules --*/

pre code {
  font-size: 0.875em;
}
````

**Comment by cderv** [comment] 2024-10-25 15:02
I am thinking of removing, but I'll check why it was added (in 13a1aac04c9ed52640996749e6b2c5d6f2e82c10 it seems)

**Comment by cscheid** [comment] 2024-10-25 15:15
> It would also probably be best using `em` for size here

Just to warn you - the reason I moved `revealjs` away from `em` as a unit for size is that it doesn't play well with _other_ formats. Using `em` means that rules which apply multiple times accumulate. This was a problem when we needed to separate the rules for inline monospace and block monospace fonts, as well as including a default rule for both monospace fonts; using `em` caused the rules to trigger twice, and instead of overriding, we ended up accumulating the effect of both rules

**Closed** 2024-10-28 12:50 UTC
Labels: bug, code-annotation
