### ISSUE TITLE
Xarray/Dask html repr not rendered correctly

### ISSUE THREAD

**Issue by maawoo** [quarto-dev/quarto-cli#7095] opened 2023-09-30 10:55 UTC
### Bug description

[Xarray](https://xarray.dev/) is a widely used package in various scientific domains. It closely integrates with [Dask](https://www.dask.org/) to enable lazily evaluated arrays ([1](https://examples.dask.org/xarray.html#), [2](https://docs.xarray.dev/en/stable/user-guide/dask.html)) and work with datasets that normally don't fit into memory (e.g. Earth Observation satellite data). 

The structure of these Dask-backed Xarray objects are nicely rendered in Jupyter Notebooks: 

![image](https://github.com/quarto-dev/quarto-cli/assets/56583917/43e85ada-a0a2-4358-a095-747f0c2c429b)

Converting the notebook using `quarto render test.ipynb --to html` results in the following, almost correct, render: 

![image](https://github.com/quarto-dev/quarto-cli/assets/56583917/ef9c23f2-60b2-49cb-bd6e-322f2f611489)

The array structure is a key component in my opinion and is a very useful visualization when creating guides or documentation for beginners. 

### Steps to reproduce

Setup environment: 

```bash
mamba create -n test_env python=3.10
mamba activate test_env
mamba install xarray dask jupyter
```

Create and visualize dummy data in a Jupyter Notebook:
```python
import xarray as xr
import numpy as np
import dask.array as da
import pandas as pd

dask_array = da.random.random((10, 10, 10), chunks=(5, 5, 5))
x_coords = np.linspace(-5, 5, 10)
y_coords = np.linspace(-5, 5, 10)
time_coords = pd.date_range('2023-01-01', periods=10)
coords = {'x': x_coords, 'y': y_coords, 'time': time_coords}

data_array = xr.DataArray(dask_array, dims=['x', 'y', 'time'], coords=coords)
data_array
```

Render Jupyter Notebbok  with Quarto:

```bash
quarto render test.ipynb --to html
```

I've attached the `test.ipynb` and rendered `test.html` files here:
[xarray_dask_quarto_test.zip](https://github.com/quarto-dev/quarto-cli/files/12774480/xarray_dask_quarto_test.zip)

### Expected behavior

The Xarray/Dask HTML representation in Jupyter Notebooks is rendered correctly when integrating them into Quarto projects.

### Actual behavior

The key component of visualizing the array structure is not rendered correctly.

### Your environment

- IDE: VSCodium
- OS: AlmaLinux release 8.7 (Stone Smilodon)

Also tested on another Linux distribution, with another IDE (JupyterLab) and the newest Jupyter / JupyterLab versions. Same result. 

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /home/du23yow/opt/quarto-1.3.450/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /home/du23yow/micromamba/envs/sdc_env/bin/python
      Jupyter: 5.3.1
      Kernels: python3

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /usr/lib64/R
      LibPaths:
        - /usr/lib64/R/library
        - /usr/share/R/library
      knitr: (None)
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by cscheid** [comment] 2023-09-30 16:49
Can you run `quarto render test.ipynb --to ipynb -o test-output.ipynb` and share `test-output.ipynb` here? Thank you.

**Comment by maawoo** [comment] 2023-09-30 19:28
Sure, here it is: [test-output.zip](https://github.com/quarto-dev/quarto-cli/files/12775387/test-output.zip)

**Comment by cscheid** [comment] 2023-10-01 00:32
I'm looking at the output emitted by the xr.DataArray object, and that does not look like particularly well-formed HTML to me. I'll quote from your file here:

````
              "</div></div></li><li class='xr-section-item'><input id='section-7afb5e06-2c89-4eeb-8fa6-e8d65aee7a29' class='xr-section-summary-in' type='checkbox'  checked><label for='section-7afb5e06-2c89-4eeb-8fa6-e8d65aee7a29' class='xr-section-summary' >Coordinates: <span>(3)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><ul class='xr-var-list'><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>x</span></div><div class='xr-var-dims'>(x)</div><div class='xr-var-dtype'>float64</div><div class='xr-var-preview xr-preview'>-5.0 -3.889 -2.778 ... 3.889 5.0</div><input id='attrs-4a90ad46-62d5-406e-994a-acc4dc3b87d9' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-4a90ad46-62d5-406e-994a-acc4dc3b87d9' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-98e2e6a6-f1a8-4455-90db-3494f14fc0c0' class='xr-var-data-in' type='checkbox'><label for='data-98e2e6a6-f1a8-4455-90db-3494f14fc0c0' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([-5.      , -3.888889, -2.777778, -1.666667, -0.555556,  0.555556,\n",
              "        1.666667,  2.777778,  3.888889,  5.      ])</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>y</span></div><div class='xr-var-dims'>(y)</div><div class='xr-var-dtype'>float64</div><div class='xr-var-preview xr-preview'>-5.0 -3.889 -2.778 ... 3.889 5.0</div><input id='attrs-f6b87e1e-f9a8-44e6-b394-b92b526c8f8b' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-f6b87e1e-f9a8-44e6-b394-b92b526c8f8b' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-c2e4a108-c285-4f21-adc2-f3421eedd389' class='xr-var-data-in' type='checkbox'><label for='data-c2e4a108-c285-4f21-adc2-f3421eedd389' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([-5.      , -3.888889, -2.777778, -1.666667, -0.555556,  0.555556,\n",
              "        1.666667,  2.777778,  3.888889,  5.      ])</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>time</span></div><div class='xr-var-dims'>(time)</div><div class='xr-var-dtype'>datetime64[ns]</div><div class='xr-var-preview xr-preview'>2023-01-01 ... 2023-01-10</div><input id='attrs-33df2813-b939-43d6-a2d9-354a6d695cb4' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-33df2813-b939-43d6-a2d9-354a6d695cb4' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-72b6c849-c921-488b-8296-4c04767813d0' class='xr-var-data-in' type='checkbox'><label for='data-72b6c849-c921-488b-8296-4c04767813d0' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([&#x27;2023-01-01T00:00:00.000000000&#x27;, &#x27;2023-01-02T00:00:00.000000000&#x27;,\n",
              "       &#x27;2023-01-03T00:00:00.000000000&#x27;, &#x27;2023-01-04T00:00:00.000000000&#x27;,\n",
              "       &#x27;2023-01-05T00:00:00.000000000&#x27;, &#x27;2023-01-06T00:00:00.000000000&#x27;,\n",
              "       &#x27;2023-01-07T00:00:00.000000000&#x27;, &#x27;2023-01-08T00:00:00.000000000&#x27;,\n",
              "       &#x27;2023-01-09T00:00:00.000000000&#x27;, &#x27;2023-01-10T00:00:00.000000000&#x27;],\n",
              "      dtype=&#x27;datetime64[ns]&#x27;)</pre></div></li></ul></div></li><li class='xr-section-item'><input id='section-b556389a-31ef-452b-ab80-f8ff14d1fc23' class='xr-section-summary-in' type='checkbox'  ><label for='section-b556389a-31ef-452b-ab80-f8ff14d1fc23' class='xr-section-summary' >Indexes: <span>(3)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><ul class='xr-var-list'><li class='xr-var-item'><div class='xr-index-name'><div>x</div></div><div class='xr-index-preview'>PandasIndex</div><div></div><input id='index-8dc58739-86f5-47dd-83c2-ce99f87818b2' class='xr-index-data-in' type='checkbox'/><label for='index-8dc58739-86f5-47dd-83c2-ce99f87818b2' title='Show/Hide index repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-index-data'><pre>PandasIndex(Index([               -5.0,  -3.888888888888889, -2.7777777777777777,\n",
              "       -1.6666666666666665, -0.5555555555555554,  0.5555555555555554,\n",
              "         1.666666666666667,  2.7777777777777786,  3.8888888888888893,\n",
              "                       5.0],\n",
              "      dtype=&#x27;float64&#x27;, name=&#x27;x&#x27;))</pre></div></li><li class='xr-var-item'><div class='xr-index-name'><div>y</div></div><div class='xr-index-preview'>PandasIndex</div><div></div><input id='index-dab66382-f85d-4bfa-8a71-cc7111bfb5c2' class='xr-index-data-in' type='checkbox'/><label for='index-dab66382-f85d-4bfa-8a71-cc7111bfb5c2' title='Show/Hide index repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-index-data'><pre>PandasIndex(Index([               -5.0,  -3.888888888888889, -2.7777777777777777,\n",
              "       -1.6666666666666665, -0.5555555555555554,  0.5555555555555554,\n",
              "         1.666666666666667,  2.7777777777777786,  3.8888888888888893,\n",
              "                       5.0],\n",
              "      dtype=&#x27;float64&#x27;, name=&#x27;y&#x27;))</pre></div></li><li class='xr-var-item'><div class='xr-index-name'><div>time</div></div><div class='xr-index-preview'>PandasIndex</div><div></div><input id='index-5263762f-1701-4674-96c0-2c9763706ab4' class='xr-index-data-in' type='checkbox'/><label for='index-5263762f-1701-4674-96c0-2c9763706ab4' title='Show/Hide index repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-index-data'><pre>PandasIndex(DatetimeIndex([&#x27;2023-01-01&#x27;, &#x27;2023-01-02&#x27;, &#x27;2023-01-03&#x27;, &#x27;2023-01-04&#x27;,\n",
              "               &#x27;2023-01-05&#x27;, &#x27;2023-01-06&#x27;, &#x27;2023-01-07&#x27;, &#x27;2023-01-08&#x27;,\n",
              "               &#x27;2023-01-09&#x27;, &#x27;2023-01-10&#x27;],\n",
              "              dtype=&#x27;datetime64[ns]&#x27;, name=&#x27;time&#x27;, freq=&#x27;D&#x27;))</pre></div></li></ul></div></li><li class='xr-section-item'><input id='section-f842c0d8-df7c-49a0-aaac-6a5ba3eb802d' class='xr-section-summary-in' type='checkbox' disabled ><label for='section-f842c0d8-df7c-49a0-aaac-6a5ba3eb802d' class='xr-section-summary'  title='Expand/collapse section'>Attributes: <span>(0)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><dl class='xr-attrs'></dl></div></li></ul></div></div>"
````

Notice how this HTML starts with two _closing_ div tags. There's no way we can do the right thing here; unfortunately, xr.DataArray needs to emit more general HTML that works on places other than the very specific DOM from jupyter lab HTML pages.

**Comment by itcarroll** [comment] 2023-11-09 21:47
I'm not convinced this is an xarray or dask HTML output problem; reproducible example of a notebook that does not render correctly below. The HTML output in the original looks fine, but the HTML output in the result of `quarto render ... --to ipynb` is severely truncated.

To reproduce you'll need to install `xarray` and `dask[array]`. Execute a notebook with this one cell:
```
import xarray as xr
ds = xr.Dataset(
    {chr(i): ("x", [0, 1, 2]) for i in range(65, 91)},
)
ds.chunk()
```
If you look at the raw JSON, there is tons of HTML in the cell's output.

After `quarto render --to ipynb`, the relevant output has waaay less content:

```
[
  {
    "output_type": "display_data",
    "metadata": {},
    "data": {
      "text/html": [
        "</div></li></ul></div></li><li class='xr-section-item'><input id='section-c694cac4-dd81-4242-9d10-f63c53b807c8' class='xr-section-summary-in' type='checkbox' disabled ><label for='section-c694cac4-dd81-4242-9d10-f63c53b807c8' class='xr-section-summary'  title='Expand/collapse section'>Indexes: <span>(0)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><ul class='xr-var-list'></ul></div></li><li class='xr-section-item'><input id='section-74514174-77f2-44fc-98cd-4436f843488e' class='xr-section-summary-in' type='checkbox' disabled ><label for='section-74514174-77f2-44fc-98cd-4436f843488e' class='xr-section-summary'  title='Expand/collapse section'>Attributes: <span>(0)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><dl class='xr-attrs'></dl></div></li></ul></div></div>"
      ]
    }
  }
]
```
In notebook view, much of the output is missing compared to the original.

**Comment by cscheid** [comment] 2023-11-09 21:50
The point is that this is _badly formed HTML_; it requires existing surrounding divs and lists to operate correctly. Look at the first tags, it's `</div></li></ul>`. What lists is this closing?

**Comment by cscheid** [comment] 2023-11-09 21:52
The output you see in that JSON is not produced by quarto code, it's produced by `nbclient`, a jupyter library that we call. If that HTML is badly formed, there's nothing we can do.

**Comment by itcarroll** [comment] 2023-11-09 21:55
I see that it is bad HTML. My observation is that it is not xarray or dask producing it though, since the original notebook has good HTML. Becomes bad during `quarto render`, but I will gladly try to trace it to `nbclient`. If you can hint at what call would invoke nbclient without quarto, that will help.

Thanks for revisiting.

**Comment by cscheid** [comment] 2023-11-09 21:57
@itcarroll I take it back, I apologize. You have `render --to ipynb`, which is a different codepath than above.

**Comment by cscheid** [comment] 2023-11-09 21:59
For example, `quarto preview --to html` on your example works fine:

<img width="842" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/5021d6b3-5a9d-4126-a927-77489fb45018">

The issue you're bringing up is _quarto output to .ipynb_ specifically.  That was not in the original report, although that might have been the underlying cause!

**Comment by itcarroll** [comment] 2023-11-09 22:04
Different, yes, huh. But still not right with quarto preview for me, because the drop-down for "Data variables" should list 26 letters.

**Comment by cscheid** [comment] 2023-11-09 22:05
Ok, now it all makes sense (thanks for the patience, folks!)

The truncation of the HTML in that .ipynb is happening by _us_: that's a separate bug.

We then have to figure out why the inline SVG is not showing in our HTML page, as well as the drop-down being slightly off.

**Comment by cscheid** [comment] 2023-11-09 22:24
Ok, whew: I know what this is. Here's a workaround for now. Add the following to your front matter:

```
---
html-table-processing: none
---
```

**Comment by cscheid** [comment] 2023-11-09 22:35
The useful lesson for us going forward is that, for debugging purposes, it's safer to use `keep-ipynb: true` than to use `--to ipynb`; We should make sure to ask bug reporters for `keep-ipynb: true` specifically (my apologies again, @maawoo!). If something in our Lua pipeline is causing the HTML to be malformed (in this case, our table processing), then `--to ipynb` inherits that bad behavior and worse yet, misplaces the blame. We won't make that mistake again!

The ultimate cause of the issue here is that Quarto attempts to parse raw HTML blocks for tables. This is good behavior (because the Pandoc HTML Table reader supports table features that the Markdown reader doesn't), but it currently has the limitation that nested tables are not supported.

Crucially, this tool emits (perfectly well-formed!) nested tables in its HTML. Which is totally fine, but breaks our processing.

**Comment by itcarroll** [comment] 2023-11-10 02:02
Thank you for the (pre-release 😉 ) workaround!

**Comment by maawoo** [comment] 2023-11-10 07:53
Thank you @cscheid and @itcarroll ! 🙂

**Comment by cscheid** [comment] 2023-11-10 23:13
This is fixed on `main`, and will be available on the prereleases in a couple of hours. Thanks again for the multiple reports!

**Closed** 2023-11-10 23:13 UTC
Labels: bug, jupyter
