### ISSUE TITLE
No handler registered for histoslider.

### ISSUE THREAD

**Issue by nipnipj** [quarto-dev/quarto-cli#7907] opened 2023-12-13 00:30 UTC
### Bug description

```
Warning: Error in <Anonymous>: No handler registered for type Input2:histoslider.histosliderdate
  5: <Anonymous>
  3: rmarkdown::run
  2: run
  1: .main
Error in (function (name, val, shinysession)  : 
  No handler registered for type Input2:histoslider.histosliderdate
```

**Comment by mcanouil** [comment] 2023-12-13 07:03
Thanks for the report.
Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.
Also could you share the output of `quarto check`?

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

**Comment by cscheid** [comment] 2023-12-13 16:02
"histoslider" seems to be this: https://github.com/cpsievert/histoslider I encourage you to file a report at that repo with a reprex: https://reprex.tidyverse.org/

I'm going to go ahead and close this one, since this is not a quarto issue.

**Closed by cscheid** 2023-12-13 16:02 UTC
Labels: bug, needs-repro
