### ISSUE TITLE
Table number does not appear when using a single table inside a div element.

### ISSUE THREAD

**Issue by magnusnosnes** [quarto-dev/quarto-cli#3931] opened 2023-01-11 09:44 UTC
Hi, 

Is there a way to obtain a numbered table caption above a single table using div elements: ":::"?

According to the documentation at [tables ](https://quarto.org/docs/authoring/tables.html) one can use div elements around multiple tables to get a a **numbered table** with the caption above using this code: 

For example, this code:

````
::: {#tbl-panel layout-ncol=2}
| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

: First Table {#tbl-first}

| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

: Second Table {#tbl-second}

Main Caption
:::
````

will give a numbered table with caption above as I want. But when using a single table, the table number is not displayed, like this code:

````
::: {#tbl-panel}

| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

Main Caption
:::
````

I am trying to use this as a workaround to get numbered table caption above my datatable produced using R. In the following code, I would like the table caption to be numbered according to the order it appears in the document (relative to other tables), and appear above the datatable.

````
::: {#tbl-panel}

```{r}
library(DT)
datatable(my_interactive_table)
```

My table caption that should give the table number and appear above the table.
:::
````

Thank you for your time and help,
Magnus Nygård Osnes

**Comment by cscheid** [comment] 2023-02-27 16:51
The issue here is that this level of coordination between table libraries and quarto is currently not as good as we'd like it to be. We've made some improvements in 1.3 but the specific relationship between table subcaptions etc interferes with the crossref system, which we are going to rebuild in 1.4.

**Comment by cscheid** [comment] 2023-05-23 18:06
Duplicate of #1829.

**Comment by cscheid** [comment] 2023-09-20 00:19
This example:

````
---
title: issue-3931
---

::: {#tbl-panel}

| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

Main Caption
:::

See @tbl-panel.
````

now works on `main`:

<img width="667" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/b1056b22-9d2e-47b2-be5c-884cfb9a70b2">

**Closed by cscheid** 2023-09-20 00:19 UTC
Labels: enhancement, crossref, tables
