### ISSUE TITLE
`revealjs` column divs have extraneous whitespace

### ISSUE THREAD

**Issue by pgseye** [quarto-dev/quarto-cli#8498] opened 2024-01-29 23:26 UTC
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8494

<div type='discussions-op-text'>

<sup>Originally posted by **pgseye** January 30, 2024</sup>
### Description

I recently updated my 8 yr old iMac to a Mac Studio. I opened up and rendered a talk I had been working on and the image positioning in some slides is mucked up (see attached examples of old and new computer). The thing is - the code is completely unchanged and everything looks correct as it did before. I can render this same .qmd file on my 4 yr old MacBook Pro and the images look correct (as they did on my iMac). 

I am using Quarto v. 1.0.28 on my MacBook and it looks like 1.3.450 on my new Mac Studio.

I don't know how to troubleshoot this when the code is unchanged and everything works as it should on one machine. Any ideas where to start as this is pretty frustrating? It's not an intel/Apple silicon thing is it?

Thank you - Paul

The code I used to produce this in the slide is:

```
## Some basic concepts

<br>

These all play a role in logistic regression, but they are nothing more than transformations of one another:

::: {.column width="33.3%"}
::: {.fragment .fade-in}
<br>

::: {style="font-size: 1.2em"}
Probability
:::
:::

::: {.fragment .fade-in}
![](images/prob_vert.png){.absolute height="300" left="80"}
:::
:::

::: {.column width="33.3%"}
::: {.fragment .fade-in}
<br>

::: {style="font-size: 1.2em"}
Odds
:::
:::

::: {.fragment .fade-in}
![](images/odds_vert.png){.absolute height="300" left="420"}
:::
:::

::: {.column width="33.3%"}
::: {.fragment .fade-in}
<br>

::: {style="font-size: 1.2em"}
log-odds
:::
:::

::: {.fragment .fade-in}
![](images/logodds_vert.png){.absolute height="300" left="770"}
:::
:::

::: fragment
![](images/arrows.png){.absolute top="320" left="0"}
:::
```
Macbook
<img width="1909" alt="screenshot_02" src="https://github.com/quarto-dev/quarto-cli/assets/12015304/c6c42d53-22b0-4426-921c-5298e6e26942">

Mac Studio
<img width="1891" alt="screenshot_03" src="https://github.com/quarto-dev/quarto-cli/assets/12015304/57898e36-a97c-4850-9552-47ef6dd5c2d1">
</div>

quarto check (Mac Studio)
```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

quarto check (MacBook)
```
[✓] Checking Quarto installation......OK
      Version: 1.0.28
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.7.3
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

**Comment by pgseye** [comment] 2024-01-30 00:49
For anyone else who might potentially experience this problem, after experimenting with different things, it turns out the problem seems to be related to the column widths specified. The formatting issues only occurred on slides that had multiple columns. If I changed the percentages to add up to something less than 100%, all the alignments seemed to fall back into place. 

For the above slide I dropped the 0.3% from each column (i.e. 33% rather than 33.3%) and now it works.

Is there any reason why?

**Comment by dragonstyle** [comment] 2024-01-30 12:47
I don't the precise cause, but I would say there are two major possibilities:

- We likely updated the version of RevealJS we use internally between 1.0 and the 1.3 version of Quarto. This could've changed some layout behavior. This seem most likely to me.

- The CSS we use for Reveal slides also certainly changed between those versions and could also be a culprit.

I tried tinkering with the above example briefly and though I could reproduce the issue,  I couldn't sort out why the layout was shifting and tweaking the column widths didn't seem to resolve it for me (I was testing with broken images, so that could be the underlying cause).

Happy to keep troubleshooting - it would be helpful if you could share a complete example of the slide w/images if possible.

**Comment by mcanouil** [comment] 2024-01-30 13:23
May I suggest to check with 1.4 if not already done?

Note that nearly every (if not all) dependencies were upgraded between 1.0 and 1.4, this includes Reveal.js and many tweaks to CSS in this context (to avoid confusion, Reveal.js does not use Bootstrap).

**Comment by pgseye** [comment] 2024-01-30 20:20
Thanks - glad it's not just me.

I did upgrade to version 1.4.549 and the problem persisted.

I'm sorry - I have used GitHub, but I'm still not great with it, so I am posting what I think are the necessary files here to reproduce that slide (let me know if there's an issue). More than happy for you to put on GitHub if needed.
[test.zip](https://github.com/quarto-dev/quarto-cli/files/14103739/test.zip)

**Comment by dragonstyle** [comment] 2024-02-13 22:17
I checked in Quarto 1.2, 1.3, and 1.4 and all have this behavior, so we'll need to go back pretty far to pin down a change that is causing it.

I think a likely culprit is a change in whitespace between the column divs (since they are `display: inline-block` I think that whitespace may affect layout computations when wrapping). I confirmed the computed widths of the columns and slide body region are correct, which makes me think that whitespace in the HTML could be the culprit.

Edit: Confirmed manually removing new lines between column divs fixes the issue. We'll track down where those are coming in.

**Closed** 2024-06-12 16:05 UTC
Labels: bug, revealjs
