### ISSUE TITLE
Automatically adding a .png suffix to dynamic image in Quarto

### ISSUE THREAD

**Issue by gaospecial** [quarto-dev/quarto-cli#8261] opened 2024-01-14 02:52 UTC
### Bug description

When I use badges in Markdown, the image url is broken in Quarto rendered document.  For instance:

`[![](https://www.r-pkg.org/badges/version/factoextra)](https://cran.r-project.org/package=factoextra)`

turns into: `[![](https://www.r-pkg.org/badges/version/factoextra.png)](https://cran.r-project.org/package=factoextra)`.

It seems that Quarto automatically added a unwanted `.png` suffix to the image link of markdown document.

### Steps to reproduce

To reproduce this, I created a bare md document `file.md`:

```md
![](image)
```

and run `quarto render file.md`, the image link of generated html would be `image.png`.

### Expected behavior

Dynamic image should be allowed in markdown as well as in html document. So expected result is:

[![](https://www.r-pkg.org/badges/version/factoextra)](https://cran.r-project.org/package=factoextra)

However, the actual result is:

### Actual behavior

[![](https://www.r-pkg.org/badges/version/factoextra.png)](https://cran.r-project.org/package=factoextra)

Therefore, I believe this is a bug.

### Your environment

- IDE: VS code
- OS: Darwin MacBook.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:51 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6030 arm64
- Quarto: 1.3.450

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.0 (Conda)
      Path: /opt/homebrew/anaconda3/envs/mcmodel/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2024-01-14 05:11
Closing as a duplicate of:
- #6092

**Closed** 2024-01-14 05:11 UTC
Labels: duplicate
