### ISSUE TITLE
Can't knit child qmds in a sub-directory

### ISSUE THREAD

**Issue by boshek** [quarto-dev/quarto-cli#2566] opened 2022-09-22 21:17 UTC
### Bug description

👋 thanks again for quarto. the more i use it, the more i am appreciating it. 

I am reporting this here with quarto rather than knitr because it changes for me from `1.1.251` -> `1.2.148`.

I also tested on the dev version with this HEAD (https://github.com/quarto-dev/quarto-cli/commit/5da03618fedf82742fac3635364a8074f11d3d3e) and the issue was this present. As of `1.2.148` I can't knit child qmds that are in a separate folder. I can reproduce with these two files:

````md
---
title: "Untitled"
execute: 
  eval: true
  echo: false
  warning: false
format: html
---

```{r r-pkgs}
library(dplyr)
library(gt)
library(purrr)
```
# Tables

::: {.panel-tabset}

```{r}
#| output: asis
res <- purrr::map_chr(unique(starwars$homeworld), \(hw) {
    knitr::knit_child(
      input = "child-dir/_child.qmd", 
      envir = environment(), 
      quiet = TRUE
      )
  })

cat(res, sep = '\n')
```
:::
````

### child-dir/_child.qmd
 
````md
## `r hw`

```{r}
#| echo: false
starwars %>%
  filter(homeworld == hw) %>%
  count(sex) %>%
  head() %>%
  gt()
```
````

Here is the error I am getting: 
> Error in readLines(con, warn = FALSE) : cannot open the connection
Calls: .main ... <Anonymous> -> enumerate_output_formats -> read_utf8 -> readLines
In addition: Warning message:
In readLines(con, warn = FALSE) :
  cannot open file '_child.qmd': No such file or directory
>
> Execution halted

This works if the child qmds are in the same directory as the main qmd. 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment] 2022-09-23 10:01
Hello @boshek 

I can't reproduce this. I have added an example about this 

* Source at: https://github.com/quarto-dev/quarto-examples/tree/main/tabsets/tabsets-from-r-chunks
* Live at : https://cderv.quarto.pub/create-tabsets-panel-from-r-code/

This renders correctly for me. 

Does the error happens during `quarto render` ? In a specific IDE or scenario ? 

> ```
> Error in readLines(con, warn = FALSE) : cannot open the connection
> Calls: .main ... -> enumerate_output_formats -> read_utf8 -> readLines
> ```

This issue mentions `enumerate_output_formats` which is not called by Quarto, so I am surprised. 🤔

**Comment by boshek** [comment] 2022-09-23 16:29
Thanks for the response. Great to have that in an example! And it also made me realized that my reprex could be more minimal. So I can reproduce this locally using vscode, RStudio and calling the CLI tool. And I am finding that it is some interaction between {gt} and quarto. The part that has me confused is that I can only reproduce with the dev versions of quarto. 

Here is the more minimal reprex:

## index.qmd
````md
---
title: "Untitled"
format: html
---

# single
```{r}
#| results: asis
res <- knitr::knit_child(
  input = "child-dir/_child.qmd",
  envir = environment(),
  quiet = TRUE
)

cat(res, sep = "\n")
```
````

## _child.qmd
````md
```{r}
gt::gt(head(iris))
head(iris)
```
````

## Calling it

Commenting `gt::gt(head(iris))` removes the error. So via calling the CLI I see:

```bash
~ quarto --version
1.2.150
~ quarto render index.qmd


processing file: index.qmd
  |.......................                                               |  33%
  ordinary text without R code

  |...............................................                       |  67%
label: unnamed-chunk-1 (with options)
List of 1
 $ results: chr "asis"

Quitting from lines 4-5 (~/temp-for-issue/child-dir/_child.qmd)
Error in readLines(con, warn = FALSE) : cannot open the connection
Calls: .main ... <Anonymous> -> enumerate_output_formats -> read_utf8 -> readLines

Execution halted
```

With the release version this works
````md
~ quarto --version
1.1.251
~ quarto render index.qmd


processing file: index.qmd
  |.......................                                               |  33%
  ordinary text without R code

  |...............................................                       |  67%
label: unnamed-chunk-1 (with options)
List of 1
 $ results: chr "asis"

  |......................................................................| 100%
  ordinary text without R code


output file: index.knit.md

pandoc
  to: html
  output-file: index.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Untitled

Output created: index.html
```

**Comment by cderv** [comment] 2022-09-23 20:17
> Thanks for the response. Great to have that in an example!

Does the example I share works for you ? Just to be sure, as it was my attempt to reproduce. 

Currently I can't reproduce. 

This is my folder `test-child` where I created the quarto project, and the files.

````
> tree . /f
Structure du dossier pour le volume OS
C:\USERS\CHRIS\DOCUMENTS\TEST-CHILD
│   index.qmd
│   _quarto.yml
│
└───child-dir
        _child.qmd
````

and calling `quarto render index.qmd` works still fine fine (and I upgraded from `1.2.148 -> 1.2.151`)

Can you share a reproducible example as a Github repo maybe ? So that we can really clone the same one ?

**Comment by boshek** [comment] 2022-09-23 20:38
Good idea. Here is the repo: https://github.com/boshek/quarto-child-issue

I am on a M1 mac. I don't have access right now but I will try on a different OS later. 

And no the code from your example did not work for me past 1.1.251.

**Comment by cderv** [comment] 2022-09-23 21:04
Thanks for the repo. I definitely can't reproduce on windows by cloning, and then running `quarto render index.qmd`

@dragonstyle could you try this out on Mac maybe ?

**Comment by dragonstyle** [comment] 2022-10-07 16:10
I'm on an intel mac, but cloning that repo and running `quarto render index.qmd` also does not reproduce any error for me.

**Comment by mvwestendorp** [comment] 2022-11-25 13:56
I am encountering this issue too in multiple projects (on windows,).
The common thing to me seemed the use of the gtsummary package for my projects, 
I also see the gt package being used here (which gtsummary also uses I think). 

I can reproduce the error using @boshek's repo and removing the gt line in the _child.qmd file fixes the error for me.

Let me know if there is further info that I can give to help solve this!

**Comment by cderv** [comment] 2022-11-28 10:41
@mvwestendorp Is this possible for you to share a reproducible example that fails for you ? 

With last one shared ([boshek/quarto-child-issue](https://github.com/boshek/quarto-child-issue)) we can't reproduce the issue. 

Please do update every tools, and also share configurations. Maybe this is something about some tools versions somewhere

**Comment by mvwestendorp** [comment] 2022-12-02 15:42
@cderv you're right its tools versions (or package version) .
The gt package at version 0.7.0 gives the error while version 0.8.0 works fine.

**Comment by boshek** [comment] 2022-12-02 16:34
Yeah same result as @mvwestendorp as me. As long as no one is specifically needing that version pair of quarto and gt, this can probably be closed?

**Comment by cderv** [comment] 2022-12-02 17:00
Great ! Thanks for confirming. 

I indeed believe this should be closed as fixed in newer gt version.

**Closed** 2022-12-02 20:48 UTC
Labels: bug, need-repro
