### ISSUE TITLE
revealjs: callout title/icon lacks alignment when $presentation-font-size-root adjusted

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#9549] opened 2024-05-01 17:50 UTC
### Bug description

Callout titles are no longer aligned with the icon after adjusting `presentation-font-size-root`

### Steps to reproduce

Given an `index.qmd`

````markdown
---
title: reveal callouts
format:
  revealjs:
    theme: [simple, custom.scss]
---

## what

::: {.callout-warning}
you need to see this.
:::
````

and a simple `custom.scss`

```scss
/*-- scss:defaults --*/

/*-- scss:variables --*/
$presentation-font-size-root: 28px;

/*-- scss:rules --*/
```

### Expected behavior

The callout icon and title remain aligned.

<img width="388" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/f378b100-a9b1-4067-92f2-106bbe900dc1">

(screenshot taken without font-size adjustment)

### Actual behavior

The callout icon and title are not aligned.

<img width="245" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/0c0ff0ef-6fd7-4d0c-a6f1-40cd78a57591">

### Quarto check output

```
Quarto 1.4.551
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.551
      Path: /Users/aron/quarto/quarto-1.4.551-macos/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2024-05-01 17:58
Is it a duplicate of https://github.com/quarto-dev/quarto-cli/issues/5832 ?

**Comment by mcanouil** [comment] 2024-05-01 18:00
Duplicate of #5832

**Closed** 2024-05-01 18:01 UTC
Labels: duplicate

**Comment by aronatkins** [comment] 2024-05-01 18:24
@mcanouil - perhaps similar to #5832, but in this case, one of the documented variables is being modified. In #5832, custom styles are in play.

**Comment by mcanouil** [comment] 2024-05-01 18:27
In both cases, the misalignment occurs when the font size is modified.
So, I really believe the root cause is the same.
I don't think how the issue is triggered (using SCSS variable or adding a CSS class) changes anything.

**Comment by cderv** [comment] 2024-05-02 08:52
Thanks @aronatkins for the report. 

First, just a reminder that `/*-- scss:defaults --*/` is the place to have the variables. `/*-- scss:variables --*/` is not a layer processed by Quarto. it works here because it is inside defaults, and comment syntax makes it ignored. See the layers processed at https://quarto.org/docs/output-formats/html-themes-more.html

We have this problem because we use PNG image for the icon in **revealjs** and SVG in the **HTML**, so the font size does not apply to the background image used in the callout inside revealjs.

I need to see why we don't use SVG image. 🤔 

I'll rename the other issue and we'll track there
