### ISSUE TITLE
`quarto-preview.js` Not Found In Quarto 1.4.554

### ISSUE THREAD

**Issue by kadykov** [quarto-dev/quarto-cli#9574] opened 2024-05-03 15:26 UTC
### Bug description

`quarto preview` cannot find `Quarto\share\preview\quarto-preview.js`, the auto refresh functionality is broken.
In the 1.4.553 version, everything works fine.

### Steps to reproduce

````qmd
---
title: "quarto-preview-js-issue"
format: html
---

This is a Quarto website.

````

Then

```
quarto preview index.qmd --no-browser --no-watch-inputs
```

### Expected behavior

Here is the output with Quarto 1.4.553
```
(data-analysis) PS C:\Users\kadykov\Documents\prog\temp\quarto-preview-js-issue> quarto preview c:/Users/kadykov/Documents/prog/temp/quarto-preview-js-issue/index.qmd --no-browser --no-watch-inputs
pandoc 
  to: html
  output-file: index.html     
  standalone: true
  section-divs: true
  html-math-method: mathjax   
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true        
  date-format: long
  lang: en
  title: quarto-preview-js-issue

Output created: index.html

Watching files for changes
Browse at http://localhost:4143/
```

```
(data-analysis) PS C:\Users\kadykov\Documents\prog\temp\quarto-preview-js-issue> quarto preview c:/Users/kadykov/Documents/prog/temp/quarto-preview-js-issue/index.qmd --no-browser --no-watch-inputs
pandoc 
  to: html
  output-file: index.html     
  standalone: true
  section-divs: true
  html-math-method: mathjax   
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: quarto-preview-js-issue

Output created: index.html

Watching files for changes
Browse at http://localhost:4143/
(data-analysis) PS C:\Users\kadykov\Documents\prog\temp\quarto-preview-js-issue> quarto check
Quarto 1.4.553
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.553
      Path: C:\Users\kadykov\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: 869685

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\kadykov\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.7 (Conda)
      Path: C:/Users/kadykov/mambaforge/envs/data-analysis/python.exe
      Jupyter: 5.7.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Actual behavior

```
(data-analysis) PS C:\Users\kadykov\Documents\prog\temp\quarto-preview-js-issue> quarto preview c:/Users/kadykov/Documents/prog/temp/quarto-preview-js-issue/index.qmd --no-browser --no-watch-inputs
pandoc 
  to: html
  output-file: index.html     
  standalone: true
  section-divs: true
  html-math-method: mathjax   
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true        
  date-format: long
  lang: en
  title: quarto-preview-js-issue

Output created: index.html

Watching files for changes
Browse at http://localhost:3214/
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
WARNING: The system cannot find the file specified. (os error 2): readfile 'C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'
```

### Your environment

VS Code Version: 1.89.0 (system setup)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

### Quarto check output

```
(data-analysis) PS C:\Users\kadykov\Documents\prog\temp\quarto-preview-js-issue> quarto check
Quarto 1.4.554
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.554
      Path: C:\Users\kadykov\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: 869685

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\kadykov\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.7 (Conda)
      Path: C:/Users/kadykov/mambaforge/envs/data-analysis/python.exe
      Jupyter: 5.7.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cscheid** [comment] 2024-05-03 15:30
I think this is a duplicate of #9478. Will be fixed soon.

**Comment by cderv** [comment] 2024-05-06 11:42
@cscheid Are you sure you referred to the right issue ? #9478 is only for pre-release version and implies knitr engine. 

This seems to be different. 

@kadykov just to be sure:  Did you check that this file exists on your system `C:\Users\kadykov\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js` ? 
it is just to confirm this not some weird state of the installer.

**Comment by cderv** [comment] 2024-05-06 14:10
I can see the warning too now, and I can say on my side that `quarto-preview.js` is not in `share\preview` folder on my installation. So something has changed somehow, or we got a build problem at release.  🤔

**Comment by cderv** [comment] 2024-05-06 14:44
Ok - @cscheid our configure script on windows does not stop CI execution when there is an error during the Quarto Web UI building task 
https://github.com/quarto-dev/quarto-cli/actions/runs/8938251447/job/24552025613#step:5:112

On other OS it worked ok. 

I'll investigate the error, and we'll need to push a patch release as soon as it fixed.

Unless `quarto-preview.js` is optional somehow. Preview work ok for me without this file 🤔

**Comment by cscheid** [comment] 2024-05-06 14:45
> Unless quarto-preview.js is optional somehow. Preview work ok for me without this file 🤔

It's not optional afaict.

**Comment by cderv** [comment] 2024-05-06 19:07
I don't know what is happening yet. I can't reproduce locally, it only fails in CI on windows. 

Though 
https://github.com/quarto-dev/quarto-cli/blob/a604268ea7724d8991512f1f7ed89ce7b84f391a/src/core/previewjs.ts#L9-L25

https://github.com/quarto-dev/quarto-cli/blob/a604268ea7724d8991512f1f7ed89ce7b84f391a/package/src/common/configure.ts#L37-L42

It does not throw an error here because, the result of `buildCmd.outputSync()` is 
````
{
  success: true,
  code: 0,
  signal: null,
  stdout: [Getter],
  stderr: [Getter]
}
````

So still a success despite the build error. 

This is one thing to solve, but the most important is still a mystery to me

**Comment by cderv** [comment] 2024-05-06 19:31
Some notes about today's debugging 

* Error is from a dependency importing `@griffel/react` in this files `node_modules/.deno/@fluentui+react-teaching-popover@9.1.2/node_modules/@fluentui/react-teaching-popover/lib/components/TeachingPopoverCarouselFooterButton/useTeachingPopoverCarouselFooterButtonStyles.styles.js`
	````
	import { __styles, mergeClasses, shorthands } from '@griffel/react';
	````
* Somehow this dependency is on CI but I don't have it locally (`@fluentui+react-teaching-popover` is not there). 
Also on CI it is the only one with a folder not symlinked which probably explain why `@griffel/react` is not found
````
# ls -l node_modules/.deno/@fluentui+react-teaching-popover@9.1.2/node_modules/@fluentui/
total 4
lrwxrwxrwx 1 runneradmin None 132 May  6 19:10 react-aria -> /d/a/quarto-cli/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-aria@9.11.1/node_modules/@fluentui/react-aria
lrwxrwxrwx 1 runneradmin None 136 May  6 19:10 react-button -> /d/a/quarto-cli/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-button@9.3.78/node_modules/@fluentui/react-button
lrwxrwxrwx 1 runneradmin None 156 May  6 19:10 react-context-selector -> /d/a/quarto-cli/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-context-selector@9.1.59/node_modules/@fluentui/react-context-selector
lrwxrwxrwx 1 runneradmin None 135 May  6 19:10 react-icons -> /d/a/quarto-cli/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-icons@2.0.239/node_modules/@fluentui/react-icons
lrwxrwxrwx 1 runneradmin None 146 May  6 19:10 react-jsx-runtime -> /d/a/quarto-cli/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-jsx-runtime@9.0.37/node_modules/@fluentui/react-jsx-runtime
lrwxrwxrwx 1 runneradmin None 137 May  6 19:10 react-popover -> /d/a/quarto-cli/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-popover@9.9.7/node_modules/@fluentui/react-popover
lrwxrwxrwx 1 runneradmin None 154 May  6 19:10 react-shared-contexts -> /d/a/quarto-cli/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-shared-contexts@9.18.0/node_modules/@fluentui/react-shared-contexts
lrwxrwxrwx 1 runneradmin None 138 May  6 19:10 react-tabster -> /d/a/quarto-cli/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-tabster@9.21.1/node_modules/@fluentui/react-tabster
drwxr-xr-x 1 runneradmin None   0 May  6 18:51 react-teaching-popover
lrwxrwxrwx 1 runneradmin None 134 May  6 19:10 react-theme -> /d/a/quarto-cli/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-theme@9.1.19/node_modules/@fluentui/react-theme
lrwxrwxrwx 1 runneradmin None 142 May  6 19:10 react-utilities -> /d/a/quarto-cli/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-utilities@9.18.8/node_modules/@fluentui/react-utilities
````

So definitely a dependency issue somewhere... 🤔

**Comment by 197315** [comment] 2024-05-25 15:27
Hello, I have the same issue when I render a .qmd file:

WARNING: El sistema no puede encontrar el archivo especificado. (os error 2): readfile 'C:\Users\Gabri\AppData\Local\Programs\Quarto\share\preview\quarto-preview.js'

I wish you fix it.
thanks

**Comment by cderv** [comment] 2024-05-28 17:41
> I still don't know why this is different on CI than locally - maybe this will give us the right clue. I'll try another time

Ok so I found the problem as I managed to recreate it locally by ... removing Deno CACHE_DIR

Now I get same error than in CI, so this is link to Deno caching dependency and somehow missing some or doing some other thing. 

Now I get the same locally 
````
❯ ls -l node_modules/.deno/@fluentui+react-teaching-popover@9.1.6/node_modules/@fluentui/
total 0
lrwxrwxrwx 1 cderv cderv 151 May 28 19:09 react-aria -> /mnt/c/Users/chris/Documents/DEV_R/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-aria@9.11.4/node_modules/@fluentui/react-aria
lrwxrwxrwx 1 cderv cderv 155 May 28 19:09 react-button -> /mnt/c/Users/chris/Documents/DEV_R/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-button@9.3.82/node_modules/@fluentui/react-button
lrwxrwxrwx 1 cderv cderv 175 May 28 19:09 react-context-selector -> /mnt/c/Users/chris/Documents/DEV_R/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-context-selector@9.1.60/node_modules/@fluentui/react-context-selector
lrwxrwxrwx 1 cderv cderv 154 May 28 19:09 react-icons -> /mnt/c/Users/chris/Documents/DEV_R/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-icons@2.0.240/node_modules/@fluentui/react-icons
lrwxrwxrwx 1 cderv cderv 165 May 28 19:09 react-jsx-runtime -> /mnt/c/Users/chris/Documents/DEV_R/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-jsx-runtime@9.0.38/node_modules/@fluentui/react-jsx-runtime
lrwxrwxrwx 1 cderv cderv 157 May 28 19:09 react-popover -> /mnt/c/Users/chris/Documents/DEV_R/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-popover@9.9.10/node_modules/@fluentui/react-popover
lrwxrwxrwx 1 cderv cderv 173 May 28 19:09 react-shared-contexts -> /mnt/c/Users/chris/Documents/DEV_R/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-shared-contexts@9.19.0/node_modules/@fluentui/react-shared-contexts
lrwxrwxrwx 1 cderv cderv 157 May 28 19:09 react-tabster -> /mnt/c/Users/chris/Documents/DEV_R/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-tabster@9.21.4/node_modules/@fluentui/react-tabster
drwxrwxrwx 1 cderv cderv 512 May 28 19:09 react-teaching-popover
lrwxrwxrwx 1 cderv cderv 153 May 28 19:09 react-theme -> /mnt/c/Users/chris/Documents/DEV_R/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-theme@9.1.19/node_modules/@fluentui/react-theme
lrwxrwxrwx 1 cderv cderv 161 May 28 19:09 react-utilities -> /mnt/c/Users/chris/Documents/DEV_R/quarto-cli/src/webui/quarto-preview/node_modules/.deno/@fluentui+react-utilities@9.18.9/node_modules/@fluentui/react-utilities
````

not sure how we fix, if maybe a deno update fix it, or if this is configuration somehow.

**Closed** 2024-05-30 16:03 UTC
Labels: bug, windows, installers
