### ISSUE TITLE
Quarto not using python interpreter from virtual environment

### ISSUE THREAD

**Issue by SamEdwardes** [quarto-dev/quarto-cli#2801] opened 2022-10-11 19:18 UTC
### Bug description

**Background**

When I render documents with Python code chunks the incorrect python interpreter is being used. I would like quarto to execute the code chunks using my virtual environment, but instead it is using a different python interpreter.

**System details**

- Quarto: 1.1.113
- Operating System: M1 mac, macOS Monterey 12.6

**Reprex**

Create and activate a virtual environment:

```bash
python -m venv .venv
source .venv/bin/activate
which python
# /Users/samedwardes/tmp/quarto-env-reprex/.venv/bin/python
python -m pip install jupyter
```

Check quarto:

```bash
quarto check
# [✓] Checking Quarto installation......OK
#       Version: 1.1.113
#       Path: /Applications/quarto/bin
# 
# [✓] Checking basic markdown render....OK
# 
# [✓] Checking Python 3 installation....OK
#       Version: 3.10.4
#       Path: /Users/samedwardes/tmp/quarto-env-reprex/.venv/bin/python3
#       Jupyter: 4.11.1
#       Kernels: python3, connectapi-kernel, my-project-kernel, connectapi
# 
# [✓] Checking Jupyter engine render....OK
# 
# [✓] Checking R installation...........OK
#       Version: 4.2.1
#       Path: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources
#       LibPaths:
#         - /Users/samedwardes/Library/R/arm64/4.2/library
#         - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
#       rmarkdown: 2.16
# 
# [✓] Checking Knitr engine render......OK
```

Create a new document `example.qmd`:

````markdown
---
title: Virtual environment
---

Python code chunk:

```{python}
import sys

print(sys.executable)
```
````

Then render it:

```bash
quarto render example.qmd --output - 
# Executing 'example.ipynb'
#   Cell 1/1...Done
# 
# pandoc --output /var/folders/v9/fyndz9rs2hs34xwbs1rtmqtm0000gn/T/quarto-session0e5cab67/6e2ffbde/35950ad9.md
#   to: markdown
#   standalone: true
#   default-image-extension: png
#   
# metadata
#   title: Virtual environment
#   
# ---
# title: Virtual environment
# toc-title: Table of contents
# ---
# 
# Python code chunk:
# 
# ::: {.cell execution_count="1"}
# ``` {.python .cell-code}
# import sys
# 
# print(sys.executable)
# ```
# 
# ::: {.cell-output .cell-output-stdout}
#     /Users/samedwardes/.virtualenvs/py3912/bin/python
# :::
# :::
```

As you can see in the example above, `sys.executable` returns `/Users/samedwardes/.virtualenvs/py3912/bin/python` as opposed to `/Users/samedwardes/tmp/quarto-env-reprex/.venv/bin/python` which is what I was expecting.

**related issues**

- https://github.com/quarto-dev/quarto-web/pull/431

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by ifateri** [comment] 2022-10-12 12:21
I'm having the same issue with Poetry virtual environments and can reproduce using your example qmd. `quarto check` points to the right Python within the virtual environment that I want to use. 

I'm on Windows 10 and am using Quarto 1.1.251

**Comment by SamEdwardes** [comment] 2022-10-12 14:29
> I'm having the same issue with Poetry virtual environments and can reproduce using your example qmd. `quarto check` points to the right Python within the virtual environment that I want to use.
> 
> I'm on Windows 10 and am using Quarto 1.1.251

The issues initially arose for me when using poetry. But they also happen when working in virtual environments create by venv.

Also of interest, I am experiencing a similar issue with JupyterBook. I can create a reprex for that later.

**Comment by cscheid** [comment] 2022-10-18 17:13
I can't reproduce this locally. (I'm rendering to HTML). Following your script, I get:

```
<div class="cell-output cell-output-stdout">
<pre><code>/Users/cscheid/Desktop/daily-log/2022/10/18/.venv/bin/python3</code></pre>
</div>
```

That's where I just created the virtual environment.

**Comment by cscheid** [comment] 2022-10-18 17:13
Can you try downloading a v1.2 pre-release version of quarto? Thanks!

**Comment by ifateri** [comment] 2022-10-19 07:30
I can still reproduce with 1.2.226. `quarto check` points to the right Python in the virtual environment but when I render the qmd it goes back to my global interpreter (installed with scoop).

`<div class="cell-output cell-output-stdout">
<pre><code>C:\Users\name\scoop\apps\python\current\python.exe</code></pre>
</div>`

I have this both in the Poetry environment as well as in a fresh new venv virtual environment.

When I click Run Cell directly in the qmd it shows the right path in my interactive Window (below using Poetry): 
`c:\Users\name\AppData\Local\pypoetry\Cache\virtualenvs\logging-analysis-CyQINOo2-py3.8\Scripts\python.exe`

**Comment by SamEdwardes** [comment] 2022-10-19 15:41
I was able to resolve my issues. It is tough to figure out exactly what was happening, but my best guess is I had multiple kernels installed named "python3". @cscheid I have tried to reproduce this error, but I have been unable to. However, here is a suggested approach to try and fix it.

For example, I ran this command with no virtual environment activated:

```bash
$ jupyter kernelspec list --json
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "/Users/samedwardes/.virtualenvs/py3912/bin/python",
      "spec": {
        "argv": [
          "python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3 (ipykernel)",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {
          "debugger": true
        }
      }
    }
  }
```

This line was unexpected:

```bash
"resource_dir": "/Users/samedwardes/.virtualenvs/py3912/bin/python",
```

It should have been:

```bash
/Users/samedwardes/.pyenv/versions/3.10.4/bin/python
```

To fix this I did the following with no virtual environment activated:

```bash
# Uninstall the kernel
jupyter kernelspec uninstall python3

# Then check again to see where it is pointing
jupyter kernelspec list --json
```

If `jupyter kernelspec list --json` is pointing to the expected location, you have (hopefully) fixed the problem. If it is still pointing to an unexpected location repeat the steps!

@ifateri does this work for you?

@jthomasmock thank you for your help.

**Comment by SamEdwardes** [comment] 2022-10-19 15:47
For future reference, here is my attempt at a reprex, but for some reason now it is working 🫠

`Dockerfile`

```docker
FROM python:3.10

# Install quarto
ENV QUARTO_VERSION="1.1.251"
RUN curl -o quarto-linux-amd64.deb -L https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb
RUN apt-get update
RUN apt-get install -y gdebi-core
RUN gdebi -n quarto-linux-amd64.deb

# Create a virtual environment and install jupyter
RUN python -m venv venv
RUN venv/bin/pip install jupyter

# Then install jupyter in your "base" environment
RUN /usr/local/bin/pip install jupyter

# Create a quarto "project"
RUN mkdir /my-project
RUN python -m venv /my-project/venv
RUN /my-project/venv/bin/pip install jupyter
COPY ./doc.qmd /my-project/doc.qmd
```

`doc.qmd`

``````markdown
---
title: Virtual environment
---

Python code chunk:

```{python}
import sys

print(sys.executable)
```
``````

**Steps**

```bash
# On laptop
docker image build --platform linux/amd64 --tag quarto-reprex .
docker run -it --rm --platform linux/amd64 quarto-reprex /bin/bash

# Inside docker container
cd my-project
source venv/bin/activate
quarto render doc.qmd --to markdown --output -

# ---
# title: Virtual environment
# toc-title: Table of contents
# ---
# 
# Python code chunk:
# 
# ::: {.cell execution_count="1"}
# ``` {.python .cell-code}
# import sys
# 
# print(sys.executable)
# ```
# 
# ::: {.cell-output .cell-output-stdout}
#     /my-project/venv/bin/python3
# :::
# :::
```

It used the correct python interpreter.

**Comment by cscheid** [comment] 2022-10-19 15:55
Ok, I'm going to close this but please reopen if you manage to find a reprex.

**Closed by cscheid** 2022-10-19 15:55 UTC
Labels: bug, need-repro, windows

**Comment by cscheid** [comment] 2022-10-20 16:18
@SamEdwardes https://quarto.org/docs/projects/virtual-environments.html

**Comment by SamEdwardes** [comment] 2022-10-20 17:51
Wow that was quick 😉 

Thank you @cscheid!

**Comment by mcanouil** [comment] 2024-06-01 19:14
Please open a new discussion especially when the original one is two years old.

Note that Quarto detect and uses activated environment.
So yours is not at first.
You can check using for example `which python` to locate what Python is used.
