### ISSUE TITLE
callout blocks result in lua filter fail

### ISSUE THREAD

**Issue by aghaynes** [quarto-dev/quarto-cli#9694] opened 2024-05-16 09:32 UTC
### Bug description

Typst no longer handles callout blocks, producing a lua filter error

### Steps to reproduce

Here's a document. When rendered using the newest quarto version, I get a lua filter error 

```
---
title: "Untitled"
format: typst
---
something

::: {.callout}
callout

:::

```

Here's the error:
```
Error running filter C:/PROGRA~1/Quarto/share/filters/main.lua:
C:/PROGRA~1/Quarto/share/filters/main.lua:21222: attempt to concatenate a nil value (local 'icon')
stack traceback:
	C:/PROGRA~1/Quarto/share/filters/main.lua:1211: in local 'filter_fn'
	C:/PROGRA~1/Quarto/share/filters/main.lua:613: in function <C:/PROGRA~1/Quarto/share/filters/main.lua:603>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	C:/PROGRA~1/Quarto/share/filters/main.lua:535: in function <C:/PROGRA~1/Quarto/share/filters/main.lua:524>
	(...tail calls...)
	C:/PROGRA~1/Quarto/share/filters/main.lua:1312: in local 'callback'
	C:/PROGRA~1/Quarto/share/filters/main.lua:1330: in upvalue 'run_emulated_filter_chain'
	C:/PROGRA~1/Quarto/share/filters/main.lua:1366: in function <C:/PROGRA~1/Quarto/share/filters/main.lua:1363>
stack traceback:
	C:/PROGRA~1/Quarto/share/filters/main.lua:535: in function <C:/PROGRA~1/Quarto/share/filters/main.lua:524>
	(...tail calls...)
	C:/PROGRA~1/Quarto/share/filters/main.lua:1312: in local 'callback'
	C:/PROGRA~1/Quarto/share/filters/main.lua:1330: in upvalue 'run_emulated_filter_chain'
	C:/PROGRA~1/Quarto/share/filters/main.lua:1366: in function <C:/PROGRA~1/Quarto/share/filters/main.lua:1363>

```

### Expected behavior

The document would render with just the content of the callout included

### Actual behavior

Error (see above)

### Your environment

IDE: RStudio 2024.04.0 build 735
quarto: 1.5.37

### Quarto check output
```
$ quarto check
Quarto 1.5.37
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.37
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.7 (Conda)
      Path: C:/ProgramData/Anaconda3/python.exe
      Jupyter: 4.8.1
      Kernels: nbstata, python3

(\) Checking Jupyter engine render....[IPKernelApp] ERROR | No such comm target registered: quarto_kernel_setup
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/haynes/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2024-05-16 09:37
@aghaynes Could you properly fill the issue template? Unfortunately, it's not optional as without, we won't be able to do anything about your report.

**Comment by aghaynes** [comment] 2024-05-16 09:38
sorry, i hit enter a couple of times thinking i was in RStudio, and it posted... I've just been editing it :)

**Comment by mcanouil** [comment] 2024-05-16 09:39
The syntax you are using does not exist, see <https://quarto.org/docs/authoring/callouts.html>.

**Comment by aghaynes** [comment] 2024-05-16 09:41
it works in html though... perhaps unintentionally ;)
![image](https://github.com/quarto-dev/quarto-cli/assets/6594028/e10f551b-3cf1-4de1-a82c-fda5e922405e)


Indeed, using .callout-note does work...

**Comment by mcanouil** [comment] 2024-05-16 09:42
Indeed, it works, and it seems autocomplete in editors suggest `.callout` as a valid entry as well ...

**Comment by aghaynes** [comment] 2024-05-16 09:45
it also worked with a previous version of quarto bundled with RStudio (it didnt apply a blue border as it does now, which i would actually perfer for my use case)

**Comment by mcanouil** [comment] 2024-05-16 09:47
In which version exactly did it work for Typst?

**Comment by mcanouil** [comment] 2024-05-16 09:54
To summarise, there are two issues here:

- `.callout` is undocumented.
- `.callout` does not work for Typst format. As far as I can tell, it has never worked (or not as intended as of 1.4.205, found via random testing).

**Comment by mcanouil** [comment] 2024-05-16 10:13
The commit that "broke" `.callout` is cb41de7e3e1506e697b3362c42735b4781a276c9 (kind of ironic considering the commit message^^)

**Comment by aghaynes** [comment] 2024-05-16 12:40
> In which version exactly did it work for Typst (it's a 1.4 feature)?

```
$ quarto typst -V
typst 0.11.0 (2bf9f95d)
```

**Comment by mcanouil** [comment] 2024-05-16 12:47
Sorry, you are confusing me. Typst appeared in Quarto 1.4. And Typst version does not matter here.

From my bisect, the `.callout` never really worked, but did not crashed until the commit I linked.

> it also worked with a previous version of quarto bundled with RStudio

Maybe here you were referring with "it" to using `.callout-TYPE`?
I was asking the version of "quarto bundled with RStudio", but again from my bisect, all 1.4 versions released as stable crashed when using `.callout`.

**Comment by aghaynes** [comment] 2024-05-16 13:50
with "it" i was referring to ::: {.callout} without the type.

I last installed quarto via RStudio, but I'm not sure exactly which version i'm afraid. All i know is that it was working yesterday (RStudio had been reminding about an update only since the beginning of the week, so that couldn't have been all that old, and i know i updated it last to be able to try out typst) and it stopped working when i updated RStudio. If you say that it doesnt work under any stable version of quarto... then i must have changed it... but this is a tiny part of the contents of one such callout from a PDF I had shared with a colleage. As you see, there's no box around it, so i dont think i used any of the documented callout types. The callout was preceeded by a pagebreak, so the whole thing was on this page.
![image](https://github.com/quarto-dev/quarto-cli/assets/6594028/10786567-93f0-4a84-8c19-dda3d0e7815d)

**Comment by mcanouil** [comment] 2024-05-16 13:54
You can see the output if `.callout` in https://github.com/quarto-dev/quarto-cli/issues/9694#issuecomment-2114741908
After https://github.com/quarto-dev/quarto-cli/commit/cb41de7e3e1506e697b3362c42735b4781a276c9 it only leads to crash.

It's possible that somehow, it was fixed and broken again in between 1.4 patches.
Within RStudio, you should be able to use the terminal and call `quarto --version`.

**Comment by aghaynes** [comment] 2024-05-16 14:01
I don't know then. I can't check the version i was using yesterday obviously. I don't think so, but maybe I was imagining it... 
In anycase, we've found something that works in other formats but not typst...

**Comment by cscheid** [comment] 2024-05-16 18:34
We should fix the crash. But, as mcanouil explains, this isn't syntax that we support anywhere; the fix here will be to provide a better error message instead.

**Comment by gordonwoodhull** [comment] 2024-05-16 19:31
Seems like it's not documented correctly, because the implementation explicitly accepts `.callout`

https://github.com/quarto-dev/quarto-cli/blob/fcfdc4ca661e666bc276049b3d2a5ddc2dc10c22/src/resources/filters/customnodes/callout.lua#L169-L171

It hits the `__other` category, which has `nil` icon. A trivial fix:

```diff
diff --git a/src/resources/filters/customnodes/callout.lua b/src/resources/filters/customnodes/callout.lua
index a8b9137f1..e624f682e 100644
--- a/src/resources/filters/customnodes/callout.lua
+++ b/src/resources/filters/customnodes/callout.lua
@@ -700,7 +700,7 @@ end, function(callout)
     { "title", _quarto.format.typst.as_typst_content(title) },
     { "background_color", pandoc.RawInline("typst", background_color) },
     { "icon_color", pandoc.RawInline("typst", icon_color) },
-    { "icon", pandoc.RawInline("typst", "" .. icon .. "()")}
+    icon and { "icon", pandoc.RawInline("typst", "" .. icon .. "()")}
   })
 
   if callout.attr.identifier == "" then
```

**Comment by cderv** [comment] 2024-05-17 14:46
@cscheid @mcanouil I agree we don't document it, but it has been supported since the beginning (and we use it in a test and example also). We can easily change, but just want to share that our current code supports no type. 

* We say its valid 
	https://github.com/quarto-dev/quarto-cli/blob/283ed3ba786e99f7892342972a3bcc1a9bf3c527/src/resources/filters/customnodes/callout.lua#L169-L171
* And we default to `"none"` as a type in this case
	https://github.com/quarto-dev/quarto-cli/blob/283ed3ba786e99f7892342972a3bcc1a9bf3c527/src/resources/filters/customnodes/callout.lua#L6-L17
* Which we handle specifically as appearance `"simple"`
	https://github.com/quarto-dev/quarto-cli/blob/283ed3ba786e99f7892342972a3bcc1a9bf3c527/src/resources/filters/customnodes/callout.lua#L69-L73

So we had a fallback mode for no type provided it seems. Not sure it was a feature, but it works in format. 

It does not on Typst because we match the type against 
https://github.com/quarto-dev/quarto-cli/blob/283ed3ba786e99f7892342972a3bcc1a9bf3c527/src/resources/filters/customnodes/callout.lua#L547-L597

and the `__other` matching unknown style (including "none") uses `nil` for icons 
https://github.com/quarto-dev/quarto-cli/blob/283ed3ba786e99f7892342972a3bcc1a9bf3c527/src/resources/filters/customnodes/callout.lua#L589-L596

So when requestion `attrs` for typst callout, I think we never get `attrs == nil` because of `__other` field. 
https://github.com/quarto-dev/quarto-cli/blob/283ed3ba786e99f7892342972a3bcc1a9bf3c527/src/resources/filters/customnodes/callout.lua#L681-L691

and our callout for typst does not handle a `nil` value for `attrs.icon` 
https://github.com/quarto-dev/quarto-cli/blob/283ed3ba786e99f7892342972a3bcc1a9bf3c527/src/resources/filters/customnodes/callout.lua#L703

So IMO our default fallback for typst is not working, and this is the same error with custom type that someone could maybe define using `quarto.Callout()` 

So I believe we should fix the fallback for callout type in Typst format here as it could crash custom type. 

Also, Our doc at https://quarto.org/docs/prerelease/1.3/custom-ast-nodes/callout.html says `type` is optional in the constructor too... It does not seem optional for Typst here. 

To me no matter the choice made, there is some adaptations to make our code really works as we expect across format.

**Closed** 2024-05-20 16:51 UTC
Labels: bug, callouts, typst
