### ISSUE TITLE
[FR] Make 'Others formats" field configurable (e.g `format: typst` will lead to Typst format and not just PDF)

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#8610] opened 2024-02-05 21:41 UTC
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8596

<div type='discussions-op-text'>

<sup>Originally posted by **fredguth** February  4, 2024</sup>
### Description

When you generate a manuscript that besides html also generate a typst built pdf, in "Other Formats" it shows "Typst".
![image](https://github.com/quarto-dev/quarto-cli/assets/392879/b1667ff5-6d64-44a9-9bc5-7e1ab9f30a84)

Would it be possible to just call it "PDF"?</div>

**Comment by cscheid** [comment] 2024-02-06 16:01
(I think this is a duplicate of a different request to configure this "other format" more generally)

**Comment by mcanouil** [comment] 2024-03-01 10:19
FYI:
- https://github.com/quarto-dev/quarto-cli/issues/7459

```
format-links:
  - html
  - format: typst
    text: PDF
    icon: pdf
  - title: Other Link
     href: https://www.charlesteague.com/
     icon: thumbs-up
```

**Comment by mcanouil** [comment] 2024-03-01 10:24
Note that beyond the fact that's undocumented, there is a bug in this.

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
---
title: "Quarto Playground"
format:
  html: default
  typst: default
format-links:
  - format: typst
    text: PDF
    icon: pdf
---

This is a playground for Quarto.

````

</td><td>

<img width="454" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/8b5188a2-81b6-4c27-858a-70d5130d3e6b">

</td></tr>
</table>

**Comment by cderv** [comment] 2024-03-01 14:10
Oh I did not know it was done. It seems it is even available in 1.4 but it was not added into the changelog. 

So we have here 

- [ ] Document this feature 
- [ ] Fix the bug 

Is that right @mcanouil ?

**Comment by mcanouil** [comment] 2024-03-01 14:44
Yes @cderv 
In case it was not clear about the bug, renaming a format link should remove the default link for the format.

**Comment by cscheid** [comment] 2024-03-01 14:46
Relevant commit here: https://github.com/quarto-dev/quarto-cli/commit/6b62246852f45e0fb87ad450e0f13405ef2aa150

**Comment by jolars** [comment] 2024-05-14 08:34
It would be nice if it was possible to also change the name of the link in case the format comes from an extension. I.e., if I have a multi-format extension that is called foobar, which contributes a pdf format, the link now says PDF (foobar), but It would be nice if I could make it just say PDF instead.

**Comment by cderv** [comment] 2024-05-14 14:37
I believe this is really a documentation issue here. The schema does have the right information of what is allowed 
https://github.com/quarto-dev/quarto-cli/blob/99fad064789715bf2eb11dc9ee3adc59b7c15b8f/src/resources/schema/document-links.yml#L28-L69

This works ok 
````markdown
---
title: "Layout test"
format: 
  html: default
  typst: default
format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf
  - text: Other Link
    href: https://quarto.org
    icon: hand-thumbs-up
---

```{r}
#| label: fig-charts
#| fig-cap: "Charts"
#| layout: "[1, 1]"

plot(cars)
plot(pressure)
```

See @fig-charts-1.

````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/7cbdf984-9b2f-4f18-b096-cea9eb10e026)

Note the correct icon names. 

@jolars you should be able to configure the format using this part
```` 
  - format: typst
    text: PDF
    icon: file-pdf
````

Regarding #9606, it seems adding the `html` format as a string has completely deactivated the duplication problem. 

I'll look into that for #9606 as it seems to be unexpected behavior.

**Closed** 2024-06-24 17:05 UTC
Labels: documentation
