### ISSUE TITLE
Rendering to PDF, DOCX, and HTML fails with Julia 1.10 when making plots

### ISSUE THREAD

**Issue by jdossgollin** [quarto-dev/quarto-cli#8425] opened 2024-01-24 18:30 UTC
### Bug description

Quarto can render to DOCX, HTML, or PDF, but cannot render to all three at once.

When I do, I get an error that seems to relate to the figures being converted one way for docx and another way for pdf.

### Steps to reproduce

Let the following be `bug.qmd`:

````qmd
---
title: "My demo bug"

# use Julia!
jupyter: julia-1.10

# execution options
execute:
  freeze: auto  
  cache: true

format: 
    html: default
    pdf: default
    docx: default
---

This super simple Julia code breaks, provided I use Plots to make a plot

```{julia}
using Plots
```

And we can make a plot that breaks

```{julia}
x = 0:0.01:25
y = sin.(x)
plot(x, y; label="sin(x)")
```
````

Then, `quarto render bug.qmd` causes the following error (see "Error" below). However, `quarto render bug.qmd --to pdf` works, as does `--to html` and `--to docx`

**Important observation:** if I delete the `.docx` conversion (i.e., if I zap `docx: default`) and convert **only** to HTML and PDf then I don't get this error when running `quarto render bug.qmd`. So I think the issue is related to converting SVG images to one format for DOCX and another format for PDF. But that's just my very naive guess!

## Long error message.

This is the long error message when running `quarto render bug.qmd`:

```shell
❯ quarto render bug.qmd
(Notebook read from cache)

pandoc 
  to: html
  output-file: bug.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: My demo bug
  jupyter: julia-1.10
  
(Notebook read from cache)

pandoc 
  to: latex
  output-file: bug.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: My demo bug
  jupyter: julia-1.10
  
(Notebook read from cache)

pandoc 
  to: docx
  output-file: bug.docx
  default-image-extension: png
  
metadata
  title: My demo bug
  jupyter: julia-1.10
  
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages

compilation failed- error
Unable to load picture or PDF file 'bug_files/mediabag/bug_files/figure-pdf/cell-3-output-1.pdf'.
<to be read again> 
                   }
l.218 ...bug_files/figure-pdf/cell-3-output-1.pdf}
                                                   

see bug.log for more information.
```

### Your environment

VS Code, MacOS 14.2.1 (M1 chip)

### Quarto check output

```bash
❯ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.16 (Conda)
      Path: /Users/jamesdoss-gollin/anaconda/bin/python
      Jupyter: 5.3.0
      Kernels: julia-1.10, julia-1.6, julia-1.8, julia-1.9, julia-1.7, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /opt/homebrew/Cellar/r/4.3.2/lib/R
      LibPaths:
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.2/lib/R/library
      knitr: 1.43
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by jdossgollin** [comment] 2024-01-24 18:31
Note: messing with my execute options doesn't change this behavior.

**Comment by cscheid** [comment] 2024-01-24 18:43
Your guess is precisely correct; our handling of multiple-format outputs and temporary files is going wrong.

**Comment by cderv** [comment] 2024-01-24 19:42
I think this is related (even duplicate) to this one 
* https://github.com/quarto-dev/quarto-cli/issues/8373

and it is not related to Julia. 

Note: this is regarding our cleaning order when multiple formats using the same file. We had similar issues in the past with HTML formats I believe. Can't find it but I'll reference if I can.

**Comment by cscheid** [comment] 2024-06-17 18:17
(This is a duplicate of #8373)

**Closed** 2024-06-17 18:19 UTC
Labels: bug, duplicate
