### ISSUE TITLE
ERROR: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by yurivict** [quarto-dev/quarto-cli#358] opened 2022-02-20 17:32 UTC
I installed the [release files](https://github.com/quarto-dev/quarto-cli/releases/download/v0.9.30/quarto-0.9.30-linux-amd64.tar.gz) into /usr/local and there's this error on a simple testcase:
```
$ quarto render hello.qmd --to html
ERROR: TypeError: Path must be a string. Received undefined
```

**Comment by jjallaire** [comment] 2022-02-23 14:32
@dragonstyle It looks like this is for a simple tarball install on Linux. Could you try to repro this?

**Comment by dragonstyle** [comment] 2022-02-23 16:09
I think that the issue is how we're resolving the `share` dir (we currently are assuming that it is directly adjacent to the to `bin` dir). I've made a change to try to resolve the `share` path differently when running running from `/usr/local/bin` here:

https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.38

@yurivict do you mind giving it a try and letting me know how it works for you? If you still run into issues, can you let me know the paths where you're placing `bin` and `share` directories- I'll try to make the resolution more sophisticated.

**Closed** 2022-03-16 11:06 UTC
