### ISSUE TITLE
Typst output geom_sf with fill aes produces black box

### ISSUE THREAD

**Issue by ttalVlatt** [quarto-dev/quarto-cli#9245] opened 2024-04-01 16:02 UTC
### Bug description

When making a report with typst output, it seems geom_sf with a fill aes() produces a black box when rendered.

### Steps to reproduce

````qmd
---
format: typst
---


```{r}
#| message: false
library(ggplot2)
library(sf)

nc <- read_sf(system.file("shape/nc.shp", package="sf"))
```

## Works fine without fill aes

```{r}
ggplot(nc) +
  geom_sf(aes())
```

## But produces black square with fill aes

```{r}
ggplot(nc) +
  geom_sf(aes(fill = BIR74))
```
````

### Expected behavior

It should produce as geom_sf ggplot with fill aes

### Actual behavior

It produces a black box

### Your environment

IDE RStudio Version 2023.12.1+402 (2023.12.1+402)
macOS Monterey 12.7.3

### Quarto check output

```
quarto check
Quarto 1.4.552
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.552
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/matt/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment] 2024-04-01 16:54
`system.file("shape/nc.shp"` Can you create an example without a file that we cannot load ourselves?

**Comment by cscheid** [comment] 2024-04-01 16:57
I think it's the same problem as this: https://github.com/quarto-dev/quarto-cli/discussions/9217

We're going to fix this soon in Quarto directly, but in the mean time, can you try adding the following to your document metadata?

````
knitr:
  opts_chunk:
    dev: svglite
````

**Comment by ttalVlatt** [comment] 2024-04-01 18:10
My mistake, I thought that shapefile was part of `sf`... Either way, yes, that fixed the issue for now, thanks for the quick response!

**Comment by mcanouil** [comment] 2024-04-01 18:14
Yes, it is part of `sf`.
The main issue in your example is the formatting which currently makes your example unusable without manual editing.

Anyhow, the issue is clearly the SVG graphic device used as switching to `svglite` solves the problem.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by ttalVlatt** [comment] 2024-04-01 18:20
Oh gotcha, gotcha, will bear in mind for future! Thanks everything y'all do!

**Comment by mcanouil** [comment] 2024-04-01 18:21
@ttalVlatt could you at least edit your example to make it readable/usable? Thank your for your cooperation.

**Comment by ttalVlatt** [comment] 2024-04-01 18:27
Done! I was able to copy and run it now. Let me know if you need anything else!

**Comment by cscheid** [comment] 2024-04-01 19:30
(@ttalVlatt I was wrong, forgive me embarrassing ignorance of R! Thanks for the report as well.)

**Comment by cderv** [comment] 2024-04-02 13:40
For completeness, this is not happening on Windows. 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/e4ceed73-8235-40a0-b158-32095693af8d)

Which was also the case for 
* #9217 

So this is related to SVG graphic device in R and Mac OS. I'll test on linux to see if this happens too.

**Comment by mcanouil** [comment] 2024-04-02 14:03
FYI, on macOS:

```r
capabilities()
#>       jpeg         png        tiff       tcltk         X11        aqua 
#>       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
#>   http/ftp     sockets      libxml        fifo      cledit       iconv 
#>       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE 
#>        NLS       Rprof     profmem       cairo         ICU long.double 
#>       TRUE        TRUE        TRUE        TRUE        TRUE       FALSE 
#>    libcurl 
#>       TRUE 
```

**Comment by cderv** [comment] 2024-04-02 14:24
Thanks ! As expected, `X11` is true. so it could definitely be related.

**Comment by cderv** [comment] 2024-04-03 14:19
A note regarding this issue , and related to #9217. if this is because some `filter` tag are used in the SVG file, it seems this should be now handled by Typst 
- https://github.com/typst/typst/issues/2988 (closed by https://github.com/typst/typst/pull/3254) 

This is available in v0.11.0 of typst that we should use soon. 

From https://typst.app/docs/changelog/#v0.11.0 

> Added support for SVG filters

@gordonwoodhull  we should test this for new typst too.

**Comment by gordonwoodhull** [comment] 2024-04-04 13:51
Confirmed, Typst 0.11 fixes this example (and also corrects the black box in #9217). I also repro the black boxes using Typst 0.10

I guess I am confused why svglite also fixes this.

**Comment by mcanouil** [comment] 2024-04-04 13:59
> I guess I am confused why svglite also fixes this.

I believe the main difference between `svglite` and default SVG device in R, is on how they handle text.
`svglite` keeps text as text (it can also embed fonts).
Default SVG encode all texts as paths.

**Comment by gordonwoodhull** [comment] 2024-04-04 18:57
Here it apparently has something to do with a different way gradients are drawn in svglite. 

Typst is now upgraded to 0.11 on `main` and will go into the next 1.5.* release, so closing this.

**Closed by gordonwoodhull** 2024-04-04 18:57 UTC
Labels: bug, knitr, typst
