### ISSUE TITLE
Quarto Tikz Error

### ISSUE THREAD

**Issue by jlgraves-ubc** [quarto-dev/quarto-cli#10481] opened 2024-08-08 20:38 UTC
### Bug description

The recent update to the Quarto CLI seems to have changed the functionality of `tikz` rendering.  Code that was working previously seems to be failing now; different render targets will work or fail, with opaque error messages.

### Steps to reproduce

```bash
quarto render 02_sd.qmd --to revealjs
```
will produce correctly rendered RevealJS slides.  However,

```bash
quarto render 02_sd.qmd --to pdf
```

produces:

```bash
Error in !raw : invalid argument type
Calls: .main ... knitr_options -> has_crop_tools -> <Anonymous> -> <Anonymous>
Execution halted
```

This error is very cryptic, but has something to do with the `tikz` cell in the example below, since it compiles without this.

The relevant minimal part of the file `02_sd.qmd` is:

````qmd
---
title: 02 - Markets and Supply & Demand
author: Jonathan Graves
date: last-modified
version: 1.0
format: 
  revealjs:
    footer: "v{{< meta version >}} © Jonathan Graves 2024"
  pdf: 
    documentclass: scrreprt
    toc: false

smaller: false 
slide-number: true
scrollable: false
touch: true
code-fold: true
#logo:
show-slide-number:  all
execute:
  echo: false
  cache: false
---

## Individual Choices, Aggregate Consequences

Goods are fundamental to economic models and analysis.

* However, it's equally important to consider how they are exchanged.
* This process, in aggregate, creates the kinds of things measured in macroeconomics, like GDP.

We often call these _modes of exchange_.

```{r, engine = 'tikz', fig.cap = "Supply and Demand Model", fig.ext = 'png'}

\usetikzlibrary{arrows,intersections}

\begin{tikzpicture}[
    thick,
    >=stealth',
    dot/.style = {
      draw,
      fill = white,
      circle,
      inner sep = 0pt,
      minimum size = 4pt
    }
  ]

  \coordinate (0) at (0,0);
  \draw[thick,->] (0) -- (0,10) node[label = {above:$P$}] {};
  \draw[thick,->] (0) -- (10,0) node[label = {right:$Q$}] {};

  \draw (-0.05,9) -- (0,9) node[label = left:$60$] {};

  \draw (-0.05,7.5) -- (0,7.5) node[label = left:$50$] {};

  \draw (-0.05,5.25) -- (0,5.25) node[label = left:$35$] {};

  \draw (-0.05,3.75) -- (0,3.75) node[label = left:$25$] {};

  \draw (-0.05,0) -- (0,0) node[label = left:$0$] {};

  \draw (0,0) -- (0,-0.05) node[label = below:$0$] {};

  \draw (1.8,0) -- (1.8,-0.05) node[label = below:$1$] {};

  \draw (3.6,0) -- (3.6,-0.05) node[label = below:$2$] {};

  \draw (5.4,0) -- (5.4,-0.05) node[label = below:$3$] {};


  \draw (7.2,0) -- (7.2,-0.05) node[label = below:$4$] {};

  \draw (9,0) -- (9,-0.05) node[label = below:$5$] {};

\end{tikzpicture}
```

````

### Expected behavior

The PDF should render just like the RevealJS document; this was working as of 2023-09 (not sure what CLI version, sorry), but now it does not.

### Actual behavior

The error thrown is:

```bash
Error in !raw : invalid argument type
```

### Your environment

- IDE: Visual Studio Code 1.92.1
- OS: Windows 11

### Quarto check output

```
Quarto 1.5.56
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.56
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: 869685

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\ProgramData\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.0
      Path: C:/Python/python.exe
      Jupyter: 5.0.0
      Kernels: ir, stata, python3

(\) Checking Jupyter engine render....[IPKernelApp] ERROR | No such comm target registered: quarto_kernel_setup
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/Jonathan Graves/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.1/library
      knitr: 1.47
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2024-08-08 22:24
Thanks for the report.

Unfortunately, we can't use your metadata as there many things we don't have in it.
Note also that your example is not minimal. Are all the options necessary (including the commented lines)? Could you remove everything not necessary to reproduce the issue and make your example self-contained, *i.e.*, see my example below or the one from the issue template.


Using a simplified and self-contained version, I cannot reproduce.


<table>
<tr><th>Input</th><th>Output</th></tr>
<tr><td>

````qmd
---
title: "Quarto Playground"
format: pdf
engine: knitr
execute:
  echo: false
---

```{tikz}
#| fig-cap: Supply and Demand Model
#| fig-ext: png
\usetikzlibrary{arrows,intersections}
\begin{tikzpicture}[
    thick,
    >=stealth',
    dot/.style = {
      draw,
      fill = white,
      circle,
      inner sep = 0pt,
      minimum size = 4pt
    }
  ]
  \coordinate (0) at (0,0);
  \draw[thick,->] (0) -- (0,10) node[label = {above:$P$}] {};
  \draw[thick,->] (0) -- (10,0) node[label = {right:$Q$}] {};
  \draw (-0.05,9) -- (0,9) node[label = left:$60$] {};
  \draw (-0.05,7.5) -- (0,7.5) node[label = left:$50$] {};
  \draw (-0.05,5.25) -- (0,5.25) node[label = left:$35$] {};
  \draw (-0.05,3.75) -- (0,3.75) node[label = left:$25$] {};
  \draw (-0.05,0) -- (0,0) node[label = left:$0$] {};
  \draw (0,0) -- (0,-0.05) node[label = below:$0$] {};
  \draw (1.8,0) -- (1.8,-0.05) node[label = below:$1$] {};
  \draw (3.6,0) -- (3.6,-0.05) node[label = below:$2$] {};
  \draw (5.4,0) -- (5.4,-0.05) node[label = below:$3$] {};
  \draw (7.2,0) -- (7.2,-0.05) node[label = below:$4$] {};
  \draw (9,0) -- (9,-0.05) node[label = below:$5$] {};
\end{tikzpicture}
```
````

</td><td>

<img width="624" alt="image" src="https://github.com/user-attachments/assets/43495c47-bb41-4e0d-9099-7a3f2d750f36">

</td></tr>
</table>

Using the development version:

```sh
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      commit: fe989e5468f2a5e0545a0db441a771a74f9e3098
      Path: /Users/mcanouil/Projects/quarto/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/mcanouil/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.4
      Path: /Users/mcanouil/Projects/quarto/quarto-playground/.venv/bin/python3
      Jupyter: 5.7.2
      Kernels: julia-1.10, python3

[✓] Checking Jupyter engine render....OK

(\) Checking R installation...........ℹ R version 4.4.1 (2024-06-14)
! Config '~/.Rprofile' was loaded!
[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/mcanouil/Projects/quarto/quarto-playground/renv/library/macos/R-4.4/aarch64-apple-darwin20
        - /Users/mcanouil/Library/Caches/org.R-project.R/R/renv/sandbox/macos/R-4.4/aarch64-apple-darwin20/f7156815
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

**Comment by jlgraves-ubc** [comment] 2024-08-08 23:02
OK, I updated the example with a self-contained one.  Same issue occurs.

**Comment by mcanouil** [comment] 2024-08-08 23:04
Does my example work for you?
It does for me using the same Quarto version as you.

**Comment by jlgraves-ubc** [comment] 2024-08-09 19:36
No, same error occurs.

**Comment by mcanouil** [comment] 2024-08-09 20:19
Could you update `knitr`?

**Comment by cscheid** [comment] 2024-08-15 15:42
```
Error in !raw : invalid argument type
Calls: .main ... knitr_options -> has_crop_tools -> <Anonymous> -> <Anonymous>
Execution halted
```

This points to an error in `knitr`. I'm fairly sure it's not a Quarto issue, and I'll go ahead and close this. If I'm wrong and there's new evidence to the contrary, please reopen the issue.

**Closed by cscheid** 2024-08-15 15:42 UTC
Labels: bug, needs-repro

**Comment by jlgraves-ubc** [comment] 2024-08-16 14:55
OK, I'm documenting this fix.

1.  It doesn't look like it was directly an issue with `knitr` since I updated the package and it didn't resolve the issue.

However, given the comments here, I figured that it might be a R issue more generally.  So, I updated my R installation.

Originally, I was using R  Version: 4.2.1 and after updating the problem resolved:

```bash
Quarto 1.5.56
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.56
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: 869685

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\ProgramData\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.4.1
      Path: C:/PROGRA~1/R/R-44~1.1
      LibPaths:
        - C:/Program Files/R/R-4.4.1/library
      knitr: 1.48
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK
```

So, tag this as "resolved" or at least fixable for future reference.
