### ISSUE TITLE
Mermaid subgraphs in a flowchart have a too dark background

### ISSUE THREAD

**Issue by dmkaplan2000** [quarto-dev/quarto-cli#9259] opened 2024-04-03 09:55 UTC
### Bug description

I am starting to use mermaid to make flowcharts in my presentations and I just noticed that subgraphs in a mermaid flowchart look quite bad by default, with the subgraph background being really dark and taking over the node backgrounds (the nodes seem to be alpha blended with the dark and so they appear nearly as dark) so the nodes are hard to see. This is fixable with either using a mermaid theme or custom CSS, but it seems like the default should be legible.

### Steps to reproduce

This document demonstrates the issue:

````quarto
---
format: 
  html: default
---

## Subgraph has too dark background

```{mermaid}
flowchart TB
    c1-->a2
    subgraph ide1 [one]
    a1-->a2
    end
```

## Better, but nodes alpha blended

```{mermaid}
flowchart TB
    c1-->a2
    subgraph ide1 [one]
    a1-->a2
    end
    
    style ide1 fill: lightyellow
```

## Uniform styling

```{mermaid}
flowchart TB
    c1-->a2
    subgraph ide1 [one]
    a1-->a2
    end
    
    style c1 fill: lightgray
    style a1 fill: lightgray
    style a2 fill: lightgray
    style ide1 fill: lightyellow
```

````

Another solution using mermaid theme:

````quarto
---
format: 
  html:
    mermaid: 
      theme: neutral
---

## Legible...

```{mermaid}
flowchart TB
    c1-->a2
    subgraph ide1 [one]
    a1-->a2
    end
```
````

### Expected behavior

Legible flow chart

### Actual behavior

Subgraph background too dark

### Your environment

RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-29) for Ubuntu Focal
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

OS: Ubuntu 22

### Quarto check output

```bash
$ quarto check
Quarto 1.5.27
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.27
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/dmk/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.13 (Conda)
      Path: /home/dmk/miniforge3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /usr/lib/R
      LibPaths:
        - /home/dmk/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment] 2024-04-03 10:36
Thanks for opening an issue ! 

I do think this is a duplicate of 
* https://github.com/quarto-dev/quarto-cli/issues/9178

What do you think ?

**Comment by mcanouil** [comment] 2024-04-03 13:42
Duplicate of https://github.com/quarto-dev/quarto-cli/issues/9178

**Closed by mcanouil** 2024-04-03 13:42 UTC
Labels: duplicate
