### ISSUE TITLE
Default Mermaid theme makes subgraphs hard to read

### ISSUE THREAD

**Issue by adrhill** [quarto-dev/quarto-cli#10214] opened 2024-07-03 10:08 UTC
First of all, thanks a lot for your work on Quarto!

I found that when rendering nested Mermaid graphs, the resulting diagrams are close to unreadable, even though the [Quarto documentation advertises theming compatibility](https://quarto.org/docs/authoring/diagrams.html#default-colors-for-mermaid-diagrams).
The problem is especially bad when using revealjs.

**Revealjs output:**
<img width="768" alt="image" src="https://github.com/quarto-dev/quarto/assets/20258504/f2c1c387-2f1a-48f6-a2dd-ef2f1c622a53">

**HTML output:**
<img width="507" alt="image" src="https://github.com/quarto-dev/quarto/assets/20258504/2ff98eb2-36c9-4880-872a-d1887cd3334b">

Minimal example:
````md
---
title: "Mermaid test"
format: revealjs
---

## Mermaid test
```{mermaid}
%%| echo: false
flowchart LR

  subgraph B
    direction TB
    C-->D
  end

  A-->B
```
````

**Comment by mcanouil** [comment] 2024-07-03 15:55
I believe this to be a duplicate of:
- #9178

**Closed** 2024-07-03 15:56 UTC
Labels: duplicate
