### ISSUE TITLE
Beamer columns not working in 1.4

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#6937] opened 2023-09-21 15:03 UTC
### Bug description

It seems that column divs have no effect with the Beamer format in 1.4.

### Steps to reproduce

Render the following (based on the [doc example](https://quarto.org/docs/presentations/beamer.html#multiple-columns)):

```
# Slide

:::: {.columns}

::: {.column width="40%"}
contents...
:::

::: {.column width="60%"}
contents...
:::

::::
```

### Expected behavior

The PDF should show two columns.

### Actual behavior

The PDF shows two paragraphs in a single column. Indeed the generated `tex` contains:

```
\begin{frame}{Slide}
\phantomsection\label{slide}
contents\ldots{}

contents\ldots{}
\end{frame}
```

while with quarto 1.3.450 it was

```
\begin{frame}{Slide}
\protect\hypertarget{slide}{}
\begin{columns}[T]
\begin{column}{0.4\textwidth}
contents\ldots{}
\end{column}

\begin{column}{0.6\textwidth}
contents\ldots{}
\end{column}
\end{columns}
\end{frame}
```

### Your environment

- OS: Pop!_OS 22.04

### Quarto check output

```bash
Quarto 1.4.376
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.376
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3, julia-1.8, octave, sos, julia-1.9, atk, sagemath

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /usr/lib/R
      LibPaths:
        - /home/j/R/x86_64-pc-linux-gnu-library/4.1
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.40
      rmarkdown: 2.17

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2023-09-21 15:13
Closing as duplicate of:
- https://github.com/quarto-dev/quarto-cli/issues/6936

Next time, could you ensure your example is complete, i.e., since your issue is about `format: beamer`, then it is require in your example.

**Closed by mcanouil** 2023-09-21 15:13 UTC
Labels: bug

**Comment by knuesel** [comment] 2023-09-21 15:48
Sure! and sorry for the duplicate.

(I rendered the example with `quarto render a.qmd --to beamer` so it was complete in this sense, but I'll try to remember setting the format in a header next time :) )

**Comment by mcanouil** [comment] 2023-09-21 16:54
No worries, the other was opened within the same hour.

"steps to reproduce" would also contain `quarto render a.qmd --to beamer` if you don't put the format in the document, but putting everything in the document makes it way easier to use or to identify what's wrong directly (when possible).
