### ISSUE TITLE
Lang option not working in cross-reference

### ISSUE THREAD

**Issue by cizgeler** [quarto-dev/quarto-cli#9263] opened 2024-04-03 17:46 UTC
### Bug description

I can use a collout block with the language option `tr`. For example, it correctly converts `Tip` to `Tavsiye`. But when I put a tag to cross reference the block, the language option does not work in the output. `Tip` is written as `Tip` again. 

### Steps to reproduce

````
---
title: "Colllout block"
format: html
lang: tr
---

::: {.callout-tip}
This place works right.
:::

::: {#tip-example .callout-tip}
## Cross-Referencing a Tip
This place doesn't work right.
:::

See @tip-example...
````

### Expected behavior

`{#tip-example .callout-tip}` the block should say `Tavsiye`, not `Tip`.

### Your environment

- IDE: VSCode 1.87.2-1709912201
- Pardus GNU/Linux 23

### Quarto check output

```
Quarto 1.5.28
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.10.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.28
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /usr/bin/python3
      Jupyter: 4.12.0
      Kernels: python3

(-) Checking Jupyter engine render....[IPKernelApp] ERROR | No such comm target registered: quarto_kernel_setup
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /usr/lib/R
      LibPaths:
        - /home/acarzfr/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment] 2024-04-03 18:41
Thanks for the report. This should be indeed sensible to the language as other cross reference item.

**Comment by cderv** [comment] 2024-04-03 18:52
@cscheid I can try have a look in how to add support for our language file for those crossref item. it seems it should be a working feature. Though I understand this new support for crossref callouts may come with custom crossref, where there is no language option either. 

Anyhow, as we handle language for callouts directly, it seems we should support when they are cross referenced too.

**Comment by cizgeler** [comment] 2024-04-03 19:01
"Anyhow, as we handle language for callouts directly, it seems we should support when they are cross referenced too." I totally agree with that. :+1:

**Comment by mcanouil** [comment] 2024-04-17 09:00
Duplicate of #8281 

@MarcoPortmann Thanks for catching the duplicate.

**Comment by cizgeler** [comment] 2024-04-17 09:02
> Bu hata #8281 ile ilgili mi ?

It seems so.

**Closed** 2024-04-17 09:01 UTC
Labels: duplicate
