### ISSUE TITLE
Avoid incrementing the footnote number when reusing a footnote reference

### ISSUE THREAD

**Issue by bjornasm** [quarto-dev/quarto-cli#10156] opened 2024-06-27 09:04 UTC
### Bug description

Sometimes you want to reference the same footnote several places in the text. Even if using the same identifier to a footnote, it seems like Quarto/pandoc auto-increments the footnote.

### Steps to reproduce

````qmd
---
title: "My Document"
---

Here is a footnote reference,[^1] and this is referencing the same [^1].
Trying with inline footnotes ^[Inline] and another inline footnote^[Inline]

[^1]: This is an example footnote.

````

### Expected behavior

Expected behavior would be (in my opinion at least) that the references to the same footnote should have the same numbering.

### Actual behavior

The numbering is auto incrementing, i.e the above results in the following footnotes: 

**Footnotes:**

1. This is an example footnote.
2. This is an example footnote.
3. Inline
4. Inline 

### Your environment

VSCode

### Quarto check output

````bash
Quarto 1.4.553
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK      
[>] Checking Quarto installation......OK
      Version: 1.4.553
      Path: C:\Users\bjornbsm\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\bjornbsm\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: C:/Users/bjornbsm/Prosjekt/DeepFishing/deepFishvenv/Scripts/python.exe
      Jupyter: 5.7.2
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org
````

**Comment by mcanouil** [comment] 2024-06-27 11:20
Duplicate of https://github.com/quarto-dev/quarto-cli/issues/5440

**Closed** 2024-06-27 11:20 UTC
Labels: duplicate
