### ISSUE TITLE
FATAL internal error with Quarto CLI if `fig-cap` is used instead of `tbl-cap`

### ISSUE THREAD

**Issue by GegznaV** [quarto-dev/quarto-cli#6909] opened 2023-09-19 18:53 UTC
### Bug description

The following error appears if `fig-cap` is accidentally used instead of  `tbl-cap` in a Jupyter Notebook with a displayed table.

```
FATAL (C:/Users/user/AppData/Local/Programs/Quarto/share/filters/main.lua:12174) An error occurred:
This is an internal error. Please file a bug report at https://github.com/quarto-dev/quarto-cli/

Error running filter C:/Users/user/AppData/Local/Programs/Quarto/share/filters/main.lua:
...user/AppData/Local/Programs/Quarto/share/filters/main.lua:2009: attempt to call a nil value (global 'crash_with_stack_trace')
stack traceback:
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:1590: in function 'fail'
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:1595: in function 'internal_error'
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:12174: in function <...user/AppData/Local/Programs/Quarto/share/filters/main.lua:12123>
        (...tail calls...)
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:2317: in function <...user/AppData/Local/Programs/Quarto/share/filters/main.lua:2311>
        (...tail calls...)
        [C]: in ?
        [C]: in method 'walk'
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:148: in function <...user/AppData/Local/Programs/Quarto/share/filters/main.lua:138>
        (...tail calls...)
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:725: in local 'callback'
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:738: in upvalue 'run_emulated_filter_chain'
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:773: in function <...user/AppData/Local/Programs/Quarto/share/filters/main.lua:770>
stack traceback:
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:148: in function <...user/AppData/Local/Programs/Quarto/share/filters/main.lua:138>
        (...tail calls...)
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:725: in local 'callback'
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:738: in upvalue 'run_emulated_filter_chain'
        ...user/AppData/Local/Programs/Quarto/share/filters/main.lua:773: in function <...user/AppData/Local/Programs/Quarto/share/filters/main.lua:770>
```

### Steps to reproduce

1) Create a Jupyter notebook with Python engine.
2) Create a cell with code as follows:
![image](https://github.com/quarto-dev/quarto-cli/assets/12725868/d423575d-1313-42c9-8fd2-6b64c431bbf8)
```python
# | label: tbl-1
# | fig-cap: There fig-cap should be tbl-cap.
import pandas as pd
pd.DataFrame({"a": [1, 5, 2]})
```
3. Run Python code (cell must have output)
4. Try to render the Jupyter Notebook with Python code into HTML:
```
quarto render notebook.ipynb
```

The notebook with the example is added:
[notebook.zip](https://github.com/quarto-dev/quarto-cli/files/12665397/notebook.zip)

### Expected behavior

**Option A:** Render HTML (with the table caption missing) but give an **informative** warning.

**Option B:** Give an **informative** error message with instructions on how to fix the issue.

### Actual behavior

Rendering to HTML crashes with a fatal error. 

### Your environment

- GitBash terminal via VSCode
![image](https://github.com/quarto-dev/quarto-cli/assets/12725868/e584b355-646a-4a8d-9c18-e7c2ba4be097)

- Quarto 1.4.373
- Python 3.11

### Quarto check output

```bash
$ quarto check
Quarto 1.4.373
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK      
[>] Checking Quarto installation......OK
      Version: 1.4.373
      Path: C:\Users\user\AppData\Local\Programs\Quarto\bin
      CodePage: unknown

[>] Checking tools....................OK
      TinyTeX: v2023.01
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\user\AppData\Roaming\TinyTeX\bin\win32\
      Version: 2022

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: C:/Users/user/anaconda3/envs/env/python.exe
      Jupyter: 5.3.1
      Kernels: python3, ir, julia-1.9, proj-ml-1

(|) Checking Jupyter engine render....0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
(/) Checking Jupyter engine render....0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-4.3.1
      LibPaths:
        - C:/Users/user/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.44
      rmarkdown: 2.24

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment] 2023-09-19 18:58
Thanks for the report! I think I _just_ fixed this on `main`, by sheer luck, a couple of hours ago (I can't repro that locally). I'll create a new prerelease binary soon enough and we can check, but if you're willing to run the github version, you should be able to ascertain that right now.

**Comment by cscheid** [comment] 2023-10-04 18:44
I still can't reproduce this with the latest pre-release and this document:

````
---
title: issue-6909
format:
  html:
    embed-resources: true
---

```{python}
import pandas as pd
pd.DataFrame({"a": [1, 5, 2]})
```
````

I'm going to go ahead and close the issue. Please feel free to reopen if it doesn't work on the latest pre-releases. Thanks!

**Closed by cscheid** 2023-10-04 18:44 UTC
Labels: bug, verify-fixed
