### ISSUE TITLE
Quarto says it can't find R when an error occurs in an R code chunk

### ISSUE THREAD

**Issue by michaelwalshe** [quarto-dev/quarto-cli#8602] opened 2024-02-05 09:25 UTC
### Bug description

When I render a quarto document with some R code that has an error, it correctly reports the error but also says at the end "Unable to locate an installed version of R".

### Steps to reproduce

Using the following quarto doc:

````
---
title: test
format: html
---

Testing testing

```{r}
# Call an object that doesn't exist
this_does_not_exist
```
````

### Expected behavior

This should produce the error message, but not warn about R installations as R is installed and the code will run

### Actual behavior

This produces, from `quarto preview test.qmd --to html --no-watch-inputs --no-browse` via RStudio:

```
processing file: test.qmd
  |...................................                 |  67% [unnamed-chunk-1]
Quitting from lines 10-12 [unnamed-chunk-1] (test.qmd)
Error:
! object 'this_does_not_exist' not found
                                                                                                            
Execution halted

Unable to locate an installed version of R.
Install R from https://cloud.r-project.org/
```

### Your environment

- IDE: RStudio 2023.12.1 "Ocean Storm" Release (4da58325, 2024-01-28) for windows
- R: "R version 4.3.1 (2023-06-16 ucrt)"
- Quarto: 1.3.45
- OS: Windows 10

### Quarto check output

```bash
$ quarto check
A new release of Deno is available: 1.28.2 → 1.40.3 Run `deno upgrade` to install it.

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Users\Michael.Walshe.AMADEUS\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: C:/Users/Michael.Walshe.AMADEUS/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.4.0
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\Michael.Walshe.AMADEUS\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\Michael.Walshe.AMADEUS\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[>] Checking Jupyter engine render....OK
```

**Comment by mcanouil** [comment] 2024-02-05 11:37
Duplicate of #6929

**Closed by mcanouil** 2024-02-05 11:37 UTC
Labels: bug
