### ISSUE TITLE
Listing pdf output

### ISSUE THREAD

**Issue by everval** [quarto-dev/quarto-cli#8214] opened 2024-01-10 18:05 UTC
Using listing to generate a list of publications works in html output but it does not show on pdf output. 
The difference in output can be seen here:
[https://everval.github.io/cv.html](https://everval.github.io/cv.html)

**Comment by gbruer15** [comment] 2024-03-20 19:57
This is a duplicate of #1752

**Comment by mcanouil** [comment] 2024-03-20 23:10
Duplicate of #1752

Indeed.

**Closed by mcanouil** 2024-03-20 23:10 UTC
Labels: enhancement
