### ISSUE TITLE
`column:` specifications cause `{gt}` tables to appear stacked instead of side-by-side when using `layout:` or `layout-ncol`.

### ISSUE THREAD

**Issue by RegalPlatypus** [quarto-dev/quarto-cli#8791] opened 2024-02-19 19:15 UTC
### Bug description

- Primary: any specification of `column` forces side-by-side tables into a stacked configuration.
- Secondary: Without outputting my tables `as_raw_html()`, tables are rendered with an unexpected duplicated bottom border.

### Steps to reproduce

````
---
title: "Reprex"
author: "John Smith"
date: 2024-02-19
format:
  html:
    toc: true
    toc-location: left
    anchor-selections: false
    fig-cap-location: bottom
    tbl-cap-location: top
    number-sections: true
    smooth-scroll: true
    self-contained: true
    output-file: "reprex.html"
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = TRUE, dev = "png", cache = FALSE)
```

```{r}
#| label: head
#| message: false
#| warning: false
#| include: false

library(tidyverse)
library(showtext)
library(gt)
```

```{r}
#| label: meat-and-potatoes
#| message: false
#| warning: false
#| include: false

#THEMES###
gt_theme_538 <- function(data,...) {
  data %>%
    opt_table_font(font = list(google_font("Roboto"), "sans-serif")) %>%
    tab_style(
      style = cell_borders(
        sides = "bottom", color = NULL, weight = px(2)
      ),
      locations = cells_body(
        columns = everything(),
        rows = nrow(data$`_data`)
      )
    )  %>% 
    tab_options(
      column_labels.background.color = "white",
      table.border.top.width = px(3),
      table.border.top.color = NULL,
      table.border.bottom.color = NULL,
      table.border.bottom.width = px(3),
      column_labels.border.top.width = px(3),
      column_labels.border.top.color = NULL,
      column_labels.border.bottom.width = px(3),
      column_labels.border.bottom.color = "black",
      data_row.padding = px(3),
      source_notes.font.size = 12,
      table.font.size = pct(100),
      table.font.weight = "300",
      heading.align = "left",
      ...
    ) 
}

my.table <- datasets::iris %>%
  group_by(Species) %>%
  summarise(mean.sepal = mean(Sepal.Length),
            n = n()) %>%
  gt() %>%
  cols_label(mean.sepal = html("Mean Sepal<br />Length (mm)")) %>%
  fmt_number(mean.sepal, decimals = 1) %>%
  gt_theme_538()

```

```{r}
#| label: tbl-double-normal
#| tbl-cap: Normal gt output adds an unexpected line at the bottom of the gt table. Table widths can be modified using table.width in table_options().
#| tbl-subcap: 
#| - Left caption.
#| - Right caption.
#| tbl-cap-location: top
#| layout-ncol: 2
#| echo: false
#| message: false
#| warning: false

my.table
my.table %>% tab_options(table.width = pct(100))
```
<br>
<br>
<br>
```{r}
#| label: tbl-double-raw
#| tbl-cap: The line can be removed by outputting as raw HTML. The table.width option still works here.
#| tbl-subcap: 
#| - Left caption.
#| - Right caption.
#| tbl-cap-location: top
#| layout-ncol: 2
#| echo: false
#| message: false
#| warning: false

my.table %>% as_raw_html()
my.table %>% tab_options(table.width = pct(100)) %>% as_raw_html()
```
<br>
<br>
<br>
```{r}
#| label: tbl-double-ncol
#| tbl-cap: "Any specification of 'column' causes the tables to become stacked. I have found no way to position gt tables side-by-side while increasing the page column and table widths."
#| tbl-subcap: 
#| - Left caption.
#| - Right caption.
#| tbl-cap-location: top
#| layout-ncol: 2
#| column: body-outset
#| echo: false
#| message: false
#| warning: false

my.table %>% as_raw_html()
my.table %>% as_raw_html()
```
````

### Expected behavior

````
```{r}
#| label: tbl-double-ncol
#| tbl-cap: Main Caption
#| tbl-subcap: 
#| - Left caption.
#| - Right caption.
#| tbl-cap-location: top
#| layout-ncol: 2
#| column: body-outset
#| echo: false
#| message: false
#| warning: false

my.table %>% as_raw_html()
my.table %>% as_raw_html()
```
````
This should produce two side-by-side gt tables with the page column increased to `body-outset` and table widths increased accordingly. 

### Actual behavior

Instead of the expected behavior, tables end up stacked. I have found no way to position tables side-by-side while making a `page:` specification.

### Your environment

- IDE: RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-07) for windows
- OS: 
  + Edition	Windows 10 Business
  + Version	21H2
  + Installed on	‎6/‎30/‎2022
  + OS build	19044.3086
  + Experience	Windows Feature Experience Pack 1000.19041.1000.0

### Quarto check output

```
Quarto 1.4.550
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.550
      Path: C:\Users\AaronBrown\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.08
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\AaronBrown\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/AaronBrown/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2024-02-19 19:30
Thanks for the report!

Duplicate of #8763

**Closed** 2024-02-19 19:31 UTC
Labels: duplicate

**Comment by RegalPlatypus** [comment] 2024-02-19 20:13
@mcanouil Thanks for the response; sorry I wasn't able to locate the duplicate before posting!

Do you have any ideas/fixes on the unexpected added border when not using `as_raw_html()`?

**Comment by mcanouil** [comment] 2024-02-19 20:16
Could you open a separate discussion or issue with a small reproducible example?

By the way, `self-contained` was superseded more than a year and half ago by `embed-resources`.
Do not use it unless you plan to use Quarto < 1.1

**Comment by RegalPlatypus** [comment] 2024-02-19 20:27
@mcanouil Yes, I'll do that. I looked at #8444. I don't think it's related, but you'll be able to suss that out better than I.

Thanks for that heads-up. Since I crank out a lot of very similar reports I just use a snippit with my YAML. Time to update it!

**Comment by mcanouil** [comment] 2024-02-19 20:30
> Thanks for that heads-up. Since I crank out a lot of very similar reports I just use a snippit with my YAML. Time to update it!

I suggest to replace the whole snippet YAML with `format: html` and to use the options only if it is relevant to the issue.
