### ISSUE TITLE
Automatic scrolling after clicking on panel tabs including plotly charts

### ISSUE THREAD

**Issue by ArnaudAcoucite** [quarto-dev/quarto-cli#9707] opened 2024-05-17 14:49 UTC
### Bug description

After clicking on a tab name from a panel tabset, the HTML page automatically scrolls upward. It happens if one of the tab contains a plotly chart. I wonder if it is related to the issue #4705

### Steps to reproduce

1. Render in RStudio the Reproducible Quarto Document (import tidyverse and plotly if necessary)
2. Browse the generated HTML file
3. Click on "Tab 1", "Tab 2" or "Tab 3" on the panel tabset

````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a minimal self-contained reproducible Quarto document using `format: html` and `knitr` engine.
It is written in Markdown and contains embedded R code.

```{r}
library(tidyverse)
library(plotly)
```

::: panel-tabset

## Tab 1

```{r}
a <- tibble(col = 1:20)

plot_ly(a, x = ~col) |>
  add_trace(y = ~col,
            type = "scatter",
            mode = "lines")
```

## Tab 2

```{r}
b <- tibble(col = 1:20)

plot_ly(b, x = ~col) |>
  add_trace(y = ~col,
            type = "scatter",
            mode = "lines")
```

## Tab 3

```{r}
c <- tibble(col = 1:20)

plot_ly(c, x = ~col) |>
  add_trace(y = ~col,
            type = "scatter",
            mode = "lines")
```
:::



The end.
````

### Expected behavior

The plotly chart corresponding to "Tab 1", "Tab 2" or "Tab 3" should be displayed in the panel tabset.

### Actual behavior

The plotly chart corresponding to "Tab 1", "Tab 2" or "Tab 3" should be displayed in the panel tabset AND the HTML page automatically scrolls upward.

### Your environment

- IDE: RStudio 2024.04.1 Build 748
- OS: Windows 11 Professionnel 23H2

### Quarto check output

```bash
Quarto 1.4.553
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.553
      Path: C:\Users\Arnaud\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: C:/Users/Arnaud/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.4.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.3
      Path: C:/PROGRA~1/R/R-43~1.3
      LibPaths:
        - C:/Users/Arnaud/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.3/library
      knitr: 1.46
      rmarkdown: 2.26

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment] 2024-05-17 14:53
Please I'd like to ask you in the future to make sure the document you describe as reproducible actually runs. You're missing `a` and `y` objects in here.

**Comment by ArnaudAcoucite** [comment] 2024-05-17 14:59
Sorry, I ran the document but forgot to correct it. I modified it, it should be ok now (typo in Tab 1, 'c' instead of 'a' variable declaration).

**Comment by mcanouil** [comment] 2024-05-18 16:50
I cannot reproduce on VSCode or browser.
I believe this to be an RStudio issue which would probably better to be reported on its repository: https://github.com/rstudio/rstudio

**Comment by mcanouil** [comment] 2024-05-21 14:36
Are you running the latest version? Did you try to run Firefox in troubleshooting mode with extensions/plugins disabled? I think that's a bad interaction of the JavaScript with something in your browser setting.

**Comment by ArnaudAcoucite** [comment] 2024-05-27 13:15
I tried running the latest version of Firefox in troubleshooting mode with extensions/plugins disabled but got the same behaviour. After few trials, I think it is related to the display of interactive tools created with htmlwidgets for R within a tabset and opened in Firefox browser. Indeed, creating a plotly graph with Python instead of R and displaying it in the tabset doesn't reproduce the same behaviour. Same with a leaflet map. But I don't know what causes the bad interaction and will skip it as it is minor for my work.

Should I close the comment?

Thanks for your answers.

**Comment by cscheid** [comment] 2024-06-12 17:00
I'm going to close this one. If folks can get a clean repro, then please feel free to reopen.

**Closed by cscheid** 2024-06-12 17:00 UTC
Labels: bug, needs-repro, third-party

**Comment by ppm1337** [comment] 2024-11-28 13:04
Having the same issue. Can confirm that this only happens in Firefox (using Firefox Developer Edition 134.0b1). To clarify, it's unrelated to the content in the tabset, i.e. it doesn't need to be a HTML widget such as a plotly plot.
