### ISSUE TITLE
Static table of contents not showing all the levels

### ISSUE THREAD

**Issue by juan-g-p** [quarto-dev/quarto-cli#2366] opened 2022-09-08 20:09 UTC
### Bug description

I have been having trouble when writing a `.qmd` file that I want to have a static table of contents at the beginning with all the levels.

I am including the following yaml options at the beginning of the focument. 

```yaml
---
title: "My document"
format: html
editor: visual
params:
  solutions: false
toc: true
toc-location: body
toc-depth: 6
self-contained: true
---
```

Nonetheless, the table of contents only shows the level 1 headers.

I am running R studio build 554 (2022.07.01) and R 4.1.2 within Windows 11.

Changing self-contained or removing it altogether does not play a role. Neither does removing the parameters.

Please I need to solve this issue urgently.

Best.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment] 2022-09-09 12:43
I'm not able to reproduce this - when I use the following document, I see the TOC. 

```markdown
---
title: "My document"
format: html
editor: visual
params:
  solutions: false
toc: true
toc-depth: 6
toc-location: left
self-contained: true
---

# Hello World

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.

## This is a test

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.

### what is up

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec 
posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.

#### dog

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.
```

Note that the `tac-depth` controls what headers are included in the TOC, not whether the TOC collapses / expands as the user scrolls. This could be confusing since the TOC will be in a collapsed state initially, showing only the peer top level headers until the user scrolls down.

Is this perhaps the issue and are you wanting to control the expansion / collapsing as well as the depth?

Side note - we generally recommend using level 2 headings as primary headings since the title will be rendered as a level 1 heading.

**Comment by juan-g-p** [comment] 2022-09-12 03:36
> I'm not able to reproduce this - when I use the following document, I see the TOC entries for each of the headings as I scroll.
> 
> ```gfm
> ---
> title: "My document"
> format: html
> editor: visual
> params:
>   solutions: false
> toc: true
> toc-depth: 6
> toc-location: left
> self-contained: true
> ---
> 
> # Hello World
> 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.
> 
> ## This is a test
> 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.
> 
> ### what is up
> 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec 
> posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.
> 
> #### dog
> 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.
> ```
> 
> Note that the `toc-depth` controls what headers are included in the TOC, not whether the TOC collapses / expands as the user scrolls. This could be confusing since the TOC will be in a collapsed state initially, showing only the peer top level headers until the user scrolls down.
> 
> Is this perhaps the issue and are you wanting to control the expansion / collapsing as well as the depth?
> 
> Side note - we generally recommend using level 2 headings as primary headings since the title will be rendered as a level 1 heading.

Many thanks @dragonstyle for your answer.

I have updated the original post to show that I want the paramenter `toc-location: body`, meaning I want the **toc to be at the top of the document in a static manner**. I also want **all the levels to be displayed at the same time, meaning the toc to be fully spread**.

When I do this I get neither the toc at the top and centered, nor the fully expanded static version of the toc.

**Could you please help?** This is actually very important for my classes, I use the fully expanded TOC to give students an overview of everything to be discussed within a session.

Thank you.

Juan

**Comment by dragonstyle** [comment] 2022-09-22 14:47
I continue to not see this issue- this document:

```markdown
---
title: "My document"
format: html
editor: visual
params:
  solutions: false
toc: true
toc-depth: 6
toc-location: body
self-contained: true
---

# Hello World

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.

## This is a test

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.

### Another level

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec 
posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.

#### Yet Another Level

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.

##### Yet Another Level

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.


##### Yet Another Level 2

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.


## Higher Level

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat quam feugiat, egestas urna at, ullamcorper sapien. Donec posuere lectus a neque viverra, et pulvinar erat accumsan. Pellentesque luctus consequat elit ac feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fermentum auctor turpis in faucibus. Vestibulum tincidunt molestie malesuada. Mauris cursus commodo dolor, eu porttitor urna mollis id. Curabitur ac sollicitudin elit. Sed sodales arcu at urna tincidunt, sit amet ornare ex cursus. Vestibulum elementum lobortis congue. Nulla tempor nulla augue, a dignissim nunc vestibulum eu. Praesent congue mauris enim, eu tempus libero finibus vel. Nulla velit velit, ullamcorper in risus eget, sagittis laoreet justo.
```

Appears to render correctly with the TOC in the body fully expanded:


![Screen Shot 2022-09-22 at 10 46 22 AM](https://user-images.githubusercontent.com/261654/191778855-0d8b4e4d-3bc7-414c-ae20-91cf06f1d764.png)

Could you verify the version of Quarto that you are using? I would recommend you be sure you're using either the latest release or pre-release build:

https://quarto.org/docs/download/

**Closed** 2022-09-23 13:25 UTC
Labels: bug
