### ISSUE TITLE
GitHub Action publish does not create "site_libs" folder

### ISSUE THREAD

**Issue by schochastics** [quarto-dev/quarto-cli#5738] opened 2023-05-30 09:55 UTC
### Bug description

We are using the GitHub action to publish the website in this repository: https://github.com/gesiscss/quarto-workshop
to https://gesiscss.github.io/quarto-workshop/ but the action does not produce the `site_libs` folder with the required libraries. rendering it locally does produce the `site_libs` folder (quarto 1.3.151). The GA was setup according to the documentation on quarto.org.
This is the `publish.yml` file
```yaml
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Edit: using `lib-dir: "libs"` to change the default "site_libs" folder also did not fix the issue

### Steps to reproduce

deploy  https://github.com/gesiscss/quarto-workshop in a different github account

**Comment by mcanouil** [comment] 2023-05-30 10:47
I do not have any issues, see <https://github.com/mcanouil/quarto-workshop-test>.

I cloned, remove Git, initialise Git, and ran `quarto publish gh-pages` without touching anything in the code.

**Comment by cderv** [comment] 2023-05-30 12:53
Not sure why but indeed this commit has made the `site_libs` folder to be removed: https://github.com/gesiscss/quarto-workshop/actions/runs/5118579265/jobs/9202774062#step:4:73

It was build with `1.3.361` and previous working build was with `1.3.353` 

This is curious ! Especially because in your case @mcanouil the lib folder is `libs/`  (https://github.com/mcanouil/quarto-workshop-test/tree/gh-pages/libs) and not `site_libs/` as it was (https://github.com/gesiscss/quarto-workshop/tree/964e1055f1323f56c8aff2415ceafd1270afffdf/site_libs) - I wonder if there was change. 🤔 

It is as if `site_libs/` was changed to `libs/` but then the `libs/` folder is not commited 🤔

**Comment by cderv** [comment] 2023-05-30 13:13
Oh missed that. Thanks ! 

I don't understand why this `site_libs` was removed. I found the other issue like: https://community.rstudio.com/t/quarto-website-index-not-publishing-correctly-but-rendering-fine-in-rstudio/166358
Same behavior. 

When lib_dir is changed, the new `libs` folder is not published in their website. Something is not right here

**Comment by mcanouil** [comment] 2023-05-30 13:19
I was able to reproduce.
I changed the setting for "libs" back to default to trigger the action.
As expected "libs" is removed, but "_site_libs" is is staged/committed by the action.

I am doing some more tests at the moment.

**Comment by mcanouil** [comment] 2023-05-30 13:42
It's really weird, but I think the issue comes down to Quarto CLI.
After few tries with 1.2, 1.3, dev, even with. `quarto render` I sometimes end up with `_site` that does not contain the default `site_libs`.
It seems to be some copy issue which I can't fully explain at this moment.

**Comment by mcanouil** [comment] 2023-05-30 13:48
I might have found the issue.
There are documents with `embed-resources: true` and since `freeze: auto` depending on what document is rendered as last, the whole `site_libs` is embedded in it.

**Comment by cderv** [comment] 2023-05-30 13:56
Wow nasty bug! Not related to publish only then ? You can reproduce locally with a quarto project ? 

> It seems to be some copy issue which I can't fully explain at this moment.

FYI We copy the outputs to a temp folder before commiting to `gh-pages`. If `site_libs` isn't there, we don't copy it for sure. 

> There are documents with embed-resources: true and since freeze: auto depending on what document is rendered as last, the whole site_libs is embedded in it.

I am suprised we remove the `site_libs` even in this situation ! Good catch.

**Comment by mcanouil** [comment] 2023-05-30 14:12
All tests were performed locally using `quarto render`.

I am not sure, it's really a bug.
If you render a project, it's kind of weird to have self-contained documents in it.
The only way to do that would be for Quarto to generate a per document "libs" directory, but this seems a really bad idea.

Here, I believe, self-contained should be rendered in "pre-render" and ignored in the project for it to render properly.

**Comment by schochastics** [comment] 2023-05-30 14:43
removing `embed-resoures: true` did the trick, thanks @mcanouil (This was a copy paste artifact...). 
I think there should still be a mechanism to not make this occur. In my case, it happened because I added slides to the project and those might have been self-contained before. If users, like me, forget to remove the embed statement, they will get as confused as I was ;-)

**Comment by cderv** [comment] 2023-05-30 14:50
> I am not sure, it's really a bug.

I find it "buggy" that the whole `site_libs` is removed because one document has a `embed-resources: true`, while `site_libs` is a shared directory. 

Yes this could be seen as "weird" to use self-contained document in a project, but IMO

* We should fix this as a bug 
* or as you kind of suggest that `embed_resource` in a project should be ignored. 

Could you open a new issue with your project reprex so that this behavior can be discussed ? 
I believe this is kind confusing and really hard to debug unless you know about it.

**Comment by cderv** [comment] 2023-05-31 07:44
Yes let's close this as the real issue is #5748. Thank you for opening it!

**Closed by cderv** 2023-05-31 07:44 UTC
Labels: bug, publishing-github
