### ISSUE TITLE
Multi-column table output prioritizes center of new page or top of new page in PDF

### ISSUE THREAD

**Issue by pentagramswheel** [quarto-dev/quarto-cli#11684] opened 2024-12-14 00:45 UTC
### Bug description

I am trying to use the YAML chunk options mentioned in [Table Computations](https://quarto.org/docs/authoring/tables.html#computations) to create a two-column output with separate tables. I am observing one of the following two cases:

1. If I have a Markdown chunk leading up to a multi-column `kable` print, where a PDF page break occurs in the middle of the Markdown chunk, then the `kable` print interrupts the chunk at the *top* of the following page before continuing the Markdown preceding it sequentially.
2. If I have the same lead-up at the end of a document, but no page break needs to occur, the `kable` print is "skipped" sequentially so that it can be printed at the *center* of the following page.

### Steps to reproduce

Case 1:
````qmd
---
title: "Project Title"
author: "Author"
format:
  pdf: default
  gfm: default
date: "2024-12-06"
sansfont: "Times New Roman"
mainfont: "Times New Roman"
---

```{r}
#| label: imports
#| include: false
library(knitr)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.1

```{r}
#| label: r-chunk1
var <- 4
var2 <- 5
var3 <- 6
var4 <- 7
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.2

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.3

```{r}
#| label: r-chunk2
#| echo: false
tbl1 = data.frame(reason = c("Catgeory 1", "Catgeory 2", "Catgeory 3", "Catgeory 4", "Category 5"),
                  n = c(43, 23, 4, 7, 63))
tbl2 = data.frame(reason = c("Catgeory 1", "Catgeory 2", "Catgeory 3"),
                  n = c(32, 4, 11))
```

```{r}
#| label: tbl-counts
#| echo: false
#| tbl-cap: "Counts"
#| tbl-subcap: 
#|   - "Table 1"
#|   - "Table 2"
#| layout-ncol: 2
knitr::kable(tbl1)
knitr::kable(tbl2)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.4

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.5

````

Case 2:
````qmd
---
title: "Project Title"
author: "Author"
format:
  pdf: default
  gfm: default
date: "2024-12-06"
sansfont: "Times New Roman"
mainfont: "Times New Roman"
---

```{r}
#| label: imports
#| include: false
library(knitr)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.1

```{r}
#| label: r-chunk1
var <- 4
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.2

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.3

```{r}
#| label: r-chunk2
#| echo: false
tbl1 = data.frame(reason = c("Catgeory 1", "Catgeory 2", "Catgeory 3", "Catgeory 4", "Category 5"),
                  n = c(43, 23, 4, 7, 63))
tbl2 = data.frame(reason = c("Catgeory 1", "Catgeory 2", "Catgeory 3"),
                  n = c(32, 4, 11))
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.4

```{r}
#| label: tbl-counts
#| echo: false
#| tbl-cap: "Counts"
#| tbl-subcap: 
#|   - "Table 1"
#|   - "Table 2"
#| layout-ncol: 2
knitr::kable(tbl1)
knitr::kable(tbl2)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.5
````

### Expected behavior

PDF Export Case 1:
Table 1 should print after the 3rd "lorem ipsum" paragraph.

PDF Export Case 2:
Table 1 should print after the 4th "lorem ipsum" paragraph.

### Actual behavior

PDF Export Case 1:
Table 1 prints at the top of Page 2, in the middle of the 5th "lorem ipsum" paragraph.

PDF Export Case 2:
Table 1 prints after the 5th "lorem ipsum" paragraph and at the center of Page 2.

### Your environment

R version 4.4.1 (2024-06-14)
IDE/Platform: Sublime Text 3
OS: MacOS Sequoia 15.1.1

### Quarto check output

```
Quarto 1.6.39
[✓] Checking environment information...
      Quarto cache location: /Users/wilaquino/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.39
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/wilaquino/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.4
      Path: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2024-12-14 04:15
Could you update your code to be fully reproducible?
We need actual "working" code, not pseudo-code.
Thank you!

**Comment by pentagramswheel** [comment] 2024-12-15 06:01
Sure @mcanouil !

### Bug description

I am trying to use the YAML chunk options mentioned in [Table Computations](https://quarto.org/docs/authoring/tables.html#computations) to create a two-column output with separate tables. I am observing one of the following two cases:

1. If I have a Markdown chunk leading up to a multi-column `kable` print, where a PDF page break occurs in the middle of the Markdown chunk, then the `kable` print interrupts the chunk at the *top* of the following page before continuing the Markdown preceding it sequentially.
2. If I have the same lead-up at the end of a document, but no page break needs to occur, the `kable` print is "skipped" sequentially so that it can be printed at the *center* of the following page.

### Steps to reproduce

Case 1:
````qmd
---
title: "Title"
author: "Author"
format:
  pdf: default
  gfm: default
sansfont: "Times New Roman"
mainfont: "Times New Roman"
---

```{r}
#| label: imports
#| include: false
library(tidyverse)
library(lubridate)
library(knitr)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.1

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.2

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.3

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.4

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.5

```{r}
#| label: label1
#| echo: false
#| include: false
reason <- c('Category 1', 'Category 2', 'Category 3', 'Category 4')
n <- c('7', '1', '7', '24')
df1 = data.frame(reason, n)

reason <- c('Category 1', 'Category 2', 'Category 3')
n <- c('4', '48', '27')
df2 = data.frame(reason, n)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.6

```{r}
#| label: tbl-label
#| echo: false
#| tbl-cap: "Tables"
#| tbl-subcap: 
#|   - "Table 1"
#|   - "Table 2"
#| layout-ncol: 2

kable(df1)
kable(df2)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.7
````

Case 2:
````qmd
---
[same]
---

<!-- More R and Markdown chunks -->

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

```{r}
#| label: tbl-label
#| echo: false
#| tbl-cap: "Tables"
#| tbl-subcap: 
#|   - "Table 1"
#|   - "Table 2"
#| layout-ncol: 2

kable(tbl1)
kable(tbl2)
```

This is a non-lorem ipsum sentence. This is a non-lorem ipsum sentence. This is a non-lorem ipsum sentence.

<!-- End of Document -->
````

### Expected behavior

PDF Export Case 1:
```md
Title
Author

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.1

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.2

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.3

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.4

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.5


[Top of New Page]
This is a non-lorem ipsum sentence. This is a non-lorem ipsum sentence. This is a non-lorem ipsum sentence.

Table 1: Tables
<tbl1> | <tbl2>

...
```

PDF Export Case 2:
```md
Title
Author

...

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

Table 1: Tables
<tbl1> | <tbl2>

This is a non-lorem ipsum sentence. This is a non-lorem ipsum sentence. This is a non-lorem ipsum sentence.

[End of Document]
```

### Actual behavior

PDF Export Case 1:
```md
Title

...

[End of Page via PDF]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

[Top of New Page]
Table 1: Tables
<tbl1> | <tbl2>

This is a non-lorem ipsum sentence. This is a non-lorem ipsum sentence. This is a non-lorem ipsum sentence.

[Other R and Markdown chunks]
```

PDF Export Case 2:
```md
Title

...

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

This is a non-lorem ipsum sentence. This is a non-lorem ipsum sentence. This is a non-lorem ipsum sentence.

[Center of New Page]
Table 1: Tables
<tbl1> | <tbl2>

[End of Document]
```

### Your environment

R version 4.4.1 (2024-06-14)
IDE/Platform: Sublime Text 3
OS: MacOS Sequoia 15.1.1


### Quarto check output

```
Quarto 1.6.39
[✓] Checking environment information...
      Quarto cache location: /Users/wilaquino/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.39
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/wilaquino/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.4
      Path: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```

**Comment by pentagramswheel** [comment] 2024-12-16 16:48
It turns out this was not a Quarto problem but a potential problem with the `knitr` package working with LaTeX and figures/tables/etc. I wanted to research more about the problem first before adding an edit here. I found the following threads talking about problems similar to mine, with reproducible examples and solutions:
- [Knitr/kable: table moving to the end of page when adding caption/figure label](https://stackoverflow.com/questions/49550731/knitr-kable-table-moving-to-the-end-of-page-when-adding-caption-figure-label)
- [Rmarkdown setting the position of kable](https://stackoverflow.com/questions/53153537/rmarkdown-setting-the-position-of-kable)
- [How to hold figure position with figure caption in pdf output of knitr?](https://stackoverflow.com/questions/29696172/how-to-hold-figure-position-with-figure-caption-in-pdf-output-of-knitr)
- [How do I make knitr::kable tables stop floating?](https://stackoverflow.com/questions/42764032/how-do-i-make-knitrkable-tables-stop-floating)

The conclusion I came to is that `knitr::kable` is at least partially derived from LaTeX when it comes to printing figures/tables/etc which "floats" said objects according to some formula. Maybe that is not completely true, but since I found my solution, I don't plan to look into it more currently.

The problem described in the above threads occurred when I was using the [Quarto documentation syntax](https://quarto.org/docs/authoring/tables.html#computations) for tables. Adding the following `header-includes` block in my YAML header is what fixed my tables from pushing away/against any other content:

````qmd
---
title: "Title"
author: "Author"
format:
  pdf: default
  gfm: default
date: "2024-12-16"
sansfont: "Times New Roman"
mainfont: "Times New Roman"

# fix table floats
header-includes:
  - \usepackage{float}
  - \floatplacement{table}{H}
---

```{r}
#| label: imports
#| include: false
library(tidyverse)
library(lubridate)
library(readxl)
library(knitr)
```

<!-- Other R and Markdown chunks -->

```{r}
#| label: tbl-label
#| echo: false
#| tbl-cap: "Caption"
#| tbl-subcap: 
#|   - "Subcaption 1"
#|   - "Subcaption 2"
#| layout-ncol: 2
knitr::kable(tbl1)
knitr::kable(tbl2)
```
````

Should I still edit my original post @mcanouil ?

**Comment by pentagramswheel** [comment] 2024-12-16 21:37
@mcanouil The `tidyverse` package was needed for my bigger project, but I've now updated the original post with full reproducible examples. How does it look? I also see `fig-pos` for the [Figures chunks](https://quarto.org/docs/reference/cells/cells-knitr.html#figures). Is there a tables equivalent for Quarto?

**Comment by mcanouil** [comment] 2024-12-16 22:15
Here is what I get adding `tbl-pos: H` in the code cell.

<img width="679" alt="Image" src="https://github.com/user-attachments/assets/dbccb93f-6157-4ff6-844b-5f84d211e4d5" />


````
qmd
---
title: "Project Title"
author: "Author"
format: pdf
---

```{r}
#| label: imports
#| include: false
library(knitr)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.1

```{r}
#| label: r-chunk1
var <- 4
var2 <- 5
var3 <- 6
var4 <- 7
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.2

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.3

```{r}
#| label: r-chunk2
#| echo: false
tbl1 = data.frame(reason = c("Catgeory 1", "Catgeory 2", "Catgeory 3", "Catgeory 4", "Category 5"),
                  n = c(43, 23, 4, 7, 63))
tbl2 = data.frame(reason = c("Catgeory 1", "Catgeory 2", "Catgeory 3"),
                  n = c(32, 4, 11))
```

```{r}
#| label: tbl-counts
#| echo: false
#| tbl-pos: H
#| tbl-cap: "Counts"
#| tbl-subcap: 
#|   - "Table 1"
#|   - "Table 2"
#| layout-ncol: 2
knitr::kable(tbl1)
knitr::kable(tbl2)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.4

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.5

**Comment by pentagramswheel** [comment] 2024-12-16 22:37
That is exactly what I needed. After cross-referencing with other issues and discussions, I see that it's mentioned in the future milestones already as well. Thank you!

**Comment by mcanouil** [comment] 2024-12-17 16:42
I am going to reopen because `tbl-pos` is not documented anywhere inside Quarto and does not seem to work at top level (it works in a code cell and in a fenced div).

**Comment by mcanouil** [comment] 2024-12-18 07:49
Never mind, let's close this one.

- https://github.com/quarto-dev/quarto-cli/issues/10784

**Closed** 2024-12-18 07:50 UTC
Labels: support
