### ISSUE TITLE
Section anchors are over-written when updating the preview (visual mode only)

### ISSUE THREAD

**Issue by tpoisot** [quarto-dev/quarto-cli#6505] opened 2023-08-11 21:35 UTC
### Bug description

When using VS Code, editing a document in visual mode, and then pressing refresh, will modify the IDs of all sections with an anchor.

### Steps to reproduce

Write a document `gradientdescent.qmd` with the content below, edit in visual mode in VS Code, call *Quarto: render project*, then switch to source mode.

````qmd
# Minimizing error: the gradient descent algorithm {#sec-gradientdescent}
````

### Expected behavior

Preview opens, document is unchanged

### Actual behavior

````qmd
# Minimizing error: the gradient descent algorithm {#gradientdescent-sec-gradientdescent}
````

### Your environment

- OS: Linux x1 6.2.0-27-generic #28-Ubuntu
- IDE: VS Code 1.81.0

### Quarto check output

````bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.294
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
````

**Comment by tpoisot** [comment] 2023-08-11 21:36
Important bit of context: _this does not happen when preview runs in source mode_.

**Comment by mcanouil** [comment] 2023-08-12 08:43
I am not sure to follow the steps to reproduce.
I have no issue.

https://github.com/quarto-dev/quarto-cli/assets/8896044/d7144d5f-230e-475b-b8f9-7212e571ba13

**Comment by tpoisot** [comment] 2023-08-12 12:38
I'll make a screen recording later today.

**Comment by tpoisot** [comment] 2023-08-12 13:30
There you go -- I also tried with and without a YAML front-matter, and it makes no difference. This is within a book project.

[Screencast from 2023-08-12 09-26-53.webm](https://github.com/quarto-dev/quarto-cli/assets/579329/12ac8a20-82a4-4e67-90a2-592f5e370a82)

**Comment by tpoisot** [comment] 2023-08-13 14:21
Update: this is adding the slug of the file on every save, leading to *e.g.*

````markdown
## The problem: how many interactions in a food web? {#gradientdescent-gradientdescent-gradientdescent-gradientdescent-sec-gradientdescent-problem}
````

**Comment by mcanouil** [comment] 2023-08-19 10:55
@jjallaire there seems to be something off with the visual editor.
See also:
- https://github.com/quarto-dev/quarto-cli/issues/6548

**Comment by jjallaire** [comment] 2023-08-19 11:52
This is almost certainly due to a Pandoc update (and related change in the behavior of `--id-prefix`). I'll investigate further.

**Comment by jjallaire** [comment] 2023-08-21 18:50
@tpoisot we've rolled back to Pandoc 3.1.2 while waiting for a fix (this behavior result from a change in Pandoc 3.1.2). You can download this version (v1.4.330) here: https://quarto.org/docs/download/prerelease.html

**Comment by cscheid** [comment] 2023-11-30 20:01
This should be fixed on `main`. Please check with the latest 1.4 prereleases and re-open if the problem persists. Thanks!

**Closed by cscheid** 2023-11-30 20:01 UTC
Labels: bug, editors, triaged-to
