### ISSUE TITLE
Documentation for custom cross references no longer matches new YAML schema

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto-cli#7859] opened 2023-12-10 14:52 UTC
### Bug description

The documentation about custom cross reference types ([here](https://quarto.org/docs/authoring/cross-references-custom.html#example-supplemental-figures)) no longer works or passes YAML validation.

I know some work was done about this (here I think https://github.com/quarto-dev/quarto-cli/pull/7847), but I can't tell how to update the previous version of the syntax to get it working again.

### Steps to reproduce

Using this document…

````qmd
---
title: "Custom figure"
crossref:
  custom:
    - kind: float
      ref-type: suppfig
      latex-env: suppfig
      prefix: Figure S
      name: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
---

Blah
````

…causes this error:

```
ERROR: Validation of YAML front matter failed.
ERROR: In file testing.qmd
(line 4, column 3 through line 11, column 53) Field "crossref" has value

custom:
  - kind: float
...
    space-before-numbering: false
    latex-list-of-description: Supplementary Figure

The value must instead be 'false'.
 3: crossref:
 4:   custom:
     ~~~~~~~~
 5:     - kind: float
   ~~~~~~~~~~~~~~~~~~
...
10:       space-before-numbering: false
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:       latex-list-of-description: Supplementary Figure
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12: ---

ERROR: Render failed due to invalid YAML.
```

It also causes a validation error in RStudio: 

<img width="425" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/82353105-a804-4726-8961-0b7c777e7fa6">

### Expected behavior

It should work :)

(or the documentation should show how to make it work)

### Actual behavior

It doesn't :(

### Your environment

- IDE: RStudio Version 2023.12.0-daily+283
- OS: macOS Sonoma 14.1.2

### Quarto check output

```
Quarto 1.4.525
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.525
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/andrew/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2023-12-10 15:29
Note that 1.4 is a pre-release so there is no regression per se since it was never stable in the first place.
See:
- https://github.com/quarto-dev/quarto-cli/issues/7484

**Comment by andrewheiss** [comment] 2023-12-10 17:03
I just changed the title to reflect that. The main issue is that the documentation doesn’t match the newly updated schema (or that the yaml validation is maybe messed up?)

**Comment by cscheid** [comment] 2023-12-10 18:01
It's the docs. We got a bit of a race condition going on atm; I'm surprised that https://quarto.org/docs/authoring/cross-references-custom.html is referencing 1.4 content, and I missed that when doing the doc changes after my latest fix.

**Comment by cscheid** [comment] 2023-12-10 18:08
The website is fixed now. It should take a bit to rebuild, but you can consult the [qmd source](https://github.com/quarto-dev/quarto-web/blob/main/docs/authoring/cross-references-custom.qmd).

**Closed by cscheid** 2023-12-10 18:08 UTC
Labels: bug

**Comment by andrewheiss** [comment] 2023-12-10 18:12
Oh cool cool, it works now! Thanks!!
