### ISSUE TITLE
ojs cell broken in quarto 1.4.550 and pre-release 1.5.16

### ISSUE THREAD

**Issue by Pierre9344** [quarto-dev/quarto-cli#8840] opened 2024-02-22 13:06 UTC
### Bug description

Hello,
I tried to use ojs cell with the latest version of quarto but the ojs cell don't work in the rendered document (I'm using firefox to visualize it):

I think other people had the same problem and from the release note, it should have been resolved #6267 .

I also have the same problem with the pre-release.

### Steps to reproduce

Render a html document with the latest version of quarto and the pre-release and visualize it in firefox.

````
---
title: "TEST"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true
    standalone: true
    self-contained: true
---

```{r}
ojs_define(iris = iris)
```


```{ojs}
yearlyChart = Plot.plot({
  marks: [
    Plot.line(transpose(co2data), 
      {x: "Sepal.Length", y: "Sepal.Width"}, 
      { stroke: "black" }
    )
  ]}
)
```
````

### Expected behavior

The rendered document should display a plot generated by observable js

### Actual behavior

The document is rendered with a non functionnal ojs cell that display the message :` This document uses OJS, which requires JavaScript features disabled when running in file://... URLs. In order for these features to work, run this document in a web server.`

[rendered document](https://github.com/quarto-dev/quarto-cli/files/14373978/index.zip)

### Your environment

R: 4.2.3
RStudio: 2023-12-1.402
Windows 11
Firefox 122.0.1

### Quarto check output

````
>quarto check
Quarto 1.4.550
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.550
      Path: C:\Users\E142543N\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.01
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\E142543N\AppData\Roaming\TinyTeX\bin\win32\
      Version: 2022

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.9
      Path: C:/Users/E142543N/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: 5.2.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.3
      Path: C:/PROGRA~1/R/R-42~1.3
      LibPaths:
        - C:/Users/E142543N/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.3/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
````

**Comment by mcanouil** [comment] 2024-02-22 13:30
Thanks for the report!

Your example is not fully reproducible, *i.e.*, we do not have `styles.css` and `co2data` does not exist.
Also do not include options that are not necessary to reproduce the issue, it means we have to check if those are relevant or not while you already know if those are.

Please make sure your example can be executed.

Note that `self-contained` was "deprecated" since 1.1 and that `embed-resources` is doing the exact same thing, *i.e.*, do not use `self-contained` if you are using Quarto >1.0.

**Comment by mcanouil** [comment] 2024-02-22 13:32
I am going to close this as the issue is the code not Quarto.
Feel free to reopen if you have still an issue and have a reproducible example.

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/1ae0046f-d64a-41cd-a4b7-e64aac7a4095">

**Closed by mcanouil** 2024-02-22 13:32 UTC
Labels: support

**Comment by Pierre9344** [comment] 2024-02-22 13:57
Thank you for the quick answer. I used the code you shared and I can see the plot in the preview but not when using the rendered html document.

- viewer panel of RStudio:
![Capture d'écran 2024-02-22 145506](https://github.com/quarto-dev/quarto-cli/assets/86181677/63137292-b138-4290-9084-e40bf32f92b4)
- preview in windows (firefox):
![Capture d'écran 2024-02-22 145311](https://github.com/quarto-dev/quarto-cli/assets/86181677/50517d68-5455-4016-95f9-faf6cf2125f8)

But when I open the rendered document in firefox by double clicking the html document, the plot don't show:
![Capture d'écran 2024-02-22 144754](https://github.com/quarto-dev/quarto-cli/assets/86181677/7f7563cb-305f-4d7e-b96f-22f3de9575d3)

[code and rendered document](https://github.com/quarto-dev/quarto-cli/files/14374625/TEST.zip)

**Comment by mcanouil** [comment] 2024-02-22 14:21
You cannot run most JavaScript library through the file protocol.
You need a web server which the "preview panel" is.

**Comment by cscheid** [comment] 2024-02-22 14:39
Please, we do insist that you read the messages we write. They're for you.

<img width="396" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/47508c25-e80d-4fea-aca2-7b8b130f5825">
