### ISSUE TITLE
canonical-url includes double // and no trailing slash

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#9524] opened 2024-04-29 13:47 UTC
### Bug description

Given a Quarto project configuration:

```yaml
project:
  type: website

website:
  site-url: https://quarto.org/

format:
  html:
    canonical-url: true
```

The `about/index.qmd` file receives the following tag:

```html
<link rel="canonical" href="https://quarto.org//about">
```

This link tag has two problems:

1. Double slash when concatenating `site-url` with the page path.
2. Missing trailing slash (causing an unnecessary redirect).

### Steps to reproduce

Create a Quarto project with an index file in a subdirectory. Render that project. Look at the generated HTML.

### Expected behavior

```html
<link rel="canonical" href="https://quarto.org/about/">
```

### Actual behavior

```html
<link rel="canonical" href="https://quarto.org//about">
```

### Quarto check output

```
Quarto 1.4.551
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.551
      Path: /Users/aron/quarto/quarto-1.4.551-macos/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by aronatkins** [comment] 2024-04-29 13:57
The top-level index page receives double-slashes, too:

```html
<link rel="canonical" href="https://quarto.org//">
```

**Comment by mcanouil** [comment] 2024-05-06 18:10
I believe, it's because of the trailing `/`.

- https://github.com/quarto-dev/quarto-cli/blob/fd6d0a22fc2eb89938f3501ae1910dffc7275986/src/format/html/format-html-meta.ts#L293-L316

to:

```ts
function writeCanonicalUrl(
  doc: Document,
  url: string | boolean,
  input: string,
  inputMetadata: Metadata,
  outputFile?: string,
  offset?: string,
) {
  if (typeof url === "string") {
    // Use the explicitly provided URL
    writeLinkTag("canonical", url.replace(/\/$/, ""), doc);
  } else if (url) {
    // Compute a canonical url and include that
    const canonicalUrl = synthesizeCitationUrl(
      input,
      inputMetadata,
      outputFile,
      offset,
    );
    if (canonicalUrl) {
      writeLinkTag("canonical", canonicalUrl.replace(/\/$/, ""), doc);
    }
  }
}
```

fixes the issue, but I don't know if that's the best way here. (cc @cscheid )

**Comment by mcanouil** [comment] 2024-05-06 18:17
A full reprex: https://github.com/mcanouil/quarto-issues-experiments/tree/main/quarto-cli-9524

**Comment by mcanouil** [comment] 2024-05-06 18:31
I've found where the additional `/` is added.

- https://github.com/quarto-dev/quarto-cli/blob/fd6d0a22fc2eb89938f3501ae1910dffc7275986/src/quarto-core/attribution/document.ts#L443-L471

```ts
export function synthesizeCitationUrl(
  input: string,
  metadata: Metadata,
  outputFile?: string,
  offset?: string,
) {
  const siteMeta = metadata[kWebsite] as Metadata | undefined;
  let baseUrl = siteMeta?.[kSiteUrl] as string;
  baseUrl = baseUrl.replace(/\/$/, "");

  if (baseUrl && outputFile && offset) {
    const rootDir = normalizePath(join(dirname(input), offset));
    if (outputFile === "index.html") {
      return `${baseUrl}/${
        pathWithForwardSlashes(relative(rootDir, dirname(input)))
      }`;
    } else {
      const relativePath = relative(
        rootDir,
        join(dirname(input), basename(outputFile)),
      );
      const part = pathWithForwardSlashes(relativePath);
      return `${baseUrl}/${part}`;
    }
  } else {
    // The url is unknown
    return undefined;
  }
}
```

Resolves the issue.

I am not aware of the requirement for a trailing `/` for canonical URLs as implied in the expected behaviour though.

**Comment by cscheid** [comment] 2024-05-06 18:41
> I am not aware of the requirement for a trailing `/` for canonical URLs as implied in the expected behaviour though.

We have to be very careful about how to resolve this in the case of `index.qmd` files, because `GET /subdir/` is **very** different from `GET /subdir`, and this is a constant source of confusion for users.

I know many people think this is ugly, but I think `foo/index.qmd` should be resolved to `foo/index.html`. It's the only safe client-side resolution that doesn't imply additional behavior from the HTTP server (about which Quarto shouldn't assume any additional behavior). There's no guarantee that a web server will respond to `foo/` by searching for `foo/index.html`, and the situation gets even worse when web servers redirect `foo` to `foo/index.html`, because the parent directory structure now has changed.

I believe that as of right now, Aron's "expected behavior" is what we expected to do. The actual behavior is completely broken, but I think we should instead fix it to `about/index.html` instead.

**Comment by mcanouil** [comment] 2024-05-06 18:43
Spo the function would be: something like below?

```ts
export function synthesizeCitationUrl(
  input: string,
  metadata: Metadata,
  outputFile?: string,
  offset?: string,
) {
  const siteMeta = metadata[kWebsite] as Metadata | undefined;
  let baseUrl = siteMeta?.[kSiteUrl] as string;
  baseUrl = baseUrl.replace(/\/$/, "");

  if (baseUrl && outputFile && offset) {
    const rootDir = normalizePath(join(dirname(input), offset));
    if (outputFile === "index.html") {
      const part = pathWithForwardSlashes(relative(rootDir, dirname(input)));
      if (part.length === 0) {
        return `${baseUrl}/`;
      } else {
        return `${baseUrl}/${part}/`;
      }
    } else {
      const relativePath = relative(
        rootDir,
        join(dirname(input), basename(outputFile)),
      );
      const part = pathWithForwardSlashes(relativePath);
      return `${baseUrl}/${part}`;
    }
  } else {
    // The url is unknown
    return undefined;
  }
}
```

**Comment by cscheid** [comment] 2024-05-06 18:46
Show me the diffs in a PR?

**Comment by mcanouil** [comment] 2024-05-06 18:46
coming right up.

**Comment by aronatkins** [comment] 2024-05-06 19:07
I'll also note that I went to configure `canonical-url` because a Quarto site may include both `sub/` and `sub/index.html` links. Crawlers encounter both URLs and complain about duplicate content.

If Quarto could emit only `sub/` links, I would not need a site-wide `canonical-url` configuration.

**Comment by cscheid** [comment] 2024-05-06 19:54
> Crawlers encounter both URLs and complain about duplicate content.

Huh. I think that's a problem with the crawler, for similar reasons as I stated above :( Unfortunately, there's no guarantee that `sub/` and `sub/index.html` will be the same resource, and I don't think we should be dictating that.

**Comment by aronatkins** [comment] 2024-05-06 20:02
> I think that's a problem with the crawler, for similar reasons as I stated above

I see your problems with the crawler and raise you:

https://github.com/quarto-dev/quarto-cli/blob/a604268ea7724d8991512f1f7ed89ce7b84f391a/src/resources/projects/website/navigation/quarto-nav.js#L271-L279

`PATH/index.html` is rewritten in the browser to `PATH/`.

I don't want to shift the purpose of this issue, which is reporting URL construction problems.

**Comment by cscheid** [comment] 2024-06-06 21:52
(Coming back to this)

Yuck, that index.html rewriting is a "bug". We need to, at the very least, be able to disable the behavior if wanted.

**Comment by mcanouil** [comment] 2024-06-06 22:01
As a reminder, The OP issue is fixed in the linked PR, it's just lacking the full tests for sub directories.

- #9595

**Closed** 2024-06-13 10:23 UTC
Labels: bug, websites
