### ISSUE TITLE
Cache on rendering videos bug

### ISSUE THREAD

**Issue by danilotpnta** [quarto-dev/quarto-cli#6577] opened 2023-08-22 08:05 UTC
### Bug description

If I want to insert a video with html I need to first use ![]() and then erase that and use <video> tag. Example:

I.e. I have a video called demo.mp4 that I want to show it in a qmd file. If I do: 
<video src="demo.mp4" class="img-fluid" ></video>
It does not show.

However, if I first let quarto render
![](demo.mp4)
and then comment and use 
<video src="demo.mp4" class="img-fluid" ></video>
then it shows.

It this normal bhv? Explanation would be appreciated. Thank you 

### Steps to reproduce

---
title: "Title"
date: "2023-08-22"
---

<video style="border-radius: 7px"  class="img-fluid" autoplay="true" loop="true" src="demo.mp4" class="img-fluid" ></video>

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.0 (Conda)
      Path: /../envs/openCV/bin/python
      Jupyter: 5.2.0
      Kernels: git-pages, opencv, ml, cv, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.1/Resources/library
      knitr: 1.37
      rmarkdown: 2.11

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment] 2023-08-22 09:27
Thanks for the report!

Could you format your post using code blocks (_i.e._, ` ``` `) and could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by cscheid** [comment] 2023-08-22 15:06
In quarto, we expect you to use the [`{{< video >}}` shortcode](https://quarto.org/docs/authoring/videos.html). I'm going to go ahead and close this issue, but if that doesn't solve your problem, feel free to reopen it.

**Closed by cscheid** 2023-08-22 15:06 UTC
Labels: bug, needs-repro, video

**Comment by danilotpnta** [comment] 2023-08-22 16:09
Thank you @cscheid for quick response. This is not the case though, I have replaced it as documentation and as you have suggested but I still video does not show.

Regarding the warning I am not receiving what you've mentioned. 
I am getting: 
GET: /blog/2023-08-22_video-error/index.html
  /blog/2023-08-22_video-error/demo.mp4 (404: Not Found)

Very frustrating but also fun to learn Quarto, thanks for the hard work guys. Let me know if you can replicate my issue my website can be forked. Cheers

**Comment by cscheid** [comment] 2023-08-22 16:26
I really cannot reproduce this error. This is with `quarto preview` directly from your latest commit:

<img width="808" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/2b2bbce9-75cb-408a-9ab9-50385a709d1f">

If you look at your `gh-pages` branch, you will see that it is missing the actual video file. I don't know how you're creating that branch, though.

**Comment by cderv** [comment] 2023-08-30 14:37
> If you look at your gh-pages branch, you will see that it is missing the actual video file. I don't know how you're creating that branch, though.

Possibly related to 
* https://github.com/quarto-dev/quarto-cli/issues/3892 and others linked there 

But I think it may have been fixed by https://github.com/quarto-dev/quarto-cli/commit/eb969b2b0625d785ec57665e65129bf1c9dbde36 - this requires Quarto 1.4 pre-release to work  and you have  1.3 if I look at your Quarto check.
