### ISSUE TITLE
Support for arm64 arch

### ISSUE THREAD

**Issue by pat-s** [quarto-dev/quarto-cli#4215] opened 2023-02-04 11:47 UTC
### Bug description

I'd like to ask if there are any plans to support arm64 for Linux? 

Quarto not being available for arm64 currently blocks a full-fledged Posit Workbench arm64 setup. 

AFAICS one blocking issue is that `deno` is not yet available for arm64? https://github.com/denoland/deno/issues/1846

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment] 2023-02-04 13:26
We are hoping to have this for our 1.3 release- we have found a reliable build of Deno for arm64 that we will attempt to use!

I'll leave this open to track our local status...

**Comment by salfaris** [comment] 2023-02-04 17:21
I got a problem with running `quarto` on my Mac M1. Is that related to this issue – i.e. that you can't run `quarto` on Mac M1 yet – or is arm64 for Linux a different thing? In the latter case, I will post a new issue, but I want to confirm this first here.

**Comment by dragonstyle** [comment] 2023-02-05 14:25
That is a different issue - Quarto should work well on an M1 Mac.

**Comment by salfaris** [comment] 2023-02-05 15:02
Great to know, and for some magical reason my issue was also resolved on its own today.

**Comment by eitsupi** [comment] 2023-02-06 23:29
I think this issue is duplicate of #190.

**Comment by dragonstyle** [comment] 2023-02-08 01:50
Let us know if you run into further problems. Native support for ARM on Linux should be available shortly. Closing as a duplicate as noted above.

**Comment by eitsupi** [comment] 2023-02-11 03:59
It seems to still be open.

**Comment by dragonstyle** [comment] 2023-02-11 15:07
(ARM64 support for Linux is available now in the Quarto pre-release)

**Closed** 2023-02-11 15:06 UTC
Labels: bug

**Comment by cbrnr** [comment] 2023-02-22 19:43
Is native support for ARM64 Macs (M1/M2) also planned (if so, when)? I just tried the 1.3 prerelease, but it still prompts me to install Rosetta.

**Comment by cscheid** [comment] 2023-02-22 20:28
@cbrnr we have native _deno_ support for it, but some of our dependencies don't build for Apple Silicon. Specifically,

- Pandoc [currently only releases x86_64 mac builds](https://github.com/jgm/pandoc/issues/6960)
- we are using an older build of esbuild which we plan to upgrade soon.

**Comment by cbrnr** [comment] 2023-02-23 08:37
Thanks @cscheid! Should I open a new issue to track Apple Silicon support?

Regarding Pandoc, Homebrew has been shipping a native version for almost 2 years now. Would it make sense to ping the Pandoc developers and ask if there are any remaining issues? If so, would it be possible to use the Homebrew version when you build Quarto for Mac?

**Comment by cscheid** [comment] 2023-02-23 16:09
We want to depend on first-party builds only, if at all possible. I'm curious - is there a specific reason you don't want Rosetta 2 installed? I develop primarily on M1 and haven't experienced any issues with Pandoc's x86_64 version.

**Comment by cbrnr** [comment] 2023-02-23 17:50
I have no problem with installing and using Rosetta 2 if that's the only way I can run a particular app. I've also had zero issues using Pandoc so far. However, obviously this is far from ideal, and although Rosetta2 works really nicely and surprisingly fast, a native binary is still a lot faster and more efficient. Not that it matters much for Pandoc, but since M1 has been out for more than 2 years, and Homebrew has had a native version since almost 2 years, I'd say building an ARM version of Pandoc should be possible. I suppose it comes down to finding some CI that supports Apple Silicon, but there are should be a few available nowadays. I guess I'll just ask them, as it also looks like this issue has probably been forgotten.

**Comment by cbrnr** [comment] 2023-03-13 16:52
@cscheid the next Pandoc release will include a native Apple Silicon binary. I guess this means that Quarto could also make a native release soon?

**Comment by cscheid** [comment] 2023-03-13 17:26
Let us know when that exist, and we'll make sure to do it on our side!

**Comment by cbrnr** [comment] 2023-03-28 12:45
Pandoc 3.1.2 has just been released, and it now includes an ARM64 macOS package!

https://github.com/jgm/pandoc/releases/tag/3.1.2

**Comment by cscheid** [comment] 2023-03-28 15:17
We're very late into 1.3, and being very conservative about changes to take into 1.3. But we'll definitely change our 1.4 packages to have a native apple silicon binary.
