### ISSUE TITLE
Quotation marks rendering as TeX ligatures 

### ISSUE THREAD

**Issue by pascalsiemsen** [quarto-dev/quarto-cli#6613] opened 2023-08-25 07:50 UTC
### Bug description

If using quatation marks in a quarto document and rendering to pdf, the quotation marks come out as the latex quotation marks and not the curly ones. 

This is not the case when converting the document to markdown and running pandoc.

```
pandoc -f markdown -t pdf -o qu.pdf  test_quotation_marks_md.md 
```

 I suppose it has something to do with the "smart" extension?

https://pandoc.org/chunkedhtml-demo/7.1-typography.html

### Steps to reproduce

Quarto document:

````qmd

---
title: "Test"
format: pdf
---

## Quarto


Test the quotation "marks" here and 'here'. 

````

and press render in Rstudio.

### Expected behavior

[qu.pdf](https://github.com/quarto-dev/quarto-cli/files/12436881/qu.pdf)

### Actual behavior

[test_quotation_marks.pdf](https://github.com/quarto-dev/quarto-cli/files/12436842/test_quotation_marks.pdf)

### Your environment

- IDE: Rstudio 2023.06.1.524-1
- Endeavour OS

### Quarto check output

```bash

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

(-) Checking Jupyter engine render....[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib64/R
      LibPaths:
        - /home/pascal/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/lib/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK


```

**Comment by cderv** [comment] 2023-08-25 13:53
This is indeed related to the `smart` extension. Usually with Quarto you can pass extension to `format` string like this 
````markdown
---
title: "Test"
format: latex-smart
---

## Quarto


Test the quotation "marks" here and 'here'.

````

However, it does not work with `format: pdf-latex` - probably because it really means `--to latex` for Pandoc and then we convert to `pdf` ourself, so we need to extract extensions and append to `latex`

@dragonstyle do you know if we already handle this ?

**Comment by dragonstyle** [comment] 2023-09-20 21:38
I'm not reproducing this issue using Quarto 1.4.* or Quarto 1.3.450 - LaTeX quotes are being properly rendered (as attached). The `+smart` extension is default enabled in pandoc for latex output (which is what it would see when we use to render the latex before we convert that to PDF), so I'm not sure what would explain the difference in our output (and in fact, the rendered PDF shows the typopgraphic characters that should be rendered by LaTeX to curly quotes).

One theory would be the presence or absence of fonts on the system that is rendering the output - perhaps you are using a font which doesn't support typographic glyphs? 

[test.pdf](https://github.com/quarto-dev/quarto-cli/files/12677678/test.pdf)

**Comment by cderv** [comment] 2023-09-21 08:12
Indeed I can't reproduce either, or I misunderstood in the first place. Sorry.  

What is relevant in my previous comment is that we have probably no way to pass `-smart` Pandoc extension when rendering to PDF with quarto. 🤔 Maybe something we should improve and allow

**Comment by pascalsiemsen** [comment] 2023-10-02 13:00
Thanks for the comments. I still don't know where the problem lies. But I found out that it is related to using xelatex. Using pdflatex works fine. The font is "IBM Plex Serif".

Works:

```

---
title: "Fonts in Quarto"
format:
  pdf:
    pdf-engine: pdflatex
    include-in-header:
      - text: |
          \usepackage{plex-serif}
---

## Quarto

Quarto enables you to weave together content and executable code into a finished "document". 

```

Does not work:

```

---
title: "Fonts in Quarto"
format: pdf
pdf-engine: xelatex
mainfont: "IBM Plex Serif"
---

## Quarto

Quarto enables you to weave together content and executable code into a finished "document". 


```

**Comment by cderv** [comment] 2023-10-02 13:26
Can you run with `keep-tex: true` and look into the `tex` content produced for the quotes ?

**Comment by pascalsiemsen** [comment] 2023-10-02 14:11
The output in the tex file is ``document''.

I've installed quarto on a different laptop and used tintytex (`quarto install tinytex) instead of the local texlive install (on Arch Linux) and the quotes work under xelatex. Hence, it is something with my installation and I will look into that.

**Comment by cscheid** [comment] 2023-10-04 16:24
Thanks for the added context! We have sporadic latex issue reports from Arch users, and this is good to know. I'm going to go ahead and close the issue.

**Closed by cscheid** 2023-10-04 16:24 UTC
Labels: bug, needs-repro, latex
