### ISSUE TITLE
Embeds within includes do not work in projects

### ISSUE THREAD

**Issue by davidpomerenke** [quarto-dev/quarto-cli#6304] opened 2023-07-21 16:05 UTC
### Bug description

When a file `{{< include >}}`s another file that `{{< embed >}}`s content from a Jupyter notebook, the embed is ignored, as long as the files are situated within a Quarto project. When no `_quarto.yaml` project declaration is present, it works!

### Steps to reproduce

See https://github.com/davidpomerenke/quarto-bugs/tree/main/embeds

### Expected behavior

The embed should be displayed.

This is actually the case when

- rendering the `{{< include >}}`d file directly
- deleting `_quarto.yaml`

but not in this not-so-uncommon setting of having a project and sub-documents.

This contradicts

> Include shortcodes are equivalent to copying and pasting the text from the included file into the main file. (https://quarto.org/docs/authoring/includes.html)

### Actual behavior

The embedded figure (same for tables btw) is just not displayed.

### Your environment

- IDE: VSCode
- OS: MacOS Ventura 13.4.1 (c) 

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10 (Conda)
      Path: /opt/homebrew/Caskroom/miniconda/base/bin/python3
      Jupyter: 5.2.0
      Kernels: ir, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.39
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2023-07-27 20:54
Thanks for the report.

I can reproduce using your repository (thanks for providing it).

**Comment by dragonstyle** [comment] 2023-07-31 14:10
I can't reproduce this on the latest pre-release version of Quarto (which does have changes related specifically to project behavior of embeds). Could you try updating to this version and confirm that the issue is also resolve?

**Comment by mcanouil** [comment] 2023-07-31 14:45
I no longer can reproduce using the latest development version.
I am going to go ahead and close this as resolved.

@davidpomerenke If you can upgrade to 1.4 pre-release, you should see it is fixed. If not for some reason, feel free to comment/reopen this issue.

**Closed by mcanouil** 2023-07-31 14:45 UTC
Labels: bug, triaged-to, includes

**Comment by davidpomerenke** [comment] 2023-07-31 22:56
You're right, it seems to be resolved in pre-release. Thank you!
