### ISSUE TITLE
Support cross reference to book part

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#3234] opened 2022-11-08 02:44 UTC
### Bug description

Originally reported at https://github.com/quarto-dev/quarto-cli/discussions/3218

Quarto supports [cross reference to book chapters](https://quarto.org/docs/books/book-crossrefs.html) but does **not** support to book parts.

![Screenshot 2022-11-08 at 10-43-17 MWE](https://user-images.githubusercontent.com/1506457/200462372-3455379b-078f-4e1f-a5e9-f8e7975cd883.png)
 
[Minimal working example](https://github.com/quarto-dev/quarto-cli/files/9957180/3218.zip).

`quarto check` output

```
[✓] Checking Quarto installation......OK
      Version: 1.2.117
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.10 (Conda)
      Path: /home/raniere/mambaforge/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /usr/lib/R
      LibPaths:
        - /home/raniere/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.16

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by baptiste** [comment] 2022-11-08 04:22
I seem to have run into a similar issue with a book I'm writing; references aren't picked up or resolved in the Front and Back matter. I'll try to narrow it down to a minimal example, but I wanted to follow the thread here in case it's the same issue.

**Comment by DhruvaSambrani** [comment] 2023-03-14 20:07
Not entirely sure if this is the same issue, but "chapters" in my book are not being crossref'd in html output (works fine in pdf). Each of my "chapters" is a different file with a H1 title and #sec-xxx label.

H2 level "sections" are fine. 

I'm a little lost on the terminology, so please forgive me

**Comment by cscheid** [comment] 2023-05-23 17:07
This is a duplicate of #2571.

**Closed by cscheid** 2023-05-23 17:07 UTC
Labels: bug, duplicate, crossref
