### ISSUE TITLE
graphviz dot cell ignores figure caption and other info unless it's the first chunk in the script

### ISSUE THREAD

**Issue by harrelfe** [quarto-dev/quarto-cli#3660] opened 2022-12-13 18:31 UTC
### Bug description

The following example documents the problem.  No figure caption or figure number appears unless the first chunk is removed.  I'm using Quarto 1.3.55 on Ubuntu 22 and running `quarto render test.qmd`.

````
---
title: "Test"
format:
  html:
    self-contained: true
---


```{r}
x <- 3
```

```{dot}
//| label: fig-labt
//| fig-cap: "This is a figure caption"
digraph D {
  FOO [label="xyz"];
  FOO -> {BAR, BAZ};
}
```
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2023-05-23 17:49
(Sorry for the delayed response!) I can't reproduce this using the latest stable 1.3 version. I'm going to assume we fixed this and close the issue, but if it still happens for you, please feel free to reopen.

**Closed by cscheid** 2023-05-23 17:49 UTC
Labels: bug, crossref
