### ISSUE TITLE
Limiting table size with quarto using Julia

### ISSUE THREAD

**Issue by ymer** [quarto-dev/quarto-cli#6897] opened 2023-09-19 11:24 UTC
### Bug description

If I run `pretty_table(df, display_size = (50, 50))` this displays only a limited part of the large dataframe df.

However, if I `quarto render` this inside a julia block in a .qmd file, the resulting html file has no limitations on the table size.

### Your environment

- OS: MacOS Ventura 13.5.2
- IDE: terminal

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: /opt/homebrew/anaconda3/bin/python
      Jupyter: 4.11.1
      Kernels: julia-1.8, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/jsmp/Library/R/arm64/4.2/library
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.41
      rmarkdown: 2.18

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment] 2023-09-19 11:25
Thanks for the report!

Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by ymer** [comment] 2023-09-19 11:31
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{julia}
using DataFrames, PrettyTables

n = 1000
df = DataFrame(A = rand(n), B = rand(n), C = rand(n))
pretty_table(df, header = names(df), display_size = (50, 50))
```

The end.
````

**Comment by mcanouil** [comment] 2023-09-19 12:30
Also the output of `quarto check` as initially requested in the issue template, please.

**Comment by cderv** [comment] 2023-09-19 13:33
@ymer from the doc at https://ronisbr.github.io/PrettyTables.jl/stable/lib/library/#PrettyTables.pretty_table-Tuple{Any}

> display_size::Tuple{Int, Int}: A tuple of two integers that defines the display size (num. of rows, num. of columns) that is available to print the table. It is used to crop the data **depending on the value of the keyword crop**. Notice that if a dimension is not positive, then it will be treated as unlimited. (Default = displaysize(io))

You did not set `crop`

> crop::Symbol: Select the printing behavior when the data is bigger than the available display size (see display_size). It can be :both to crop on vertical and horizontal direction, :horizontal to crop only on horizontal direction, :vertical to crop only on vertical direction, or :none to do not crop the data at all. **If the io has :limit => true, then crop is set to :both by default. Otherwise, it is set to :none by default.**

I understand that the default IO here has set `crop = :none`. If you set `crop = :both`, you'll see the effect of your display size for the text output. `display_size` and `crop` are for text backend output.

**Comment by dragonstyle** [comment] 2023-11-28 20:33
Based on the latest message here, this looks like we can safely close this. Please feel free to re-open if it seems there is something we should look more closely at.

**Closed by dragonstyle** 2023-11-28 20:33 UTC
Labels: julia, support
