### ISSUE TITLE
Visual Editor Changes Figure Labels

### ISSUE THREAD

**Issue by BradyAJohnston** [quarto-dev/quarto-cli#6548] opened 2023-08-17 09:01 UTC
### Bug description

In quarto 1.4, When changing from source to visual editor, in both VSCode and RStudio, if there are multiple `.qmd` files in a project, then the name of the current `.qmd` files is prepended into the `#fig-example` labels for figures.

For a file called `intro.qmd`, `#fig-example` becomes `#intro-fig-example`, which subsequently breaks all in-text references to the figure.

The effect stacks. So I tested it in VScode, which prepended the `intro`, then opened in RStudio and tried the visual editor and it did the same thing, turning the example in to `#intro-intro-fig-example`.

Did not previously occur with quarto 1.3.450 which I had installed prior to testing out the daily build.

### Steps to reproduce

Using the base project from `quarto create-project mybook --type book`, in `intro.qmd` I added two possible figures.

````qmd
# Introduction

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.

::: {#fig-example}
![](https://i.imgur.com/gSfYoGT.jpg)

A dogo photo.
:::

![](https://i.imgur.com/gSfYoGT.jpg){#fig-example-2}
````

### Expected behavior

The figure labels should remain unchanged, when moving between visual and source editors.

### Actual behavior

`intro` was prepended on to each of the figure labels, resulting int the below `.qmd` file: 

````qmd
# Introduction

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.

::: {#intro-fig-example}
![](https://i.imgur.com/gSfYoGT.jpg)

A dogo photo.
:::

![](https://i.imgur.com/gSfYoGT.jpg){#intro-fig-example-2}
````

### Your environment

MacOS Ventura 13.4, 2017 macbook pro. Tested on both VSCode and RStudio.

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.322
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/brady/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10 (Conda)
      Path: /usr/local/Caskroom/miniconda/base/bin/python
      Jupyter: 5.3.1
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK
```

**Comment by mcanouil** [comment] 2023-08-17 09:21
Seems heavily related to:
#6545

**Comment by jjallaire** [comment] 2023-08-19 11:52
This is almost certainly due to a Pandoc update (and related change in the behavior of `--id-prefix`). I'll investigate further.

**Comment by jjallaire** [comment] 2023-08-19 11:57
It's this change right here: https://github.com/jgm/pandoc/issues/8878

Formerly `--id-prefix` only affected footnotes for markdown output, now it affects all ids.

**Comment by jjallaire** [comment] 2023-08-19 13:13
Reported upstream here: https://github.com/jgm/pandoc/commit/561510166f59b024beb5d49f1c0575ba8efce147#commitcomment-124935109

We will revert to an earlier version of Pandoc while we wait for resolution: https://github.com/quarto-dev/quarto-cli/pull/6558

**Comment by jjallaire** [comment] 2023-08-21 18:49
@BradyAJohnston We've rolled back to Pandoc 3.1.2 while waiting for a fix. You can download this version (v1.4.330) here: https://quarto.org/docs/download/prerelease.html

**Comment by BradyAJohnston** [comment] 2023-08-22 06:16
Yep that works no with `1.4.330`, thanks for the fix!

**Comment by mcanouil** [comment] 2023-08-22 06:27
@BradyAJohnston glad it works unfortunately that's not really a fix but more of a temporary solution.

**Comment by cscheid** [comment] 2023-11-30 19:27
This is a duplicate of #6505

**Closed by cscheid** 2023-11-30 19:27 UTC
Labels: bug, duplicate, editors, triaged-to
