### ISSUE TITLE
PDF format: what is the best way to include a single figure with long captions and a label?

### ISSUE THREAD

**Issue by JulianTao** [quarto-dev/quarto-cli#217] opened 2021-12-12 03:59 UTC
When including a single figure with long captions, I tried several different strategies.

1. Use the markdown `img` syntax directly

```
![This is a long caption. (a) $\theta=2*x^2$; (b) this is the second part; (c) this is the third part](./img/Fig2.pdf){#fig-native}

```
This worked as expected and the figure is **centered** by default; the captions are rendered properly. The figure is **numbered** and cross-ref works as expected.

**However, in the editor, the text does not look clean and tidy.** 

I prefer to define long captions outside of the brackets `[ ]`, so I tried the following

2. Use the quarto `layout` with 1 column
```
::: {#fig-layout layout-ncol=1}
![](./img/Fig2.pdf) 

This is a long caption. (a) $\theta=2*x^2$; (b) this is the second part; (c) this is the third part
:::
```
This strategy worked, **except that the figure is no longer "centered"**. After checking the `tex` file, it is found that the image was implemented using a `minipage` environment.

3. To center the image using the layout method, 
```
::: {#fig-layout2 layout="[-30, 40, -30]"}

![](./img/Fig2.pdf) 

This is a long caption. (a) $\theta=2*x^2$; (b) this is the second part; (c) this is the third part
:::
```
This worked, expect that **one need to manually adjust the layout parameters; and three minipage environments were created in the `tex` file and made it inconvenient to submit to a publisher**

4. Lastly, I tried the [`Figure Div`](https://quarto.org/docs/authoring/figures-and-layout.html#figure-divs) as described in the quarto documentation
```
::: {#fig-div}
![](./img/Fig2.pdf) 

This is a long caption. (a) $\theta=2*x^2$; (b) this is the second part; (c) this is the third part
:::
```
The figure is inserted. But there are a few problems. 

-  The figure is not centered
-  The figure is not numbered
-  Figure reference still partially work but no number is given

After checking the `tex` file, it is found that the figure is not put in a `figure` environment. 

**Summary:**
-  Native markdown syntax works best and gives a clean `tex` file; but the editing experience is not idea
-  Quarto layouts work; the `tex` file is not as clean; and the editing experience is not idea
-  Quarto `figure div` does not give satisfactory results

**Idea method:**
- use quarto `figure div` syntax, but put it into a `figure` environment for latex output.

Thanks for your patience and time for reviewing all my issues!

**Comment by jjallaire** [comment] 2021-12-12 12:45
The `figure div` syntax is _supposed_ to work exactly as you describe (centered, supporting cross refs, using a `figure` environment, etc.). We recently made a bunch of changes to figure to support laying them out within or across the right margin, and my guess is that we broke something while doing that.

@dragonstyle Here is my simple repro case for the figure div not working:

```markdown
::: {#fig-foo}
![](images/image.png)

This is the figure
:::

See @fig-foo for more.
```

Could you take a look to see what might be going wrong here?

**Comment by dragonstyle** [comment] 2021-12-13 18:09
Ok, we had definitely regressed the way we were handling figure divs, and I've made a change to fix that regression here: 3a886685819e849c1418d1cd522447c95e29da65.

This should provide the expected figure behavior- great catch!

**Comment by JulianTao** [comment] 2021-12-13 19:06
> Ok, we had definitely regressed the way we were handling figure divs, and I've made a change to fix that regression here: [3a88668](https://github.com/quarto-dev/quarto-cli/commit/3a886685819e849c1418d1cd522447c95e29da65).
> 
> This should provide the expected figure behavior- great catch!

I confirm that it works as expected. Thank you!

**Comment by JulianTao** [comment] 2022-01-03 00:21
> Ok, we had definitely regressed the way we were handling figure divs, and I've made a change to fix that regression here: 3a886685819e849c1418d1cd522447c95e29da65.
> 
> 
> 
> This should provide the expected figure behavior- great catch!

Hi Charles, it seems that this issue reappeared in the newer versions.

**Comment by dragonstyle** [comment] 2022-01-03 01:05
Hmm so sorry about that! I’ll take a look!

**Comment by dragonstyle** [comment] 2022-01-03 01:43
Ok I just took a look and the simple test case:

```
::: {#fig-foo}
![](images/image.png)

This is the figure
:::

See @fig-foo for more.
```

Does appear to still be working correctly. Do you have an example I could use to reproduce the issue that you're seeing?

**Comment by JulianTao** [comment] 2022-01-03 02:05
I used the same test. The cross-ref and caption work as expected. But as before, the figure is not centered.

**Comment by jjallaire** [comment] 2022-01-03 02:54
I know you can do `fig-align=center` to get center alignment.

@dragonstyle I don't recall whether center alignment is the intended default for figures (I thought it was left?)

**Comment by JulianTao** [comment] 2022-01-03 04:28
It seems that neither `{fig-align="center"}` nor `{fig-align=center}` works for PDF format. They do both work for html output thought. 

Also, I can confirm that, when rendered using the latest version of Quarto the default alignment for a figure is indeed left for html output format.

For all the output formats, is it possible that an user can set the default alignment in the YAML header? For most of my use cases, I center align the figures. 

BTW, I updated to the latest version today, the figures were center aligned by default before the update (I could not figure out which exact version I used, but it was definitely before the Christmas break when I updated the version last time).

**Comment by JulianTao** [comment] 2022-01-03 04:33
BTW, if I use the markdown syntax for figures instead of figure-div, the default is center-aligned, for both pdf and html formats.

**Comment by jjallaire** [comment] 2022-01-03 13:12
Okay, that's a good thing to note! We'll dig into this more here and make sure we get it right.

We did check in a bunch of changes over the holiday break related to `tbl-cap` and `tbl-subcap` -- these did also touch figure handling so I'm not 100% surprised there was a regression.

**Comment by dragonstyle** [comment] 2022-01-03 17:13
This is fixed once again in 5c1446830b9176bda7386d22d30d479397374df2 . This time I've also added a test to compare the output of figures when generated using divs vs imgs, so hopefully we'll catch that before you do next time @JulianTao . 

The latest build should have this fix (https://github.com/quarto-dev/quarto-cli/releases/tag/v0.2.415). Thanks for finding this again!

**Comment by JulianTao** [comment] 2022-01-06 20:07
I can confirm that this works for the single figures now.

Just spotted that, for subfigures with `layout-ncol` or `layout-nrow` options, the subcaptions "(a)", "(b)" and etc are centered with regard to the page width, but the subfigures are left aligned. 

Reproducible snippets:

```markdown
::: {#fig-foo layout-nrow=2}

![](img/kitten.png){#fig-foo1}

![](img/kitten.png){#fig-foo2}

This is the figure
:::

See @fig-foo for more.
```
or 

```markdown
::: {#fig-bar layout-ncol=2}

![](img/kitten.png){#fig-bar1 width=2in}

![](img/kitten.png){#fig-bar2 width=2in}

This is the figure
:::

See @fig-bar for more.
```

**Comment by jjallaire** [comment] 2022-01-07 20:02
Thanks for following up, that was indeed not working properly! Fix is here: https://github.com/quarto-dev/quarto-cli/commit/664b095c0f35703c0c52b0370d2e9482c85b6fcd (will be in build v0.2.454)

**Closed by jjallaire** 2022-01-07 20:02 UTC
