### ISSUE TITLE
Julia transpose operator not rendering properly

### ISSUE THREAD

**Issue by Gabrielforest** [quarto-dev/quarto-cli#991] opened 2022-05-26 22:45 UTC
Hi! The code bellow works just fine but it seems to be rendering as a string sign when it should be a transpose sign.

![image](https://user-images.githubusercontent.com/63704591/170590943-6ca3e0f8-d4af-46fb-a8d6-285146a30a20.png)

This problem also occurs on Rstudio IDE (at VS Code it did not happen).

![image](https://user-images.githubusercontent.com/63704591/170591093-60a873ed-cb53-4712-8980-7e28eb270a0b.png)

**Comment by jjallaire** [comment] 2022-05-31 23:44
Could you provide some paste-able snippets so that we can reproduce this? It would also be good to see an example of what the output / editor is supposed to look like.

**Comment by Gabrielforest** [comment] 2022-06-01 00:08
> Could you provide some paste-able snippets so that we can reproduce this? It would also be good to see an example of what the output / editor is supposed to look like.

The parentheses shouldn't be green. It should be white, the same problem with the color happens on Rstudio IDE. The output works properly, but the code colors not.

**Comment by jjallaire** [comment] 2022-06-01 00:14
I see, the syntax highlighting is wrong! This unfortunately needs to be fixed in the respective syntax highlighting modes of pandoc (KDE) and RStudio. 

For Pandoc, the author(s) of the Julia highlighting should be notified of this (or ideally be given a pull request for it): https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/julia.xml

For RStudio, the Ace highlighting mode for Julia needs to be improved: https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/julia_highlight_rules.js

**Closed by jjallaire** 2022-06-01 00:14 UTC

**Comment by jjallaire** [comment] 2022-06-30 17:43
Hi there @Gabrielforest, posting back here because I'm giving a talk on Quarto at JuliaCon next month and was hoping to find some good examples of using Julia w/ Quarto. If you are able to share any of your own (or are aware of others) please LMK over on this discussion thread: https://github.com/quarto-dev/quarto-cli/discussions/1261. Thanks!

**Comment by Gabrielforest** [comment] 2022-07-01 10:30
Hi! I have got an example https://github.com/Gabrielforest/kaggle_competitions/tree/main/digit_recognizer and maybe some of my connections from Linkedin are using Julia with Quarto package. Can I post your question there?
