### ISSUE TITLE
Local videos with video shortcode in website projects fail to load.

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#5496] opened 2023-05-11 08:33 UTC
## Description: 
Local videos with video shortcode in website projects fail to load.
May be related to https://github.com/quarto-dev/quarto-cli/issues/3892.

## Steps to Reproduce:
- Create a simple website project `quarto create-project mysite --type website`
- `cd mysite`
- Add `local-video.mp4` so it is in the root of the site.
- Update `index.qmd`
```
---
title: ''
---

{{< video local-video.mp4 >}}

```
- `quarto preview mysite`

### Expected Result:
The video loads.

### Actual Result:
The video does not load.
Console error: `/local-video.mp4 (404: Not Found)`

#### Workaround
- Manually copy `local-video.mp4` to `_site` directory.  It now works.

**Comment by allenmanning** [comment] 2023-06-01 08:13
As requested @cscheid I've added you as an assignee.

**Comment by cderv** [comment] 2023-06-01 10:15
@allenmanning I believe this is because of this issue: https://github.com/quarto-dev/quarto-cli/issues/5268

The video shortcode is inserting the following code 
```html
<div class="quarto-video"><video id="video_shortcode_videojs_video1" class="video-js vjs-default-skin vjs-fluid" controls="" preload="auto" data-setup="{}" title=""><source src="[local-video.mp4](http://localhost:3709/local-video.mp4)"></video></div>
````

and `<source>` is not among the html element parsed to identified which resource to move into the `_site` folder. 

So I think this is a duplicate of #5268 and fixing this will fix the video shortcode issue.

**Closed** 2023-07-03 13:37 UTC
Labels: bug, websites, video
