### ISSUE TITLE
Wrong title in revealjs when including a code block

### ISSUE THREAD

**Issue by m-guggenmos** [quarto-dev/quarto-cli#6411] opened 2023-08-02 15:14 UTC
### Bug description

If the following two conditions are met, the title of a revealjs presentation is erroneously set to the heading of the first slide:

1. Using `_quarto.yml` to define the title
2. Including a block of code in one of the slides

### Steps to reproduce

_quarto.yml
```
project:
  output-dir: _slides
  render:
    - test.qmd

title: "My title"
author: "John Doe"

format: revealjs
```

test.qmd
~~~
## First slide heading

```{python}

```
~~~

### Expected behavior

The title on the title slide is "My title".

### Actual behavior

The title on the title slide is "First slide heading".

### Your environment

- VSCode version 1.80.1
- Quarto Extension v1.90.0
- OS: Ubuntu Linux

### Quarto check output

~~~
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.251
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /usr/lib/R
      LibPaths:
        - ~/R
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
~~~

**Comment by cderv** [comment] 2023-08-22 10:13
Thanks for the report. I can reproduce in a specific situation. 

* It happens with Jupyter engine and not knitr engine 
* It is not link to revealjs and it will also happen with `format: html`

* `_quarto.yml`
````yaml
title: "My title"
author: "John Doe"

format: html
````

* `index.qmd`
````
## First slide heading

Some content

```{python}
1 + 1
```
````

`title` is correctly identified in the metadata
````
Starting python3 kernel...Done

Executing 'index.ipynb'
  Cell 1/1: ''...Done

pandoc 
  to: html
  output-file: index.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: My title
  author: John Doe
  
Output created: index.html
````

but indeed the document move the `##` as title, and overwrite it. 

To me, this is a duplicated (or at least a variation) of
* https://github.com/quarto-dev/quarto-cli/issues/5363

@dragonstyle I am assigning you on this as this is probably website related. 
@cscheid I remember some discussion (but can't find it) about `.qmd` document for Jupyter with no title, and first header being used. 

It seems here, we should at least consider the global `title` meta before using the `##` as the title of the document.

**Comment by knuesel** [comment] 2023-10-05 15:52
I think I have a fix for this but it requires a bit more work (just a note to avoid duplicating efforts).

**Comment by mcanouil** [comment] 2023-10-05 19:47
Thank you @knuesel for letting us know and your future contribution!

**Comment by dragonstyle** [comment] 2023-12-14 12:42
This is actually not fixed in the referenced commit (it is more specifically a project title being present and should be dealt with separately).

**Closed** 2023-12-14 16:25 UTC
Labels: bug, jupyter

**Comment by floholl** [comment] 2025-04-22 11:06
I believe I might continue to observe a variation of this issue with Quarto 1.7.27:

I can confirm that in that Quarto version, the issue is resolved in the [MWE](https://github.com/quarto-dev/quarto-cli/issues/6411#issuecomment-1687902179) provided by @cderv, as [these release notes](https://github.com/quarto-dev/quarto-cli/blob/v1.4.557/news/changelog-1.4.md) suggest, i.e., the expected title from `_quarto.yml` is being used.

However, in that same MWE, if I simply

```bash
mv _quarto.yml _metadata.yml
```
and render via

```bash
quarto render index.qmd --to html
```
the issue re-appears again, i.e., the first section heading becomes the document title.

If I then delete the Python code block from `index.qmd` and re-render, the issue disappears once more, i.e., the expected document title from the `.yml` file is being used.

I am guessing this behavior is not by design?

**Comment by mcanouil** [comment] 2025-04-22 12:12
@floholl please don't comment on very old and closed issues.
Open a new GitHub Discussion. Link (eventually) to this issue and provide up to date information such as `quarto check` output and a small, simple, low dependency (or none), reproducible document.

**Comment by floholl** [comment] 2025-04-29 20:38
This is now reported as issue #12646.
