### ISSUE TITLE
 New Quarto file options not available in RStudio if the RStudio path or app has a space

### ISSUE THREAD

**Issue by ronblum** [quarto-dev/quarto-cli#7032] opened 2023-09-27 08:10 UTC
### Bug description

*This issue is from https://github.com/rstudio/rstudio/issues/12902 to link the repositories. 
I believe this issue is fixed in Quarto 1.4, but bringing it over to track.*

If the name or path of RStudio has a space in it, and hence the same for the path for `quarto`, the Quarto options aren't available in the `File` menu.

### Steps to reproduce

1. Install RStudio Desktop.
2. Change the application's filename so that there's a space in it, e.g. `RStudio Cherry Blossom`
3. Start RStudio Desktop.
4. <kbd>File -> New File</kbd>
    - `Quarto Document` and `Quarto Presentation` are missing
5. In the Console Pane: `quarto::quarto_version()`
    - An error is displayed:
    > Error: invalid version specification ‘ERROR: Cannot determine the Quarto source path. This script must be run from the bin or common folder.’
In addition: Warning message:
In system2(quarto_bin, "--version", stdout = TRUE) :
  running command ''/Applications/RStudio Cherry Blossom.app/Contents/Resources/app/quarto/bin/quarto' --version' had status 1

### Expected behavior

Quarto options should be available even if there's a space in the path or file name.

### Actual behavior

If the name or path of RStudio has a space in it, and hence the same for the path for `quarto`, the Quarto options aren't available in the `File` menu.

### Your environment

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0+386, 2023.05.0-daily+92, and 2023.09.0+463
    OS Version      : MacOS 13.2 and 14
    R Version       : 4.2.3 and 4.3.1

### Quarto check output

```
ronblum@Rons-Busy-Bee ~ % /Applications/RStudio\ Cherry\ Blossom.app/Contents/Resources/app/quarto/bin/quarto check 
ERROR: Cannot determine the Quarto source path. This script must be run from the bin or common folder.
```

```
ronblum@Rons-Busy-Bee quarto % mv /Applications/RStudio\ Cherry\ Blossom.app /Applications/RStudio-2023.09.0-463.app
ronblum@Rons-Busy-Bee quarto % /Applications/RStudio-2023.09.0-463.app/Contents/Resources/app/quarto/bin/quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/RStudio-2023.09.0-463.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/ronblum/Library/R/x86_64/4.3/library
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment] 2023-09-27 09:11
I can definitely reproduce this on Ubutun by moving the `quarto` folder in a path with space. 

Issue is from
https://github.com/quarto-dev/quarto-cli/blob/ae1060b29cee4823f784bf9a9664cb457fe420e0/package/scripts/common/quarto#L22-L33

**Comment by cderv** [comment] 2023-09-27 09:26
> ```
> ronblum@Rons-Busy-Bee ~ % /Applications/RStudio\ Cherry\ Blossom.app/Contents/Resources/app/quarto/bin/quarto check 
> ERROR: Cannot determine the Quarto source path. This script must be run from the bin or common folder.
> ```

@ronblum I push a commit that should fix this, and this should fix the File options in IDE. We were missing a quoting, which lead to wrong path computation. 

Thanks a lot for report. I am leaving this open until this is confirmed that this was the issue. 

@dragonstyle maybe we should backport this small change ? Quite important and really small change. What do you think ?

**Comment by dragonstyle** [comment] 2023-09-27 12:27
@cderv Thanks for fixing this! Unfortunately, I think we'd also want this commit (https://github.com/quarto-dev/quarto-cli/commit/9f105ce81dfb3a61d3a478f2cb37720a41eede2e) to fix the issue (I actually thought that _did_ fix the issue ;-) ). We decided not to back port since it was a bigger change to the main script and we rarely have reports of people installing into paths with spaces (since that does unfortunately commonly create problems)...

**Comment by cderv** [comment] 2023-09-27 13:10
All good ! So first step was done in this PR 
* https://github.com/quarto-dev/quarto-cli/pull/4980

Just a missing pair of quotes then...

Should we build a pre-release so that @ronblum can test ?

**Comment by cderv** [comment] 2023-09-27 15:46
@ronblum [1.4.388](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.4.388) contains the fix if you want to try it

**Comment by dragonstyle** [comment] 2023-11-29 17:33
This should be fixed now.

**Closed by dragonstyle** 2023-11-29 17:33 UTC
Labels: bug, verify-fixed
