### ISSUE TITLE
Citations in tables do not render correctly outside of raw markdown and kable

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto-cli#3340] opened 2022-11-16 00:19 UTC
### Bug description

There is inconsistent behavior when including citation keys inside tables, but it's a really tricky issue and I'm not sure if it's a Quarto issue or an issue with other table-making packages. 

When making a table with regular Markdown or with `knitr::kable()`, citation keys that are included in table rows are rendered correctly by pandoc.

However, when making a table with `kableExtra::kbl()` or `gt::gt()`, pandoc doesn't see the citation keys.

Here's a reproducible example:

````
---
title: "Citations in tables"
format: html

references:
- type: article-journal
  id: Lovelace1842
  author:
  - family: Lovelace
    given: Augusta Ada
  issued:
    date-parts:
    - - 1842
  title: >-
    Sketch of the analytical engine invented by Charles Babbage, by LF Menabrea, 
    officer of the military engineers, with notes upon the memoir by the translator
  title-short: Molecular structure of nucleic acids
  container-title: Taylor’s Scientific Memoirs
  volume: 3
  page: 666-731
  language: en-GB
---

## Raw Markdown

This works.

| Thing | Citation      |
|-------|---------------|
| 1234  | @Lovelace1842 |


## `knitr::kable()`

This works.

```{r}
library(knitr)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  kable()
```


## `kableExtra::kbl()`

This doesn't work.

```{r}
library(kableExtra)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  kbl() |>
  kable_styling()
```


## `gt::gt()`

This doesn't work.

```{r}
library(gt)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  gt()
```
````

Raw Markdown and `knitr::kable()` work correctly:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/73663/202052027-f7683db1-cd2b-47ca-86c4-6b1910aed957.png">

`kableExtra::kbl()` and `gt::gt()` do not render the citation:

<img width="753" alt="image" src="https://user-images.githubusercontent.com/73663/202052106-610933bc-b59e-4bc7-af44-dc8bb7bed568.png">

---

This is a known issue in both **kableExtra** (https://github.com/haozhu233/kableExtra/issues/214#issuecomment-421706528) and **gt** (https://github.com/rstudio/gt/issues/112#issuecomment-632936052), and the existing solution for both packages is to use **bookdown**'s text reference feature to render the citation outside of the table and then automatically include the rendered citation inside the table when knitting, like this:

````
(ref:lovelace) @Lovelace1842

```{r}
library(kableExtra)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "(ref:lovelace)"
) |>
  kbl() |>
  kable_styling()
```
````

This doesn't work in Quarto, though. #1959 and #1785 are about adding bookdown-esque text references to Quarto, which would potentially solve this issue.

---

This is with RStudio 2022.07.2+576 on macOS Monterey 12.6, but it happens across platforms

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by andrewheiss** [comment] 2022-11-16 01:51
Ooh, @debruine's issue/solution in https://github.com/quarto-dev/quarto-cli/issues/1710 also works here! This can be fixed by removing the class with `unclass()`, printing the result with `cat()`, and including `results="asis"` in the chunk options


````
## `kableExtra::kbl()` with `unclass()`

This works!

```{r results="asis"}
library(kableExtra)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  kbl() |>
  kable_styling() |>
  unclass() |> cat()
```
````

<img width="851" alt="image" src="https://user-images.githubusercontent.com/73663/202063540-01c2d92c-65ad-40d3-b3cb-d73f38b1dbf4.png">

**Comment by MohdAzmiSuliman** [comment] 2022-11-17 01:16
i was looking for this too. however if i use result = "asis", the rendered html files unable to recognise it as table for cross reference.

````
---
title: "kable extra citation"
format: html
---

refer @tbl-table

```{r}
#| label: tbl-table
#| tab-cap: "table with citation"
#| results: asis

library(kableExtra)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  kbl() |>
  kable_styling() |>
  unclass() |> cat()
```
````

![image](https://user-images.githubusercontent.com/1527738/202330165-54678f36-b4b0-45b0-a487-432733aac8a0.png)


is there any way to caption the table and crossref it?

**Comment by cscheid** [comment] 2022-11-17 14:13
I think you need `tbl-cap` instead of `tab-cap`?

**Comment by andrewheiss** [comment] 2022-11-17 19:14
Using `tbl-cap` adds the caption to the table itself, but it is still not cross-referencable: 

````
See @tbl-table

```{r}
#| echo: fenced
#| label: tbl-table
#| tbl-cap: Table with citation
#| results: asis

library(kableExtra)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  kbl() |>
  kable_styling() |>
  unclass() |> cat()
```
````

<img width="879" alt="image" src="https://user-images.githubusercontent.com/73663/202537630-1f3b03c3-29c0-42e6-b284-b87ff1217656.png">

**Comment by cscheid** [comment] 2023-02-08 21:19
This is now fixed, although `kableExtra` will need to use a slightly different method (it's currently emitting plain HTML without enclosing it in a RawBlock, which is not HTML syntax that we officially support).

For a preview of how this is going to work in the future, consider this snippet using an in-development branch of `gt`:

````
```{r}
library(gt)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  gt() |> fmt_markdown()
```
````

If you tell gt that you're providing it with markdown input (through `fmt_markdown`, which can also be scoped to cells, columns, rows, etc), then you get this:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/285675/217653057-75c4de69-a7fe-4ef2-afed-15421e59c59b.png">

If you don't call `fmt_markdown()`, you get this:

<img width="651" alt="image" src="https://user-images.githubusercontent.com/285675/217653148-19b16ac4-fed8-422c-8c62-273686fe1e96.png">

**Comment by cderv** [comment] 2023-02-09 14:48
> This is now fixed, although kableExtra will need to use a slightly different method (it's currently emitting plain HTML without enclosing it in a RawBlock, which is not HTML syntax that we officially support).

@cscheid about this, Aren't we enclosing ourself the result in Raw Block ? I believe we do it [here ](https://github.com/quarto-dev/quarto-cli/blob/2490fe61088db67615f3a154bdfc48391caf943d/src/resources/rmd/patch.R#L100-L107)

What more would be needed ? I think we need to make sure what is planned for **gt** will work for other framework. 

Also, some comment on why in R Markdown ecosystem the raw block is not used. This is because that way it can benefit with Pandoc from the [`markdown_in_html_blocks`](https://pandoc.org/MANUAL.html#extension-markdown_in_html_blocks) extension. 
With Quarto we loose this feature. 

This means that with **rmarkdown**,  

<details>
<summary>Rmd file</summary>

````markdown
---
title: "Citations in tables"
output: 
  bookdown::html_document2:
    keep_md: true
references:
- type: article-journal
  id: Lovelace1842
  author:
  - family: Lovelace
    given: Augusta Ada
  issued:
    date-parts:
    - - 1842
  title: >-
    Sketch of the analytical engine invented by Charles Babbage, by LF Menabrea, 
    officer of the military engineers, with notes upon the memoir by the translator
  title-short: Molecular structure of nucleic acids
  container-title: Taylor’s Scientific Memoirs
  volume: 3
  page: 666-731
  language: en-GB
---

## Raw Markdown

This works.

| Thing | Citation      |
|-------|---------------|
| 1234  | @Lovelace1842 |


## `knitr::kable()`

This works.

```{r}
library(knitr)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  kable()
```


## `kableExtra::kbl()`

This doesn't work.

```{r}
library(kableExtra)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  kbl() |>
  kable_styling()
```


## `gt::gt()`

This doesn't work.

```{r}
library(gt)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  gt()
```
````

</details>

* We get the reference in `kable()` because it outputs markdown
* We get the reference in `kableExtra()` because the inside markdown is process thanks to `markdown_in_html_blocks`
* We don't get it working in **gt** because it outputs its code in inside raw block

Putting that here in case R Markdown user are wondering why the difference.

**Comment by andrewheiss** [comment] 2023-03-06 19:29
@cscheid Do you know which branch of **gt** has support for the preview version here (https://github.com/quarto-dev/quarto-cli/issues/3340#issuecomment-1423252268)? Using the `gt() > fmt_markdown()` approach with today's GitHub version still leads to non-working output: 

<kbd><img width="830" alt="image" src="https://user-images.githubusercontent.com/73663/223211027-9183a5b3-7505-4253-b69b-b8b63724c4e4.png"></kbd>

**Comment by cscheid** [comment] 2023-03-06 19:40
@rich-iannone ?

**Comment by jameshowison** [comment] 2023-08-29 18:47
Anyone know if this should be working now?  I don't think it is for me.

```
---
title: "trial"
format: html
---

## Quarto {#sec-testing}

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

Inside a table cross-refs don't render:

```{r}
library(gt)
tibble::tribble(
  ~Thing, ~Link,
  1234, "@sec-testing"
) |>
  gt() |> fmt_markdown()
```

But outside a table it works fine @sec-testing
```

Produces this output:

![Screen Shot 2023-08-29 at 1 43 11 PM](https://github.com/quarto-dev/quarto-cli/assets/91986/c24b05bd-d8b9-442b-a309-84536ba0a5c4)


I'm expecting a Linked "Section 1" to appear inside the table?  This also doesn't work with `kable` for me either.

Current versions:
gt (0.9.0)
quarto (cmdline) 1.3.242

**Comment by cscheid** [comment] 2023-08-29 19:13
> Anyone know if this should be working now? I don't think it is for me.

This issue is open, so the problem exists today. We're working on it, keep an eye on when we merge #6620.

**Comment by cscheid** [comment] 2023-08-29 19:17
Actually, now that I say that, I wonder. @rich-iannone, shouldn't that fmt_markdown be wrapping the markdown content in a `<span data-qmd="..."></span>` element? It doesn't seem to be right now. This is the HTML being emitted:

````
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Thing">Thing</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Link">Link</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="Thing" class="gt_row gt_right"><div class='gt_from_md'><p>1234</p>
</div></td>
<td headers="Link" class="gt_row gt_left"><div class='gt_from_md'><p>@sec-testing</p>
</div></td></tr>
  </tbody>
  
  
</table>
````

**Comment by cscheid** [comment] 2023-08-29 19:29
We do have a _second_ issue, though, which is that gt emits `data-quarto-disable-processing="false"`, and quarto checks for 

```lua
              if table.attributes[constants.kDisableProcessing] ~= nil then
```

This one is a `quarto` bug and I'll fix that one. In my testing, if `<div class='gt_from_md'><p>...</p></div>` is replaced with `<span data-qmd="..."></span>`, then quarto (after this bugfix) actually renders this crossref correctly.

@jameshowison : you'll need to install the latest 1.4 prerelease (and wait for the confirmation and fix of the `gt` issue) but this should all be working very soon. Thanks for the patience!

**Comment by rich-iannone** [comment] 2023-08-29 21:13
Okay, there was a change required in `gt` to ensure that Quarto is detected during the render. I've made that change just now as https://github.com/rstudio/gt/commit/e1feb6ba5a474c58d22b2a95a3c12cfed1f3117b and the interface mentioned above by Carlos now works. You'll need to get the latest dev version of `gt` with `devtools::install_github("rstudio/gt")`.

I tested with this .qmd:

````
---
format: html
references:
- type: article-journal
  id: Lovelace1842
  author:
  - family: Lovelace
    given: Augusta Ada
  issued:
    date-parts:
    - - 1842
  title: >-
    Sketch of the analytical engine invented by Charles Babbage, by LF Menabrea, 
    officer of the military engineers, with notes upon the memoir by the translator
  title-short: Molecular structure of nucleic acids
  container-title: Taylor’s Scientific Memoirs
  volume: 3
  page: 666-731
  language: en-GB
---

```{r}
library(gt)

tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  gt() |> fmt_markdown()
```
````

and got this document, where hovering on the formatted citation yields the full reference.

<img width="1020" alt="quarto-gt-citation-in-table" src="https://github.com/quarto-dev/quarto-cli/assets/5612024/f8a6b8d2-f992-4f1b-a45a-e2fc8382a253">

Really sorry it took so long to discover the underlying `gt` issue. Try it out and let me know if it doesn't work on your system.

**Comment by cscheid** [comment] 2023-09-20 00:32
I can confirm this works on `main`(and the version of `gt` on github) as well. kableExtra will need to emit its output slightly differently, so I'm going to go ahead and close this one.

**Closed by cscheid** 2023-09-20 00:32 UTC
Labels: bug, crossref, tables

**Comment by andrewheiss** [comment] 2023-10-31 14:37
This issue persists when rendering to PDF (using gt 0.10.0 and Quarto 1.4.424):

````qmd
---
title: "Citations in tables"
format: pdf

references:
- type: article-journal
  id: Lovelace1842
  author:
  - family: Lovelace
    given: Augusta Ada
  issued:
    date-parts:
    - - 1842
  title: >-
    Sketch of the analytical engine invented by Charles Babbage, by LF Menabrea, 
    officer of the military engineers, with notes upon the memoir by the translator
  title-short: Sketch of the analytical engine
  container-title: Taylor’s Scientific Memoirs
  volume: 3
  page: 666-731
  language: en-GB
---

```{r}
library(gt)

tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  gt() |> fmt_markdown()
```
````

<img width="929" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/1430fc23-47f5-4fd8-bd89-dbbd17f4d56c">

**Comment by andrewheiss** [comment] 2023-10-31 14:47
`knitr::kable()` works with PDF:

````
```{r}
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  knitr::kable()
```
````

<img width="795" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/548a4632-eef8-47b9-a543-3db93ee7fa04">

&nbsp;

`kableExtra::kbl()` doesn't work with PDF:


```{r}
library(kableExtra)

tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  kbl() |> kable_styling()
```
````
````

<img width="255" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/cd12ed25-a3c9-4fba-b9e8-4c3c92fd2b13">

That *might* be related to https://github.com/yihui/knitr/issues/2289, though that issue is specifically about HTML output

**Comment by cscheid** [comment] 2023-10-31 15:09
````
```{r}
library(gt)

tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  gt() |> fmt_markdown()
```
````

Somehow, gt is not formatting this with markdown, but is emitting LaTeX, cf `keep-md: true`

````
::: {.cell}

```{.r .cell-code}
library(gt)

tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  gt() |> fmt_markdown()
```

::: {.cell-output-display}
\begin{longtable}{rl}
\toprule
Thing & Citation \\ 
\midrule\addlinespace[2.5pt]
1234 & @Lovelace1842 \\ 
\bottomrule
\end{longtable}

:::
:::
````

@rich-iannone, do you know what's going on here?

**Comment by cderv** [comment] 2023-10-31 15:42
The document is using `format: pdf` here, this means that PDF output is expected. **gt** will then output `as_latex()` because this is used in a `format: pdf` rendering. 

I don't think we have yet an equivalent of `data-qmd` trick on Span that works with LaTeX tables. (probably because we don't parse tables). 

If you want HTML tables, even in `format: pdf` document, because you known Quarto will parse the HTML table anyway, you can ask for it 
````markdown
```{r}
library(gt)

tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842"
) |>
  gt() |> fmt_markdown() |> as_raw_html()
```
````

This will correctly process the citation in the table, even for PDF outputs. 

So at the end, this is a **gt** choice: when inside quarto document rendering, if output format is LaTeX, should it generate a HTML table anyway ? At least when `fmt_markdown()` is used maybe ? 

Otherwise, it will be to the user to explicitly ask for HTML version of the table.

**Comment by cscheid** [comment] 2023-10-31 16:41
> I don't think we have yet an equivalent of data-qmd trick on Span that works with LaTeX tables. (probably because we don't parse tables).

But if you provide an HTML quarto-style table _in LaTeX_, we will do the right thing. That was the whole point of doing a uniform parser for tables in quarto. See:

<table>
<tr>
<td>

````
---
format: pdf
---

```{r}
#| label: fig-1
#| fig-cap: A caption
plot(1:100)
```

```{r}
#| label: fig-2
#| fig-cap: Another caption
plot(20:30)
```


```{=html}
<table>
<thead>
<tr><th>What</th><th>Where</th></tr>
</thead>
<tbody><tr>
<td><span data-qmd="@fig-1"></span></td>
<td><span data-qmd="@fig-2"></span></td>
</tr></tbody>
</table>
```
````
</td>
<td>
<img width="400" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/f7626c40-b87a-4be4-b95b-1abac93ae7d4">
<br>
<img width="399" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/beff3f42-d07c-45d9-b2d1-bf8429c49255">
</td>
</tr>
</table>

**Comment by cscheid** [comment] 2023-10-31 16:42
And, more specifically, I thought that `gt` had been changed to have a way to send HTML tables to quarto, even in non-HTML formats.

**Comment by andrewheiss** [comment] 2023-10-31 17:22
Ok cool, yeah, I also thought that {gt} had changed for non-HTML formats and emitted HTML. Adding `as_raw_html()` works for PDF as expected, but leaving it on messes with regular HTML output, so some conditional work has to be done to not use it with HTML

Normal HTML output:

<img width="848" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/af2ae847-1342-4a7d-8d31-911d46bfb365">

&nbsp;

With `as_raw_html()` so that LaTeX is happy, but now the HTML output is messed up because something changed with the gt CSS or something:

<img width="834" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/436ebed7-7292-4ce9-a56f-59993be631c9">

But that's definitely a {gt} issue, not a Quarto issue

**Comment by andrewheiss** [comment] 2023-10-31 18:28
Yeah, using `as_raw_html()` strips away all custom LaTeX stuff like column widths when outputting to HTML

With HTML:

<img width="735" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/cece7898-8347-4eeb-a48b-06e50c71edaf">


With LaTeX:

<img width="788" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/abdcde89-60d3-4055-95df-1fdfe8fe3493">

**Comment by rich-iannone** [comment] 2023-11-02 16:59
@andrewheiss me and Carlos discussed this and we have a good plan in place that will preserve the LaTeX table code that gt generates while also allowing Quarto to properly handle citations as well as processing the Markdown conversion. More to come.

**Comment by cscheid** [comment] 2023-11-02 18:55
@rich-iannone the PR on the quarto side is here https://github.com/quarto-dev/quarto-cli/pull/7451

**Comment by andrewheiss** [comment] 2024-04-11 17:52
Following up on this (and related to https://github.com/quarto-dev/quarto-cli/issues/9342), @rich-iannone is there a way to use `\QuartoMarkdownBase64{}` from https://github.com/quarto-dev/quarto-cli/pull/7451 in {gt}?

For example, this qmd has an equation and a citation:

````qmd
---
title: "Citations in tables"
format: 
  html: default
  pdf: 
    keep-tex: true

references:
- type: article-journal
  id: Lovelace1842
  author:
  - family: Lovelace
    given: Augusta Ada
  issued:
    date-parts:
    - - 1842
  title: >-
    Sketch of the analytical engine invented by Charles Babbage, by LF Menabrea, 
    officer of the military engineers, with notes upon the memoir by the translator
  title-short: Molecular structure of nucleic acids
  container-title: Taylor’s Scientific Memoirs
  volume: 3
  page: 666-731
  language: en-GB
---

$$
a^2 + b^2 = c^2
$${#eq-math}

```{r}
library(gt)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "@Lovelace1842",
  5678, "@eq-math"
) |>
  gt() |> 
  fmt_markdown(Citation)
```
````

When rendering to PDF, those `@` things don't get processed, but doing it manually with LaTex and `\QuartoMarkdownBase64{}` works (kind of; in https://github.com/quarto-dev/quarto-cli/issues/9342 this doesn't work with citation keys yet)

````qmd
```{=latex}
% QExvdmVsYWNlMTg0Mg==} is "@Lovelace1842" in base-64 encoding
% QGVxLW1hdGg= is "@eq-math" in base-64 encoding
\begin{tabular}{cc}
Thing & Citation \\
1234 & \QuartoMarkdownBase64{QExvdmVsYWNlMTg0Mg==} \\
5678 & \QuartoMarkdownBase64{QGVxLW1hdGg=} \\
\end{tabular}
```
````

I tried adding the base64 content myself in `gt()`:

```
tibble::tribble(
  ~Thing, ~Citation,
  1234, "\\QuartoMarkdownBase64{QGVxLW1hdGg=}",
  5678, "\\QuartoMarkdownBase64{QExvdmVsYWNlMTg0Mg==}"
) |>
  gt()
```

…but {gt} [automatically converts](https://github.com/rstudio/gt/blob/411328ce56ec6dfac355f1df2b13749c17b27354/R/helpers.R#L3701) `\\` to `\textbackslash{}`, so we end up with this LaTeX:

```latex
\begin{longtable*}{rl}
\toprule
Thing & Citation \\ 
\midrule\addlinespace[2.5pt]
1234 & \textbackslash{}QuartoMarkdownBase64\{QExvdmVsYWNlMTg0Mg==\} \\ 
5678 & \textbackslash{}QuartoMarkdownBase64\{QGVxLW1hdGg=\} \\ 
\bottomrule
\end{longtable*}
```

and this PDF:

<img width="634" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/5b2ff7d0-b9f9-4810-b0b8-30d95ef6f983">

Is there a way to get {gt} to emit `\QuartoMarkdownBase64{}` without automatically escaping the LaTeX?

**Comment by cderv** [comment] 2024-04-11 20:10
@andrewheiss I believe this is somewhat related to this issue I opened in GT for the case for HTML

* https://github.com/rstudio/gt/issues/1487

But same workaround applies 
````markdown
library(gt)
tibble::tribble(
  ~Thing, ~Citation,
  1234, "\\QuartoMarkdownBase64{QGVxLW1hdGg=}",
  5678, "\\QuartoMarkdownBase64{QExvdmVsYWNlMTg0Mg==}"
) |>
  gt() |> 
  fmt_passthrough(
    columns = Citation,
    escape = FALSE
  )
````

Using `fmt_passthrough` with `escape = FALSE` should help here.

It should write this table 
````latex
\begin{longtable}{rl}
\toprule
Thing & Citation \\ 
\midrule\addlinespace[2.5pt]
1234 & \QuartoMarkdownBase64{QGVxLW1hdGg=} \\ 
5678 & \QuartoMarkdownBase64{QExvdmVsYWNlMTg0Mg==} \\ 
\bottomrule
\end{longtable}
````

**Comment by DanielIAvila** [comment] 2025-04-17 14:11
I am encountering a similar problem. `kableExtra` does not work with `R Markdown` to render citations inside tables. I am trying:



```
```{r metric-table, tab.cap= 'Table caption', echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
library(gt)

tibble::tribble(
  ~Type, ~Metric, ~Description, ~Example,
  "XXX", "XYZ", "Description goes here", "@Netwon1710"
  
) %>%
  gt() %>% fmt_markdown()
```



Renders as a table without a caption, a table number, and the reference reads as @Newton1710
