### ISSUE TITLE
Citation in notes div rendered on slide

### ISSUE THREAD

**Issue by erauchway** [quarto-dev/quarto-cli#5068] opened 2023-04-02 14:18 UTC
### Bug description

Markdown citation placed in notes div is rendered on slide. Reproducible example follows:

```
---
title: "Another test of Reveal.js"
format: 
  revealjs: default
  docx: default
---

## Here is a slide 
It's got some text on it.

:::{.notes}

Speaker notes go here.[^1]

[^1]: Citation goes here; should be in notes but appears on slide.

:::
```
Using macOS; happens using emacs with terminal or RStudio 2023.03.0+386 (2023.03.0+386) 

quarto check output follows

```
✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.302
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: python3

(\) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment] 2023-04-02 14:27
This is a duplicate of https://github.com/quarto-dev/quarto-cli/issues/1498

**Closed by cscheid** 2023-04-02 14:27 UTC
Labels: bug, duplicate

**Comment by cderv** [comment] 2023-04-03 10:08
@cscheid I believe this is different than #1498 -  this issue is about Speaker notes content, not being inserted only in speaker note but leaking into main presentation. 

#1498 is about some other footnotes problem (when they are collected at the end of the document instead of each slide). 

It seems two differents things to handle. Ok to reopen ?

**Comment by cderv** [comment] 2023-04-04 08:11
I understand. 

I see this issue related to the Speaker View for Revealjs in Pandoc being quite independant. We add this issue related to this https://github.com/quarto-dev/quarto-cli/issues/4112

Ultimately, footnote behavior in a `::: notes` div for Speaker View addition is a Pandoc bug IMO. 

This document  (e.g. `test.md`)
````markdown
---
title: "Another test of Reveal.js"
---

## Here is a slide
It's got some text on it.

:::{.notes}

Speaker notes go here.[^1]

[^1]: Citation goes here; should be in notes but appears on slide.

:::
````

converted by Pandoc to revealjs using `pandoc -t revealjs -s -o test.html test.md` will lead to a last slide with the footnote reference while the speaker note text is moved in the speaker view. 

So I believe that footnote for Speaker Notes are not handle as we could expect by Pandoc itself.
