### ISSUE TITLE
Typst YAML Validation Fails for Quarto Publish GitHub Action

### ISSUE THREAD

**Issue by ForBo7** [quarto-dev/quarto-cli#6156] opened 2023-07-10 06:56 UTC
### Bug description

Hello.

I have a QMD file in which there is a Typst code block. When I push this QMD file to my website hosted on GitHub, the Quarto Publish GitHub action fails, stating that my YAML is invalid.

While I know that Quarto currently can only convert QMD files containing Typst blocks to PDFs, my goal is to host the converted PDF on my website.

### Steps to reproduce

A minimal example of my QMD file.

````qmd
---
title: Matrix Calculus Practice Questions
date: 2023-07-09
format: typst
---

```{=typst}
#outline(title: none, target: heading.where(level: 2), )
== Questions
#let derive(out, inp) = {$(dif out)/(dif inp)$}
#set enum(numbering: "1.a.i.")

#par(leading: 0.7cm, justify: true)[
+ Find $derive(, x) 9(x+x^2)$.
]
```
````

### Expected behavior

I would expect that the Quarto Publish action would generate a PDF, which I can then access by going to the appropriate URL at my website.

### Actual behavior

The `build-deploy` job in `publish.yml` of the Quarto Publish action outputs the following error.

```
ERROR: Validation of YAML front matter failed.
ERROR: In file misc/matrix_calculus_practice.qmd
(line 4, columns 9--13) Field "format" has value typst, which must instead be 'asciidoc'
3: date: 2023-07-09
4: format: typst
          ~~~~~
5: ---

ERROR: Render failed due to invalid YAML.

YAMLValidationError: Render failed due to invalid YAML.
    at renderFiles (file:///opt/quarto/bin/quarto.js:86525:27)
    at async renderProject (file:///opt/quarto/bin/quarto.js:86800:25)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:121190:33)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:109089:24)
    at async Object.publish4 [as publish] (file:///opt/quarto/bin/quarto.js:120459:26)
    at async publishSite (file:///opt/quarto/bin/quarto.js:121227:38)
    at async publish5 (file:///opt/quarto/bin/quarto.js:121445:61)
    at async doPublish (file:///opt/quarto/bin/quarto.js:121401:13)
    at async publishAction (file:///opt/quarto/bin/quarto.js:121412:9)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:121389:9)
Error: Process completed with exit code 1.
```

If I specify other Typst options, a different error is output.

```
ERROR: Validation of YAML front matter failed.
ERROR: In file misc/matrix_calculus_practice.qmd
(line 5, column 5 through line 6, column 18) Field "format" has value

date: 2023-07-09
  keep-typ: true

The value must instead be no possible value.
4:   typst:
5:     date: 2023-07-09
      ~~~~~~~~~~~~~~~~~
6:     keep-typ: true
  ~~~~~~~~~~~~~~~~~~
7: ---

ERROR: Render failed due to invalid YAML.

YAMLValidationError: Render failed due to invalid YAML.
    at renderFiles (file:///opt/quarto/bin/quarto.js:86525:27)
    at async renderProject (file:///opt/quarto/bin/quarto.js:86800:25)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:121190:33)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:109089:24)
    at async Object.publish4 [as publish] (file:///opt/quarto/bin/quarto.js:120459:26)
    at async publishSite (file:///opt/quarto/bin/quarto.js:121227:38)
    at async publish5 (file:///opt/quarto/bin/quarto.js:121445:61)
    at async doPublish (file:///opt/quarto/bin/quarto.js:121401:13)
    at async publishAction (file:///opt/quarto/bin/quarto.js:121412:9)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:121389:9)
Error: Process completed with exit code 1.
```

### Your environment

IDE: Visual Studio Code 1.80.0 (Universal)
OS: macOS Sonoma 14.0 Beta (23A5257q)

This error isn't thrown on my local machine when my website is built when I execute `quarto render` or `quarto preview`. It only occurs when my website is being built on GitHub.

I also have the following two lines in my `.gitignore` file.
```
# Typst
*.typ
*.typst
```

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.193
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10 (Conda)
      Path: /Users/[REDACTED]]/mambaforge/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: (None)
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by dragonstyle** [comment] 2023-07-10 12:10
Could you see what version of Quarto you're using in the GitHub action? Based upon those errors I suspect you're using an earlier version that doesn't support `typst` output.

**Comment by mcanouil** [comment] 2023-07-10 12:55
I am assuming the workflow in question is <https://github.com/ForBo7/forbo7.github.io/blob/main/.github/workflows/publish.yml>.
In theory it uses the latest 1.3 version of Quarto.

**Comment by cscheid** [comment] 2023-07-10 12:59
FYI, `typst` is only supported on the quarto 1.4 prereleases.

**Comment by mcanouil** [comment] 2023-07-10 13:04
I was able to reproduce, the issue is indeed to use 1.3 while 1.4 is required.
@ForBo7 Update your `publish.yml` with the following to use `typst` (note your "checkout" action is not up to date and relies on deprecated tools which are going to be removed by GitHub later this year):

```yaml
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by mcanouil** [comment] 2023-07-10 13:07
I am going ahead and close this as resolved.

**Closed by mcanouil** 2023-07-10 13:07 UTC
Labels: publishing-github

**Comment by ForBo7** [comment] 2023-07-11 05:58
Thanks for the fix! 

Just want to clarify about the checkout action: is checkout in general being deprecated, or is it v2 that's being deprecated?

**Comment by mcanouil** [comment] 2023-07-11 06:10
v2 because it is based on node12 which was deprecated over a year ago and support in GHA is stopping, thus all GHA running on the v2 will error out systematically.

v3 is using node16.
Note that other GitHub Actions are based on node12, so if you have other workflows be sure to check.
(You can use dependabot to keep your workflows up to date via automatic PR)

https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/
