### ISSUE TITLE
Subfigures ignore width and height attributes 

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#3580] opened 2022-12-06 06:50 UTC
### Bug description

[Zip file with minimal working example](https://github.com/quarto-dev/quarto-cli/files/10163470/mwe.zip)

Consider the minimal working example with subfigures:

``````
---
title: "Minimal Working Example"
format: docx
---

Foo

::: {#fig-1 layout-ncol="2"}
![Awesome Logo](R_logo.svg.png){width="5cm"}

Logos
:::

Bar
``````

Render using `quarto render subfigure-height.qmd --to docx` produces

![Screenshot from 2022-12-06 14-42-02](https://user-images.githubusercontent.com/1506457/205840744-89386bf5-753f-4ae9-a08f-9a3a3a86e7c7.png)

The figure is not 5cm width and overflows the available space.

For comparison, consider the minimal working example with single figure:

``````
---
title: "Minimal Working Example"
format: docx
---

Foo

![Awesome Logo](R_logo.svg.png){width="5cm"}

Bar
``````

Render using `quarto render figure-height.qmd --to docx` produces

![Screenshot from 2022-12-06 14-42-12](https://user-images.githubusercontent.com/1506457/205841155-90f8a82f-c851-4d07-9c5d-437402ab7068.png)

The figure is 5cm width as instructed with `{width="5cm"}`.

`quarto check` reports

```
[✓] Checking Quarto installation......OK
      Version: 1.3.34
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.10 (Conda)
      Path: /home/raniere/mambaforge/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /usr/lib/R
      LibPaths:
        - /home/raniere/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.16

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2023-03-09 20:43
Unfortunately, we can't seem to reproduce this issue. We are inspecting the output on Microsoft Word, and we can see that you're using LibreOffice. (It's unfortunately not practical for us to try and match every program that reads .docx files; I understand that's frustrating for people who don't have access to MS Office.)

**Comment by PeterWang-dev** [comment] 2023-04-26 11:21
> Unfortunately, we can't seem to reproduce this issue. We are inspecting the output on Microsoft Word, and we can see that you're using LibreOffice. (It's unfortunately not practical for us to try and match every program that reads .docx files; I understand that's frustrating for people who don't have access to MS Office.)

After tested in Microsoft Word, it is really reproduced. You can compare the one in subfigure and out of subfigure.

```markdown  
![normal](assets/normal.png){#fig-normal width="5cm"}

::: {#fig-items layout-ncol=2 layout-nrow=1}

![error](assets/error.png){#fig-error width="5cm"}

Compare
:::
```

**Comment by PeterWang-dev** [comment] 2023-04-26 11:23
> > Unfortunately, we can't seem to reproduce this issue. We are inspecting the output on Microsoft Word, and we can see that you're using LibreOffice. (It's unfortunately not practical for us to try and match every program that reads .docx files; I understand that's frustrating for people who don't have access to MS Office.)
> 
> After tested in Microsoft Word, it is really reproduced. You can compare the one in subfigure and out of subfigure.
> 
> ```gfm
> ![normal](assets/normal.png){#fig-normal width="5cm"}
> 
> ::: {#fig-items layout-ncol=2 layout-nrow=1}
> 
> ![error](assets/error.png){#fig-error width="5cm"}
> 
> Compare
> :::
> ```

I got more info. After deleting the layout attributes, everything got back to normal. Seems that layout overwrite the picture's attributes.

**Comment by cscheid** [comment] 2023-04-26 14:28
Duplicate of https://github.com/quarto-dev/quarto-cli/issues/2251

**Closed by cscheid** 2023-04-26 14:28 UTC
Labels: bug, needs-repro, docx
