### ISSUE TITLE
qmd files and notebooks are executed in different environments

### ISSUE THREAD

**Issue by tpoisot** [quarto-dev/quarto-cli#6522] opened 2023-08-14 19:54 UTC
### Bug description

Running the same code in a qmd file and in the notebook generated from it give different results as they have different working directories

### Steps to reproduce

Write a qmd document with the cell

````md
```{julia}
pwd()
```
````

This gives the output as the project folder, `/home/foo/bar/`

Embed a result from this qmd document, go to the notebook and run the equivalent cell, this gives a *different* result, specifically `/home/foo/bar/notebooks/`.

Setting `execute-dir: project` makes no difference. Both the cell and the notebook are located in `/home/foo/bar/notebooks/`.

This bug is really annoying because it prevents interacting with files

### Expected behavior

Both the qmd "Run cell" and the notebook "Execute cell" should have the same working directory

**Comment by dragonstyle** [comment] 2023-08-14 21:31
1. Could you let me know a bit more about what version of Quarto you're using - the output of the command `quarto check` will provide a lot of helpful information.

2. I'm not sure that I'm completely following what you're seeing here, particularly when you're talking about differing outputs between the qmd and the notebook (I'm not sure exactly what you're referring to when you say the notebook). Could you give me a zip file or repo to work with?

**Comment by tpoisot** [comment] 2023-08-14 22:12
Here's the `quarto check` -- I'm on commit 8f28266b647d47489065 

~~~
tpoisot@x1:~$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/tpoisot/.opt/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/tpoisot/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /usr/bin/python3
      Jupyter: 4.12.0
      Kernels: julia-1.9, python3

(/) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
~~~

What I mean by different outputs is: the same instruction (`pwd()` in this case, which gives the working directory) gives a different result when I use "Run cell" when editing the `.qmd`file.

This is the output when running the cell from the `.qmd` file:

![Screenshot from 2023-08-14 18-08-12](https://github.com/quarto-dev/quarto-cli/assets/579329/fde7a66e-d9ff-43bb-b530-602bb98d2a1e)

And this is the output when running the cell from the `.ipynb` file that was created when rendering the project:

![Screenshot from 2023-08-14 18-08-26](https://github.com/quarto-dev/quarto-cli/assets/579329/9df611fb-d465-45d4-b2ef-ee4ea07888da)

Note that the output of `pwd()` is different despite the two files being in the same folder (`notebooks`).

I have attached the zip file for this example:

[quarto-demo.zip](https://github.com/quarto-dev/quarto-cli/files/12339931/quarto-demo.zip)

Note that it **does not** work (and I don't know why), as it ends up renaming `s1.ipynb` to `s1.out.ipynb` -- here is the log:

~~~
Preparing to preview
[1/2] notebooks/s1.qmd

Starting julia-1.9 kernel...Done

Executing 's1.ipynb'
  Cell 1/2: ''.......Done
  Cell 2/2: 'test'...Done

ERROR: NotFound: No such file or directory (os error 2): copy '/home/tpoisot/varia/notebooks/s1.ipynb' -> '/home/tpoisot/varia/.quarto/embed/notebooks/s1.ipynb'

Stack trace:
    at Object.copyFileSync (ext:deno_fs/30_fs.js:80:7)
    at Object.cache (file:///home/tpoisot/.opt/quarto-cli/src/render/notebook/notebook-contributor-qmd.ts:55:10)
    at Object.addRendering (file:///home/tpoisot/.opt/quarto-cli/src/render/notebook/notebook-context.ts:82:17)
    at contributeNotebook (file:///home/tpoisot/.opt/quarto-cli/src/project/types/manuscript/manuscript-render.ts:302:21)
    at Object.onPostProcess (file:///home/tpoisot/.opt/quarto-cli/src/project/types/manuscript/manuscript-render.ts:314:11)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async renderFileInternal (file:///home/tpoisot/.opt/quarto-cli/src/command/render/render-files.ts:643:3)
    at async renderFiles (file:///home/tpoisot/.opt/quarto-cli/src/command/render/render-files.ts:310:9)
    at async renderProject (file:///home/tpoisot/.opt/quarto-cli/src/command/render/project.ts:266:23)
    at async serveProject (file:///home/tpoisot/.opt/quarto-cli/src/project/serve/serve.ts:209:20)
~~~

**Comment by eitsupi** [comment] 2023-08-15 06:00
I don't think this is a quarto-cli's bug. Duplicate of quarto-dev/quarto#73

@tpoisot Could you check the document?
Code block execution on VS Code is nothing to do with quarto-cli.
https://quarto.org/docs/tools/vscode.html#execution-directory

**Closed** 2023-08-15 13:00 UTC
Labels: bug, jupyter
