### ISSUE TITLE
Images in `title-slide-attributes > data-background-image` are not embedded in standalone reveal js presentation

### ISSUE THREAD

**Issue by vandenman** [quarto-dev/quarto-cli#6275] opened 2023-07-19 15:03 UTC
### Bug description

when `standalone: true` and `embed-resources: true`, files that are passed to `title-slide-attributes > data-background-image` are not embedded in the final html file.

### Steps to reproduce

````qmd
---
title: "test"

format:
    revealjs:
        standalone: true
        embed-resources: true

        title-slide-attributes:
            data-background-image: quarto_logo.png, quarto_logo.png
            data-background-size: 15%, 15%
            data-background-position: 25% 98%, 75% 98%
editor:
    render-on-save: true
---

## test slide
````

### Expected behavior

The standalone html file should contain the image (like it does with images added to slides directly).

### Actual behavior

The html file contains a path to the file:

```html
<section id="title-slide" data-background-image="quarto_logo.png, quarto_logo.png" data-background-position="25% 98%, 75% 98%" data-background-size="15%, 15%" class="quarto-title-block center">

```

### Your environment

- IDE: VSCode
- OS: Manjaro

### Quarto check output

```bash
quarto check                                                                                                                                   ✔ 

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

(/) Checking Jupyter engine render....[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib64/R
      LibPaths:
        - /usr/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")

```

**Comment by cscheid** [comment] 2023-07-19 15:24
Maybe this is a revealjs feature I'm not aware of, but what did you expect the behavior of multiple images to be? The issue here is that we're not expecting `quarto_logo.png, quarto_logo.png` to appear at all, and that confuses our resource discovery code.

**Comment by cderv** [comment] 2023-07-19 15:39
This is a duplicate of 

* https://github.com/quarto-dev/quarto-cli/issues/980

We'll track the improvement there. I think we can do something now (even if Pandoc didn't fix the issue upstream).

**Closed by cderv** 2023-07-19 15:39 UTC
Labels: bug, duplicate, revealjs

**Comment by vandenman** [comment] 2023-07-19 18:34
@cscheid This is just a trick to add multiple images to the title slide by abusing the background property (see e.g., https://www.w3schools.com/css/css3_backgrounds.asp )

![image](https://github.com/quarto-dev/quarto-cli/assets/21319932/371fefa7-9fab-4c0b-9d1a-58f802fd1fbb)

@cderv thanks! I'll follow that issue.

**Comment by cscheid** [comment] 2023-07-19 20:00
@vandenman TIL, thanks. This means that in order for us to support this usage, Quarto needs to learn to parse the CSS background property. It doesn't seem impossible, but it's a non-trivial task: https://developer.mozilla.org/en-US/docs/Web/CSS/background
