### ISSUE TITLE
Autocomplete citations in VSCode does not work

### ISSUE THREAD

**Issue by pascalsiemsen** [quarto-dev/quarto-cli#6324] opened 2023-07-24 17:19 UTC
### Bug description

The autocomplete feature does not work in vscode for me. I am also not sure what I need to do to make it work.

So far, I tried it in the YAML of the file and for Quarto Book in the _quarto.yml file.

By the way, thanks for the great plugin!

### Steps to reproduce

---
bibliography: some.bib
---

# Introduction

This is a test. @ma...

### Expected behavior

Autocomplete the citation

### Actual behavior

No autocomplete

### Your environment

- VScode with Quarto Plugin (visual-studio-code-insiders-bin 1683870212-1)
- Endeavour OS with hyprland (wayland)

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

(\) Checking Jupyter engine render....[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib64/R
      LibPaths:
        - /home/pascal/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/lib/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment] 2023-07-24 17:35
Can you give us a git repository with a full example?

**Comment by mcanouil** [comment] 2023-07-24 18:00
I can reproduce on Mac when not using Visual editor.

````qmd
---
title: "Quarto Playground"
format: html
bibliography: "bibliography.bib"
---

This is a playground for Quarto.

@
````

```bib
@article{einstein-1905,
  author = {Einstein, Albert},
  title = {Zur Elektrodynamik bewegter Körper},
  journal = {Annalen der Physik},
  year = {1905},
  volume = {17},
  number = {10},
  pages = {891-921},
  url = {https://doi.org/10.1002/andp.19053221004},
  doi = {10.1002/andp.19053221004}
}
```

## Source

https://github.com/quarto-dev/quarto-cli/assets/8896044/16ca106a-4af8-4be4-b941-900ef698d10f 

## Visual  

https://github.com/quarto-dev/quarto-cli/assets/8896044/ecb08f55-a4f5-40f0-80e6-eb3f76a1e871

**Comment by cscheid** [comment] 2023-07-24 18:50
@mcanouil are you on our dev version? I see something, but I think it's only in the dev version (@dragonstyle is aware and on it), due to the attempt to resolve pandoc across multiple architectures.

**Comment by pascalsiemsen** [comment] 2023-07-25 06:56
Thanks to the comment by @mcanouil, I found the error. The Quarto LSP output showed an error reading my bib file. One reference couldn't be read (always worked in Rmarkdown though). Deleted the the reference and everything works fine now.

Because of the other bug found I am not sure whether I should close the issue myself. 

Thanks again for Quarto.

**Comment by mcanouil** [comment] 2023-07-25 06:59
My issue is in fact something else (now hidden as off topic by the way).

Since yours was a malformed entry in your bib file, I am going to close this.

**Closed** 2023-07-25 06:59 UTC
Labels: bug, needs-repro, vscode
