### ISSUE TITLE
No ouput from OJS code cells in rendered HTML

### ISSUE THREAD

**Issue by larnsce** [quarto-dev/quarto-cli#3446] opened 2022-11-24 15:21 UTC
### Bug description

When using OJS code cells in a Quarto file, I do not get any output in the rendered HTML. 

Hyperlink to .qmd file in GitHub repo: https://github.com/larnsce/ojs-test-drive/blob/main/ojs-test-drive.qmd

I tried to add the .qmd file here, but GiHub does not allow me to upload it. 

# My rendered document

A screenshot of my HTML output file below.

![Screenshot 2022-11-24 at 16 18 35](https://user-images.githubusercontent.com/18212549/203818289-1b716efb-520b-4a07-bd33-504a7abbdeb8.png)

# Session Info

- RStudio Version: 2022.7.2.576
- R version 4.2.1 (2022-06-23)
- Platform: x86_64-apple-darwin17.0 (64-bit)
- Running under: macOS Monterey 12.5.1

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2022-11-24 15:30
I can't reproduce:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/285675/203820092-3a9cd824-61c7-4b5a-ba2e-b6725700dd49.png">

I think what's likely to be happening is that webpages that use OJS need a web server. You're likely opening them by double-clicking them on finder (or "open ..."). That brings up the file:/ scheme, which doesn't support fetching of remote resources, which is required by the OJS runtime. Try

```
$ python3 -m http.server
```

and then browse 127.0.0.1:8000

I'm going to go ahead and close this because I'm pretty sure that's what's happening. If this doesn't solve your problem, feel free to reopen it.

**Closed by cscheid** 2022-11-24 15:30 UTC
Labels: bug

**Comment by larnsce** [comment] 2022-11-24 15:44
Thanks for the quick support.

Yes, that worked. 🥳 

I had opened it in the RStudio IDE Viewer though and don't see the output there (see screenshot below), but that's okay because I have a work around now and know that it would work if I deployed it as a website.

![Screenshot 2022-11-24 at 16 43 12](https://user-images.githubusercontent.com/18212549/203823223-cd8f055f-a303-4cd8-a8bd-e03ed21f2bae.png)

**Comment by cscheid** [comment] 2022-11-24 15:47
Yeah :( it also happens to be the case that OJS requires Javascript features that are only available on Electron builds of the RStudio IDE. I'm improving things so that you'll get better error messages in the future; I apologize in the meantime for the confusion!

**Comment by larnsce** [comment] 2022-11-24 15:50
That's perfect. Thanks again for your lightning fast feedback. I am very unexperienced in anything beyond R, which is why I get confused when trying out new tools. The explanations make perfect sense.

**Comment by cscheid** [comment] 2022-11-24 16:39
Ok, starting at v1.3, we will emit error messages when OJS is executed in file:/ protocols, as well as in QtWebEngine contexts. Thanks for the prod :)
