### ISSUE TITLE
changes in `{{ include file.md}} `  aren't  watched in quarto preview

### ISSUE THREAD

**Issue by danieltomasz** [quarto-dev/quarto-cli#6413] opened 2023-08-02 17:20 UTC
### Bug description

This is either not implemented yet or a bug, but I am making an issue as this is distinct enough from https://github.com/quarto-dev/quarto-cli/issues/3185

I created default book project and modified `index.md` file

```index.md
# Preface {.unnumbered}

This is a Quarto book.

To learn more about Quarto books visit <https://quarto.org/docs/books>.

{{< include _foreword.qmd >}}
```

And I created file `_foreword.qmd`

```
# Foreword

I want to thank the developers
```
When I run 
```quarto preview --watch-inputs```

and edited  `_foreword.qmd`

to 

```
# Foreword

I want to thank the developers of Quarto
```
the output doesnt change,  only when I change something in the `index.qmd`
 the pdf is rerendered.
I would like to `{{ include file.md}}` to be watched too.

Or if there is a limitation of quarto it should be include in the quarto page of includes https://quarto.org/docs/authoring/includes.html

Is it just the lua filter that does `include`?

Adding to `_quarto.yml`
```
resources: 
  - _foreword.qmd
```
helps with html rendering, but not with pdf.
Is there any other  mechanism than can force quarto to watch specific files on change?

Quarto Version: 1.4.287, MacOS 13.4.1

**Comment by danieltomasz** [comment] 2023-08-02 17:36
Example doesnt use "_file.qmd" underscore syntax, but later I checked and with underscores it doesnt work as well;

Only the changes in "main files"  pull the changes from includes

**Comment by danieltomasz** [comment] 2023-08-04 15:43
This either forcing me to have everything in index md to reload on change and dummy empty page as index, 
or use {{include chapters/file.md}} as I want to have my all my content in separate content, I dont want to just put into index file

**Comment by mcanouil** [comment] 2023-08-07 19:28
This is actually the same issue as #3185 because the issue is that Quarto don't watch all dependencies of a Quarto document or a Quarto project.

And a duplicate of #2795, thus closing this.

**Closed by mcanouil** 2023-08-07 19:28 UTC
Labels: bug

**Comment by danieltomasz** [comment] 2023-08-07 22:25
@mcanouil Thanks for update, I searched the issues before posting but I didt find https://github.com/quarto-dev/quarto-cli/issues/2795!
