### ISSUE TITLE
Wrongly escaped latex commands

### ISSUE THREAD

**Issue by verbalins** [quarto-dev/quarto-cli#6527] opened 2023-08-15 08:26 UTC
### Bug description

I'm using the `xparse` LaTeX package and defining this function `\NewDocumentCommand \fullarticle {O{scale=.85,clip=true,pages=-} m m O{} O{}}`. This means that there is one optional command, followed by two mandatory commands, and ending with two optional commands.

When trying to inject these values from my `_quarto.yml`:

```yaml
fullarticles: |
    \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=-]{fischer2017doctoraldissertationmanual}{manual.pdf}[\href{https://creativecommons.org/licenses/by-nc-nd/4.0/}{\ccbyncnd}]
    \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=1]{fischer2017doctoraldissertationmanual}{manual.pdf}[\copyright{} 2018 University of Skövde. Reprinted, with permission, from]
    \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=1]{fischer2017doctoraldissertationmanual}{manual.pdf}[Reprinted from][with permission from University of Skövde.]
```

Through the file `after-body.tex`:
```latex
$if(his-metadata.fullarticles)$
  % Example of including full text articles in the manuscript.
  % It's possible to specify what is written both before the reference and after.
  % \fullarticle[includepdf options]{reference}{pdf-file}[before][after]
  \begin{fullarticles}
  $for(his-metadata.fullarticles)$
    $his-metadata.fullarticles$
  $endfor$
  \end{fullarticles}
$endif$
```

The resulting .tex file looks like this:
```latex
\begin{fullarticles}
      \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=-]{fischer2017doctoraldissertationmanual}{manual.pdf}{[}\href{https://creativecommons.org/licenses/by-nc-nd/4.0/}{\ccbyncnd}{]}
      \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=1]{fischer2017doctoraldissertationmanual}{manual.pdf}{[}\copyright{}
      2018 University of Skövde. Reprinted, with permission, from{]}
      \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=1]{fischer2017doctoraldissertationmanual}{manual.pdf}{[}Reprinted
      from{]}{[}with permission from University of Skövde.{]}
\end{fullarticles}
```

The problem, I think, stems from the fact that the second set of optional arguments are escaped incorrectly. Maybe due to how it's parsed by pandoc? The `xparse` package allows for definition of methods not supported by regular LaTeX and maybe that's throwing the parser off?

### Steps to reproduce

Please see the [his-template](https://github.com/verbalins/his-template) repository. Clone it and compile with `quarto render -t his-pdf` and the problem should be visible in the `Title-for-this-example-thesis.tex` file.

### Expected behavior

Here's the correct LaTeX withouth the extra escapes.
```latex
\begin{fullarticles}
      \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=-]{fischer2017doctoraldissertationmanual}{manual.pdf}[\href{https://creativecommons.org/licenses/by-nc-nd/4.0/}{\ccbyncnd}]
      \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=1]{fischer2017doctoraldissertationmanual}{manual.pdf}[\copyright{} 2018 University of Skövde. Reprinted, with permission, from]
      \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=1]{fischer2017doctoraldissertationmanual}{manual.pdf}[Reprinted from][with permission from University of Skövde.]
\end{fullarticles}
```

### Actual behavior

```latex
\begin{fullarticles}
      \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=-]{fischer2017doctoraldissertationmanual}{manual.pdf}{[}\href{https://creativecommons.org/licenses/by-nc-nd/4.0/}{\ccbyncnd}{]}
      \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=1]{fischer2017doctoraldissertationmanual}{manual.pdf}{[}\copyright{}
      2018 University of Skövde. Reprinted, with permission, from{]}
      \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=1]{fischer2017doctoraldissertationmanual}{manual.pdf}{[}Reprinted
      from{]}{[}with permission from University of Skövde.{]}
\end{fullarticles}
```

### Your environment

- OS: Windows 10

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.315
      Path: C:\Users\A410035\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2022.11
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\<user>\AppData\Roaming\TinyTeX\bin\win32\
      Version: 2022

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Python/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/R/R-4.3.1
      LibPaths:
        - C:/R/win-library
        - C:/R/R-4.3.1/library
      knitr: 1.43
      rmarkdown: 2.23

[>] Checking Knitr engine render......OK
```

**Comment by verbalins** [comment] 2023-08-16 06:06
Thank you for your reply!
I've managed to reproduce it like this on quarto version 1.4.322:

```
---
title: "My document"
format:
  pdf:
    documentclass: article
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{xparse}
        \NewDocumentCommand \fullarticle {O{scale=.85,clip=true,pages=-} m m O{} O{}}
---

\fullarticle[optional test]{required test}{required test}[optional again][last optional]
```


It gives the following erroneous output in the resulting .tex file:
```latex
\fullarticle[optional test]{required test}{required test}{[}optional
again{]}{[}last optional{]}
```

**Comment by mcanouil** [comment] 2023-08-16 06:22
What if you actually declare raw LaTeX code as raw LaTeX?

````qmd
---
title: "My document"
format:
  pdf:
    documentclass: article
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{xparse}
        \NewDocumentCommand \fullarticle {O{scale=.85,clip=true,pages=-} m m O{} O{}}
---

```{=latex}
\fullarticle[optional test]{required test}{required test}[optional again][last optional]
```
````

**Comment by verbalins** [comment] 2023-08-16 06:40
That works!

Unfortunately I don't think it would work in my original use-case? My intention is to have those rows as metadata to a format extension and define it in the extension yaml like this:

```yaml
fullarticles: |
   \fullarticle[optional test]{required test}{required test}[optional again][last optional]
   \fullarticle[optional test]{required test}{required test}[optional again][last optional]
   \fullarticle[optional test]{required test}{required test}[optional again][last optional]
```

Or do you think I need to wrap it differently in the template partial where I read those lines?

**Comment by mcanouil** [comment] 2023-08-16 06:47
I would either put in the template partial or inject them from a LUA filter (which could read from YAML metadata).

**Comment by verbalins** [comment] 2023-08-16 11:21
Looks like the strings in the yaml are already broken up when accessing the metadata through lua. I've opted to alter the LaTeX command to instead look like `\fullarticle[optional][optional][optional]{required}{required}`. Which preserves the command as is.

**Comment by verbalins** [comment] 2023-08-17 06:40
I tried with the `quarto pandoc` command and I get the same error. Something must be going on when, I'm guessing here, Pandoc/quarto is determining whether the text command is a LaTeX string or not. As the `\fullarticle[optional][optional][optional]{required}{required}` works but `\fullarticle[optional]{required}{required}[optional][optional]` does not. I don't see a way to define the block as latex in the yaml options to force it to parse it as LaTeX.

**Comment by cscheid** [comment] 2023-08-17 14:49
`quarto pandoc` simply calls Pandoc directly; that's an indication that this is happening entirely inside Pandoc, and there's not much we can do on our side. You'll have to avoid LaTeX parsing with raw blocks as suggested above.

I'm closing this as it's not a bug.

**Closed by cscheid** 2023-08-17 14:49 UTC
Labels: bug, extensions, latex
