### ISSUE TITLE
Included self-generated markdown file takes two renderings to render

### ISSUE THREAD

**Issue by psads-git** [quarto-dev/quarto-cli#6855] opened 2023-09-16 13:03 UTC
Consider the following `quarto` document (using `Quarto 1.4.367` ):

````
---
title: "Untitled"
format: pdf
---

```{python}
md_str = 'Hello, world!'

with open('./x.qmd', 'w') as f:
    f.write(md_str)
```

{{< include x.qmd >}}

```
````

It takes _two_ renderings to render the contents of the included markdown file. By contrast, when the `quarto` document generates a LaTeX file (again using `python`), it renders it with with a _single_ rendering:

````
```{=latex}
\input{x.tex}
```
````

**Comment by mcanouil** [comment] 2023-09-16 13:08
This is not a bug, use pre-render script if you want to generate document to be included.
Include shortcode as described in the documentation is basically a copy/paste that happens before computation.

If you want to really include markdown generated content, simply output the markdown in your code cell with the `output: asis` option.

**Comment by psads-git** [comment] 2023-09-16 13:16
Thanks, Mickaël, for your answer.

I have just noticed that the `qmd` file is not actually created by the code chunk: It only modifies the `qmd` file if it is already existent. Is that expected?

**Comment by mcanouil** [comment] 2023-09-16 13:20
It's unclear what you are referring to with `qmd` file since you have two: the one included and the one that include the other.

**Comment by psads-git** [comment] 2023-09-16 13:22
The included one, Mickaël!

```
source /home/x/.virtualenvs/r-reticulate/bin/activate
(r-reticulate) [x@localhost tmp]$ quarto preview /tmp/Untitled-1.qmd --no-browser --no-watch-inputs
ERROR: Include directive failed.
  in file Untitled-1.qmd, 
  could not find file /tmp/x.qmd.

Stack trace:
  in file Untitled-1.qmd, 
  could not find file /tmp/x.qmd.
    at retrieveInclude (file:///home/x/opt/quarto-1.4.367/bin/quarto.js:70275:23)
    at Object.directive (file:///home/x/opt/quarto-1.4.367/bin/quarto.js:70311:15)
    at handleLanguageCells (file:///home/x/opt/quarto-1.4.367/bin/quarto.js:40061:82)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async renderContexts (file:///home/x/opt/quarto-1.4.367/bin/quarto.js:75021:45)
    at async renderFormats (file:///home/x/opt/quarto-1.4.367/bin/quarto.js:75041:26)
    at async previewFormat (file:///home/x/opt/quarto-1.4.367/bin/quarto.js:95298:36)
    at async preview (file:///home/x/opt/quarto-1.4.367/bin/quarto.js:95191:20)
    at async Command.fn (file:///home/x/opt/quarto-1.4.367/bin/quarto.js:96525:9)
    at async Command.execute (file:///home/x/opt/quarto-1.4.367/bin/quarto.js:8111:13)

```

**Comment by mcanouil** [comment] 2023-09-16 13:58
As I said the include shortcode is executed before computation, thus it cannot include a file that does not exist.

The following is the way to go to include generated markdown:

````qmd
---
format: pdf
---

```{python}
#| output: asis
from IPython.display import Markdown

md_str = '# Hello, world!'

Markdown(md_str)
```
````

**Comment by psads-git** [comment] 2023-09-16 14:03
The point is, Mickaël: the file is not created by the `python` code chunk, even if one renders the `quarto` document one thousand of times! Should not the `python` code chunk be executed?

**Comment by cscheid** [comment] 2023-09-16 14:08
The problem you're seeing comes from the fact that include shortcodes are resolved _before_ engine execution. That's by design, so that the included content can have executable cells. If your executable cells generate content, then that content won't be visible by quarto.

**Comment by mcanouil** [comment] 2023-09-16 14:11
You need to provide a complete reproducible example (which your first example is not) and to provide the complete steps to reproduce (all of these were requested in the bug report template you did not use when opening the GitHub issue).

Anyway, this does not change the order of execution explained several times already.

**Comment by psads-git** [comment] 2023-09-16 14:15
If you render multiple successive times the `qmd` I have posted, you will see that `x.qmd` is not created at all. Is that expected? 

So, I think I have provided a reproducible example.

**Comment by mcanouil** [comment] 2023-09-16 14:17
It can't be created because first Quarto needs to include the document which does not exist.

- includes first
- computations second

Also you example is invalid as it contains three extra backticks.

**Comment by psads-git** [comment] 2023-09-16 14:26
So, you are saying that, if the file is not existent, the computation of the code chunk will not take place, because quarto aborts before, since the file does not exist, right?

**Comment by mcanouil** [comment] 2023-09-16 14:32
Yes

**Comment by cscheid** [comment] 2023-09-16 15:44
> So, you are saying that, if the file is not existent, the computation of the code chunk will not take place, because quarto aborts before, since the file does not exist, right?

Yes. That behavior is correct, and by design. See my [original response](https://github.com/quarto-dev/quarto-cli/issues/6855#issuecomment-1722238180):

> If your executable cells generate content, then that content won't be visible by quarto's include shortcodes until the next call to quarto render.

**Comment by cscheid** [comment] 2023-09-16 15:47
I think we have both identified the source of your issue (include shortcodes happen before engine execution, as they're designed to do, and quarto is aborting because the file doesn't yet exist, as it's designed to do) and the appropriate solution (use `Markdown` from `IPython.display` like suggested).

I'm going to go ahead and close this issue.

**Closed by cscheid** 2023-09-16 15:47 UTC
Labels: computations, includes, support
