### ISSUE TITLE
Add page dedicated to the `quarto` CLI (like a manpage)

### ISSUE THREAD

**Issue by salim-b** [quarto-dev/quarto-cli#8997] opened 2024-03-07 11:31 UTC
### What would you like to do?

Report an issue on quarto.org

### Description

I just realized that the "heart" of the whole Quarto ecosystem, the `quarto` CLI, is nowhere documented on quarto.org. There should be a section dedicated to the CLI itself, featuring a (pimped) version of the output `quarto --help` as well as `quarto SUBCMD --help` gives (where `SUBCMD` stands for all the different CLI subcommands like `render`, `preview`, `create` etc.).

Of course, this Quarto CLI section should be autogenerated by all means.

Output for `quarto --help` as of v1.4.551:

```

  Usage:   quarto 
  Version: 1.4.551

  Description:

    Quarto CLI

  Options:

    -h, --help     - Show this help.                            
    -V, --version  - Show the version number for this program.  

  Commands:

    render     [input] [args...]     - Render files or projects to various document types.
    preview    [file] [args...]      - Render and preview a document or website project.  
    serve      [input]               - Serve a Shiny interactive document.                
    create     [type] [commands...]  - Create a Quarto project or extension               
    use        <type> [target]       - Automate document or project setup tasks.          
    add        <extension>           - Add an extension to this folder or project         
    update     [target...]           - Updates an extension or global dependency.         
    remove     [target...]           - Removes an extension.                              
    convert    <input>               - Convert documents to alternate representations.    
    pandoc     [args...]             - Run the version of Pandoc embedded within Quarto.  
    typst      [args...]             - Run the version of Typst embedded within Quarto.   
    run        [script] [args...]    - Run a TypeScript, R, Python, or Lua script.        
    install    [target...]           - Installs a global dependency (TinyTex or Chromium).
    uninstall  [tool]                - Removes an extension.                              
    tools                            - Display the status of Quarto installed dependencies
    publish    [provider] [path]     - Publish a document or project to a provider.       
    check      [target]              - Verify correct functioning of Quarto installation. 
    help       [command]             - Show this help or the help of a sub-command.       
```

**Comment by mcanouil** [comment] 2024-03-07 12:34
Thanks for the feedback.

Duplicate of https://github.com/quarto-dev/quarto-cli/issues/598

**Closed by mcanouil** 2024-03-07 12:34 UTC
Labels: documentation
