### ISSUE TITLE
Microsoft Edge not detected (Quarto 1.6.4)

### ISSUE THREAD

**Issue by Steinthal** [quarto-dev/quarto-cli#10464] opened 2024-08-05 12:16 UTC
### Bug description

I've removed chromium from my MacBook (and Mac Mini). After a restart, Quarto 1.6.4 complains that no chromium was detected and does not use Microsoft Edge which is installed. Reference: #10172

### Steps to reproduce

Take the example from the original post (#10162):

````
---
title: "In-Class: Relations - Digraphs"
format: 
  pdf: default
---

Any quarto document that includes a diagram and compiling a PDF; here's a sample:


```{dot}
//| fig-width: 2
digraph {
  node [shape = circle, width=0.5];
  rankdir = LR;
  1 -> 1;
  1 -> 2;
  2 -> 4; 
  1 -> 3;
  3 -> 4;
  4 -> 1;
}

```
````

### Expected behavior

Edge should be used if chromium is not installed

### Actual behavior

Error message:

ERROR: Chrome not found

No Chrome or Chromium installation was detected.

Please run 'quarto install chromium' to install Chromium.

### Your environment

- IDE: n/a
- macOS: 14.6 (23G80) as well as 15.1 Beta (24B5009l)

### Quarto check output

````bash
Quarto 1.6.4
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.4
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: /Users/USER/.pyenv/versions/3.10.2/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

````

**Comment by mcanouil** [comment] 2024-08-05 13:48
Does the following path is correct in your machine? `/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge`

**Comment by Steinthal** [comment] 2024-08-05 14:55
````bash
ls -l /Applications/Microsoft\ Edge.app/Contents/MacOS/
total 920
-rwxrwxr-x  1 USER  admin  469248  1 Aug 20:33 Microsoft Edge
````

**Comment by mcanouil** [comment] 2024-08-05 15:22
The path set in the PR is correct then, so the issue might be the following part:

```
   return programs.find((p) => {
      safeExistsSync(p);
    });
```

**Comment by mcanouil** [comment] 2024-08-21 15:41
Replacing the code I mentioned with the code below (similarly to Windows) works:
```ts
    for (let i = 0; i < programs.length; i++) {
      path = programs[i];
      if (path && existsSync(path)) break;
    }
```

- https://github.com/quarto-dev/quarto-cli/blob/39dc173c4869ebaf4d6bb087a972acb87533b64e/src/core/puppeteer.ts#L209-L212


I think the code should also be updated to observe some environment variable, for instance I would personally like to be able to use Brave (`"/Applications/Brave Browser.app/Contents/MacOS/Brave Browser"`)

**Comment by mcanouil** [comment] 2024-08-21 15:52
I made a PR with the fix:

- https://github.com/quarto-dev/quarto-cli/pull/10574

**Comment by Steinthal** [comment] 2024-08-22 19:56
I've installed Quarto 1.6.6 but still get the same error…

Anything I can check if some old settings might cause the behavior?

**Comment by mcanouil** [comment] 2024-08-22 20:02
The PR was not merged as indicated by GitHub and this issue is still open. Why would you expect things to change in a new release?

**Comment by Steinthal** [comment] 2024-08-22 20:12
Sorry, I misread

````
Other Fixes and Improvements
#10162: Use Edge on macOS as a Chromium browser when available.
````

**Comment by mcanouil** [comment] 2024-08-22 20:27
That's the initial PR you even mentioned in your report, which you already know is not working as intended.

**Closed** 2024-08-24 16:06 UTC
Labels: bug, puppeteer, chromium

**Comment by mcanouil** [comment] 2024-08-24 16:29
@Steinthal the fix should be part of the next pre-release build.

**Comment by Steinthal** [comment] 2024-08-27 20:34
Just installed 1.6.7 and can confirm that the fix is working . Thanks a lot, guys.
