### ISSUE TITLE
Feature request: CLI flag to suppress printing papermill parameters in document

### ISSUE THREAD

**Issue by jeremiahpslewis** [quarto-dev/quarto-cli#723] opened 2022-04-24 16:17 UTC
It would be nice to be able to suppress the parameter cell which is injected into a document via the [parameters](https://quarto.org/docs/computations/parameters.html) feature, as it doesn't always have relevant content for the reader.

Something equivalent to: https://github.com/nteract/papermill/pull/254 / https://github.com/nteract/papermill/blob/3d46a93a479f203750e601419aff382082dd90c6/papermill/execute.py#L147

**Comment by jjallaire** [comment] 2022-04-27 10:05
I feel like perhaps we should _never_ show the parameters as they are really metadata (perhaps we could not show them by default but allow them to be turned back on w/ `#| echo: true` ?

**Comment by jeremiahpslewis** [comment] 2022-04-27 11:42
There are potentially three issues here with the current implementation:

1. A manually added parameters cell does not respect the typical echo/hide comment syntax
2. All pages, regardless of whether they have an explicit parameters cell, will be prepended with the parameters
3. Parameters **do** affect reproducibility, so there's an argument that in many cases you will want to show them; but in other cases, you're just using a parameter to hack around an issue / spruce up formatting and you definitely don't want it included.

If you're curious what this looks like, I've got it running here:

Page with explicit parameters cell:
https://jeremiahpslewis.github.io/quarto-reproducible-gh-actions/

Page with automatically injected parameters cell:
https://jeremiahpslewis.github.io/quarto-reproducible-gh-actions/r-supporting-material.html

**Comment by jjallaire** [comment] 2022-04-29 00:19
Okay, trying to figure out what a good resolution would be here. 

For the equivalent of `--report-mode`, you can actually pass metadata on the command line like this:

```bash
quarto render document.qmd -M echo:false
```

It sounds like we should also do the following:

1) Only prepend the injected parameters cell if we find a parameters cell; and
2) Propagate any local `echo` cell option on parameters to the injected parameters

Does that like a reasonable resolution?

**Comment by jjallaire** [comment] 2022-04-29 01:38
I've implemented the following here: https://github.com/quarto-dev/quarto-cli/commit/d94ba1d707013616477cb5608347847c3e6d7e0b

- don't inject parameters unless there is a parameters cell
- duplicate options on injected parameter cell

**Comment by jeremiahpslewis** [comment] 2022-04-29 09:20
This is awesome. Once you have a release or a binary, happy to test! :)

One question...will the parameters cell metadata/options be respected (if nothing is passed via command line)?

**Comment by jjallaire** [comment] 2022-04-29 10:31
Binary release is here: https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.326

Yes, the parameters cell options should be respected even if nothing is passed on the command line.

**Comment by jeremiahpslewis** [comment] 2022-04-29 16:10
Tested the new release:

1. Parameters do not show up in documents without parameters cells ✅ 
2. But the behavior with parameters cells is a little weird. I get the following:

If you have a parameters cell with no further metadata, you get double printing (in all languages):

Julia:
<img width="856" alt="Screen Shot 2022-04-29 at 17 56 15" src="https://user-images.githubusercontent.com/4462211/165981265-4c83c69a-b25c-4d31-b979-9b6b938166e7.png">


Python:
<img width="903" alt="Screen Shot 2022-04-29 at 17 56 04" src="https://user-images.githubusercontent.com/4462211/165981314-1c080942-7f19-4003-8173-d5d050dd212c.png">

R: 
<img width="502" alt="Screen Shot 2022-04-29 at 18 00 53" src="https://user-images.githubusercontent.com/4462211/165981727-e12b5394-5445-45f6-b8b6-72d86fcf7767.png">

If you add ``#| echo: false``, both code cells disappear, the output (which is only printed in Julia, per default behavior (no semicolon)) remains.

**Comment by jjallaire** [comment] 2022-04-30 13:34
I don't think there is a clean way around this. The issue is that papermill allows you to override any. number of parameters, so both cells definitely need to execute (otherwise there could be missing params). The parameters could be merged of course, however that needs to be done in a cross-language fashion.

Note that papermill parameter injection has a set of per-language translation handlers here: https://github.com/nteract/papermill/blob/main/papermill/translators.py. This is what we call to do parameter injection. If merging is to be implemented I think it needs to be done here (rather than based on some regexes we cook up).

**Comment by jeremiahpslewis** [comment] 2022-04-30 13:38
Shall we close this issue then? Params are otherwise working great!

**Comment by jjallaire** [comment] 2022-04-30 13:39
Yup, let's close it. Thanks again for the feedback and follow-up!

**Closed by jjallaire** 2022-04-30 13:39 UTC

**Comment by multimeric** [comment] 2025-01-29 05:38
Am I right that this change only affected Julia? Because the linked commit doesn't mention Python. And unfortunately I'm getting my confidential parameters being printed in my parameterised Python document.

**Comment by mcanouil** [comment] 2025-01-29 07:08
Would you mind opening a new discussion with a small reproducible example of the issue?

This thread is three years old.
