### ISSUE TITLE
Syntax for multi-line figure captions in Python code cells

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#5413] opened 2023-05-04 07:56 UTC
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5407

<div type='discussions-op-text'>

<sup>Originally posted by **astoeriko** May  3, 2023</sup>
Some of my figure captions are quite long, so I would like to split them into several lines in the source code for better readability. What is the right syntax for this? Based on the instructions for mermaid diagrams that I found [here](https://github.com/quarto-dev/quarto-cli/discussions/1816) I tried as follows:
        
    ```{python}
    #| fig-cap: |
    #|   This is a caption for my figure.
    #|   It is long, so I put it onto two lines
    import numpy as np
    import matplotlib.pyplot as plt
    plt.plot(np.arange(10))
    ```
But when I run `quarto render`, I get an error:

```
Executing 'test.ipynb'
  Cell 1/1...ERROR: 

None of the known patterns match for   It is long, so I put it onto two lines
```
It runs fine if I put all the caption onto one line, but this is impractical with caption that are several sentences long.

    ```{python}
    #| fig-cap: "This is a caption for my figure. It is long, so I put it onto two lines."
    import numpy as np
    import matplotlib.pyplot as plt
    plt.plot(np.arange(10))
    ```
</div>

**Comment by mcanouil** [comment] 2023-05-04 08:11
FYI, the same works properly for Python code cells using `knitr` as the engine.

**Comment by cscheid** [comment] 2023-05-25 16:39
We should consider replacing poyo with [ruamel-yaml](https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/)

**Comment by dmontecino** [comment] 2023-10-03 14:27
hi there! Same deal if {r} right?

**Comment by cderv** [comment] 2023-10-03 14:34
@dmontecino what do you mean ? 

This issue is about Python through Jupyter engine, and the YAML parser used. `{r}` will use Knitr engine, and a R YAML parser that does not have this issue. 

If you encounter something you think is not expected, please open a new issue and follow the issue guide. It is better to open a new issue and link to another, than commenting in an opened or closed issue when the topic is not exactly the same. 
Also you should try test under Quarto 1.4 pre-release to check if something is fixed since Quarto 1.3

Thank you !

**Comment by cscheid** [comment] 2023-10-03 14:42
(@cderv is this in a wrong issue?)

**Comment by cscheid** [comment] 2023-11-30 15:17
We should still 100% use a better parser, but I'll note that this issue is no longer acute because of the [new syntax](https://quarto.org/docs/authoring/cross-references-divs.html) for crossreferenceable elements.

**Comment by cscheid** [comment] 2024-05-08 16:58
This is no longer an `upstream` bug now that we're using PyYAML. Our output is still broken (I think this is now a duplicate of a separate issue, but I can't find it now). This is our output:

<img width="862" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/2bda41a2-6b34-44b3-81bc-52db4a35aab5">

`keep-md: true` shows that it's entirely our fault:

````
::: {#fab881cf .cell execution_count=1}
``` {.python .cell-code}
import numpy as np
import matplotlib.pyplot as plt
plt.plot(np.arange(10))
```

::: {.cell-output .cell-output-display}
![
This is a caption for my figure.

It is long, so I put it onto two lines
](5413_files/figure-html/cell-2-output-1.png){width=558 height=411}
:::
:::
````

**Closed** 2024-06-12 17:18 UTC
Labels: bug, jupyter
