### ISSUE TITLE
Listing breaks pdf on single file rendering

### ISSUE THREAD

**Issue by rtoin** [quarto-dev/quarto-cli#6427] opened 2023-08-04 10:29 UTC
### Bug description

When rendering a single file with `quarto render`, the file being rendered to both html and pdf,  if there is an `index.qmd` file using a listing option then the pdf won't be rendered correctly.

I hope that the following details will be helpful, thank you in advance for your help.

### Steps to reproduce

Here is a simple repository reproducing the issue: https://github.com/rtoin/dummy_quarto_listing

I recreated a small project with the following file tree to demonstrate my problem:

project_dir/
├── _output/
├── _quarto.yml
├── index.qmd
├── doc/
│   ├── file.qmd

Here is the content of the files:

`_quarto.yml`
```
project:
  title: "My project"
  type: website
  output-dir: _output

format:
  html: default
  pdf: default
```

`index.qmd`
```
---
format:
  html: default
listing:
  type: default
  contents:
    - doc
  fields: [date, title, author, description, categories]
  sort: "date desc"
  sort-ui: true
  filter-ui: true
---

# Index page
```

`file.qmd`
```
---
title: "Test file"
abstract: "A test file to test a listing problem."
author: Me
categories: Technical documentation
---

# Title

My text here
```

If the project was never compiled before, using `quarto render doc/file.qmd` will produce functional html and pdf outputs.

If the project is compiled with `quarto render`, then both `index.qmd` and `doc/file.qmd` will be exported and will be functional.

However, if following a global `quarto render` I export one file only again with `quarto render doc/file.qmd` then `index.qmd` will be compiled alongside the file (to update the listing I presume) and the html outputs will be functional but the pdf output will be corrupted. Here is the corrupted pdf output: 
[file.pdf](https://github.com/quarto-dev/quarto-cli/files/12259679/file.pdf)

If I remove the listing options from the `index.qmd` file then the problem disappears.

### Expected behavior

The file rendered alone should be correctly exported to html and pdf.

### Actual behavior

The file rendered alone is correctly exported to html but the pdf output is corrupted.

### Your environment

- IDE: VSCode
- OS: Windows 10 (22H2)
- Quarto v1.4.288 (but the problem was the same with v1.3.433)
- TinyTex: installed manually from https://github.com/rstudio/tinytex-releases
- exportation method: command line executed inside a Git Bash

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.288
      Path: C:\Users\secret\AppData\Local\Programs\Quarto\bin
      CodePage: unknown

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Users/secret/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.3.1
      Kernels: python3

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by dragonstyle** [comment] 2023-08-04 12:58
I'm having trouble reproducing this issue locally. I'm never seeing the root `index.qmd` file rendered as a PDF - none of the scenarios will produce an index.pdf for me.

I'm using the vs.code terminal using the latest Quarto (should be very close to 1.4.288) on MacOS. Can you share an actual repo / project that is reproducing this by any chance? Perhaps I have transcribed something incorrectly or there is some subtle difference that isn't captured in your description above...

**Comment by rtoin** [comment] 2023-08-05 12:49
The `index.qmd` file is never rendered as pdf because only the html format is specified in its yaml header. That's the behavior I'm expecting. I only want the index to exist as an html page.

The problem I'm having is regarding the `doc/file.pdf` generated that is corrupted. The other files generated (`doc/file.html` and `index.html` are working fine).

Unfortunately I don't have a public repo that I can share. The example I provide with the 3 files should be enough:
1. Create the 3 files as mentionned
2. Run `quarto render` to generate 3 files: `index.html`, `doc/file.html` and `doc/file.pdf`. All the files are working fine.
3. Run `quarto render doc/file.qmd `: the 3 files are generated again but the `doc/file.pdf` is corrupted.
4. If I run `quarto render` again, the 3 files are generated successfully.
5. If I run `quarto render doc/file.qmd` again, the `doc/file.pdf` is corrupted again.

If I add multiple `.qmd` files in the `doc/` folder and run `quarto render` then all of them will be exported as html and pdf successfully. But rendering only one at a time will create a corrupted pdf **only if the listing property is present in `index.qmd`.**

If you can't reproduce the problem, I'm afraid that my building environment might be responsible.

**Comment by rtoin** [comment] 2023-08-05 13:04
I was able to reproduce my problem on a different Windows 10 computer, installing quarto (v1.3.450) for the first time, installing TinyTex with `quarto install tinytex` and then following the steps mentioned in my comment above.

**Comment by mcanouil** [comment] 2023-08-05 13:57
If you are unable to share the repository, could you make a simple one that does (not "should") exhibit the undesired behaviour?

**Comment by rtoin** [comment] 2023-08-05 14:46
Here is a simple repository reproducing the issue: https://github.com/rtoin/dummy_quarto_listing
Everything is detailed in the README. I hope this helps.

**Comment by dragonstyle** [comment] 2023-08-06 20:17
Thanks for sharing the repo - I was able to reproduce this on a recent development version of Quarto (only on Windows). The issue is related to a windows specific implementation of `touch` which is used when generating listing output - the implementation was assuming the touched file would be a text file (which is usually, but definitely not always true!). I should have a fix on the way shortly... Thanks for reporting this and providing the repo - it found a great low level bug!

**Comment by rtoin** [comment] 2023-08-07 07:14
Thank you for taking some time to answer my problem. For now, I will only activate listings when I release my projects.

I'm having fun with Quarto and I'm looking forward to the new releases. I let you close this issue as you see fit. Thank you.

**Comment by dragonstyle** [comment] 2023-08-07 12:09
Thank you - the fix is in the latest pre-release build now, so I am closing this.

**Closed by dragonstyle** 2023-08-07 12:09 UTC
Labels: bug, needs-repro, latex, listings
