### ISSUE TITLE
Figure arguments ignored in minipage outputs

### ISSUE THREAD

**Issue by gregmacfarlane** [quarto-dev/quarto-cli#6611] opened 2023-08-24 16:30 UTC
I am trying to create a figure with subfigures on a landscape page in a pdf output.

## Single figure
This example code creates a single figure in a sideways environment with a `t` position.

````md
---
title: "Untitled"
format: 
  pdf: 
    keep-tex: true
    include-in-header: 
      - text: |
          \usepackage{rotating}
---

```{r ex}
#| label: fig-example
#| fig-pos: t
#| fig-env: sidewaysfigure
#| fig-cap: "1 Chart"

plot(cars)
```

````

As expected, the rendered tex contains both the `sidewaysfigure` float environment as well as the top position marker. The PDF is rendered as expected.

```tex
\begin{sidewaysfigure}[t]
{\centering \includegraphics{test_tikz_files/figure-pdf/fig-example-1.pdf}}
\caption{\label{fig-example}1 Chart}
\end{sidewaysfigure}
```

## Sub-figures

I would expect that modifying the code chunk to include captions and subcaptions would work.

````md
```{r ex2}
#| label: fig-example2
#| fig-pos: t
#| fig-env: sidewaysfigure
#| fig-cap: "Charts"
#| fig-subcap: 
#|   - "Cars"
#|   - "Pressure"
#| layout-ncol: 2

plot(cars)
plot(pressure)
```
````
but the tex rendered from this chunk is in the default `figure` environment, and the `fig.pos` marker has disappeared.

```tex
\begin{figure}

\begin{minipage}[t]{0.50\linewidth}
{\centering 
\raisebox{-\height}{
\includegraphics{test_tikz_files/figure-pdf/fig-example2-1.pdf}
}}
\subcaption{\label{fig-example2-1}Cars}
\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}
{\centering 
\raisebox{-\height}{
\includegraphics{test_tikz_files/figure-pdf/fig-example2-2.pdf}
}}
\subcaption{\label{fig-example2-2}Pressure}
\end{minipage}%

\caption{\label{fig-example2}Charts}
\end{figure}
```
There doesn't appear to be a package conflict here, because I can just edit the tex to use a `sidewaysfigure` environment, and all is well. 

I don't know if this is a bug in `knitr` or  in quarto, and I haven't seen if this bug was present in bookdown or R markdown.

**Comment by mcanouil** [comment] 2023-08-24 19:15
Could you format your code properly by using more backticks than you have in your document (usually four ` ```` `)?

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by mcanouil** [comment] 2023-08-29 12:14
Thanks for the report, it seems to be a missing update when support for `fig-env` was added (https://github.com/quarto-dev/quarto-cli/pull/4833).

**Comment by cscheid** [comment] 2023-08-29 15:50
Thanks for the detailed followup, @cderv. Unfortunately, all of this treatment is changing on https://github.com/quarto-dev/quarto-cli/pull/6620.

@gregmacfarlane thanks for the bug report. We're in the process of making substantial changes to figure treatments in all formats, and I'll add a test for your usecase in our suite.

**Comment by cderv** [comment] 2023-08-29 16:03
Awesome good to know #6620 could also fix this... And good to know I'll need to learn all again about how we do figures 😅

**Comment by gregmacfarlane** [comment] 2023-08-30 21:35
Thank you all for looking into this, and for making a really useful product. I personally love that the way to do figures changes every couple of years. Keeps me on my toes...

**Comment by cscheid** [comment] 2023-08-30 22:29
> I personally love that the way to do figures changes every couple of years. Keeps me on my toes...

I'm sorry about if we're breaking your code! We really do try very hard not to regress existing behavior. Hopefully, your code won't need to change when we merge the PR; instead, we'll just fix your bug.

**Comment by cscheid** [comment] 2023-12-14 21:25
This is a duplicate of #5271.

**Closed by cscheid** 2023-12-14 21:25 UTC
Labels: bug, crossref, latex, triaged-to
