### ISSUE TITLE
code-annotations: hover quit working in 1.4.37

### ISSUE THREAD

**Issue by harrelfe** [quarto-dev/quarto-cli#5441] opened 2023-05-06 15:44 UTC
### Bug description

Hovering over the circled numbers to the right of code is ignored.  I'm running under Ubuntu 22.04.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment] 2023-05-06 15:49
Thanks for the report, could you provide a working reproducible following the [guidelines](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us)?

**Comment by harrelfe** [comment] 2023-05-06 17:13
Sorry about the lack of an example.  I created a minimal example for a standalone html document and there is no problem.  The failure is in the bigger context of what is below

```
project:
  type: book

book:
  title: "R Workflow"
  subtitle: "R Workflow for Reproducible Data Analysis and Reporting"
  author:
    - name: Frank E Harrell Jr
      url: https://hbiostat.org
      affiliation: Department of Biostatistics<br>School of Medicine<br>Vanderbilt University
  date: last-modified
  site-url: https://hbiostat.org/rflow
  url: https://hbiostat.org/rflow

  google-analytics: "..."

  twitter-card:
    creator: "@f2harrell"
    site: "@f2harrell"
		
  chapters:
    - index.qmd
    - intro.qmd
    - case.qmd
    - rbasics.qmd
    - rformat.qmd
    - fcreate.qmd
    - missing.qmd
    - datachk.qmd
    - doverview.qmd
    - descript.qmd
    - manip.qmd
    - sstats.qmd
    - merge.qmd
    - long.qmd
    - graphics.qmd
    - analysis.qmd
    - caching.qmd
    - parallel.qmd
    - sim.qmd
    - figures.qmd
    - resources.qmd

  page-footer:
    background: light
    left:
      - text: "Copyright 2022, Frank E Harrell Jr"
    right:
      - text: "License"
        href: https://www.gnu.org/licenses/gpl-3.0.en.html

  navbar:
    collapse-below: xl

format:
  html:
    theme: journal
    number-depth: 3
    cap-location: margin
    reference-location: margin
    css: h.css
    code-tools: true
    code-block-bg: "#f1f3f5"
    code-block-border-left: "#31BAE9"
    code-annotations: hover

comments:
  hypothesis:
    theme: clean
    openSidebar: false
    enableExperimentalNewNoteButton: true

execute:
  warning: false
  message: false
  freeze: auto
```

**Comment by dragonstyle** [comment] 2023-05-06 20:00
I'm guessing that there is some sort of JS error happening (not sure what would be triggering that though). We currently aren't as robust as we should be in the face of errors in javascript... Do you mind trying to use the developer tools in your browser to check the JS console for an error message (that would confirm a JS error and might give me a stack trace that would help pinpoint the issue)? Can you share any stack trace that you find (if you find one)?

**Comment by harrelfe** [comment] 2023-05-06 22:35
I don't know my way around browser tools but in Vivaldi when I do tools ... developer ... Console this is what I see
![image](https://user-images.githubusercontent.com/1150682/236649037-e045a58c-6353-45d2-81d5-c736e26911bb.png)

**Comment by dragonstyle** [comment] 2023-05-08 13:32
This is a mystery. We did introduce hover crossrefs in 1.4, which is a potential culprit (though I couldn't get an issue to happen in my local testing). Could you try disabling this feature and see if that resolves the error - then we could focus on narrowing down the content that might cause the error and I can fix it!

You can disable using:

`crossrefs-hover: false`

under `format: > html:`

Sorry for the issue!

**Comment by harrelfe** [comment] 2023-05-08 13:40
Turning off `crossrefs-hover` made code annotation hover work fine.

**Comment by dragonstyle** [comment] 2023-05-08 14:35
Ok this is great- there is definitely something that you are referencing that is somehow unexpected to us (the content is somehow problematic based on the way I have it currently working). I was immediately suspicious of mermaid diagrams as figures, but I couldn't reproduce that locally at all. Do you happen to have any theories as to any types of things you crossref that might cause issues (for example, interactive elements using javascript come to mind)?

**Comment by dragonstyle** [comment] 2023-05-08 14:37
It occurs to me that I also do some special processing for section cross references (to try to shorten the preview)- I might be causing an issue there...

**Comment by harrelfe** [comment] 2023-05-08 22:06
It's hard to say.   You might see something by looking at the rendered chapter: https://hbiostat.org/rflow/sstats.html
I don't see anything weird other than mermaid markup at the front.

**Comment by dragonstyle** [comment] 2023-05-09 13:00
Ok it turns out the issue was a pretty dumb oversight by me - the issue was the fact that the cross references are in books, which allow cross page xrefs. I should've safely walled this off (since we currently rely on being able to fetch the hover preview for xrefs out of the current page) and totally didn't. Should be fixed in our next pre-release build, which I've started (fixed by turning off hover-xrefs automatically for books, so isn't strictly required for you to update).

Thanks for reporting great catch!

**Closed by dragonstyle** 2023-05-09 13:00 UTC
Labels: bug, needs-repro
