### ISSUE TITLE
revealjs does not work with knitr embed engine

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#4712] opened 2023-03-08 20:54 UTC
### Bug description

Using Quarto 1.2.335 (which is included in recent RStudio dailies, including 2023.03.0+385). This problem can be recreated without using the RStudio IDE when rendering using Quarto from the command-line.

Given a `code.R` file:

```r
cat("this is code.R\n")
```

The following revealjs document does not show the embedded code:

````markdown
---
title: embedding with reveal
format: revealjs
engine: knitr
---

## Embed!

```{embed, file = "code.R"}
```
````

<img width="850" alt="image" src="https://user-images.githubusercontent.com/362187/223846591-cbcdd571-c6c3-484e-b323-54ec5e7c6ee6.png">

The generated HTML contains a block, but no code:

```html
<section id="embed" class="slide level2">
<h2>Embed!</h2>
<div class="cell" data-file="code.R">

</div>
<div class="footer footer-default">

</div>
</section>
```

In contrast, when we do not output to HTML, the embedded code is shown.

````markdown
---
title: embedding without reveal
engine: knitr
---

## Embed!

```{embed, file = "code.R"}
```
````

<img width="544" alt="image" src="https://user-images.githubusercontent.com/362187/223846616-9f633a3c-7c00-4bb2-9562-47f3740c15b0.png">

Using the most recent version of knitr from CRAN and R 3.6.3 on macOS 12.6.3.

```bash
R -s -e "packageVersion('knitr')"
#> [1] ‘1.42’
```

Discovered while trying to apply the workaround from https://github.com/quarto-dev/quarto-cli/issues/1237

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by aronatkins** [comment] 2023-03-08 20:56
Have tried both `embed` and `verbatim`.

**Comment by cscheid** [comment] 2023-03-08 21:08
See also #1237.

The reason this isn't working for include specifically is that the include shortcode resolution happens in typescript, before Pandoc. Other shortcodes like meta, var, etc, happen in Lua.

We need to add include processing to Lua in one shape or another, but this is easier said than done. We need to be aware of a number of issues, and it's also going to be the case that a "Lua `{{< include >}}`" will behave differently than a typescript one out of necessity. This is going to be very confusing for users.

**Comment by cderv** [comment] 2023-03-08 22:31
@aronatkins Did you try pre release yet ? 

I can't reproduce with 1.3. From 
````markdown
---
title: embedding with reveal
format: revealjs
engine: knitr
---

## Embed!

```{embed, file = "code.R"}
```
````

I get 

![image](https://user-images.githubusercontent.com/6791940/223865829-8a406a7c-107e-4d08-839b-03eb59c8f01a.png)

But I can reproduce with verbatim. 

Using also knitr 1.42 

Either some adjusments in quarto or something with **knitr** - I can have a look to this @cscheid

**Comment by cderv** [comment] 2023-03-08 23:27
In fact there is something new now since #3429 - v1.3 has added internally a `embed` handler for this feature thttps://quarto.org/docs/prerelease/1.3/embed.html 

For now we pass every cell handlers from quarto to **knitr**
https://github.com/quarto-dev/quarto-cli/blob/5e38e1e9f19868e5dd2cb9ff5773442e35cc71f4/src/resources/rmd/execute.R#L54-L68

This creates a conflict (and why I get something with 1.3 using `embed` on cell with knitr - but wrong output when looking at HTML produced). 

@cscheid @dragonstyle do all the language handler we have are supposed to pass to **knitr** ? Does setting 
````markdown
```{embed}
````
inside a document using knitr computation engine is supposed to be handled by our internal handler, or should we **NOT** overwrite knitr own `embed` engine ? 

I need your input before doing more (I have a fix already for `verbatim` engine, but `embed` knitr engine was not used as I would expect. I understand why now.)

**Comment by cderv** [comment] 2023-03-08 23:58
What I think we should do : `embed` should be filtered out `handledLanguages` to support as knitr's engine for cells

I'll go with that, unless you think otherwise.

**Comment by aronatkins** [comment] 2023-03-09 14:51
In case others find this issue, https://github.com/quarto-dev/quarto-cli/issues/1237 suggested using the https://github.com/quarto-ext/include-code-files extension.

This extension has worked and lets me include code from external files into a Quarto+revealjs presentation.

**Comment by cscheid** [comment] 2023-03-10 17:22
This will be fixed by https://github.com/quarto-dev/quarto-cli/pull/4732

**Closed** 2023-03-10 18:37 UTC
Labels: bug
