### ISSUE TITLE
Quarto render hangs after building website

### ISSUE THREAD

**Issue by zonca** [quarto-dev/quarto-cli#2676] opened 2022-09-30 05:13 UTC
### Bug description

I created a blog based on Quarto and imported about 200 old articles in markdown and Jupyter Notebooks.
It is on Github: https://github.com/zonca/zonca.dev

The problem is that when I run `quarto render`, it builds all the posts, but then hangs, with no error.
The render is actually complete, if I kill it and then publish the website, it looks fine.

I am on Debian GNU/Linux 10 (buster) on a Chromebook, the problem is that I deployed to Netlify following the documentation, and it hangs also there just after building the last post.

Not sure what I could do to understand the issue.

I tried to increase the logging level, but I only get:

```
[219/219] consult.qmd
[INFO] Loaded /tmp/quarto-session1ce7b4a5/989e2697/87ee8d18/template.patched from /tmp/quarto-session1ce7b4a5/989e2697/87ee8d18/template.patched
[INFO] Loaded /tmp/quarto-session1ce7b4a5/989e2697/87ee8d18/metadata.html from /tmp/quarto-session1ce7b4a5/989e2697/87ee8d18/metadata.html
[INFO] Loaded /tmp/quarto-session1ce7b4a5/989e2697/87ee8d18/title-block.html from /tmp/quarto-session1ce7b4a5/989e2697/87ee8d18/title-block.html
[INFO] Loaded /tmp/quarto-session1ce7b4a5/989e2697/87ee8d18/title-metadata.html from /tmp/quarto-session1ce7b4a5/989e2697/87ee8d18/title-metadata.html
[INFO] Loaded /tmp/quarto-session1ce7b4a5/989e2697/87ee8d18/toc.html from /tmp/quarto-session1ce7b4a5/989e2697/87ee8d18/toc.html
[INFO] Running filter /opt/quarto/share/filters/quarto-init/quarto-init.lua
[INFO] Completed filter /opt/quarto/share/filters/quarto-init/quarto-init.lua in 11 ms
[INFO] Running filter /opt/quarto/share/filters/authors/authors.lua
[INFO] Completed filter /opt/quarto/share/filters/authors/authors.lua in 11 ms
[INFO] Running filter /opt/quarto/share/filters/quarto-pre/quarto-pre.lua
[INFO] Completed filter /opt/quarto/share/filters/quarto-pre/quarto-pre.lua in 31 ms
[INFO] Running filter /opt/quarto/share/filters/crossref/crossref.lua
[INFO] Completed filter /opt/quarto/share/filters/crossref/crossref.lua in 14 ms
[INFO] Running filter /opt/quarto/share/filters/layout/layout.lua
[INFO] Completed filter /opt/quarto/share/filters/layout/layout.lua in 15 ms
[INFO] Running filter /opt/quarto/share/filters/quarto-post/quarto-post.lua
[INFO] Completed filter /opt/quarto/share/filters/quarto-post/quarto-post.lua in 12 ms
[INFO] Running filter /opt/quarto/share/filters/quarto-finalize/quarto-finalize.lua
[INFO] Completed filter /opt/quarto/share/filters/quarto-finalize/quarto-finalize.lua in 11 ms
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment] 2022-09-30 09:49
Hi, 

First you could try updating to our last pre-release version which would be the most updated one: https://quarto.org/docs/download/

You could see if the issue is still present.

If I understood correctly it hangs locally for a Quarto render and also on Netlify when rendered there ? Thanks for the repo. I'll try to reproduce

**Comment by zonca** [comment] 2022-09-30 14:41
Thanks!
I tested myself under Ubuntu after updating (1.2.171) over (1.1.251) and it works fine.
For Netlify should I just wait for an update of the plugin?

**Comment by cderv** [comment] 2022-09-30 15:35
If this is something that is fixed by the prerelease, you may be able to install it on netlify too by configure the version
https://github.com/quarto-dev/netlify-plugin-quarto#configuration

**Comment by zonca** [comment] 2022-09-30 16:35
thanks, I tried to add `version=` to `netlify.toml` but it gave me a syntax error.

So I tried with the environment variable, but I got another error on Netlify, opened issue at https://github.com/quarto-dev/netlify-plugin-quarto/issues/4

**Comment by dragonstyle** [comment] 2022-10-07 16:22
I think we're safe to close this since the pre-release build has fixed this issue (and the Netlify issue is tracked on that repo).

**Closed by dragonstyle** 2022-10-07 16:22 UTC
Labels: bug
