### ISSUE TITLE
New uninformative error when missing syntax

### ISSUE THREAD

**Issue by ElijahMeyer3** [quarto-dev/quarto-cli#6450] opened 2023-08-07 04:14 UTC
The following example is in regards to a change in error message for missing syntax when trying to render a document.

For example, there is missing a : after warning.  

```{{r}}
#| label: plot1
#| warning false
```
An example error in the backround jobs pane used to be the following: 

Scanner error: Scanner error: while scanning a simple key at line 2, column 1 could not find
  expected : at line 3, column 1
  
This was very useful, as it helped students identify what and where the error occured in their document. 

Now, I am getting the following error: 

can not read a block mapping entry; a multiline key may not be an implicit key

This is much less informative. Was this an intended change?

**Comment by jjallaire** [comment] 2023-08-07 11:46
@cscheid Are you aware of anything that would have precipitated this change?

**Comment by cscheid** [comment] 2023-08-11 18:09
It's definitely not an intended change. This is a YAML parse error, which happens before any YAML validation. We have limited control over those error messages but it would be useful to identify what triggered the regression. 

@ElijahMeyer3 can you share a full .qmd file whose behavior regressed? That will help us track down what happened.

**Comment by ElijahMeyer3** [comment] 2023-08-11 22:07
Hey @cscheid 

I can't seem to upload the .qmd file here because it's an unsupported file type. Will you please suggest the best way for me to share the .qmd file? Thank you. 

It's a simple qmd file with the following YAML

---
title: "Demo AE"
author: "insert name here"
format: html
editor: visual
---

I have r code chunks underneath, one of witch has the missing syntax error as stated in the first post.

**Comment by mcanouil** [comment] 2023-08-11 22:36
You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by ElijahMeyer3** [comment] 2023-08-12 16:33
Thank you @mcanouil 

The following short qmd was a demo to show off the informative error when students render a doc and are missing a : (as seen in the last code chunk after warning). The qmd did not change, but the error message did as described above. 

````qmd
---
title: "Demo AE"
author: "insert name here"
format: html
editor: visual
---

For this ae, we'll use the **tidyverse** and **palmerpenguins** packages. 

## Packages

```{r}
#| label: packages

library(tidyverse)
library(palmerpenguins) #The data set name is penguins
```

::: callout-note
Analyzing the a single variable is called **univariate** analysis.
:::

1.  Make a histogram below. Set an appropriate binwidth.

```{r}
#| label: plot1
#| warning false

#insert code here

```


````

**Comment by cscheid** [comment] 2023-08-12 17:13
I've experimented with this. A few observations.

1. The error is more informative than I think you're reporting. What we output is:
   
   ```
   $ quarto render 6450.qmd
   ERROR: YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key (6450.qmd, 27:17)
   26: #| label: plot1
   27: #| warning false
                      ~
   ```

   Now, the highlighting is not perfect, because the error message itself is not pointing to the precise issue. (And that is not something we can control, because it comes from a downstream YAML parser) Still, I think it's close enough to guide the user in the right direction.

2. The same error goes back to at least 1.2. And compared to the error in 1.1, I think the new error is _better_:

   ```
   $ quarto-1.1 render 6450.qmd
   processing file: 6450.qmd
   Error in yaml::yaml.load(meta, handlers = list(expr = parse_only)) :
     Scanner error: while scanning a simple key at line 2, column 1 could not find expected ':' at line 3, column 1
   Calls: .main ... FUN -> parse_block -> partition_chunk -> <Anonymous>
   Execution halted
   ```

   This error has wrong line numbers, and no syntax hint. It does say "could not find expected ':'", but it provides very misleading information. I am fairly confident the new error message is superior.

I'm going to go ahead and close this one; I think we're doing the right thing here.

**Closed by cscheid** 2023-08-12 17:13 UTC
Labels: yaml-validation
