### ISSUE TITLE
Make active tab/section distinguishable in navbar

### ISSUE THREAD

**Issue by batpigandme** [quarto-dev/quarto-cli#1321] opened 2022-05-25 13:10 UTC
Currently, there's no way to tell which "tab" is active in the main navbar. This should be somehow identifiable (e.g. bold or different color).

**Comment by jjallaire** [comment] 2022-08-06 14:53
It looks like we do actually attempt to latch the active nav item here (which amount to adding the `active` class as well as 
setting `aria-current=page`): 

https://github.com/quarto-dev/quarto-cli/blob/main/src/project/types/website/website-navigation.ts#L405-L422

The visual appearance is in turn controlled by these variables:

https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/html/bootstrap/dist/scss/_nav.scss#L74-L79

In the default and cosmo themes (which is what generate from `quarto create-website`) there is no visual distinguisher for `active` however for many other themes there is.

I'm going to close this issue as the system appears to have correct logic for this state (we can then separately debate whether we want to override the bootstrap default for latched visual appearance -- I will say that in a couple of themes I tried it was _very_ subtle, possibly because too heavy a treatment creates more visual noise on the navbar than people want). If it has potential to be overdone and somewhat a matter of taste/preference I'd be more inclined for this to be something resolved by themes/variables rather than a default we set.

**Closed by jjallaire** 2022-08-06 14:53 UTC

**Comment by ecomodeller** [comment] 2024-11-19 12:02
It seems like this feature is broken.

An example from the Quarto gallery is https://nbdev.fast.ai/tutorials/tutorial.html

In this example the `active` class as well as the `aria-current` attribute is set on the "Get started" anchor, instead of the "Tutorial".

```html
<li class="nav-item">
    <a class="nav-link active" href="[../getting_started.html](https://nbdev.fast.ai/getting_started.html)" aria-current="page"> 
<span class="menu-text">Get Started</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="[../tutorials/tutorial.html](https://nbdev.fast.ai/tutorials/tutorial.html)"> 
<span class="menu-text">Tutorial</span></a>
  </li>
```

Is the path `../tutorials/tutorial.html` too complicated?

This is confusing, any hints on a workaround on how to disable this?

In some themes it might not be visually apparent, but I suppose still a problem for accessibility, in some cases it is subtle:
 ![Image](https://github.com/user-attachments/assets/d8e9a646-0a3f-4084-91f4-b937340a64ab)

Mkdocs material uses a more explicit approach to indicate the [current tab](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs-with-tabs)

Example from [FastAPI docs](https://fastapi.tiangolo.com/reference/)
![Image](https://github.com/user-attachments/assets/a13122c8-7f99-49a4-934d-135c33388ae7)

**Comment by mcanouil** [comment] 2024-11-19 13:30
Please open a new issue eventually referencing this one.
Thank you!

**Comment by ecomodeller** [comment] 2024-11-19 14:57
> Please open a new issue following the issue template eventually referencing this one. Thank you!

@mcanouil I have opened a new issue where I have tried to create a minimal reproducible example.

I suspect the sidebar is causing some issue, without the sidebar it works fine.
