### ISSUE TITLE
The right sidebar ToC is having issues detecting headings inside divs

### ISSUE THREAD

**Issue by joelostblom** [quarto-dev/quarto-cli#8059] opened 2023-12-29 03:03 UTC
### Bug description

The right sidebar ToC is having issues detecting headings inside divs if there is any other comment in the div (even just a comment).

### Steps to reproduce

```qmd
## In ToC

## Also in ToC

<div>

<!-- Adding a comment or another div/paragraph inside this div and before the next heading, removes the next heading from the ToC -->

## Not in ToC

</div>

```

### Expected behavior

All the headings in the example above should be detected and included in the ToC

### Actual behavior

The last heading is not included in the ToC

![image](https://github.com/quarto-dev/quarto-cli/assets/4560057/1a8eb394-3a5e-4c7d-a89d-79e22a777746)

### Your environment

- IDE Version: 1.86.0-insider
- OS: Linux x64 6.5.6-76060506-generic

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.58.3: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /home/joel/miniconda3/envs/jl/bin

[✓] Checking basic markdown render....OK
```

**Comment by mcanouil** [comment] 2024-01-01 13:55
Why are you including headings inside a div?
I do not think Quarto should detect something like that as a proper heading.

Also note that you should not use raw html code outside or raw code block `` ```{=html} ``.

What's the use case exactly?

**Comment by cscheid** [comment] 2024-01-02 16:40
The TOC only covers top-level headings, by design. We should document this better, but I'm going to go ahead and close this one. I'm happy to hear more about the use cases, but as it stands, this is not a bug.

**Closed by cscheid** 2024-01-02 16:40 UTC
Labels: bug

**Comment by joelostblom** [comment] 2024-01-02 17:59
I used it to add a page shadow to a specific page only and it works with regular HTML. However, I found a workaround with using a separate csv file for that page only and applying the page shadow to the HTML body instead, so closing this sounds good to me too.

> Also note that you should not use raw html code outside or raw code block ```{=html}.

I regularly use raw HTML, where can I read more about the gotchas I should be aware about in these cases?

**Comment by mcanouil** [comment] 2024-01-02 18:03
Quarto/Pandoc can interfere with text even if it is LaTeX or HTML.
Using raw blocks ensure the code is untouched thus produce the expected output.
