### ISSUE TITLE
"LaTeX Error: File `footnote.sty' not found" on output to PDF

### ISSUE THREAD

**Issue by FloraCanou** [quarto-dev/quarto-cli#4241] opened 2023-02-06 10:53 UTC
### Bug description

```
pandoc 
  to: latex
  output-file: README.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
finding package for footnote.sty
> 1 package to install
> installing mdwtools (1 of 1)
  This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
finding package for footnote.sty

compilation failed- package installation error
LaTeX Error: File `footnote.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.63 \makesavenoteenv
                     {longtable}^^M 

see README.log for more information.
```

Fedora 37
Error is present in both RHEL tarball installations of 1.2.335 and 1.3.154. I'm pretty sure I installed the release correctly. There's no problem with HTML, only PDF. 

Command: 
```
quarto render README.qmd --to pdf
```

The qmd file: 
```
---
format: pdf
---

# Test
Test. 
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment] 2023-02-06 11:21
I tried to reproduce by removing `footnote.sty` on my side. It then did a installation of `mdwtools` like you 
````
> 1 package to install
> installing mdwtools (1 of 1)
  This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
````

It succeeded and document is rendering fine. So can't reproduce 

Which LaTeX distribution are you using ? Are you using Quarto provided TinyTeX ? 
 
Can you check that `mdwtools` is correctly installed for your LaTeX environment ? From you log 

> compilation failed- package installation error

It is possible that it did not go well. If not installed, you can try installing it manually ? Should `tlmgr install mdwtools` with a TeX Live distribution like TinyTeX

**Comment by FloraCanou** [comment] 2023-02-06 11:40
Ok, I did the same thing on Windows 10. The moment it came to that missing file it prompted me to install it as well as a number of other things. After that it rendered smoothly. 

In Fedora there's no prompts. 

I have no idea about TinyTex. 

I believe LaTeX is shipped with the system. 

```
latex --version
```

returns

```
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021)
kpathsea version 6.3.3
```

and some copyright information. 

```
tlmgr info mdwtools
```
returns
```
package:     mdwtools
category:    Package
shortdesc:   Miscellaneous tools by Mark Wooding
longdesc:    This collection of tools includes: support for short commands starting with @, macros to sanitise the OT1 encoding of the cmtt fonts; a 'do after' command; improved footnote support; mathenv for various alignment in maths; list handling; mdwmath which adds some minor changes to LaTeX maths; a rewrite of LaTeX's tabular and array environments; verbatim handling; and syntax diagrams.
installed:   Yes
revision:    15878
sizes:       src: 449k, doc: 2057k, run: 125k
relocatable: Yes
cat-version: 1.05.4
cat-license: gpl
cat-topics:  list-supp notes footnote syntax maths macro-supp table verbatim
collection:  collection-latexrecommended
```

So I think it's installed?

**Comment by cderv** [comment] 2023-02-06 12:06
> So I think it's installed?

It seems installed as I see "installed: Yes". I don't see why it is not found. 

Quarto should use `xelatex` engine by default, you can check if the installation used is correctly the one with this package ? In case you have several on your PATH (`which xelatex` ?)

> I have no idea about TinyTex.

See doc about PDF (https://quarto.org/docs/output-formats/pdf-engine.html)  on how to install TinyTeX. It is a portable distribution of TeX Live (that can live with another system wide installation) - more about [TinyTeX](https://yihui.org/tinytex/)

You can try installing mdwtools manually on Fedora is not done already. Then the rendering should work. Is it ?

**Comment by FloraCanou** [comment] 2023-02-06 17:06
Seems my previous texlive wasn't installed system-wide. I reinstalled it and now i found a number of .sty files in `/usr/share/texlive/texmf-dist/tex/latex/mdwtools`: 
```
at.sty    doafter.sty   mathenv.sty  mdwmath.sty  mTTcmtt.fd  sverb.sty
cmtt.sty  footnote.sty  mdwlist.sty  mdwtab.sty   mTTenc.def  syntax.sty
```
However this time it tells me it's missing another package
```
updating existing packages
finding package for tcolorbox.sty
> 1 package to install
> installing tcolorbox (1 of 1)
  This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
finding package for tcolorbox.sty

compilation failed- package installation error
LaTeX Error: File `tcolorbox.sty' not found.
```
And who knows what other packages are required.

**Comment by cderv** [comment] 2023-02-07 09:03
> So I'm comparing TinyTex with my installation of Texlive. I find texlive-tcolorbox is a separate package, which I have no idea why it's not shipped with Texlive itself. 

If you install using your system package manager, it will be split in several package, but you can install a full version with everything if you want. See here for more on Fedora : https://docs.fedoraproject.org/en-US/neurofedora/latex/

> That's not functioning as intended, I guess.

The automatic installation will work if you are allowed to install in your TeX Live distribution using `tlmgr install`. When using system installation with package manager, this may not be possible (admin right required usually) 

>  wonder if the dev team could provide the files in the release and perhaps make it work out of the box -- or document it in the installation guide that these are required (there's not an installation guide anyway)?

We can't know for sure every packages that users will use in their documents. Quarto won't provide itself such LaTeX package. However, we support and work with TinyTeX for that purpose. Installing TinyTeX with Quarto will install a bundle that contains a set of packages that covers most of the usage. But TinyTeX is available in more flavor https://github.com/rstudio/tinytex-releases/blob/master/README.md 
One of the bundle is a full TeX Live with all CTAN packages, and other will be from minimal to many packages included. 

So TinyTeX offering is our way to respond to this installation problem. 

Hope it helps understand

**Comment by FloraCanou** [comment] 2023-02-07 20:16
> The automatic installation will work if you are allowed to install in your TeX Live distribution using `tlmgr install`. 

Fun fact: as I tried to install stuff thru `tlmgr`, Fedora strongly discouraged me by giving me four whole lines of warnings. So I backed out. 

> So TinyTeX offering is our way to respond to this installation problem.

I see. I wish the documentation would be more clear about it tho, since it's almost a required component to enable this piece of software to function properly. Or if you don't see anything to improve, feel free to close this ticket.

**Comment by cderv** [comment] 2023-02-07 20:54
> Fedora strongly discouraged me by giving me four whole lines of warnings. So I backed out.

Interesting. Possibly that this would mess up the system install if you install TeX Live using package manager in the first place. 

> I see. I wish the documentation would be more clear about it tho, since it's almost a required component to enable this piece of software to function properly. 

We'll take the feedback. We can maybe add some more information about the available bundles and how to install it if the default one is not enough.

**Comment by FloraCanou** [comment] 2023-02-08 10:21
Thanks!

**Comment by cwickham** [comment] 2023-07-13 19:55
I'm going to close this as a documentation issue. It seems like we already quite strongly recommend tinytex, and helping people with unusual setups is perhaps better suited to discussions, rather than trying to address all possibilities in the docs.

**Closed by cwickham** 2023-07-13 19:55 UTC
Labels: documentation

**Comment by albersonmiranda** [comment] 2024-07-28 06:46
_Just for future reference_

As OP pointed out, Fedora will deny package install via `tlmgr`, that's why if fails. It [recommends to install individual packages via package manager](https://docs.fedoraproject.org/en-US/neurofedora/latex/):

```
# example
sudo dnf install 'tex(beamer.cls)'
sudo dnf install 'tex(hyperref.sty)'
```

Or just install the whole thing with `sudo dnf install texlive-scheme-full`.

IMHO, Tinytex saves us from the struggle that is tex installation on Windows and Debian based Linux distros. But that's not the case for Fedora. Since Fedora's package manager solves it, I'd say that for Fedora users it's preferable to keep just one tex installation (the one already shipped in it) than mantain tinytex alongside it.

The only issue for me here is that Quarto fails silently, meaning that aforementioned warnings only shows when the user calls `tlmgr`. It should shows when Quarto fails to render.
