### ISSUE TITLE
When rendering html from ipynb, plotly charts render only with plotly<=5.11, otherwise the html is truncated

### ISSUE THREAD

**Issue by paniterka** [quarto-dev/quarto-cli#5867] opened 2023-06-09 22:07 UTC
### Bug description

I have problems rendering html documents from ipynb notebooks when using plotly newer than 5.11. 

The issue exists when using `execute: true`, but also when using notebooks with frozen computations. In the second case, what matters is the plotly version in the environment used to generate the frozen output of the notebook. 

Until plotly==5.11, everything works fine. When using plotly==5.12 or newer (currently 5.15), the **html document is truncated until the cell rendering the plotly chart**, so the front matter as well as the cell ouptuts preceding the chart are missing. 

I have stored the necessary files here: https://github.com/paniterka/2023-quarto-plotly-bug You will find there a notebook with all the output cleared, the same notebook generated with 2 different plotly versions and respective html files, generated from the notebook using Quarto. 

### Steps to reproduce

https://github.com/paniterka/2023-quarto-plotly-bug 

### Expected behavior

The documents created using newer plotly versions should be rendered correctly. 

### Actual behavior

Some content is not rendered. 

### Your environment

Jupyter Notebook 6.0.3
Win 10 Pro 
Python 3.8.10 (main Jupyter env), Python 3.9 (env used to generate notebooks). 

### Quarto check output

```
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.361
      Path: C:\Users\tt\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.8.10 (Conda)
      Path: C:/APPS/Anaconda3/python.exe
      Jupyter: 4.10.0
      Kernels: quarto39, sharepoint39, streamlit39, python3, dashenv 

[>] Checking Jupyter engine render....OK

(\) Checking R installation...........During startup - Warning message:
Setting LC_CTYPE=en_US.UTF-8 failed
[>] Checking R installation...........OK
      Version: 4.1.2
      Path: C:/Users/tt/Documents/R/R-4.1.2
      LibPaths:
        - C:/Users/tt/Documents/R/R-4.1.2/library
      knitr: 1.37
      rmarkdown: 2.11

[>] Checking Knitr engine render......OK
```

**Comment by paniterka** [comment] 2023-07-15 10:57
Hi @cscheid, I have been wondering, is there any update on this? Have you been able at least to replicate the problem? Thanks in advance for the answer :)

**Comment by cscheid** [comment] 2023-07-15 11:16
I can't reproduce your issue, and I suspect your problem is the `kernel: quarto39` line in your YAML. I don't know what that is, and I had to remove it in order to be able to run your notebook. Once I did, `quarto render FILE.ipynb --execute`, things worked fine:

<img width="422" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/2d16b1aa-bbd4-425b-b3c5-6bc81fe0a4b5">

**Comment by mcanouil** [comment] 2023-07-15 11:21
I can't reproduce either.

https://github.com/quarto-dev/quarto-cli/assets/8896044/19d0996c-cdca-49f4-9585-8ea070a39b49

**Comment by paniterka** [comment] 2023-07-15 12:00
Thanks for getting back! This is interesting. I wonder if it has anything to do with my Jupyter version combined with plotly version. If you look at the two ipynb files in the repo, they are not 1-to-1 the same. Are yours? And before I nuke my Jupyter installation, could you share what is your Jupyter configuration? 

Ps `quarto39` is just a venv kernel that contains the libraries that the kernel needs to produce the content, I did it to isolate it from my main kernel.

**Comment by mcanouil** [comment] 2023-07-15 13:57
Our setup (at least mine) is the default.
If you do exotic things in your setup, you are basically on your own.
I simply created a virtual env with Python3.9 restore your libraries, install what was missing (nbclient, jupyter) and it just works (I had to execute the notebooks to erase the cache in it).
So I am pretty sure your issue has nothing to do with Quarto itself.

**Comment by paniterka** [comment] 2023-07-15 14:12
There is nothing exotic in what I am doing to be honest, it is a pretty standard setup which is used by many people working with Python. It seems that my version of jupyter is generating 2 different ipynb files depending on the plotly version and Quarto has a problem with parsing one of them. Thanks for checking anyway - I will try debugging it further on my own and let you know my findings later on.

**Comment by mcanouil** [comment] 2023-07-15 14:15
Well the fact that your Jupyter Notebook asks for `jupyter: quarto39` as kernel is definitely not a default setup.

**Comment by paniterka** [comment] 2023-07-15 15:28
Sure, I stored two rendered html files in the repo alongside the ipynb files, you can find the link to the repo in the first post. 

Would you mind running `pip freeze` in your config and letting me know which jupyter and jupyter notebook versions have you used? It would be very helpful.

**Comment by mcanouil** [comment] 2023-07-15 16:09
The latest version of Jupyter and nbclient modules.

**Comment by cscheid** [comment] 2023-07-15 17:47
Both of these were generated from a fresh virtualenv, on Python 3.10.10 and 3.11.4.

### from `requirements_plotly5-15.txt`:

```
appnope==0.1.3
asttokens==2.2.1
attrs==23.1.0
backcall==0.2.0
comm==0.1.3
contourpy==1.1.0
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
executing==1.2.0
fastjsonschema==2.17.1
fonttools==4.41.0
ipykernel==6.23.1
ipython==8.14.0
jedi==0.18.2
jsonschema==4.18.3
jsonschema-specifications==2023.6.1
jupyter_client==8.3.0
jupyter_core==5.3.1
kiwisolver==1.4.4
matplotlib==3.7.1
matplotlib-inline==0.1.6
nbclient==0.8.0
nbformat==5.9.0
nest-asyncio==1.5.6
numpy==1.24.3
packaging==23.1
pandas==2.0.2
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.8.1
plotly==5.15.0
prompt-toolkit==3.0.39
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.15.1
pyparsing==3.1.0
python-dateutil==2.8.2
pytz==2023.3
pyzmq==25.1.0
referencing==0.29.1
rpds-py==0.8.10
seaborn==0.12.2
six==1.16.0
stack-data==0.6.2
tenacity==8.2.2
tornado==6.3.2
traitlets==5.9.0
tzdata==2023.3
wcwidth==0.2.6
```

### from `requirements_plotly5-11.txt`:

```
appnope==0.1.3
asttokens==2.2.1
attrs==23.1.0
backcall==0.2.0
comm==0.1.3
contourpy==1.1.0
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
executing==1.2.0
fastjsonschema==2.17.1
fonttools==4.41.0
ipykernel==6.23.1
ipython==8.14.0
jedi==0.18.2
jsonschema==4.18.3
jsonschema-specifications==2023.6.1
jupyter_client==8.3.0
jupyter_core==5.3.1
kiwisolver==1.4.4
matplotlib==3.7.1
matplotlib-inline==0.1.6
nbclient==0.8.0
nbformat==5.9.0
nest-asyncio==1.5.6
numpy==1.24.3
packaging==23.1
pandas==2.0.2
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.8.1
plotly==5.11.0
prompt-toolkit==3.0.39
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.15.1
pyparsing==3.1.0
python-dateutil==2.8.2
pytz==2023.3
pyzmq==25.1.0
referencing==0.29.1
rpds-py==0.8.10
seaborn==0.12.2
six==1.16.0
stack-data==0.6.2
tenacity==8.2.2
tornado==6.3.2
traitlets==5.9.0
tzdata==2023.3
wcwidth==0.2.6
```

**Comment by paniterka** [comment] 2023-07-15 22:23
Thank you! For the reference, the respective jupyter-related versions in my base environment which hosts the Jupyter notebook (not the kernel used to evaluate the computations) are listed below (and they are indeed a bit outdated). It sounds the reason could be a weird combination of plotly+jupyter which silently produces ipynb which is not digestable by Quarto for documents rendered using newer plotly versions. I have never had problems with my ipynb files otherwise, neither with any other Quarto documents (which did not include plotly) generated out of them. Once I know more, I'll let you know. 

```
ipykernel==5.3.4
ipython==8.3.0
jupyter-client==6.1.12
jupyter-core==4.10.0
nbclient==0.5.13
nbconvert==6.4.4
nbformat==5.1.3
```

Regarding the truncation, here is the screenshot from the malformatted file (where plotly 5.15 was used). The html starts only after the cell containing the plotly chart and the blocks are missing from the rendered DOM as well. 

![image](https://github.com/quarto-dev/quarto-cli/assets/35473115/5840c418-a174-4778-aba9-fb37e8aec707)

**Comment by cscheid** [comment] 2023-07-16 11:03
`nbclient==0.5.13` This is a very old version that has a number of other bugs. You do need to keep your Python environment up-to-date; updating only some libraries is a recipe for trouble. I'm going to go ahead and close this one.

**Closed by cscheid** 2023-07-16 11:03 UTC
Labels: bug, needs-repro, jupyter, plotly

**Comment by paniterka** [comment] 2023-11-19 22:38
Hi @cscheid , 

I am resurrecting this issue as I have recently had an opportunity to try this with the clean installation of Python+Jupyter, and the issue still persists. 

I have changed the `.ipynb` slightly to include your comments: 
```
---
title: A beautiful report
subtitle: With a plotly bug
toc: true
format:
  html:
    code-fold: false
    echo: true
    embed-resources: true
execute:
  enabled: false
jupyter: python3
---
```

What I am doing now is: 
- install a clean Anaconda installation `Anaconda3-2023.09-0-Windows-x86_64.exe` 
- install Quarto `quarto-1.3.450-win.msi` 
- upgrade plotly `pip install --upgrade plotly`, since the Anaconda ships with plotly 5.8 
- run the problematic notebook in Jupyter, save the file with outputs 
- run `quarto preview` on a resulting file 

Consistently, with plotly <=5.11 it works as expected, and with plotly above 5.11 it breaks the resulting html. I updated `nbclient` and `jupyter_client` with pip as well and it didn't fix the issue. I thought that my previous installation was utterly broken, since I couldn't get it to work even after I updated the packages as you suggested, but now I have reproduced the same behavior on two different laptops (both Windows 10). With the current procedure, you cannot get less standard, it is really just installing Anaconda, Quarto and upgrading plotly. Would you mind taking another look into it?

**Comment by mcanouil** [comment] 2023-11-19 23:45
@paniterka Could you try the 1.4 pre-release version?

**Comment by paniterka** [comment] 2023-11-20 09:50
I installed `quarto-1.4.506-win.msi` and still getting truncated output. This happens both for frozen ipynb as well as qmd set to execute. Attached you can find the notebooks and rendered html files, as well as my python environment (it's pure Anaconda with upgraded `plotly`, `nbclient`, `jupyter_client` and `jupyter_contrib_nbextensions`). Thank you for looking into this! 
[quarto_plotly_newinst.zip](https://github.com/quarto-dev/quarto-cli/files/13412250/quarto_plotly_newinst.zip)

**Comment by cscheid** [comment] 2023-11-20 18:13
I remain unable to repro. Note that I commented out the lines about changing `pio.renderers.default`:

<img width="419" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/32620387-1b8b-4401-8175-f90dbda7bfe4">

Note, also, that quarto sets that value by default: https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/jupyter/lang/python/setup.py#L35. `plotly-connected` is taken from `execute.plotly-connected`, which by default is false.

**Comment by paniterka** [comment] 2023-11-20 22:13
This is so weird, thank you for checking. Are you on Windows as well?

**Comment by cscheid** [comment] 2023-11-20 22:14
I'm not.
