### ISSUE TITLE
Make it easier to make customized callouts

### ISSUE THREAD

**Issue by EspenRosenquist** [quarto-dev/quarto-cli#8930] opened 2024-02-29 12:28 UTC
https://github.com/quarto-dev/quarto-cli/blob/47b869c8015849ea7854d83f652f564aa8b3eeab/src/resources/filters/customnodes/callout.lua#L21

Hi. 
I've been trying to create a custom callout box instead of restyling the current supplied ones. It was harder than I thought and no matter the ways I tried and the examples I followed, e.g. [Define a new callout in Quarto](https://stackoverflow.com/questions/74647399/define-a-new-callout-in-quarto). 

I know how to make changes to common elements in all callout-boxes and how to restyle an existing class, but I cannot figure out how to make a new callout that is structually and stylistically identical to the predefined styles. Blame my lack of knowledge in SCSS/CSS perhaps.

It has been a frustrating fight and I have given up now. I will reuse `callout-note` - simply just restyle it. But calling a baby by another name is no good for neither the baby or the parents. I know I can style the callouts, but that means a lot of repetitions and error-prone typing. 

I also notice there is a function in this referenced file: 

```
function isCallout(class)
  return class == 'callout' or class:match("^callout%-")
end
```

Which led me to believe that Quarto would pick up a clue if I inserted a block thus:

```
::: {.callout-def}
# A header

Some content
:::
```

I made a class in SCSS and tried to replace styling elements: 
 ```{scss}
 .callout-def {
    border-left: 5px solid $PMS293_60 !important;

    .callout-header {
        // some transparency
        background-color: rgba($PMS293_60, 0.2) !important;
  }
}
```
However, the only way I could get the callout to be a subclass of class callout, was if I did this:

```
::: {.callout-def .callout-note}
```

Then I had trouble getting the icon to show and no matter what I do it seems to butt up against the fact that the pre-defined styles are the ONLY ones that gets the callout-treatment. It is a lot of work to get my own callout to be styled in the same manner as all the others, and the class will still be "level1" or something or the other if I just reference `.callout-def` in my styling block as shown above.

So, would it be possible to not have the predefined classes hardcoded in this lua-script and instead read in a list from a user-provided YAML or the sorts? I know I can clone this repo and manipulate everything to my need, but a) I have NO clue about lua and b) I want to be a end user and c) think that most authors/content creators are the same. :)

I LOVE what Quarto tries to achieve.

**Comment by cderv** [comment] 2024-02-29 15:47
Could be a duplicate of 
* https://github.com/quarto-dev/quarto-cli/issues/844

**Comment by cscheid** [comment] 2024-06-05 18:04
Yes, this really is a duplicate of #844.

**Closed by cscheid** 2024-06-05 18:04 UTC
Labels: enhancement, callouts
