### ISSUE TITLE
Mermaid diagrams not rendering when unrelated `<img>` tag has unknown host

### ISSUE THREAD

**Issue by QSmally** [quarto-dev/quarto-cli#5387] opened 2023-05-02 19:48 UTC
### Bug description

I've been working on a presentation at my job with a `http://myserver.local:8000/` being on the local network. The presentation includes Mermaid diagrams, and when the demo URL isn't available (whilst at home), the diagrams don't render.

My workspace is a Docker container with Quarto cloned, in previewing mode, with Vim as editor (no plugin installed).

**Environment**:

* Host MacOS `13.3.1` (x86)
* Docker `python:3.8` (Debian I believe)
* `CMD ["quarto", "preview", "/Content", "--port", "8000", "--host", "0.0.0.0", "--timeout", "0", "--no-browser"]`
* `jupyter matplotlib plotly` through pip

**Quarto check**:

```bash
$ docker exec keynote-presentation-1 quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Service/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.16
      Path: /usr/local/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Minimum working example**:

````md
---
title: "foo"
format:
  revealjs:
---

## My Mermaid slide

```{mermaid}
flowchart LR
  A --> B
  B --> A
```

## My img slide

<img src="http://myunreachableserver.local:8000/">
````

Commenting out the `<img>` tag will render the diagram instead of it echoing its declaration.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment] 2023-05-02 20:06
Thanks for the report. Can you make sure you're posting the actual contents of your file. I see a typo there that makes it so the file won't render, and I want to make sure there's no other typos before diving in.

```
$ quarto render 5387.qmd
ERROR: Validation of YAML front matter failed.
ERROR: (line 4, columns 3--11) Field "revealjs" has empty value but it must instead be an object
3: format:
4:   revealjs:
            ~
5: ---
```

**Comment by cscheid** [comment] 2023-05-02 20:11
In any case, I am fairly sure this is not a bug.  What's happening is that with a badly-resolving domain, your browser doesn't emit the "page loaded" event, and so we don't know that the HTML is ready for processing. If you wait for the "resolving host" message to go away, you will then see both a broken image in your "img slide", and a resolved mermaid diagram.

I'm going to go ahead and close this one.

**Closed by cscheid** 2023-05-02 20:11 UTC
Labels: bug, needs-repro

**Comment by QSmally** [comment] 2023-05-02 20:16
> The squiggle is positioned slightly off: the error is saying you can't have a colon after `revealjs`.

I forgot I was in a Quarto workspace and added the details as such.

> In any case, I am fairly sure this is not a bug. What's happening is that with a badly-resolving domain, your browser doesn't emit the "page loaded" event, and so we don't know that the HTML is ready for processing. If you wait for the "resolving host" message to go away, you will then see both a broken image in your "img slide", and a resolved mermaid diagram.

Thanks for the explanation of the situation!
