### ISSUE TITLE
Can't control the render order on GitHub Actions ubuntu-latest

### ISSUE THREAD

**Issue by eculler** [quarto-dev/quarto-cli#10463] opened 2024-08-05 05:40 UTC
### Bug description

I am having this problem as well on GitHub Actions with the ubuntu-latest runner, despite:

- listing files individually in project/render and
- Numbering the files so that alphanumeric order should be the correct one

The render runs as expected on my system (MacOS Sonoma 14.5).

I need the notebooks to render in order, because they use jupyter storemagic to carry variables over from one to the next.

### Steps to reproduce

My project has the following in _quarto.yml:

```{markdown
project:
  render:
    - pages/03-git-github/02-github-collaboration/02-pull-requests.qmd
    - notebooks/01-climate/climate-31.qmd
    - notebooks/01-climate/climate-32.qmd
    - notebooks/01-climate/climate-33.qmd
    - notebooks/01-climate/climate-34.qmd
```

### Expected behavior

I expect the files to be run in the order they appear in the render list, or the order they appear in the table of contents, or in alphabetic order. As it is, the run order seems to be entirely unpredictable and depends on the system.

### Actual behavior

the actual run order in my project on GitHub Actions ubuntu-latest runner is:
    - notebooks/01-climate/climate-31.qmd
    - pages/03-git-github/02-github-collaboration/02-pull-requests.qmd
    - notebooks/01-climate/climate-33.qmd
    - notebooks/01-climate/climate-32.qmd
    - notebooks/01-climate/climate-34.qmd

### Your environment

- GitHub Actions ubuntu-latest runner
- quarto installed with quarto-actions/setupv2 in an activated conda environment

### Quarto check output

Run quarto check
  
Quarto 1.4.557
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.12: OK
      Dart Sass version 1.58.3: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.557
      Path: /usr/share/miniconda/envs/learning-portal/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)
(|) Checking basic markdown render....
[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.14 (Conda)
      Path: /usr/share/miniconda/envs/learning-portal/bin/python
      Jupyter: 5.7.2
      Kernels: ir, python3
(|) Checking Jupyter engine render....
[✓] Checking Jupyter engine render....OK
(|) Checking R installation...........
[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /usr/share/miniconda/envs/learning-portal/lib/R
      LibPaths:
        - /usr/share/miniconda/envs/learning-portal/lib/R/library
      knitr: 1.48
      rmarkdown: 2.27
(|) Checking Knitr engine render......
[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment] 2024-08-05 13:51
- https://github.com/quarto-dev/quarto-cli/discussions/6944

Tracked:

- https://github.com/quarto-dev/quarto-cli/issues/6518

**Comment by allefeld** [comment] 2024-08-10 19:33
This is a duplicate of #10490.

@mcanouil: Yes, the official support will come with the epic execution planner, but previously listing files explicitly in `project / render` was a workaround. This workaround now stopped working.

**Comment by mcanouil** [comment] 2024-08-10 20:23
I know but a workaround is a workaround.
There was/is/will be no guarantee with workarounds.

Relying on workarounds is never something to be done.

**Comment by allefeld** [comment] 2024-08-10 20:32
The problem is that I need to be able to control the order for an existing project, and the execution planner is still in the medium to far future.

Is it a legitimate solution in the current situation (to avoid the term "workaround") to render from a shell script, where the script calls `quarto render <file>` for each file in sequence?
Does `quarto render` for a project do something different than `quarto render <file>` for all the render targets in the project?

**Comment by mcanouil** [comment] 2024-08-10 20:42
To be clear, I never said it's not issue or not a bug.
I am only saying that all this comes in a more global implementation.
Now, whether or not it's a bug or not that the "documented workaround" stopped working, I cannot say this the fact that the issue is opened and not assigned to anyone or any milestone.

There are no arguing about the need to be able to have ordered rendering.

**Comment by allefeld** [comment] 2024-08-10 20:44
I understand.

Could you please comment on my approach to control rendering from a shell script? Should that work?

**Comment by cscheid** [comment] 2024-08-15 15:37
Just to repeat from a slightly more official source, Quarto doesn't promise control of rendering order. The robust solution is to use a pre-render script to produce all necessary inputs before the files are rendered. We understand that this isn't ideal, but we truly can't fix this right now given the rest of our workload.

**Comment by allefeld** [comment] 2024-08-15 18:33
@cscheid, I'm not asking you to completely overturn your work plan or take on additional work, but for a bit of practical advice for a concrete problem I need to solve.

Regarding producing the necessary inputs before – the thing is that the code which creates those inputs is in the form of `qmd` files, which can't be run from pre-render scripts (I think?).

What I'm currently doing is not have a pre-render script called from Quarto, but a render script calling Quarto, for all `qmd` files separately in order. So instead of
```bash
quarto render <folder>
```
I do 
```bash
quarto render <folder>/<file1.qmd>
quarto render <folder>/<file2.qmd>
…
```
That seems to be working okay, except that I don't get sidebar contents in the main `index.md` rendering, but that may be an unrelated issue.

Could you please comment whether that is a reasonable approach, or whether there are any drawbacks to it?

**Comment by cscheid** [comment] 2024-08-15 18:43
> That seems to be working okay, except that I don't get sidebar contents in the main index.md rendering, but that may be an unrelated issue.

It's hard to have a discussion without a reprex around it. Can you create one first?

**Comment by allefeld** [comment] 2024-08-15 18:56
I'll investigate the sidebar issue, and if it points to a problem with Quarto I'll create an issue incl. reprex.

But my question is about the general behavior of `quarto render`. Say I have a Quarto project with the following structure:

```
folder/
folder/quarto.yml
folder/index.md
folder/file1.qmd
folder/file2.qmd
```

can I expect the result of

```bash
quarto render folder/index.md
quarto render folder/file1.qmd
quarto render folder/file2.qmd
```

to be identical to the result of

```bash
quarto render folder
```

(apart of course from enforcing order)?

If yes, I then I have a usable workaround to ensure order of rendering.

**Comment by willgryan** [comment] 2024-09-04 15:46
> Just to repeat from a slightly more official source, Quarto doesn't promise control of rendering order. The robust solution is to use a pre-render script to produce all necessary inputs before the files are rendered. We understand that this isn't ideal, but we truly can't fix this right now given the rest of our workload.

A report generation system that can't control the order of the report it generates?

**Comment by mcanouil** [comment] 2024-09-04 16:03
@willgryan what is the purpose of your comment exactly as it brings nothing to the discussion?! Please, be mindful in your comments.


> [!WARNING]
> As a member of the Quarto community, you are expected to follow our Code of Conduct, which outlines the standards of behavior and communication that we value. The Code of Conduct applies to all online interactions within the Quarto project, and it is enforced by the Quarto team. By participating in the Quarto community, you agree to abide by the Code of Conduct and respect the rights and dignity of others. You can find the Code of Conduct at <https://github.com/quarto-dev/quarto-cli?tab=coc-ov-file#readme>.
> 
> Thank you for your cooperation and contribution. 🙏

**Comment by willgryan** [comment] 2024-09-04 16:10
> @willgryan what is the purpose of your comment exactly as it brings nothing to the discussion?! Please, be mindful in your comments.
> 
> Warning
> 
> As a member of the Quarto community, you are expected to follow our Code of Conduct, which outlines the standards of behavior and communication that we value. The Code of Conduct applies to all online interactions within the Quarto project, and it is enforced by the Quarto team. By participating in the Quarto community, you agree to abide by the Code of Conduct and respect the rights and dignity of others. You can find the Code of Conduct at https://github.com/quarto-dev/quarto-cli?tab=coc-ov-file#readme.
> 
> Thank you for your cooperation and contribution. 🙏

Hi 🙂 Thanks for the prompt reply now on this pressing issue! To be clear, I'm asking what is the meaning of promising control of rendering order? In what way can rendering order be controlled?

**Comment by AliSajid** [comment] 2024-09-04 17:31
I want to emphasize that the precise ordering is not something we have thought about in a vacuum. It is something found on the official website.

[This is a link to the section](https://quarto.org/docs/projects/quarto-projects.html#render-targets). The relevant section is paragraph after the numbered list. [Here is the archived link](https://web.archive.org/web/20240827135408/https://quarto.org/docs/projects/quarto-projects.html#render-targets). I'm also copying the relevant section with emphasis mine.

> If you don’t want to render all of the target documents in a project, or **you wish to control the order of rendering more precisely**, you can add a project: render: [files] entry to your project metadata


@mcanouil 

> I know but a workaround is a workaround. There was/is/will be no guarantee with workarounds.
> 
> Relying on workarounds is never something to be done.
> 
> Edit: as there is a brief mention in the documentation, it's possible that the "workaround" was at some some point considered a feature which would make this a regression from previous versions.

I'm sorry, but this comes across as disingenuous. Even if there were an offhand mention in the documentation, the @quarto-dev team would be responsible for it. However, this is an explicit declaration of a way to use `quarto`.


> I know but a workaround is a workaround.
> There was/is/will be no guarantee with workarounds.

This, again, is disingenuous.

If we cannot trust official documentation on the project's website, what should we do? This feature has been broken for quite some time since the first release of [v1.5.0](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.5.0) was in January. The documentation should have been updated to reflect that.

**Comment by mcanouil** [comment] 2024-09-04 17:50
@AliSajid when quoting, please try to avoid quoting twice the same thing while making a judgment and don't ignore the exact thing you are saying, i.e., that it was in the documentation.

> Edit: as there is a brief mention in the documentation, it's possible that the "workaround" was at some some point considered a feature which would make this a regression from previous versions.

Clearly this considers it might be a "regression" thus a bug.

At no point, the request to have the ability to control render order was considered a weird idea or an invalid use case or this issue would not even be open anymore.

I would kindly ask you to avoid making judgments and assumptions here as it does not serve any positive purpose. Thank you!

**Comment by AliSajid** [comment] 2024-09-04 17:58
Thank you for acknowledging that this is a bug. I'll go ahead and open a separate bug report.

**Comment by willgryan** [comment] 2024-09-04 18:14
Render target control is a documented feature for over 2 years: https://github.com/quarto-dev/quarto-web/commit/936e9b99ffe4f9ed80ac78b05bc39e3839619354

**Comment by cderv** [comment] 2024-09-04 19:15
Thanks @AliSajid for your input. 

I suggest we work on this problem based on your new issue containing clear instructions on how to reproduce and observe the regression. We'll track down what happens with regard to this render list specification order. Then, we'll be able to tell more and take action.

**Comment by cscheid** [comment] 2024-09-05 16:49
> (Note: I decline the Warning, as it was given imprudently and hastily based on contextual misunderstanding, evidenced in later proceedings of these comments)

@willgryan I'm the main maintainer here, and I'm responsible for both enforcing the code of conduct and delegating the responsibility for doing so. "Declining a warning" is not a thing, and @mcanouil's warning was entirely justified based on your comments.

Let me be clear: participation on these forums is a privilege. Do read the code of conduct and adjust your behavior accordingly in future interactions.

**Comment by cscheid** [comment] 2024-10-14 19:33
This is closed by https://github.com/quarto-dev/quarto-cli/pull/11062 and will be in 1.5 and 1.6 releases soon.

**Closed by cscheid** 2024-10-14 19:33 UTC
Labels: enhancement, projects

**Comment by allefeld** [comment] 2024-10-14 19:42
Brilliant, thanks!
