### ISSUE TITLE
Formatting problems with multiple tables

### ISSUE THREAD

**Issue by fisher-j** [quarto-dev/quarto-cli#5956] opened 2023-06-17 00:09 UTC
### Bug description

Including subcabs in a multi-table layout produces cross-refs and well formatted tables.

But omitting subcabs leaves the cross-ref unresolved *and* horizontal scroll-bars on the tables where there wasn't previously.

### Steps to reproduce

````qmd
---
title: results
format: html
---

Refer to @tbl-fenced.

```{r}
#| label: tbl-fenced
#| tbl-cap: "Two tables"
#| layout-ncol: 2

gt::gt(mtcars[1:10, ])
gt::gt(mtcars[11:19, ])
```
````

### Expected behavior

Multi-table layout should have a cross-ref even if it lacks `tbl-subcap`s and tables should not have horizontal scroll bars.

### Actual behavior

The cross ref is not resolved, and the tables have horizontal scrollbars

### Your environment

- Neovim 0.10
- Windows 10 (19044)

### Quarto check output

```
C:\Users\walki\Desktop>quarto check
A new release of Deno is available: 1.28.2 → 1.34.3 Run `deno upgrade` to install it.

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.361
      Path: C:\Users\walki\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: C:/Users/walki/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.3.0
      Kernels: ir, python3

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/walki/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.1/library
      knitr: 1.42
      rmarkdown: 2.21

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment] 2023-06-17 02:16
This usage mode is currently not supported in quarto. I'm reluctant to characterize this as a bug. You provided two tables: which of them do you expect the crossref `@tbl-fenced` to refer to? Quarto currently expects the content of a table crossref to be specifically a single table.

With that said, we're currently redoing the crossref infrastructure, and it will be possible to "lie" to the crossref system about the content of your cross-referenceable artifacts. See https://github.com/quarto-dev/quarto-cli/issues/4944 for a full set of new features. i'm going to go ahead and close this as a duplicate of that.

**Closed by cscheid** 2023-06-17 02:16 UTC
Labels: duplicate

**Comment by fisher-j** [comment] 2023-06-17 03:28
My use case involves splitting a long (skinny) table into two columns to
make it more readable. This is not straight forward with data formatting,
as it's not super super straight forward to format a data frame with
duplicate column names. I think this kind of formatting is best done at the
page layout stage, especially because of the desirable result that the
content becomes responsive too different screen sizes.

I hear that this may be achievable after the cross ref overhaul, and I look
forward to trying it out.

Thanks for your help.

**Comment by mcanouil** [comment] 2023-06-17 03:39
Because you are using `gt`, why not use pagination?
See <https://gt.rstudio.com/reference/opt_interactive.html>.

**Comment by fisher-j** [comment] 2023-06-17 03:56
Yes, I considered using an interactive table. And I actually wasn't aware
of that gt feature, thanks!

The idea though was to maximize screen real estate in spite of my data's
long skinny format.

**Comment by rich-iannone** [comment] 2023-06-17 13:01
@fisher-j just to provide options for you (totally outside of anything Quarto), you can indeed use an interactive table with `opt_interactive()` or even go with a static table and set the container height (an option inside of `tab_options()`). The former might be preferable given that gt doesn’t have a fixed headers feature yet.
