### ISSUE TITLE
fig-cap-location not respected in revealjs presentations

### ISSUE THREAD

**Issue by rmflight** [quarto-dev/quarto-cli#9732] opened 2024-05-21 15:24 UTC
### Bug description

When inserting figures into a revealjs presentation, `fig-cap-location` is only respected if there are columns in the slide.

Persists in quarto-cli 1.5.37.

### Steps to reproduce

````
---
title: "Example Presentation"
author: "Robert M Flight"
date: "2024-05-23"
fig-cap-location: top
format: 
  revealjs
---

## A plot

- with some text

```{r}
#| label: fig-a-plot
#| fig-cap: Just a caption.
#| fig-cap-location: top
library(ggplot2)
data(mtcars)

p = mtcars |>
  ggplot(aes(x = disp, y = mpg)) +
  geom_point()
p
```

## Another plot

:::: {.columns}

::: {.column}
- with columns
:::

::: {.column}

```{r}
#| label: fig-a-plot2
#| fig-cap: Just a caption.
library(ggplot2)
data(mtcars)

p = mtcars |>
  ggplot(aes(x = disp, y = mpg)) +
  geom_point()
p
```
:::

::::

## A third

:::: {.columns}

::: {.column}
- with columns
:::

::: {.column}

```{r}
#| label: fig-a-plot3
#| fig-cap: Just a caption.
#| fig-cap-location: bottom
library(ggplot2)
data(mtcars)

p = mtcars |>
  ggplot(aes(x = disp, y = mpg)) +
  geom_point()
p
```
:::

::::

````

### Expected behavior

If `fig-cap-location` is set, I expect it to be respected for all plots.

### Actual behavior

Only those plots that are embedded in a `{.column}` have the caption in the correct location

### Your environment

- IDE: RStudio 2024.04.1+748
- OS: Linux Pop!OS 22.04 (Ubuntu based)

### Quarto check output

Quarto 1.4.554
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.554
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/rmflight/.TinyTeX/bin/x86_64-linux
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

(/) Checking R installation...........→ R version 4.3.0 (2023-04-21)
→ Running under Pop!_OS 22.04 LTS
(|) Checking R installation...........→ System time is 2024-05-21 11:16:17.433572
[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /rmflight_stuff/software/R-4.3.0
      LibPaths:
        - /rmflight_stuff/software/R-4.3.0/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment] 2024-05-21 15:33
Thanks!

Duplicate of #8938

**Closed by mcanouil** 2024-05-21 15:33 UTC
Labels: bug
