### ISSUE TITLE
revealjs: code-overflow=wrap does not work with code-line-numbers=true

### ISSUE THREAD

**Issue by skwde** [quarto-dev/quarto-cli#10309] opened 2024-07-17 04:26 UTC
### Bug description

When `code-line-numbers=true`, `code-overflow="wrap"` is ignored.

<img width="1491" alt="Screenshot 2024-07-17 at 06 25 26" src="https://github.com/user-attachments/assets/ecb09aec-29c7-4050-8706-68e7d3e971fa">
vs 
<img width="1479" alt="Screenshot 2024-07-17 at 06 25 55" src="https://github.com/user-attachments/assets/f24a94cd-4ee6-4983-acec-3f0711e43fde">

### Steps to reproduce

Use 

````qmd
---
format: revealjs
---


```{.shell code-line-numbers=false code-overflow="wrap"}
test test test test test test test test test test test test test test test test test test test
```
````

### Expected behavior

Properly wrap long lines (`code-overflow="wrap"`) even when code line numbers (`code-line-numbers=true`) are enabled.

### Actual behavior

No wrapping is done when `code-line-numbers=true`

### Your environment

- VScode 1.91.1
- Debian bookworm in devcontainer

### Quarto check output

```bash
# quarto check
Quarto 1.5.54
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.54
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /root/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.4 (Conda)
      Path: /opt/conda/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

```

**Comment by mcanouil** [comment] 2024-07-17 05:44
Duplicate of https://github.com/quarto-dev/quarto-cli/issues/3442

**Closed** 2024-07-17 05:45 UTC
Labels: duplicate

**Comment by mcanouil** [comment] 2024-07-17 05:47
I marked this as duplicate as it's really linked to the other issue and could probably be fixed at the same time.
