### ISSUE TITLE
Table caption not displayed for data.frame or tibble

### ISSUE THREAD

**Issue by sda030** [quarto-dev/quarto-cli#6458] opened 2023-08-07 20:36 UTC
### Bug description

I was not able to find a registered issue for this (obvious) bug, nor in the long [CrossRef Overhaul list](https://github.com/quarto-dev/quarto-cli/issues/4944). 
Basically, table caption only shows for kable, paged, etc, and not for data.frame (default) or tibble. Same for `df-print:` as for simplest example (seen below).

### Steps to reproduce

```` qmd
---
format: html
---


```{r}
#| label: tbl-tab1
#| tbl-cap: Why am I not showing if just a data frame?

mtcars[1:4, 1:4]
```

````

### Expected behavior

Table caption should display even as data frame or tibble.

### Actual behavior

?(caption)

### Your environment

- IDE: RStudio 2023.06.1 Build 524
- Windows 11

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.300
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Users/py128/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/py128/AppData/Local/R/win-library
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.43
      rmarkdown: 2.23

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2023-08-07 20:40
A `data.frame` and `tibble` are not table, they are plain text, thus Quarto won't add a table caption for something that is not a table.
This is not a bug.
For now, for caption to work you need to output table as markdown/latex/html.

This will change with the work ongoing on the cross-reference system.

- https://github.com/quarto-dev/quarto-cli/issues/4944

I am closing this as there is nothing to do right now, beside you outputting table rather than plain text.

**Closed by mcanouil** 2023-08-07 20:40 UTC
Labels: bug
