### ISSUE TITLE
No scrollbar for large width mermaid diagrams.

### ISSUE THREAD

**Issue by DriesSchaumont** [quarto-dev/quarto-cli#6121] opened 2023-07-06 09:01 UTC
### Bug description

Scrollbars are no longer available when displaying mermaid diagrams with a large width. They were on version 1.2.280, but no longer on the latest release or development release.

### Steps to reproduce

````quarto
---
title: "Test Mermaid"
toc: false
---

```{mermaid}
%%| column: screen-inset-shaded
flowchart LR
    p0(Input)
    p2(toSortedList)
    p4(flatMap)
    p7(filter)
    p14(add_id)
    p19(mix)
    p18(filter)
    p20(Output)
    p21(filter)
    p27(split_modalities)
    p35(concat)
    p31(filter)
    p33(test_wf:run_wf:splitStub)
    p36(flatMap)
    p37(filter)
    p40(toSortedList)
    p42(flatMap)
    p50(filter_with_counts)
    p60(do_filter)
    p71(filter_with_scrublet)
    p77(toSortedList)
    p78(filter)
    p83(toSortedList)
    p85(flatMap)
    p89(filter)
    p91(flatMap)
    p97(test_wf:run_wf:rna_multisample:add_id:add_id_process1)
    p101(collect)
    p104(mix)
    p103(filter)
    p111(concat)
    p121(normalize_total)
    p131(log1p)
    p141(delete_layer)
    p151(filter_with_hvg)
    p161(calculate_qc_metrics)
    p258(concat)
    p166(filter)
    p169(toSortedList)
    p171(flatMap)
    p179(test_wf:run_wf:prot_singlesample:filter_with_counts:filter_with_counts_process1)
    p189(test_wf:run_wf:prot_singlesample:do_filter:do_filter_process1)
    p196(toSortedList)
    p197(filter)
    p202(toSortedList)
    p204(flatMap)
    p208(filter)
    p210(flatMap)
    p216(test_wf:run_wf:prot_multisample:add_id:add_id_process2)
    p220(collect)
    p223(mix)
    p222(filter)
    p230(test_wf:run_wf:prot_multisample:concat:concat_process1)
    p240(clr)
    p245(filter)
    p247(groupTuple)
    p254(test_wf:run_wf:concat:concat_process2)
    p259(toSortedList)
    p266(merge)
    p270(filter)
    p272(toSortedList)
    p274(flatMap)
    p282(pca)
    p292(find_neighbors)
    p302(umap)
    p308(concat)
    p307(filter)
    p309(filter)
    p311(toSortedList)
    p313(flatMap)
    p321(pca)
    p331(find_neighbors)
    p341(test_wf:run_wf:initialize_integration_prot:umap:umap_process1)
    p347(concat)
    p346(filter)
    p350(toSortedList)
    p352(Output)
    p18-->p19
    p19-->p20
    p35-->p36
    p36-->p37
    p77-->p78
    p103-->p104
    p36-->p166
    p196-->p197
    p222-->p223
    p36-->p245
    p258-->p259
    p307-->p308
    p308-->p309
    p308-->p346
    p346-->p347
    p0-->p2
    p2-->p4
    p4-->p7
    p4-->p18
    p7-->p14
    p14-->p19
    p14-->p21
    p14-->p31
    p21-->p27
    p27-->p35
    p31-->p33
    p33-->p35
    p37-->p40
    p40-->p42
    p42-->p50
    p50-->p60
    p60-->p71
    p71-->p77
    p78-->p83
    p83-->p85
    p85-->p89
    p85-->p103
    p89-->p91
    p91-->p97
    p97-->p101
    p101-->p104
    p104-->p111
    p111-->p121
    p121-->p131
    p131-->p141
    p141-->p151
    p151-->p161
    p161-->p258
    p166-->p169
    p169-->p171
    p171-->p179
    p179-->p189
    p189-->p196
    p197-->p202
    p202-->p204
    p204-->p208
    p204-->p222
    p208-->p210
    p210-->p216
    p216-->p220
    p220-->p223
    p223-->p230
    p230-->p240
    p240-->p258
    p245-->p247
    p247-->p254
    p254-->p258
    p259-->p266
    p266-->p270
    p266-->p307
    p270-->p272
    p272-->p274
    p274-->p282
    p282-->p292
    p292-->p302
    p302-->p308
    p309-->p311
    p311-->p313
    p313-->p321
    p321-->p331
    p331-->p341
    p341-->p347
    p347-->p350
    p350-->p352

```
````

### Expected behavior

A scrollbar should be displayed on the diagram, making its content readable.

### Actual behavior

No scrollbar is displayed and the content of the diagram is made too small. 
An error is shown in the devel console that may explay the behavior: 

<img width="856" alt="Screenshot 2023-07-06 at 10 47 34" src="https://github.com/quarto-dev/quarto-cli/assets/5946712/e2e6b1ba-91ab-4413-98cd-135f32918b41">

### Your environment

- IDE: VScode 1.79.2
- OS: Ubuntu 22.04

### Quarto check output

For version 1.3.433
```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: /home/di/.pyenv/versions/3.10.10/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in .venv. Did you forget to activate it?

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

For develop version: 1.4.187
```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.187
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: /home/di/.pyenv/versions/3.10.10/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in .venv. Did you forget to activate it?

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by DriesSchaumont** [comment] 2023-07-06 10:02
The strange thing is that some width is still included for the viewbox and the max-width. If I set `min-width:` to the value of the `max-width` or the viewbox, I get a scrollbar. Idk where this value originates from, but could this one be used?
<img width="1283" alt="Screenshot 2023-07-06 at 12 00 07" src="https://github.com/quarto-dev/quarto-cli/assets/5946712/f8e3798a-0ce4-4188-aa65-9335bdca960b">

**Comment by cscheid** [comment] 2023-07-06 10:10
I apologize. From your screenshot, it looks like you are in fact getting a `viewBox`, which is the attribute we use to get dimensions. That means it's actually a bug. I'll look at it later today.

**Comment by cscheid** [comment] 2023-07-06 13:10
Ok. I found the cause of the javascript runtime error and fixed it. Unfortunately, the latest version of mermaid now emits this diagram with a `width:100%` style, which means that the scrollbars won't be present (since `width:100%` is resolved by the browser to mean "use the width of the viewport"). If you want scrollbars to be present, you'll have to write some javascript to handle the SVG element after mermaid generates it.

That will require you to learn about the mermaid API (since you will need to synchronize your code with their such that your detection only happens after mermaid did its thing). Unfortunately again, I'm not a mermaidJS expert and can't help you with that.

This is a general downside of using mermaid which we cannot control: they change their behavior often, and we have no option but to follow them.

**Closed** 2023-10-02 19:48 UTC
Labels: bug, mermaid

**Comment by DriesSchaumont** [comment] 2023-10-03 06:01
@cscheid Thanks a lot for looking into this! 👍
