### ISSUE TITLE
Sub-figures layout issue Quarto manuscript

### ISSUE THREAD

**Issue by m-delem** [quarto-dev/quarto-cli#8776] opened 2024-02-18 18:34 UTC
### Bug description

Hello,

I encountered an issue trying to layout sub-figures in Quarto's new manuscript project type. I don't know if this extends to other formats as I don't have much time to test, I'm using the format for work.

Context: I am trying to get two sub-figures side-by-side with `layout-ncol: 2`, but also to use `.column-page-inset` (or `column: page` in chunk options) because the subfigures are too big to fit in the HTML body. I also need to render the manuscript as a PDF. Problem:

- When using `column: page` in the chunk options, the layout applies to each subfigure, and they end up on top of each other.

- When switching to two `fig-cap:` options, the figures are positioned correctly, but I lose the possibility of having a common caption along with subcaptions.

- Enclosing the code chunk in a div with only `{.column-page}` to get the best out of divs and chunks works in HTML, but crashes in LaTeX PDF render as Quarto tries to fit a float in a box. 

I'll put the steps to reproduce each output. I reproduced this in the `index.qmd` file of the [Quarto manuscript template](https://github.com/quarto-ext/manuscript-template-rstudio). I used plotly to generate interactive figures because I need to do so in my work project, so I added it here in case it might be part of the issue.

### Steps to reproduce

**Chunk 1**

````
```{r}
#| label: fig-test
#| fig-cap: test
#| fig-subcap: 
#|  - Timeline of recent earthquakes on La Palma
#|  - Test
#| column: page
#| layout-ncol: 2

library(tidyverse)
library(plotly)

(iris |>
  ggplot(aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point()) |> ggplotly()

(iris |>
  ggplot(aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point()) |> ggplotly()
```
````

This chunk was expected to produce two side by side sub-figures spanning the page, but it produced two stacked sub-figures, each spanning the entire page width. This chunk renders well in LaTeX, producing two side-by-side figures.

**Chunk 2**
````
```{r}
#| label: fig-timeline
#| fig-cap: 
#|  - Timeline of recent earthquakes on La Palma
#|  - Test
#| column: page
#| layout-ncol: 2

library(tidyverse)
library(plotly)

(iris |>
  ggplot(aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point()) |> ggplotly()

(iris |>
  ggplot(aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point()) |> ggplotly()
```
````

I found out while testing various options that this rendered the expected setup, i.e. two side-by-side figures spanning the page in HTML, AND rendered in PDF... But they are not sub-figures anymore.

**Chunk 3**
````
:::{.column-page}
```{r}
#| label: fig-test-two
#| fig-cap: test
#| fig-subcap: 
#|  - Timeline of recent earthquakes on La Palma
#|  - Test
#| layout-ncol: 2

library(tidyverse)
library(plotly)

(iris |>
  ggplot(aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point()) |> ggplotly()

(iris |>
  ggplot(aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point()) |> ggplotly()
```
:::
````

This yields the correct layout in HTML, but crashes during LaTeX render.

### Expected behavior

I wanted **Chunk 1** to render correctly in HTML and PDF, yielding this figure:

![fig-subcap-ok](https://github.com/quarto-dev/quarto-cli/assets/125131068/267a79cc-3b87-4530-9513-a952a499685f)

### Actual behavior

**Chunk 1** produced this HTML output:

![fig-subcap](https://github.com/quarto-dev/quarto-cli/assets/125131068/bf63dced-7a0d-4a49-84cb-507cc35d690d)

![fig-subcap-2](https://github.com/quarto-dev/quarto-cli/assets/125131068/99b1e466-c039-4190-9f58-247a2979e0e2)

**Chunk 2** produced this HTML output - close, but not what I wanted:

![fig-cap](https://github.com/quarto-dev/quarto-cli/assets/125131068/ea2b4472-2e43-4eb5-9e2f-67d5b522b2da)

**Chunk 3** produces the correct HTML output shown above, but crashes during LaTeX render with the following error:

```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages
ERROR:
compilation failed- error
LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.279
```

***Edit:***

Right now I wanted to put this aside for now and fall back on the solution exposed in **Chunk 2** to render my manuscript and publish it in this state while waiting for a better solution, but it seems this solution also crashes during a project-wide `quarto render`, apparently when producing JATS, even if it renders correctly in HTML, PDF and `.docx`. I got the following error: 

```
FATAL (C:/Users/Mael/AppData/Local/Programs/Quarto/share/filters/main.lua:17685) An error occurred:
JATS format can't render layouts without floats
This is a quarto bug. Please consider filing a bug report at https://github.com/quarto-dev/quarto-cli/issues
Error running filter C:/Users/Mael/AppData/Local/Programs/Quarto/share/filters/main.lua:
...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:2238: attempt to call a nil value (global 'crash_with_stack_trace')
stack traceback:
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:1826: in function 'fail'
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:1818: in function 'fail_and_ask_for_bug_report'
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:17685: in field 'render'
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:841: in local 'filter_fn'
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:302: in function <...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:292>
        (...tail calls...)
        [C]: in ?
        [C]: in method 'walk'
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:224: in function <...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:214>
        (...tail calls...)
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:942: in local 'callback'
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:960: in upvalue 'run_emulated_filter_chain'
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:996: in function <...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:993>
stack traceback:
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:224: in function <...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:214>
        (...tail calls...)
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:942: in local 'callback'
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:960: in upvalue 'run_emulated_filter_chain'
        ...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:996: in function <...ael/AppData/Local/Programs/Quarto/share/filters/main.lua:993>
```

### Your environment

RStudio version 2023.12.1+402
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

### Quarto check output

$ quarto check
Quarto 1.4.550
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.550
      Path: C:\Users\Mael\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\Mael\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: C:/Users/Mael/AppData/Local/Programs/Python/Python312/python.exe
      Jupyter: 5.7.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/Mael/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment] 2024-02-18 19:54
Duplicate of #8763

**Closed** 2024-02-18 20:01 UTC
Labels: duplicate
