### ISSUE TITLE
r inline code not executed

### ISSUE THREAD

**Issue by jkylearmstrong** [quarto-dev/quarto-cli#5349] opened 2023-04-28 21:40 UTC
### Bug description

About this machine and it's version of R and RStudio:
```{r}
> tibble::enframe(Sys.info()) |>
+   dplyr::filter(name %in% c('sysname','release','version','machine'))
# A tibble: 4 × 2
  name    value      
  <chr>   <chr>      
1 sysname Windows    
2 release 10 x64     
3 version build 22621
4 machine x86-64     
> paste(R.version$major, R.version$minor, sep='.')
[1] "4.3.0"
> RStudio.Version()$long_version
[1] "2023.03.0+386"
> quarto::quarto_version()
[1] ‘1.4.11’
```

In the project's `_quarto.yaml` are:
```{r}
engine: knitr

project:
  type: book
  
book:
  title: "fancy title"
  author: "me"
  date: today
  date-format: long
  reader-mode: true
```
Note that I have attempted to add in the `engine: knitr` option as suggested in [https://github.com/quarto-dev/quarto-cli/discussions/4855](https://github.com/quarto-dev/quarto-cli/discussions/4855)

The `index.qmd` contains:
```{r}
# Preface {.unnumbered}

These notes have been developed with:

-   R version `r paste(R.version$major, R.version$minor, sep='.')`
-   RStudio version 2023.03.0+386
-   Quarto version `r quarto::quarto_version()`

R, RStudio, and Quarto are all free to download and use. You can learn more about both R and RStudio and download them both from <https://posit.co/download/rstudio-desktop/>.

To learn more about Quarto books visit <https://quarto.org/docs/books>.
```

However, whenever I attempt to render this document individually, the preview still shows the code and not the results. 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment] 2023-04-29 03:43
> Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.

**Comment by jasonacollins** [comment] 2023-04-30 02:04
Experiencing the same problem across my blog after Quarto update to 1.4 - the inline code stopped working. Problem resolved on winding back to 1.3. Trying to create minimal example, but can't recreate at small scale - will post if can.

**Comment by cscheid** [comment] 2023-04-30 15:24
> Experiencing the same problem across my blog after Quarto update to 1.3.34

Just to be clear, I imagine you mean 1.3.340. @jasonacollins see the [release notes](https://quarto.org/docs/download/) and this specifically for why we changed the inline engine detection behavior: https://github.com/quarto-dev/quarto-cli/issues/3908

**Comment by jkylearmstrong** [comment] 2023-05-01 01:57
@cscheid 
> > Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.

I have made a repo with an example: 
https://github.com/jkylearmstrong/quarto_in_line_error

**Comment by jkylearmstrong** [comment] 2023-05-01 02:18
I should also comment that the function 

```{r}
RStudio.Version()$long_version
```
produces this error:

```{r}
Error in RStudio.Version() : could not find function "RStudio.Version"
Calls: .main ... withVisible -> eval_with_user_handlers -> eval -> eval
```

**Comment by eitsupi** [comment] 2023-05-01 07:10
> I have made a repo with an example:
> [jkylearmstrong/quarto_in_line_error](https://github.com/jkylearmstrong/quarto_in_line_error)

There seem to be two files, `_quarto.yaml` and `_quarto.yml`. Could this be the cause?

**Comment by jkylearmstrong** [comment] 2023-05-01 13:30
@eitsupi perhaps in this repo - however, I am developing a book which only has one of these and the same error is there as well, additionally, @jasonacollins reports similar issues.

**Comment by jkylearmstrong** [comment] 2023-05-01 13:50
@eitsupi I made a different branch but now the error is with block chunks of code:

https://github.com/jkylearmstrong/Intro_Jeff_Data_Science_R
branch: dev1

**Comment by eitsupi** [comment] 2023-05-01 13:51
@jkylearmstrong What happens when you delete `_quarto.yml`?

**Comment by eitsupi** [comment] 2023-05-01 13:53
> I made a different branch but now the error is with block chunks of code:
> 
> [jkylearmstrong/Intro_Jeff_Data_Science_R](https://github.com/jkylearmstrong/Intro_Jeff_Data_Science_R)
> branch: dev1

I'm sorry but I don't understand what you are trying to tell me here.
I cannot open that link.

**Comment by jkylearmstrong** [comment] 2023-05-01 13:56
> > I made a different branch but now the error is with block chunks of code:
> > [jkylearmstrong/Intro_Jeff_Data_Science_R](https://github.com/jkylearmstrong/Intro_Jeff_Data_Science_R)
> > branch: dev1
> 
> I'm sorry but I don't understand what you are trying to tell me here. I cannot open that link.

I posted the wrong repo this is the correct one where I have deleted the second yaml file
https://github.com/jkylearmstrong/quarto_in_line_error

**Comment by eitsupi** [comment] 2023-05-01 13:58
> I posted the wrong repo this is the correct one where I have deleted the second yaml file
> [jkylearmstrong/quarto_in_line_error](https://github.com/jkylearmstrong/quarto_in_line_error)

I think this is expected behavior since the engine is not specified.

**Comment by jkylearmstrong** [comment] 2023-05-01 14:08
I would be happy to invite @eitsupi & @cscheid to the repo for the book so that I can know what is going on and the documentation could be made very clear, I have tried to create a "dummy repo" that simulates the error. 

I rendered this earlier today and you can see that there are inline errors: 

https://jkylearmstrong.quarto.pub/introduction-to-data-science-with-r/

**Comment by eitsupi** [comment] 2023-05-01 14:17
Unfortunately, I do not have the bandwidth to render your book.

I rendered a qmd file includes only inline code with Quarto 1.4 a few hours ago and it worked fine.
https://github.com/eitsupi/querying-with-prql/blob/848f2d87fe8dbd6ec2dbabaecf301cc5fe86e292/docs/info.qmd

**Comment by cderv** [comment] 2023-05-03 14:52
@jkylearmstrong in the project you shared you have two configuration file 

* https://github.com/jkylearmstrong/quarto_in_line_error/blob/main/_quarto.yml
* https://github.com/jkylearmstrong/quarto_in_line_error/blob/main/_quarto.yaml

Your `engine: knitr` key is only in the second, but quarto will use the first of those file (`.yml`  is preferred if both are present). 
So your `engine:` may not be taken into account. 

You can also add the `engine: knitr` in the doc that needs it (doc with only inline R code). 

Could it be the error ? Why do you have both file in the first place ?

**Comment by cscheid** [comment] 2023-05-03 14:56
> Could it be the error ? Why do you have both file in the first place ?

I think we should issue an error message in these situations (we have code that detects either of `_quarto.ya?ml`, but we could issue an error message in case we find _both_.

**Comment by cderv** [comment] 2023-05-03 15:04
I agree. I was looking at where this happens for that purpose. For reference, I think this is the function that detects both file 
https://github.com/quarto-dev/quarto-cli/blob/4a4e9f1226df1f6f994ac084b226150966bc7aa5/src/project/project-shared.ts#L90-L94

i'll open another issue to track this idea.

**Comment by jkylearmstrong** [comment] 2023-05-11 04:37
I removed the duplicate file and the error persisted. 

I ended up solving it by editing `index.qmd` to what follows below. I'm not sure if the length of the r code is what addresses it. 
````
# Preface {.unnumbered}

These notes have been developed with:

```{r}
#| echo: false
r_v <- paste(R.version$major, R.version$minor, sep='.')
#rs_v <- RStudio.Version()$long_version
q_v <- paste(quarto::quarto_version(), sep='.')
```

-   R version `r r_v`
-   RStudio version 2023.03.0+386 
-   Quarto version `r q_v`

R, RStudio, and Quarto are all free to download and use. You can learn more about both R and RStudio and download them both from <https://posit.co/download/rstudio-desktop/>.

To learn more about Quarto books visit <https://quarto.org/docs/books>.
````

**Comment by cderv** [comment] 2023-05-11 08:41
To have R inline code executed you need to have the knitr engine used. This happens in the following case: 

* You set `engine: knitr` in the document level or project level
* Your document has some R code chunk - in that case it will automatically bind to knitr engine. 
If you have only inline R code (and no R code chunk), it won't use an engine by default. 

As you added a R code chunk in your index file, it correcty used the knitr engine. Hence why it works probably. 

Setting `engine: knitr` in your project level configuration should have worked. 

As it is working for you now, I will close this issue. Please reopen if you think there is still an issue with the engine detectection.

**Closed by cderv** 2023-05-11 08:41 UTC
Labels: bug, needs-repro
