### ISSUE TITLE
Quarto fails to render PDF containing only a Mermaid diagram - produces stack trace

### ISSUE THREAD

**Issue by dsbitor** [quarto-dev/quarto-cli#10646] opened 2024-08-29 17:12 UTC
### Bug description

Quarto gets the command `quarto render simplemermaiddiagrampdf.qmd`

Produces the following error:

ERROR: Couldn't find open server.
Chrome process error: [1046:41987:0829/112759.155341:ERROR:trust_store_mac.cc(757)] Error parsing certificate:
ERROR: Failed parsing extensions

[1046:259:0829/112759.346188:ERROR:system_network_context_manager.cc(863)] Cannot use V8 Proxy resolver in single process mode.
[1046:259:0829/112759.379255:ERROR:system_network_context_manager.cc(863)] Cannot use V8 Proxy resolver in single process mode.
[1046:259:0829/112759.400164:ERROR:system_network_context_manager.cc(863)] Cannot use V8 Proxy resolver in single process mode.

DevTools listening on ws://127.0.0.1:9222/devtools/browser/fecd8ddc-94bc-493a-83b2-716008547586
[1046:259:0829/112759.402990:ERROR:system_network_context_manager.cc(863)] Cannot use V8 Proxy resolver in single process mode.
[0829/112759.957738:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)
[1064:259:0829/112759.959180:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[1063:259:0829/112759.959212:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[1062:259:0829/112759.959196:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[1065:259:0829/112759.959212:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[1058:259:0829/112759.959199:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[1060:259:0829/112759.959215:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)

Stack trace:
Chrome process error: [1046:41987:0829/112759.155341:ERROR:trust_store_mac.cc(757)] Error parsing certificate:
ERROR: Failed parsing extensions

[1046:259:0829/112759.346188:ERROR:system_network_context_manager.cc(863)] Cannot use V8 Proxy resolver in single process mode.
[1046:259:0829/112759.379255:ERROR:system_network_context_manager.cc(863)] Cannot use V8 Proxy resolver in single process mode.
[1046:259:0829/112759.400164:ERROR:system_network_context_manager.cc(863)] Cannot use V8 Proxy resolver in single process mode.

DevTools listening on ws://127.0.0.1:9222/devtools/browser/fecd8ddc-94bc-493a-83b2-716008547586
[1046:259:0829/112759.402990:ERROR:system_network_context_manager.cc(863)] Cannot use V8 Proxy resolver in single process mode.
[0829/112759.957738:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)
[1064:259:0829/112759.959180:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[1063:259:0829/112759.959212:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[1062:259:0829/112759.959196:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[1065:259:0829/112759.959212:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[1058:259:0829/112759.959199:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[1060:259:0829/112759.959215:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)

    at criClient (file:///Applications/quarto/bin/quarto.js:39317:15)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async file:///Applications/quarto/bin/quarto.js:39279:22
    at async Semaphore.runExclusive (file:///Applications/quarto/bin/quarto.js:38956:29)
    at async Object.createPngsFromHtml (file:///Applications/quarto/bin/quarto.js:39544:42)
    at async makePng (file:///Applications/quarto/bin/quarto.js:74827:70)
    at async makeDefault (file:///Applications/quarto/bin/quarto.js:74887:24)
    at async Object.cell (file:///Applications/quarto/bin/quarto.js:74910:20)
    at async Promise.all (index 0)
    at async Object.document (file:///Applications/quarto/bin/quarto.js:39839:25)

### Steps to reproduce

The error above now occurs whenever trying to render any code containing a Mermaid diagram as a PDF.

Simple quarto pdf source below, causes error. Does not occur if the render is to HTML

Tried re-installing Quarto.
Tried rebooting computer.

Environment is: Mac OS X  see below
Chip Apple M1 Pro
Memory 32 GB
macOS 14.6.1 (23G93) - Sonoma

Quarto using quarto check command see below

````
---
title: "DevDoc DayBook"

number-sections: true

format: 
  pdf:
    documentclass: scrreprt
    papersize: letter
    
execute:
  keep-md: true 
---

# Mermaid Diagrams

## Flowcharts

### Management or Overview Flow - Left to Right

Diagram shows a Management View or Overview Flow of a process that may be expanded in subsequent charts.


```{mermaid}
%%| echo: true
flowchart LR
  A([Start]) --> B
  B[Submit AI Query] --> C{Useful?}
  C -- Yes --> D[Use Result]
  C -- No -->  E[Ignore]
  D --> F([End])
  E --> F
```
````

Does not produce an intermediate markdown file. 

Prior to error message output from Quarto  there is no intermediate output.

### Expected behavior

Quarto should reset to a start with no requirements on previous run - looks like something has been ket open that should have closed after previous run. 

### Actual behavior

Produces error message / stack trace whether quarto rend is run from zsh shell or Rstudio. The error output above is output  from zsh.

### Your environment

R -Version 2024.04.2+764 (2024.04.2+764)

Chip Apple M1 Pro
Memory 32 GB
macOS 14.6.1 (23G93)

Using BBedit as an editor as well as RStudio
Terminal emulator is Warp

### Quarto check output

quarto check
Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/davidbanham/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /Users/davidbanham/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment] 2024-08-29 17:13
Duplicate of https://github.com/quarto-dev/quarto-cli/issues/10626 (FYI, please search for related issues in the future). This is fixed on 1.6 and will be fixed in 1.5 when our next patch release comes out on Sep 1st.

**Closed by cscheid** 2024-08-29 17:13 UTC
Labels: bug

**Comment by ondrej-such** [comment] 2024-09-12 07:45
The bug still reproes in 1.6.9. 

My config

C:\Users\Ondrej>quarto check
Quarto 1.6.9
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.6.9
      Path: C:\Users\Ondrej\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.09
      Chromium: 869685

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\Ondrej\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.4.1
      Path: C:/PROGRA~1/R/R-44~1.1
      LibPaths:
        - C:/Users/Ondrej/AppData/Local/R/win-library/4.4
        - C:/Program Files/R/R-4.4.1/library
      knitr: 1.48
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment] 2024-09-12 08:28
@ondrej-such This issue was marked as a duplicate. Please don't post on closed duplicate.
Additionally, avoid commenting on closed issue, instead, open a new issue and follow the issue template to provide all required information.
You can reference the previous issue:
- https://github.com/quarto-dev/quarto-cli/issues/10626
