### ISSUE TITLE
missing reference for flextable table in word document

### ISSUE THREAD

**Issue by rmflight** [quarto-dev/quarto-cli#3601] opened 2022-12-08 16:35 UTC
### Bug description

````
---
title: "flextable missing reference"
format: docx
---


```{r}
#| label: load_data
data(cars)

library(flextable)
```

Now lets try a table in our word document. This should be @tbl-cars.

```{r}
#| label: tbl-cars
#| tbl-cap: Something about cars.
cars |>
  dplyr::slice_head(n = 5) |>
  flextable() |>
  autofit()
```
````

[flextable_missing.docx](https://github.com/quarto-dev/quarto-cli/files/10187485/flextable_missing.docx)

Rendering the above document (RStudio render button) results in the table reference looking like ?@tbl-cars, and there is no caption.

If I force HTML output (quarto::quarto_render(..., output_format = "html")), I get the expected output of Table 1, as well as the caption.

Software details:

* R 4.2.1
* RStudio 2022.12.0-preview+348
* quarto 1.3.47
* flextable 0.8.4.001 2022-12-08 davidgohel/flextable@f38ccb1
* Linux, Pop! OS 22.04 (skinned version of Ubuntu 22.04)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2023-05-23 17:39
In Quarto 1.4's crossref system, this is a duplicate of https://github.com/quarto-dev/quarto-cli/issues/1556, https://github.com/quarto-dev/quarto-cli/issues/2297, https://github.com/quarto-dev/quarto-cli/issues/3397 and https://github.com/quarto-dev/quarto-cli/issues/3600.

**Comment by cscheid** [comment] 2023-10-22 20:21
There's something not _quite right_ with flextable and quarto just yet that I haven't figured out. Specifically, this document produces output that Microsoft Word doesn't like much. If you tell it to go ahead and read the file anyway, though, the output generated seems correct:

<img width="541" alt="3601" src="https://github.com/quarto-dev/quarto-cli/assets/285675/cfb39c89-adcb-4452-a198-210c19ea6cc1">

If I use output other than flextable (like `gt` in #3600), I don't get the warning. This is a crossref bug with quarto+flextable specifically, because if I use flextable outside of a crossreferenceable environment, I don't get the warning either.

I'm going to close this bug and open a new, more specific one.

**Closed by cscheid** 2023-10-22 20:21 UTC
Labels: bug, crossref, tables

**Comment by cderv** [comment] 2023-10-30 23:16
@cscheid I do get the warning with example in #3600 using **gt**. We can discuss tihs in the new issue https://github.com/quarto-dev/quarto-cli/issues/7321 but it seems to happen with **gt** too for me. 

Just wanted to share to be thorough.
