### ISSUE TITLE
Quarto with arrow

### ISSUE THREAD

**Issue by novotny1akub** [quarto-dev/quarto-cli#3171] opened 2022-11-04 15:20 UTC
### Bug description

I am having trouble when trying to reproduce the examples in the [docs](https://quarto.org/docs/interactive/ojs/data-sources.html) on how to use arrow as a data source for Quarto. Below is a reprex and the error message I am getting.
![image](https://user-images.githubusercontent.com/39886440/200011104-26420963-a2eb-48dd-83a1-48739f6631a8.png)

````
---
title: "Quarto with arrow"
format:
  html:
    self-contained: true
---

```{r}

arrow::write_feather(
  mtcars, 
  "data.arrow", 
  compression = "uncompressed"
)

```


```{ojs}

data = FileAttachment("data.arrow").arrow()

Inputs.table(data)

```
````
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

I am running a Windows machine.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2022-11-04 16:02
This is a duplicate of the other issue you've reported on sqlite. I'm going to close this one so we track it on a single place.

**Comment by novotny1akub** [comment] 2022-11-04 16:38
I am slightly confused as the code above is more or less taken 'as is' from the documentation. Does it mean that some examples in the documentation do not work? If that is the case, it might be a good idea to mention in the documentation that the ojs support is rather experimental.

**Comment by cscheid** [comment] 2022-11-04 16:44
Ah, I'm sorry. I misread your bug report. The issue here is the version of RStudio's IDE you're running. This specific version of RStudio uses a very old version of Chrome (QtWebEngine/5.12.8 Chrome/69.0.3497.128 is about 5 years old) and doesn't support some of the features necessary for OJS.

Can you try Elsbeth Geranium (instead of Spotted Wakerobing) from here: https://dailies.rstudio.com/?

**Comment by novotny1akub** [comment] 2022-11-04 17:04
I just want to kindly point out that I am not trying to display the output in the RStudio, but in a standalone browser. For the sake of excluding RStudio altogether, I tried to generate the html with `quarto render file_name_goes_here.qmd --to html`, but it is still not working. Are you sure updating the RStudio is going to make any difference? My Quarto version is 1.2.258.

**Comment by cscheid** [comment] 2022-11-04 17:14
Hm. I apologize. Apparently I misread it in more than one way! (In the future, it would be helpful to include this additional information you've shared just now.) I'm investigating right now.

**Comment by cscheid** [comment] 2022-11-04 17:27
I can reproduce this issue locally. https://github.com/quarto-dev/external-observablehq-stdlib is clearly being miscompiled and while `arrow` global is being renamed to `arrow$1`, the `arrow` reference is not being renamed.

**Comment by cscheid** [comment] 2022-11-04 17:43
Ok, I have a fix incoming. Thank you for the report and persistence, I definitely appreciate it.

**Comment by novotny1akub** [comment] 2022-11-04 17:46
No worries. Thanks a lot.

**Comment by eitsupi** [comment] 2022-11-05 08:31
Perhaps the label is still wrong? (duplicate?)

**Closed** 2022-11-06 19:41 UTC
Labels: bug

**Comment by novotny1akub** [comment] 2022-11-07 15:15
@cscheid Should this be fixed now? I tried to render the reprex above with Quarto 1.2.262, but the error seems not to have disappeared.

**Comment by novotny1akub** [comment] 2022-11-09 10:27
I can confirm that using Quarto 1.2.269 it is now working.
