### ISSUE TITLE
Error loading deno-dom-native / Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by svilupp** [quarto-dev/quarto-cli#3896] opened 2023-01-09 15:02 UTC
### Bug description

First of all, thank you for the amazing tool!

I'm trying to produce an HTML report from .QMD and getting the following error: 
> ERROR: TypeError: Cannot read properties of undefined (reading 'startsWith')

It seems to be related to dyno-dom (as per debug log):
> Error loading deno-dom-native: Could not open library: Could not open library: dlopen(/Applications/quarto/bin/tools/deno_dom/libplugin.dylib, 0x0005): tried: '/Applications/quarto/bin/tools/deno_dom/libplugin.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

Out of curiosity, when / why does deno-dom-native gets triggered? This is the first time I saw error and I've been using Quarto for >6 months. It would help me isolate the problem.

**Steps:**
- I ran: `quarto render _analysis_1/prediction.qmd --to html`
- Jupyter notebook gets produced (and everything looks okay, nothing out of place), assets are saved in a separate folder
- But then the error gets triggered when creating the HTML self-contained file
- The following error shows up:
> ERROR: TypeError: Cannot read properties of undefined (reading 'startsWith')

**Version:**
- I have ARM64 / Mac M1 architecture
- System: Mac OS Monterey (12.5.1 (21G83))
- I tried both 1.2.269 and 1.3.91 (pre-release) -- all checks pass

**Eliminating possible causes:**
- Is it common? No, I have produced several different reports earlier today, there were no significant differences between them
- Are there some large / unusual attachments, formats, etc? No.

**Troubleshooting steps:**
- I ran with `-log-level debug`, see the above error message about dyno-dom-native not being the right version (for ARM64_
- I ran `quarto check` -- all passes
- Updated Quarto to latest release and pre-release + ran quarto check -- all passes
- Tried to manually update dyno-dom to the latest release (0.1.35 supports ARM64) -- no difference

I'm unable to provide the underlying jupyter notebook due to confidentiality issues -- I'll try to reduce it and reproduce the error.

YAML Header
```md
---
title: Some title
author: Some name
date: 2022-01-09
format:
  html:
    toc: true
    toc-depth: 2
    code-fold: true
    self-contained: true
  revealjs:
    auto-stretch: true
    self-contained: true
    scrollable: true
    incremental: true
    preview-links: auto
    slide-number: true
    transition: slide
    background-transition: fade
    fig-align: center
jupyter: julia6-1.8
---
```

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2023-01-09 15:47
This is strange, I don't understand why you're getting the native codepath for deno_dom, since we do have a WASM module that we use and check. 

I understand your confidentiality issues but unfortunately, it's very hard for us to track this down without a reproducible example. Can you attempt your rendering with `QUARTO_PRINT_STACK=1` on your environment?

**Comment by svilupp** [comment] 2023-01-09 19:17
Hi @cscheid, thank you for your reply. I've isolated the cell that causes the trouble -- it's a simple text stdout, but I suspect something goes wrong in rendering the metadata (not sure why it triggers the deno-dom error)

I've added 4 files (in the attached Archive.zip)
- file_1.qmd -> source file with the offending cell, unfortunately not runnable (hopefully, not necessary, as it can be reproduced from the .ipynb files)
- file_1.ipynb -> pruned output to the problematic cell --> conversion FAILS with the above error
- file_2.ipynb -> removed all outputs and source (suspected wrong characters) --> still FAILS
- file_3.ipynb -> when the whole first part of outputs cell is removed -- it WORKS

The offending part is the first part of the outputs:
- I've tried removing the "data" key, or changing the "output_type" -- still fails
- the only solution that works is to remove the whole first part of outputs (highlighted part)
<img width="578" alt="image" src="https://user-images.githubusercontent.com/49557684/211388512-9ac2d037-8f74-411a-8a45-100a64223638.png">

I've tried PRINT_STACK (but had to set it to =true), but cannot tell much from it:
> Error loading deno-dom-native: Could not open library: Could not open library: dlopen(/Applications/quarto/bin/tools/deno_dom/libplugin.dylib, 0x0005): tried: '/Applications/quarto/bin/tools/deno_dom/libplugin.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
ERROR: TypeError: Cannot read properties of undefined (reading 'startsWith')

> TypeError: Cannot read properties of undefined (reading 'startsWith')
    at file:///Applications/quarto/bin/quarto.js:49273:43
    at Array.filter (<anonymous>)
    at mdFromCodeCell (file:///Applications/quarto/bin/quarto.js:49267:42)
    at jupyterToMarkdown (file:///Applications/quarto/bin/quarto.js:48967:34)
    at Object.execute (file:///Applications/quarto/bin/quarto.js:51063:31)
    at async renderExecute (file:///Applications/quarto/bin/quarto.js:88715:27)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:88836:51)
    at async render (file:///Applications/quarto/bin/quarto.js:89195:21)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:89594:32)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:4238:13)

[Archive.zip](https://github.com/quarto-dev/quarto-cli/files/10376163/Archive.zip)

**Comment by cscheid** [comment] 2023-01-09 19:46
I think what's happening is that the deno-dom error is a red herring; we're printing that to stdout but still successfully loading the WASM version of deno-dom. The following TypeError, though, is the real source of the bug.

```
TypeError: Cannot read properties of undefined (reading 'startsWith')
at file:///Applications/quarto/bin/quarto.js:49273:43
at Array.filter ()
at mdFromCodeCell (file:///Applications/quarto/bin/quarto.js:49267:42)
at jupyterToMarkdown (file:///Applications/quarto/bin/quarto.js:48967:34)
at Object.execute (file:///Applications/quarto/bin/quarto.js:51063:31)
at async renderExecute (file:///Applications/quarto/bin/quarto.js:88715:27)
at async renderFiles (file:///Applications/quarto/bin/quarto.js:88836:51)
at async render (file:///Applications/quarto/bin/quarto.js:89195:21)
at async Command.fn (file:///Applications/quarto/bin/quarto.js:89594:32)
at async Command.execute (file:///Applications/quarto/bin/quarto.js:4238:13)
```

This here is the issue.

**Comment by cscheid** [comment] 2023-01-09 19:50
Ok, I can repro:

```
$ quarto render file_1.ipynb --to html
ERROR: TypeError: Cannot read properties of undefined (reading 'startsWith')

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/core/jupyter/jupyter.ts:1064:37
    at Array.filter (<anonymous>)
    at mdFromCodeCell (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/core/jupyter/jupyter.ts:1050:40)
    at jupyterToMarkdown (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/core/jupyter/jupyter.ts:669:27)
    at Object.execute (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/execute/jupyter/jupyter.ts:302:26)
    at async renderExecute (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/render-files.ts:190:25)
    at async renderFiles (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/render-files.ts:428:39)
    at async render (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/render-shared.ts:100:18)
    at async Command.fn (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/cmd.ts:193:26)
    at async Command.execute (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
```

**Comment by cscheid** [comment] 2023-01-09 23:48
This is fixed now on `main`. We'll create a new pre-release set of installers soon. Thanks for reporting!

**Closed** 2023-01-09 23:47 UTC
Labels: bug, need-repro
