### ISSUE TITLE
Typst #bibliography does not respect absolute directory paths

### ISSUE THREAD

**Issue by cjber** [quarto-dev/quarto-cli#7354] opened 2023-10-25 13:05 UTC
### Bug description

Unlike compilation using pandoc and tex, compilation using pandoc and typst does not respect absolute directory paths in `bibliography:`.

### Steps to reproduce

````qmd
---
title: "My Document"
format:
  typst: 
    keep-typ: true
  pdf:
    keep-tex: true
bibliography: /home/cjber/references.bib
---


Test [@cohen1963].
````

The `pdf` document using `tex` will correctly compile, however typst will generate an error:

```
pandoc 
  to: typst
  output-file: typst_demo.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  
metadata
  title: My Document
  bibliography:
    - /home/cjber/references.bib
  
[typst]: Compiling typst_demo.typ to typst_demo.pdf...error: file not found (searched at /home/cjber/drive/typst_quarto/home/cjber/references.bib)
    ┌─ typst_demo.typ:160:14
    │
160 │ #bibliography("/home/cjber/references.bib")
    │               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^


[Process exited 1]
```

### Expected behavior

Typst should search for the file starting at the root directory, not the project directory. This may be a typst issue, given the `#bibliography` appears to be correct, but I thought I'd create this issue as it is an unexpected behaviour, as the `yaml` is identical for `pdf` but produces a different result.

### Actual behavior

Searchs relative to the project directory.

### Your environment

Linux

### Quarto check output

```bash
Quarto 1.4.446
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.446
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.10
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/cjber/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /home/cjber/drive/typst_quarto/.venv/bin/python3
      Jupyter: 5.4.0
      Kernels: python3

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
(\) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment] 2023-10-25 13:58
This is not a bug.
In a reproducibility goal, Quarto resolves `/` as root of the project.

**Comment by cjber** [comment] 2023-10-25 14:06
@mcanouil HTML works identically to pdf for me.

 In terms of specifying whether the path should be relative or absolute, I believe the format would be to either starting with a dot i.e. `./bibliography` or omit the preceding slash entirely: `bibliography`.

So in my example as I use a preceding /, Quarto correctly identifies that it should use an absolute path.

What seems unusual is that this seems correct in `#bibliography("/home/cjber/references.bib")`, but when compiling it fails as typst looks relative to the project directory.

**Comment by mcanouil** [comment] 2023-10-25 14:10
> Quarto has never resolved / to the project root in my experience.

It only means you never used "absolute" paths in images or in include shortcodes.

**Comment by cjber** [comment] 2023-10-25 14:13
Sorry I should have clarified that  I meant within the `yaml` metadata, i.e. the `bibliography:` where I always use absolute paths, with external `.bib` files. 

You are correct that images included through markdown syntex `![]()` resolve differently, and use `/` relative to the project  root.

**Comment by cscheid** [comment] 2023-10-25 14:16
> Expected behavior

> Typst should search for the file starting at the root directory, not the project directory. This may be a typst issue, given the #bibliography appears to be correct, but I thought I'd create this issue as it is an unexpected behaviour, as the yaml is identical for pdf but produces a different result.

That's not how paths in Quarto work are meant to be resolved. @mcanouil is correct: paths that start in `/` are resolved relative to the root of the project, by design. If they are resolved absolutely in other formats, that's actually a bug in the other formats. I'm going to close this one.

**Comment by cscheid** [comment] 2023-10-25 15:07
@cjber Turns out the true story is more complicated; I don't know how quickly we'll get a fix out, but we'll probably document that `bibliography` is an exception (because it's not handled by quarto itself in most cases).

**Comment by cscheid** [comment] 2023-12-04 15:57
The underlying issue is that Typst itself [doesn't support resolving paths from the filesystem root](https://github.com/typst/typst/issues/199#issuecomment-1686678495), and they have signaled that they don't consider this to be a bug. Unfortunately, there's not much we can do here.

**Closed by cscheid** 2023-12-04 15:57 UTC
Labels: bug, typst
