### ISSUE TITLE
Git hangs on preparing worktree

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1916] opened 2022-08-16 11:10 UTC
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1509

<div type='discussions-op-text'>

<sup>Originally posted by **jmgirard** July 23, 2022</sup>
Sometimes when I run `quarto publish gh-pages`, it hangs (i.e., gets stuck) on "Preparing worktree."

     * branch            gh-pages   -> FETCH_HEAD
    Rendering for publish:
    
    ...

    branch 'gh-pages' set up to track 'origin/gh-pages'.
    HEAD is now at 2054a64 Built site for gh-pages
    Preparing worktree (resetting branch 'gh-pages'; was at 2054a64)

Any ideas how to troubleshoot, fix, or prevent this?</div>

**Comment by jjallaire** [comment] 2022-08-17 15:39
Moving this issue to v1.2 and updated docs to emphasize that publishing directly from `docs` also works: https://quarto.org/docs/publishing/github-pages.html#render-to-docs

**Comment by cderv** [comment] 2022-09-14 13:47
Duplicate of #1524

**Closed by cderv** 2022-09-14 13:47 UTC
