### ISSUE TITLE
No path variable added when instaling through winget

### ISSUE THREAD

**Issue by KronosTheLate** [quarto-dev/quarto-cli#1977] opened 2022-08-18 21:49 UTC
After installing quarto through winget:
```
PS C:\Users\Dennis Bal> winget show quarto
Found Quarto [RStudio.quarto]
Version: 1.0.38
Publisher: Rstudio, PBC
Publisher Url: https://www.rstudio.com/
Moniker: quarto
Description: Main features of Quarto:
   Create dynamic content with Python, R, Julia, and Observable.
   Author documents as plain text markdown or Jupyter notebooks.
   Publish high-quality articles, reports, presentations, websites, blogs, and books in HTML, PDF, MS Word, ePub, and more.
   Author with scientific markdown, including equations, citations, crossrefs, figure panels, callouts, advanced layout, and more.
Homepage: https://quarto.org/
License: GPL v2
License Url: https://quarto.org/license.html
Copyright: Copyright (C) RStudio, PBC
Copyright Url: https://quarto.org/trademark.html
Installer:
  Type: wix
  Locale: en-US
  Download Url: https://github.com/quarto-dev/quarto-cli/releases/download/v1.0.38/quarto-1.0.38-win.msi
  SHA256: 1139e8a8c0a0e220937a4b137f330fa8b8cf6fa04af27dc52c1e73b842661ac7
```

I am unable to determine how to launch the application:
```
PS C:\Users\Dennis Bal> quarto
quarto: The term 'quarto' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

VSCode is complaining that quarto is not installed.
So it seems like installing through winget is not adding the right entry to the path by default, and I do not know how to make it work.

**Comment by KronosTheLate** [comment] 2022-08-18 21:52
It might be related to the fact that I have a space in my username. This is suggested by the error message I get when I run the quarto executable after a manual installation:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/61620837/185501647-b5cdd811-1145-43b8-8dfa-3147efb5a808.png">

**Comment by jjallaire** [comment] 2022-08-19 14:20
@cderv Are you familiar with the winget distribution and could a space in the path indeed be the source of the troubles?

**Comment by KronosTheLate** [comment] 2022-08-20 10:52
I have in the past had to enclose my path in quotation marks ("), eg in the shell, due to the space. That would explain why "Bal" is parsed as a command, because the parser thinks that the path is finnished.

**Comment by cderv** [comment] 2022-08-26 16:04
I can confirm that the Winget package is working fine for me and `quarto` is found in PATH. But I don't have a space in my username. 

Considering your screenshot above @KronosTheLate I see a FINDSTR issue, and I believe we have fix something related in our current pre-release version, which should be next release very soon. 

I just need to prepare new release for winget repo for Quarto v1.1 and hopefully it will work.

**Comment by KronosTheLate** [comment] 2022-08-26 16:58
Lovely! Ping me when that is the case with a comment here, and I will give it a shot. If that works, I will close the issue.

**Comment by cderv** [comment] 2022-08-29 11:51
PR for latest v1.1 has been opened by community @dpprdan: https://github.com/microsoft/winget-pkgs/pull/75350#pullrequestreview-1088512915 
Once merged should be available through **winget**, or you could probably install based on the PR and local manifest.

I am still trying to reproduce the "space in name" problem on my side.

**Comment by dpprdan** [comment] 2022-08-30 07:07
v1.1.149 is available via winget now
```
PS C:\> winget search quarto
Name   ID             Version Quelle
-------------------------------------
Quarto RStudio.quarto 1.1.149 winget
```

**Comment by dpprdan** [comment] 2022-08-31 09:34
v.1.1.149 did not fix this 

```powershell
PS C:\> winget install RStudio.quarto -v 1.1.149
Found Quarto [RStudio.quarto] Version 1.1.149
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.149/quarto-1.1.149-win.msi
  ██████████████████████████████  70.9 MB / 70.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\> gcm quarto

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     quarto.cmd                                         0.0.0.0    C:\Program Files\Quarto\bin\quarto.cmd


PS C:\> quarto -V
error: Found argument 'Files\Quarto\bin\\tools\deno.exe' which wasn't expected, or isn't valid in this context

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
```

I doubt that this has anything to do with winget though. I saw the same problem installing quarto manually with the msi installer. v1.1.165 fixes this.

AFAIK winget always installs quarto with machine scope (all users) for now, by the way, because the winget manifests do not have a user scope entry and the winget default is [machine scope](https://github.com/microsoft/winget-pkgs/discussions/16219#discussioncomment-827014) then (see also https://github.com/microsoft/winget-pkgs/discussions/76300).

**Comment by KronosTheLate** [comment] 2022-08-31 11:06
The command `quarto` is now on my path, so this issue could be considered resolved. I am however also getting the error seen in the comment above:
```
PS C:\Users\Dennis Bal> winget uninstall quarto
Found Quarto [RStudio.quarto]
Starting package uninstall...
Successfully uninstalled
PS C:\Users\Dennis Bal> winget search quarto
Name   Id             Version Source
-------------------------------------
Quarto RStudio.quarto 1.1.149 winget
PS C:\Users\Dennis Bal> winget install quarto
Found Quarto [RStudio.quarto] Version 1.1.149
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.149/quarto-1.1.149-win.msi
  ██████████████████████████████  70.9 MB / 70.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Users\Dennis Bal> quarto
error: Found argument 'Files\Quarto\bin\\tools\deno.exe' which wasn't expected, or isn't valid in this context

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
```

**Comment by cderv** [comment] 2022-08-31 12:43
Thanks both of you.  Glad the PATH issue with winget is resolved. 

Our new version 1.1.165 should fix the other issue with space in Program files, and I'll do test on that.

**Closed** 2022-08-31 12:45 UTC

**Comment by dpprdan** [comment] 2022-09-01 15:03
@KronosTheLate v1.1.165 is now available via winget https://github.com/microsoft/winget-pkgs/pull/76319

**Comment by cderv** [comment] 2022-09-01 15:09
Thanks @dpprdan . 

BTW we already have a new version. I suggest we wait for our final v1.1 before any other version are pushed through winget. I don't know how many it will be, probably not much but it is worth the wait I believe. Thanks for you help and contribution on this!

**Comment by cderv** [comment] 2022-09-01 15:38
I completely agree with you here and I am just talking about this specific v1.1 release. Things will be more smooth for v1.2 and subsquent releases. 

> Eventually I think it's best to automate the publishing via winget, rather than waiting for the final final release, though.

Currently it is a choice we made not to automate on winget. We'll reconsider for future releases probably.
