### ISSUE TITLE
use "#| label: eq-xxx" to add label to equation generated in code chunks (e.g. sympy) 

### ISSUE THREAD

**Issue by kompre** [quarto-dev/quarto-cli#3397] opened 2022-11-19 21:30 UTC
### Bug description

Hello,

I noticed that for figures and tables generated by a code chunks, Quarto let me reference those by adding a `#| label:` and the relevant label. The same isn't true for equation generated by code chunks.

I would like to display math and equation expressions that actually works in the document, so I'm thinking about using `sympy` or `handcalcs` to display nicely formatted math expression that actually yield results; these equation need to be cross referenceable across the document.

I got a working example where I show the issue using sympy, and a workaround that let me reference a sympy expression by wrapping it in a ``$$...$$` environment, similar to the solution used for displaying pandas dataframe mentioned in the guide.

[equation_label_in_code_chunks.pdf](https://github.com/quarto-dev/quarto-cli/files/10047971/equation_label_in_code_chunks.pdf)

(I would like to attach also the qmd file, but it doesn't seems to be supported by github)

![image](https://user-images.githubusercontent.com/11796345/202872270-85f2ea29-8226-4c6d-ba12-bcbedb570ef4.png)

(So I tricked it by changing the extension, just rename it)

[change file extension to qmd.md](https://github.com/quarto-dev/quarto-cli/files/10047974/change.file.extension.to.qmd.md)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2022-11-19 23:31
This would be a great feature to have. 

We're hoping to put in some work in crossrefs in this pre-release version. In the meantime, if you have a way to generate Markdown from sympy, you can work around this limitation by producing Markdown that conforms to [this syntax](https://quarto.org/docs/authoring/cross-references.html#equations) and Quarto should be able to find the cross reference.

**Comment by kompre** [comment] 2022-11-20 10:03
> you can work around this limitation by producing Markdown that conforms to [this syntax](https://quarto.org/docs/authoring/cross-references.html#equations) and Quarto should be able to find the cross reference.

That is exactly the workaround I used in the qmd file attached above, and it works quite well. The only issue I have with that is that such reference get processed only when rendering, therefore the quarto extension (vscode) does not know about it and it doesn't offer it in the autocompletion list that appears when I type @.

Hence it could become an inconvenience during the draft, even tough the final output looks good

**Comment by cscheid** [comment] 2023-05-23 17:28
Note to quarto devs: In Quarto 1.4's new crossref system, this is a duplicate of #2297 and #1556. Specifically, if the markdown content tells us there is a crossreferenceable item of some kind, we should trust the user to be right and accept that, even if the content doesn't match our expectation. (#2297 and #1556 are about Float crossrefs, and this is about an Inline crossref. But the principle is the same.)

**Closed by cscheid** 2023-05-23 17:28 UTC
Labels: duplicate, enhancement, crossref
