### ISSUE TITLE
Code-Generated R Figures Not Center-Aligned with `format: typst`

### ISSUE THREAD

**Issue by mgastner** [quarto-dev/quarto-cli#9312] opened 2024-04-09 09:32 UTC
### Bug description

When `format: typst`, the execution option `fig-align: center` fails to center-align figures. Instead, figures appear left-aligned. The expected behavior is that figures should be center-aligned when this option is used.

To verify against any potential Quarto-syntax errors, I conducted tests by changing `format: typst` to `format: pdf` in the example QMD files. In this scenario, all figures appeared center-aligned as expected.

Currently, the only method I can think of to achieve the desired effect is to save the figure as a file and then display it using plain Markdown syntax (see example below). However, this workaround is suboptimal as it introduces an additional step and results in a superfluous file.

### Steps to reproduce

Option 1: Using local execution option

````{qmd}
---
title: "How Can Figures Be Center-Aligned?"
format: typst
---

```{r}
#| label: setup
#| message: false

library(ggplot2)
gg <- ggplot(mtcars, aes(wt, mpg)) + geom_point()
ggsave("mtcars.svg", plot = gg, width = 4, height = 3)
```


# First Attempt

```{r}
#| label: fig-place-fig-align-in-chunk
#| echo: fenced
#| fig-align: center
#| fig-width: 4
#| fig-height: 3
#| fig-cap: "A scatterplot of the `mtcars` dataset."

gg
```


# Second Attempt

```{r}
#| fig-align: center
#| fig-cap: "A scatterplot of the `mtcars` dataset."


knitr::include_graphics("mtcars.svg")
```


# Third Attempt

![A scatterplot of the `mtcars` dataset.](mtcars.svg){width="50%"}
````

Option 2: Using global execution option

````{qmd}
# Fourth Attempt

```{r}
#| label: fig-place-fig-align-in-chunk
#| echo: fenced
#| fig-align: center
#| fig-width: 4
#| fig-height: 3
#| fig-cap: "A scatterplot of the `mtcars` dataset."

gg
```
````

[centered_using_local_option.pdf](https://github.com/quarto-dev/quarto-cli/files/14916433/centered_using_local_option.pdf)
[centered_using_global_option.pdf](https://github.com/quarto-dev/quarto-cli/files/14916466/centered_using_global_option.pdf)

### Expected behavior

Figures should be center-aligned when the `fig-align: center` option is used in conjunction with `format: typst`.

### Actual behavior

Figures are displayed left-aligned instead of being centered, despite using the `fig-align: center` option with `format: typst`.

### Your environment

- IDE: RStudio 2023.12.1+402
- OS: MacOS Sonoma 14.4.1

### Quarto check output

Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment] 2024-04-09 09:33
Duplicate of #8767

**Closed by mcanouil** 2024-04-09 09:33 UTC
Labels: bug
