### ISSUE TITLE
Preview images are distorted

### ISSUE THREAD

**Issue by richardsprague** [quarto-dev/quarto-cli#4998] opened 2023-03-28 20:03 UTC
### Bug description

I have a nice listing grid that renders correctly, but the preview images are distorted.  Apparently, `preview-image` is trying to make the entire image fit within the confines of `class="thumbnail-image card-img"`. On 1.2, it crops the image rather than distort it. Here's the html:

![image](https://user-images.githubusercontent.com/2120747/228351807-cfe89257-b75a-405a-b257-a5a62c4e280d.png)

Reproducible example in this repo [richardsprague/quartosample: extrapage](https://github.com/richardsprague/quartosample/tree/extrapage)

Using 1.3.290 on OSX 13.2.1

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment] 2023-03-28 20:37
This should be fixed in our next pre-release build. Duplicate of #4985.

**Closed by dragonstyle** 2023-03-28 20:37 UTC
Labels: bug, triaged-to
