### ISSUE TITLE
RStudio "Render Website" doesn't render all outputs (sometimes)

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#4525] opened 2023-02-24 22:27 UTC
### Bug description

Using template website created with `quarto create`, and editing YAML in `about.qmd` to specify a couple of formats:
````
---
title: "About"
format:
  revealjs: default
  pdf: default
---
````
I would expect if I hit RStudio's "Render Website" I would have `about.pdf` and `about.html` (Revealjs slides) in `_site/`, but I'm missing `about.pdf`:
```
_site
├── about.html
├── index.html
├── search.json
├── site_libs
└── styles.css
```

I actually get the same thing from `quarto preview` (no `about.pdf`), although if I then navigate to `about.html`, `about.pdf` is generated. (Browsing to `about.html` from the Preview of "Render Website", does not trigger a render of `about.pdf`). 

`quarto render` generates all files as expected.

I thought the problem didn't occur with `pdf` and `html`:
```
---
title: "About"
format:
  html: default
  pdf: default
---
```
~~But, I seem to be having the same problem with "Render Website" for this too.~~ While `about.pdf` isn't generated initially, it does get triggered if I hit the PDF version in the "Other Formats" links. 

(@mine-cetinkaya-rundel)

This feels a bit like #4469 - but I'm not convinced they are exactly the same problem.

Mac OS, Version 2023.03.0-daily+302 (2023.03.0-daily+302), dev Quarto

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2023-02-27 15:49
(This is the same format pinning issue we've discussed before, I'm pretty sure, right @jjallaire?.)

**Comment by prosoitos** [comment] 2023-10-24 04:36
Not sure whether this is pertinent to the same issue or whether I should open a different one, but for many months (maybe after my website reached a certain size??), `quarto render` has systematically failed to render the `site_libs`.

For this to get created, after a full `quarto render`, I have to run a `quarto preview`.

This is for the website at https://github.com/WestDRI/arc-training.

**Comment by cscheid** [comment] 2023-10-24 13:54
@prosoitos We use quarto render on https://quarto.org, so I don't believe size is an issue. Unfortunately, we need a small reproducible case to be able to help.

**Comment by prosoitos** [comment] 2023-10-24 14:11
If it is not a known problem, it probably is something idiosyncratic to my system and setup again.

It is not a huge issue. I just have to do a preview after every render.

I believe my site might be quite a bit larger than the Quarto site, with several heavy reveal.js presentations in it. Renders are taking quite a long time now, even with freezing and caching, so I wouldn't rule out size to be the problem. But I could be totally wrong. I'll do some testing when I have time and try to produce a small reproducible example (although that might be impossible if it has to do with size).

**Comment by jcoliver** [comment] 2024-05-02 22:36
Same behavior (PDF formats not created when "Render Website" button is pressed, but PDF file _is_ generated when clicking the "PDF" hyperlink in the Other formats section on the rendered HTML) on Ubuntu 22.04, R 4.4.0, RStudio 2023.06.0, quarto 1.4.

**Comment by cscheid** [comment] 2024-06-11 21:24
This is the output of `quarto render` on a project created in that fashion. Note the presence of both `about.pdf` and `about.html` as a revealjs file:

```
$ ls -l
total 136
drwxr-xr-x  8 cscheid  staff   256B Jun 11 14:18 .
drwxr-xr-x  8 cscheid  staff   256B Jun 11 14:18 ..
-rw-r--r--  1 cscheid  staff    31K Jun 11 14:18 about.html
-rw-r--r--  1 cscheid  staff   4.8K Jun 11 14:18 about.pdf
-rw-r--r--  1 cscheid  staff    20K Jun 11 14:18 index.html
-rw-r--r--  1 cscheid  staff   230B Jun 11 14:18 search.json
drwxr-xr-x  8 cscheid  staff   256B Jun 11 14:18 site_libs
-rw-r--r--  1 cscheid  staff    17B Jun 11 14:18 styles.css
$ head -n 25 about.html
<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-html.min.css" rel="stylesheet" data-mode="light">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-99.9.9">

  <title>Issue-4525 – About</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
```

It is true that `quarto preview` sometimes operates incrementally, but that's not a bug; that's a feature, and when the .pdf file is requested, the standalone preview server renders and displays it.

If this behavior isn't happening inside RStudio, then it's likely that this is an RStudio bug?

I'm going to go ahead and close this one, but please feel free to reopen if you believe my assessment is wrong.

**Closed by cscheid** 2024-06-11 21:24 UTC
Labels: bug, editors, rstudio

**Comment by prosoitos** [comment] 2024-06-12 16:31
For info, the problem I had and mentioned above about site_libs not being produced during a render got fixed by a reinstall of Quarto.

**Comment by jcoliver** [comment] 2024-06-21 18:02
Will try to create a reprex, but I notice this behavior (of only rendering into HTML and _not_ into PDF format) seems to only occur on the second (and subsequent) press of the "Render" button. That is, I can open a new RStudio session, edit a qmd file, and press the "Render" button and both HTML and PDF outputs are created (both formats are listed in the `format` section of my _quarto.yml file). However, in the same RStudio session, if I make additional changes and press the "Render" button (just clicking the button, not using the drop-down options to pick either HTML or PDF) _only_ the HTML-formatted file is created. This might help with understanding the idiosyncratic behavior.

**Comment by cscheid** [comment] 2024-06-21 18:17
@jcoliver Thanks for the added context. It's still the case that you're experiencing this only inside RStudio, right?

If so, then the place to report that is https://github.com/rstudio/rstudio

**Comment by jcoliver** [comment] 2024-07-03 23:45
Done! https://github.com/rstudio/rstudio/issues/14920
