### ISSUE TITLE
Invalid (Julia) jupyter YAML data found in file

### ISSUE THREAD

**Issue by cadojo** [quarto-dev/quarto-cli#1884] opened 2022-08-14 19:32 UTC
### Bug description

I've been using Python on my website, but I recently added Julia too. On my CI, this works fine. On local MacOS, this fails due to an error shown with `quarto check` (shown below).

I have Julia 1.7 installed, and I've installed `IJulia`. My operating system is MacOs 12.5.

- Website Source: https://github.com/cadojo/aperiodic

### `quarto check` Output

```
➜ quarto check

[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /opt/homebrew/opt/python@3.10/bin/python3.10
      Jupyter: 4.11.1
      Kernels: julia-1.7

[✓] Checking Jupyter engine render....OK

ERROR: Invalid jupyter YAML metadata found in file (must be string or object)
```

### `quarto tools check` Output

```
quarto tools check
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [x] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [x] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cadojo** [comment] 2022-08-14 20:43
I believe this is a MacOs configuration issue, because the same conditions work in my CI, but do not work locally. I'm not sure where any Quarto configuration files are outside of the project I'm working on. Please let me know if I should add anything else!

**Comment by cadojo** [comment] 2022-08-15 02:50
This happens on the development build (GitHub repo) too. That output is...

```

ERROR: Invalid jupyter YAML metadata found in file (must be string or object)

Error: Invalid jupyter YAML metadata found in file (must be string or object)
    at jupyterKernelspecFromMarkdown (file:///Users/joey/GitHub/Personal/quarto-cli/src/core/jupyter/jupyter.ts:482:7)
    at async quartoMdToJupyter (file:///Users/joey/GitHub/Personal/quarto-cli/src/core/jupyter/jupyter.ts:238:34)
    at async createNotebookforTarget (file:///Users/joey/GitHub/Personal/quarto-cli/src/execute/jupyter/jupyter.ts:391:14)
    at async Object.target (file:///Users/joey/GitHub/Personal/quarto-cli/src/execute/jupyter/jupyter.ts:159:12)
    at async fileExecutionEngineAndTarget (file:///Users/joey/GitHub/Personal/quarto-cli/src/execute/engine.ts:192:18)
    at async renderFiles (file:///Users/joey/GitHub/Personal/quarto-cli/src/command/render/render-files.ts:279:36)
    at async render (file:///Users/joey/GitHub/Personal/quarto-cli/src/command/render/render-shared.ts:92:18)
    at async checkJupyterRender (file:///Users/joey/GitHub/Personal/quarto-cli/src/command/check/check.ts:145:18)
    at async file:///Users/joey/GitHub/Personal/quarto-cli/src/command/check/check.ts:111:9
    at async withSpinner (file:///Users/joey/GitHub/Personal/quarto-cli/src/core/console.ts:85:5)
```

**Comment by jjallaire** [comment] 2022-08-15 12:55
Thanks for reporting this. The issue was that we were assuming that if Jupyter is installed then a Python kernel is also available (not necessarily the case though!). I have a fix for this here: https://github.com/quarto-dev/quarto-cli/commit/e35f349487a6188b23380a21028001834679d2cc

**Comment by cadojo** [comment] 2022-08-15 23:04
Thank you @jjallaire! I actually still get the error though after updating the development install with your commit.

In my [project](https://github.com/cadojo/aperiodic), I run `quarto preview` and get the following output on my MacOs machine. Once again, CI works just fine. 

I have tried to install a Python kernel with `python -m pip install jupyterlab`. This all happened after I installed the `IJulia`Julia package, so I'm wondering if something messed up my Quarto install. 
```sh
Preparing to preview
ERROR: Invalid jupyter YAML metadata found in file (must be string or object)

Error: Invalid jupyter YAML metadata found in file (must be string or object)
    at jupyterKernelspecFromMarkdown (file:///Users/joey/GitHub/Personal/quarto-cli/src/core/jupyter/jupyter.ts:482:7)
    at async quartoMdToJupyter (file:///Users/joey/GitHub/Personal/quarto-cli/src/core/jupyter/jupyter.ts:238:34)
    at async createNotebookforTarget (file:///Users/joey/GitHub/Personal/quarto-cli/src/execute/jupyter/jupyter.ts:394:14)
    at async Object.target (file:///Users/joey/GitHub/Personal/quarto-cli/src/execute/jupyter/jupyter.ts:159:12)
    at async fileExecutionEngineAndTarget (file:///Users/joey/GitHub/Personal/quarto-cli/src/execute/engine.ts:192:18)
    at async renderContexts (file:///Users/joey/GitHub/Personal/quarto-cli/src/command/render/render-contexts.ts:195:30)
    at async renderFormats (file:///Users/joey/GitHub/Personal/quarto-cli/src/command/render/render-contexts.ts:285:22)
    at async inputTargetIndex (file:///Users/joey/GitHub/Personal/quarto-cli/src/project/project-index.ts:76:19)
    at async resolveInputTarget (file:///Users/joey/GitHub/Personal/quarto-cli/src/project/project-index.ts:166:17)
    at async serveFiles (file:///Users/joey/GitHub/Personal/quarto-cli/src/project/serve/serve.ts:626:20)
```

**Comment by cadojo** [comment] 2022-08-15 23:06
```sh
➜ quarto check

[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/joey/GitHub/Personal/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /opt/homebrew/opt/python@3.10/bin/python3.10
      Jupyter: 4.11.1
      Kernels: julia-1.7

      NOTE: No Jupyter kernel for Python found

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

It seems the `quarto check` does not check for a Julia kernel, could that be the issue? @jjallaire

**Comment by jjallaire** [comment] 2022-08-15 23:08
That was actually my initial fix (to not run the jupyter check if there is no Python) so that's working as expected. I didn't do anything w/ quarto preview though -- thanks for that lead, should be able to narrow it down quickly from here!

**Comment by cadojo** [comment] 2022-08-15 23:13
Thank you for the quick replies! I don't mean to rush you here, just posting things as I see them :) thanks to you and the whole team, I love Quarto!

**Comment by jjallaire** [comment] 2022-08-17 14:24
I'm unfortunately not able to repro this. Could you provide the exact source file you are using that yields this problem?

**Comment by jjallaire** [comment] 2022-08-18 13:19
I'm going to close this since I am not able to repro. Feel free to re-open if you can post a reproducible example along w/ info on your config (`quarto check`)

**Closed by jjallaire** 2022-08-18 13:19 UTC
Labels: bug
