### ISSUE TITLE
Not evaluating inline code consistently

### ISSUE THREAD

**Issue by pommevilla** [quarto-dev/quarto-cli#40] opened 2021-06-21 02:57 UTC
When rendering the following `example.rmd` I ran into some inconsistencie regarding evaluation of inline code:

```
--- 
title: "RStudio Workbench"
date: "`r Sys.Date()`"
---

One plus two is `r 1 + 2`.

Today's date is `r Sys.Date()`.
```

When I knit `example.rmd`  in Rstudio, I get the expected output:

![image](https://user-images.githubusercontent.com/6981612/122700841-a9348300-d211-11eb-930c-0bc6a5dbbee6.png)

Calling `quarto render example.rmd` gives:

![image](https://user-images.githubusercontent.com/6981612/122701007-f57fc300-d211-11eb-9ea2-b4c501715892.png)

When I label it as `example.qmd` and render it from RStudio, I get this:

![image](https://user-images.githubusercontent.com/6981612/122700876-bbaebc80-d211-11eb-8d12-8c9481bacd2b.png)

Calling `quarto render example.qmd` gives:

![image](https://user-images.githubusercontent.com/6981612/122700940-db45e500-d211-11eb-9dd3-f2ac1c63bb58.png)

This was on the most recent dev release of `quarto-cli`.

**Comment by jjallaire** [comment] 2021-06-21 20:00
You should be able to work around this for now by just adding `knitr: true` to the `_quarto.yml` file or by changing the file extensions to `.Rmd` (the issue is that the inline R code isn't tripping the auto-engine detection code)

**Comment by jjallaire** [comment] 2021-06-21 20:07
Actually that won't full work around the second issue you identified (still figuring out what is going on there)

**Comment by cderv** [comment] 2021-06-22 08:01
About the inline code used in YAML header, how does quarto handle the metadata before the knitr step ? 

With **rmarkdown**, the whole Rmd file is knitted including the YAML header. This means that any inline R code in YAML will be evaluated by knitr to be replaced for Pandoc to read the resulting value as metadata. 

When I run `quarto render`, the message shows that metadata are retrieved before knitting:
````
> quarto::quarto_render("test.Rmd")


processing file: test.Rmd
  |......................................................................| 100%
   inline R code fragments


output file: test.knit.md

pandoc 
  to: html
  from: markdown
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  filters:
    - crossref
  
metadata
  document-css: false
  link-citations: true
  title: RStudio Workbench
  date: '`r Sys.Date()`'
  
Output created: test.html
````

We see that the metadata that are read (and seemed to be used in the resulting document) are not the one after knitting step, because the inline R code is still there.

Is the YAML header part of what is knitted ? and if so, are the Pandoc metadata re-read after this knitted step so that the result of knitr inline code can be used as Medatata. 

I am not yet enough used to quarto cli codebase to check this myself, so I am sharing this idea here before looking at the source code.

This is also a practice we possibly want to change as it will work only with knitr engine. I don't know how you can do inline code with jupyter engine. The aim is to be able to problematically sets some metadata for Pandoc - date is often set that way, but sometimes title too or other. I don't know if there is already another way of doing that with Quarto.

**Comment by jjallaire** [comment] 2021-06-22 10:22
All these documents should now render as expected (resolved by https://github.com/quarto-dev/quarto-cli/commit/341cc3b8eb79c6cc53e172dec3b532148db107c9 and https://github.com/quarto-dev/quarto-cli/commit/4240d00e97fe232adcf8a2fd23da4242d795c9a9).

@cderv You are correct that formerly all yaml was processed by quarto _before_ calling the knitr engine (so inline expressions didn't work at all). It's actually not possible for us to make inline R expressions work everywhere b/c we do need to handle the markdown prior to engine processing (e.g. merging from project files, resolving format specific metadata, etc.).

What I've implemented here is a limited ability to continue to do this for regular pandoc metadata fields (e.g. `title`, `date`, etc. -- basically anything valid at the top-level that isn't a quarto internal field like `keep-md`, `theme`, etc.). The reason that quarto fields can't use R expressions is that we need them to actually determine how and what to execute.

**Comment by cderv** [comment] 2021-06-22 12:59
That makes sense to allow it for some common field use as variable by Pandoc, and not for Quarto config. 
This is the same limitation with **rmarkdown** actually where some YAML fields don't support inline knitr code because the value is used by rmarkdown directly before any knitr rendering. (like the `output:` field option and any other directly related to `rmarkdown::render()`). For other field, this is why currently you have to use `! expr` at the start of the YAML field if you want to pass R code to determine the value. **rmarkdown** will load the YAML using the **yaml** package which allow this syntax. 

So currently, this is not very clear what to use and how when you want to do something like that. If we think there is a better way to set those type of Pandoc variables with the execution engine, then there is an opportunity for quarto to offer a new clearer solution. 

But I believe the most common use case are inside `title` and `date` for R users and this is now covered with your change.

**Comment by jjallaire** [comment] 2021-06-22 14:00
Yes, this should definitely cover the common cases. Note that !expr won't
work at all b/c the reader of the markdown is quarto not R.

**Comment by cderv** [comment] 2021-06-22 16:55
> Note that !expr won't
work at all b/c the reader of the markdown is quarto not R.

yes I have noted that. This will be something to document when we tackle conversion documentation from Rmd with rmarkdown to Quarto rendering. But I believe most use case are in the `output:` field which is no more used. We'll see. Thanks!

**Closed** 2021-06-26 01:12 UTC
