### ISSUE TITLE
kbd is not styles for revealjs outcome

### ISSUE THREAD

**Issue by EmilHvitfeldt** [quarto-dev/quarto-cli#6477] opened 2023-08-09 17:42 UTC
### Bug description

The [kbd shortcodes](https://quarto.org/docs/authoring/markdown-basics.html#keyboard-shortcuts) doesn't have style applied to them. The icons looks fine, but it doesn't have then button look that comes in the html format.

The html styling happens here:
- https://github.com/quarto-dev/quarto-cli/blob/174828920f27decc77f627682d3404da494ca146/src/resources/formats/html/bootstrap/_bootstrap-rules.scss#L909-L918
- https://github.com/quarto-dev/quarto-cli/blob/174828920f27decc77f627682d3404da494ca146/src/resources/formats/html/bootstrap/_bootstrap-rules.scss#L1264-L1271

I would be happy to provide an PR to fix this!

### Steps to reproduce

````qmd
---
format: revealjs
---

## Using `kbd`

To print, press {{< kbd Shift-Ctrl-P >}}. To open an existing new project, press {{< kbd mac=Shift-Command-O win=Shift-Control-O linux=Shift-Ctrl-L >}}.

````

### Expected behavior

![Screenshot 2023-08-09 at 10 23 28 AM](https://github.com/quarto-dev/quarto-cli/assets/14034784/14ea12b8-a187-418a-964b-353fbb1a7a95)

### Actual behavior

![Screenshot 2023-08-09 at 10 12 26 AM](https://github.com/quarto-dev/quarto-cli/assets/14034784/8facde29-095e-461a-b36e-db424c5d2890)

### Your environment

- IDE: Version 2023.09.0-daily+233 (2023.09.0-daily+233)
- OS: Ventura 13.4

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.309
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2021.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/emilhvitfeldt/Library/TinyTeX/bin/universal-darwin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.7 (Conda)
      Path: /Users/emilhvitfeldt/miniforge3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter
```

**Comment by mcanouil** [comment] 2023-08-09 19:16
Duplicate of #6012 (closing)

This being said, PRs are welcome.

**Closed by mcanouil** 2023-08-09 19:16 UTC
Labels: bug
