### ISSUE TITLE
Lua filters not found when upgrading to pre-release version on Mac OS

### ISSUE THREAD

**Issue by mikheyev** [quarto-dev/quarto-cli#4433] opened 2023-02-20 05:29 UTC
### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mikheyev** [comment] 2023-02-20 05:31
When I upgrade to the pre-release version on Mac OS, I am getting the following error:

```
Error running filter /Applications/quarto/share/filters/authors/authors.lua:
cannot open /Applications/quarto/share/filters/authors/authors.lua: No such file or directory
```

Indeed, these filters are not there.

Downgrading to the latest release version fixes the problem. I tried several recent pre-release versions and they all have this error.

**Comment by dragonstyle** [comment] 2023-02-21 18:49
- How are you installing the pre-release versions on MacOS? I tested locally using quarto `1.3.213` and using the simple `pkg` installer and didn't see any errors. 

- What version of Quarto are you running when you see this error. You can confirm this explicitly using `quarto --version` from the terminal.

Based upon the error, I'm thinking that perhaps somehow you have another copy of Quarto installed / on the path which is still being used somehow, though not completely sure how.

**Comment by mikheyev** [comment] 2023-02-21 23:15
I used the pgk installer and verified that the version changed using `quarto --version` when both upgrading and downgrading. I saw this error with the latest pre-release version, then tried several versions published in the past couple of weeks (sorry didn't write down which ones), then downgraded to the release version and everything works.

**Comment by petrbouchal** [comment] 2023-02-22 12:00
Does this happen when running Quarto from within RStudio? I've had this happen - restarting RStudio helped.

**Comment by dragonstyle** [comment] 2023-03-13 13:47
Ok I'm closing for now since I can't find a repro to help debug. If this does come up again, please feel free to re-open and I'll be pinged!

**Closed by dragonstyle** 2023-03-13 13:47 UTC
Labels: bug, need-repro

**Comment by drscotthawley** [comment] 2023-06-13 03:22
@dragonstyle I just updated quarto using the Mac installer from the website and now I'm getting this error.  

Previously I had 
```
$ quarto --version
1.2.269
```
...and everything was working fine.   But I couldn't get my images to appear in previews on Twitter or other websites. So Ithought I'd try updating.

After installing the new Mac package, I have
```
$ quarto --version
1.3.361
```

but the problem is that when I run `quarto publish`, I get the error
```
Error running filter /Applications/quarto/share/filters/authors/authors.lua:
cannot open /Applications/quarto/share/filters/authors/authors.lua: No such file or directory
```

How do we update in such a way that we can fix this?   Thanks.
