### ISSUE TITLE
table html parsing - add missing docs

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#9697] opened 2024-05-16 14:29 UTC
We're missing docs about one way to disable table parsing (html comment)

**Comment by cwickham** [comment] 2024-06-05 19:49
We do mention it here: https://prerelease.quarto.org/docs/authoring/tables.html#library-authors

**Comment by cwickham** [comment] 2024-06-05 19:51
Duplicate of https://github.com/quarto-dev/quarto-cli/issues/9215

**Closed by cwickham** 2024-06-05 19:51 UTC
Labels: documentation
