### ISSUE TITLE
Access array elements in shortcodes like `{{< meta >}}`

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#6769] opened 2023-09-08 10:35 UTC
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/6764

<div type='discussions-op-text'>

<sup>Originally posted by **multimeric** September  8, 2023</sup>
### Description

The quarto documentation explains how to use metadata within the document, and also how to access nested values using the dot notation: https://quarto.org/docs/authoring/variables.html. However, it doesn't explain how to access array/list elements, and indeed I can't find a syntax that supports this. 

In the following document I show my attempts to do this:

```
---
top: "Top Lvel"
nested:
    str: "Nested String"
    array:
        - foo
        - bar
---

{{< meta top >}}
{{< meta nested.str >}}
{{< meta nested.array[0] >}}
{{< meta nested.array[1] >}}
{{< meta nested.array.0 >}}
{{< meta nested.array.1 >}}
```

This renders to PDF like this, showing that none of my attempted array accesses worked:

![Screen Shot 2023-09-08 at 11 57 41 am](https://github.com/quarto-dev/quarto-cli/assets/5019367/310681ed-7452-4002-8914-51ddccb5c8f4)
</div>

**Comment by cscheid** [comment] 2024-01-03 20:55
This is a duplicate of #8086 (which I'm keeping open because of the open PR to close it)

**Closed by cscheid** 2024-01-03 20:55 UTC
Labels: enhancement, triaged-to
