### ISSUE TITLE
VSCode extension : Render on Save not working as expected

### ISSUE THREAD

**Issue by declann** [quarto-dev/quarto-cli#6440] opened 2023-08-05 17:19 UTC
### Bug description

Hi!

Using VSCode extension Render on Save doesn't appear to be obeyed for my website project in the latest 1.4 Quarto.

`quarto preview` (i.e. bypassing extension) is a good workaround for my usecase, but interested in whats going wrong and getting this working inside VSCode.

Thanks!
Declan

### Steps to reproduce

```sh
quarto create
# then select project, website, name: the-website
cd the-website
code .
# F1 > Quarto : Render Project
# edit index.qmd or about.qmd, no reload, despite Render on Save set.
```

### Expected behavior

Expect a reload as I save `.qmd` pages (because Render on Save is turned on in extension preferences)

### Actual behavior

No refresh, I need to Render pages individually to pick up changes

### Your environment

Ubuntu 22.04.2 LTS
VSCode Quarto extension v1.91.0

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.294
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK
```

**Comment by mcanouil** [comment] 2023-08-07 19:55
I cannot reproduce.

https://github.com/quarto-dev/quarto-cli/assets/8896044/9bba93a9-823b-4876-88e4-06135454bb87

**Comment by declann** [comment] 2023-08-12 01:36
Might be OS specific. Is this on Ubuntu?
Quarto version? and is this Render Project command?

my experience now:

![image](https://github.com/quarto-dev/quarto-cli/assets/353214/b3e0f257-3d97-4bc8-9e93-f5607a220de1)

[Screencast from 12-08-23 02:31:53.webm](https://github.com/quarto-dev/quarto-cli/assets/353214/553e3b4e-3bf0-4a76-aa59-945d1a59b444)

**Comment by mcanouil** [comment] 2023-08-12 09:17
The issue is your setup.


https://github.com/quarto-dev/quarto-cli/assets/8896044/bf95b951-c76c-47a7-b59b-b0d39675ce7e

**Comment by declann** [comment] 2023-08-12 10:16
Seems like the button has a different behavior to what I am using:

Press F1 `> Quarto: Render Project` command

Are you reproducing my issue with that path?

Render button works for me but doesn't give me the functionality I want since I am developing multiple pages of a website, i.e. it doesn't render on save across `.qmd` files. Separate issue but think that for projects Render Project is more sensible for the UI?

Another subtle difference I notice (besides different `quarto preview` commands) is that the Render button view includes a zoom setting and defaults to Auto.

Hopefully it's not a lot of work to either bring Render on Save functionality into the Quarto Render command path or else bring those code paths closer if it makes sense? (and if you reproduce behavior I see)

In the meantime, I will use `quarto preview` manual command and external browser.

**Comment by mcanouil** [comment] 2023-08-12 10:56
> I am developing multiple pages of a website

As any website by definition.

I don't understand your issue with using the default preview button `render project` is to render everything in the project, see the `--render all`.


https://github.com/quarto-dev/quarto-cli/assets/8896044/6e06d5ad-2ce0-4564-b01d-ecd15d3dbbd4

**Comment by declann** [comment] 2023-08-12 12:28
You hit multiple Render buttons to show live updates to separate pages - this isn't merely saving the file, which is what I expect by Render on Save when working with a website.

We can argue this expectation might be bad for the button (its unclear if Render should apply to the page or the project - it clearly applies to the page), but when I run `Render Project` then I think that goes away, and my expectation is also how things work when running `quarto preview` outside of the extension.

So try this to reproduce:

Hit Render on the index.qmd file, then navigate to About in the preview, then edit About.qmd - does it update? No? Should it?

Separately:

Run `Render Project` command via F1, follow the same process - does it update - if not - you are reproducing what I'm experiencing, and it is not working as I'm expecting. It is a bug, unless my expectation is bad.

Finally:

Run `quarto preview` in the project folder without using the extension. Edit about.qmd, you see a live refresh. Edit index.qmd, a live refresh that navigates to the index page. This is the DX I am expecting, and certainly, it works better for me when dealing with projects (multiple pages).

**Comment by mcanouil** [comment] 2023-08-12 12:36
Did you look at the video?
I went back twice to edit and see the previewed pages.
Where do you see me hit render every time?

**Comment by declann** [comment] 2023-08-12 12:50
Oh, you hovered where I thought you clicked. So you clicked once.

So this is what I'm understanding from the video:

You are getting a live render for index.qmd - as that is where you clicked the button.

When you edited index.qmd where you were navigated to the About page, the preview was brought back to the index page.

However when you edited about.qmd from index.qmd, the preview was not brought back to the About page.

`quarto preview` has a different behavior that appears to be deliberate and preferable.

The button is a little ambiguous because it does not say Render Project, however the **command `Render Project` does not appear to respond to Render on Save at all**.

**Comment by mcanouil** [comment] 2023-08-15 13:45
Currently Quarto does not follow/sync with code changes when previewing, so you have to navigate to the pages you changed.
This should get better with #6518 as Quarto will have more knowledge of which document creates which pages, etc.

Regarding the "ambiguous" naming, this has been discussed in Quarto team. `render` button does render everything, but also preview if possible the document(s).
Regarding, the command associated with `Render Project`, I am not sure if it is a bug/conflict or a design that  `render-on-save: true` does not work when `--render all`.

**Comment by mcanouil** [comment] 2023-08-30 06:00
> Regarding, the command associated with `Render Project`, I am not sure if it is a bug/conflict or a design that `render-on-save: true` does not work when `--render all`.

@cscheid @jjallaire any pointer here? I would personally assume, `--render all` would still respect the option even if only for the format being previewed.

**Comment by cscheid** [comment] 2024-06-17 20:35
(@mcanouil sorry to revive this old issue, but I don't understand your question here, and I'd like to.)

**Comment by mcanouil** [comment] 2024-06-17 20:40
If I recall properly, setting `render-on-save: true` in VSCode has no effect when rendering a project using the command from the command palette.
It only applies when previewing one format.

<img width="597" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/90f14f49-dd05-402d-8882-07feed67e4fd">

I am not sure it still applies as the extension and Quarto CLI had many changes in that area in the past year.

**Comment by cscheid** [comment] 2024-06-17 20:51
> If I recall properly, setting render-on-save: true in VSCode has no effect when rendering a project using the command from the command palette.

Sorry, I still don't understand. it's "render-on-save", not "save-on-render". Why should an option that triggers on save have any effect on a command that is about rendering?

**Comment by mcanouil** [comment] 2024-06-17 20:54
I think at that time, there was a preview but it was not trigger on save when "render all".

**Comment by mcanouil** [comment] 2024-06-17 20:56
But I really need to check and test again the VSCode commands.

For instance the command has been renamed since this issue.

**Comment by mcanouil** [comment] 2024-06-23 13:55
Let's close this as, I tried and everything seems to work as I would expect (at least now).

The original post issue was a confusion with preview/render and the `render-on-save` option designed to work with `quarto preview`.

**Comment by mcanouil** [comment] 2024-06-23 13:58
Re-qualifying this as support and closing.

In case, there is still an issue, please go to <https://github.com/quarto-dev/quarto>.

**Closed by mcanouil** 2024-06-23 13:58 UTC
Labels: triaged-to, vscode, support

**Comment by declann** [comment] 2024-06-23 19:16
If the original issue was a confusion, I don't think the UI change addresses this.

The button says Preview, but `quarto preview` command redirects the browser to the actively edited ('saved') document.
Render on Save suggests that something happens when quarto files are saved. But nothing happens in my normal workflow on websites because -

the Preview command is tied to a single qmd file - **including for a website project**. I can only determine this by studying the command that's issued.

Preview This Page as button would mitigate my confusion, Preview doesn't improve it.

**Comment by mcanouil** [comment] 2024-06-23 20:44
- quarto-dev/quarto#472

Issue is more related to VSCode extension than Quarto CLI, *i.e.*, VSCode extension is missing a "preview project" command. Currently, the `quarto preview` command always take an input file so only that file is watched for changes.
See https://github.com/quarto-dev/quarto/issues/472#issuecomment-2185317653

**Comment by VivaldoMendes** [comment] 2024-08-29 17:20
Hi all,

I have the same problem. 

I am on a Windows 10 machine, Quarto v1.5.56, VSCode v1.92.2 (user setup). I am editing a website using Quarto. Everything works fine except for previewing the **_changes_** I produce in the document. 

Suppose I produce some changes in the document and try previewing them by typing the usual shortcut `Shift+Ctrl+K`. The problem pops in in that case: I can see those changes only if I **_close_** the `Quarto editor` pane and do `Shift+Ctrl+K` again. This is annoying if we have a lot of changes to test in the document. How can I solve this problem? I searched in forums like these and tried to implement the solutions that have been proposed, but I have yet to be successful so far. 

Thanks. 

![a](https://github.com/user-attachments/assets/559c0b81-dc3e-491d-ab74-3d867f41bfa8)

**Comment by mcanouil** [comment] 2024-09-01 15:32
@VivaldoMendes This issue is closed. Please open a new [GitHub Discussion](https://github.com/quarto-dev/quarto-cli/discussions/new?category=q-a) possibly referencign this issue. Thank you!
