### ISSUE TITLE
Incorrect fragment image placement after bullet point in a quarto revealjs presentation

### ISSUE THREAD

**Issue by dmkaplan2000** [quarto-dev/quarto-cli#10063] opened 2024-06-19 14:51 UTC
### Bug description

I am having some strange image placement in a quarto revealjs presentation when the image occurs immediately after a bullet point. The image seems to be placed erratically, sometimes to the right of the text if it will fit. Removing the bullet point fixes this...

### Steps to reproduce

````qmd
---
title: "Test image placement"
format: revealjs
---

## Title...

- Point 1

- Point 2

![](https://static.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg)
````

### Expected behavior

![Screenshot from 2024-06-19 16-47-46](https://github.com/quarto-dev/quarto-cli/assets/584741/ae03bb90-35f7-4358-9073-10111a155bc7)

### Actual behavior

![Screenshot from 2024-06-19 16-49-14](https://github.com/quarto-dev/quarto-cli/assets/584741/d5aef97b-1103-43f6-85f2-e17d7074b8ba)

### Your environment

RStudio 2024.04.2+764 "Chocolate Cosmos" Release (e4392fc9ddc21961fd1d0efd47484b43f07a4177, 2024-06-05) for Ubuntu Focal
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36, Quarto 1.5.27 (/opt/quarto/bin/quarto)

OS: Ubuntu 20.04

### Quarto check output

```bash
$ quarto check
Quarto 1.5.27
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.27
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/dmk/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.13 (Conda)
      Path: /home/dmk/miniforge3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /usr/lib/R
      LibPaths:
        - /home/dmk/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by dmkaplan2000** [comment] 2024-06-21 07:04
Is this the same issue as #9951?

**Comment by mcanouil** [comment] 2024-06-21 07:20
Yes indeed.

**Comment by mcanouil** [comment] 2024-06-21 07:20
Duplicate of #10073

**Closed** 2024-06-21 07:21 UTC
Labels: bug
