### ISSUE TITLE
Code cells of different languages are wrongly merged when inside a layout

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8179] opened 2024-01-09 03:35 UTC
Code cells of different languages are wrongly merged when inside a layout (independently of knitr/Jupyter being the engine)

<table>
<tr><th>Quarto document</th><th>v1.3.450</th><th>v1.4</th></tr>
<tr>
<td>

````qmd
---
title: "Block layout"
format: html
engine: knitr
---

# Code chunk block layout

:::: {layout="[48,-4,48]"}

::: {}

### R

```{r}
sqrt(2)
```

:::

::: {}

### Python

```{python}
import math
math.sqrt(2)
```

:::

::::

````

</td>
<td>
<img width="723" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/c0fb7190-0aa7-4495-a174-0c2aba8989d3">
</td>
<td>
<img width="729" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/bb66d9dd-731d-4b2c-a039-915f0e5172ea">
</td>
</tr>
</table>

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8178

<div type='discussions-op-text'>

<sup>Originally posted by **luifrancgom** January  9, 2024</sup>
### Description

I want to display code chunks side by side where I try the solution specify in #3423 and the instructions pointed out in the documentation [here](https://quarto.org/docs/authoring/figures.html#block-layout) but I did not obtain the expected behavior in relation to the code. The solution only works for the result of the code.

### Steps to reproduce

````qmd
---
title: "Block layout"
format: 
  html: default
  pdf: default
editor: visual
---

# Code chunk block layout

:::: {layout="[48,-4,48]"}

::: {}

### R

```{r}
sqrt(2)
```

:::

::: {}

### Python

```{python}
import math
math.sqrt(2)
```

:::

::::
````
### Expected behavior

![expected_behavior](https://github.com/quarto-dev/quarto-cli/assets/50002526/a639d2e8-6051-4723-b010-8917147ff679)

### Actual behavior

![actual_behavior](https://github.com/quarto-dev/quarto-cli/assets/50002526/80ed2b29-1ef4-434b-b49f-b6c85238409e)

### Question

How can I obtain the expected behavior?

### Quarto and dependencies I am running

```bash
Quarto 1.4.537
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.537
      Path: C:\Users\Usuario\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: 869685

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\Usuario\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.6 (Conda)
      Path: C:/Users/Usuario/anaconda3/python.exe
      Jupyter: 5.7.0
      Kernels: ir, julia-1.9, python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/Usuario/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```</div>

**Comment by cderv** [comment] 2024-01-09 09:06
FWIW this is the intermediate .md 
````markdown
# Code chunk block layout

:::: {layout="[48,-4,48]"}

::: {}

### R


::: {.cell}

```{.r .cell-code}
sqrt(2)
```

::: {.cell-output .cell-output-stdout}

```
[1] 1.414214
```


:::
:::


:::

::: {}

### Python


::: {.cell}

```{.python .cell-code}
import math
math.sqrt(2)
```

::: {.cell-output .cell-output-stdout}

```
1.4142135623730951
```


:::
:::


:::

::::
````

**Comment by cderv** [comment] 2024-01-09 09:22
This is the change that created the regression  [`c4ab028` (#7598)](https://github.com/quarto-dev/quarto-cli/pull/7598/commits/c4ab028a479ebb6834e1394b4ac223b441b3b851) from https://github.com/quarto-dev/quarto-cli/pull/7598 to solve https://github.com/quarto-dev/quarto-cli/issues/4370 

I did a git bisect to confirm

**Comment by cderv** [comment] 2024-01-09 10:49
No need to justify. And no need to do triaging at 4AM too. 😉

**Comment by mcanouil** [comment] 2024-01-09 11:23
@cderv Well, it was no time wasted 😉

**Comment by cscheid** [comment] 2024-01-09 14:33
Let me start by the first comment. The "expected" vs "actual" behavior goes the opposite way. We've always wanted to merge the code from layout cells but weren't doing it in all situations. This is now working as expected, as isn't a bug.

**Comment by cscheid** [comment] 2024-01-09 14:34
We might want to add an option to _not_ to code hoisting, but this isn't a bug.

**Comment by mcanouil** [comment] 2024-01-09 14:35
Well, the two code cells are of different languages. Only code cell sharing the same language should be merged at least.

**Comment by cscheid** [comment] 2024-01-09 14:39
I'm honestly reluctant to change the behavior at this point in the release because that code is pretty fragile.

**Comment by cderv** [comment] 2024-01-09 15:56
>  The "expected" vs "actual" behavior goes the opposite way. We've always wanted to merge the code from layout cells but weren't doing it in all situations. This is now working as expected, as isn't a bug.

I was not expecting this. I am probably missing the use case where merging two different code cells is required ... 🤔 

If indeed we should not merged two cells of different languages, example given in my previous answer (https://github.com/quarto-dev/quarto-cli/issues/8179#issuecomment-1882663591) is mono language python, and it still feels very surprising to have the headers moved in column layout while code source cell is kept outside of columns and merged. 

Example with no merging about this "hoisting" outside 

`````markdown
---
format: html
---

# two columns

:::: {layout="[ 40, 60 ]"}

::: {#first-column}
```{r}
1 + 1
```

Some text that should be laid out below the code
:::

::: {#second-column}
![](https://placehold.co/400)
:::

::::

`````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/4fd00d61-6009-4258-ae4d-cc7ad2b20c8a)

I don't think we have any way to put code cells in layout now. 

It seems to me we want to merge code cells when using in-cell options for layout (https://quarto.org/docs/authoring/figures.html#computations) , as this applies to the cell outputs. In that case currently, `layout*` attributes is put onon the `.cell` div in the intermediate markdown. This is different to me than wrapping in a div of attribute `layout`. 

Feels like a breaking change for 1.4 if this syntax was used in the while to layout in columns some cell code + output content. Let's see if we have more report with RC out.

**Comment by mcanouil** [comment] 2024-01-09 16:00
I do agree with the breaking change/regression part of this.
If it stays that way, it should be really emphasise.

**Comment by mcanouil** [comment] 2024-01-09 16:13
What I am afraid of with this is for all users using the layout in Reveal.js for educational purposes.
It's no longer usable.

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr>
<td>

````qmd
---
title: "Block layout"
format: revealjs
engine: knitr
execute:
  echo: true
---

## Code chunk block layout

:::: {layout="[48,-4,48]"}

::: {#r-code1}

### R

```{r}
sqrt(2)
```

:::

::: {#python-code1}

### Python

```{python}
import math
math.sqrt(2)
```

:::

::::

````

</td>
<td>
<img width="730" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/a928f138-6e6e-49c9-8e8c-6eb6f5c64b83">

</td>
</tr>
</table>

**Comment by cscheid** [comment] 2024-01-09 16:15
> I am probably missing the use case where merging two different code cells is required ... 🤔

[This](https://github.com/quarto-dev/quarto-cli/issues/8187) is a pretty clear case where merging is a good thing. The merging is not going away, I'm sorry. This has been a feature since 1.0.

We _should_ do better in multi-language cases.

I believe that the revealjs case can be solved by using the revealjs columns feature instead of the panel layout.

**Comment by mcanouil** [comment] 2024-01-09 16:22
Indeed, using columns/column does not merge the cells.
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/74fd11c5-2b5e-4eed-a60a-e46f419c3060">

By the way, where this merging behaviour is documented? I cannot find any trace of this.

**Comment by cscheid** [comment] 2024-01-09 16:52
> By the way, where this merging behaviour is documented? I cannot find any trace of this.

This is an example of it in use - https://quarto.org/docs/authoring/figures.html#custom-layout

**Comment by cscheid** [comment] 2024-01-09 17:05
> Indeed, using columns/column does not merge the cells.

And this works in other formats as well (I don't love the padding but you see that the idea is sound)

`````
---
title: columns
---

:::: {.columns}

::: {.column width="50%"}

```{r}
plot(1:10)
```

:::

::: {.column width="50%"}

```{python}
from matplotlib import pyplot as plt
plt.plot([1,2,3,4])
```

:::

::::
`````

<img width="711" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/9c3c1d32-ec82-40d5-89ab-c915a989b846">

I do believe the issues are:

1. we shouldn't merge multiple-language cells. But that's:
  - not trivial to detect and fix
  - relatively rare (multi-language is not a common thing)
  - fixable with .columns  
  
  So we ought to do it in 1.5.
2. The layouts that are not being computed _are_ broken. We ought to do it in 1.4.

**Comment by cscheid** [comment] 2024-01-09 17:48
I think the principle we should be obeying (which, to be clear, we currently are not obeying) is that when `echo: true`, code cells in the output should as they do on the input. Specifically, there should exactly as many output code cells as there are input code cells. knitr breaks those apart, which requires us to do that merging. Quarto 1.3 didn't merge all of them successfully (although I can't seem to find an example of this now). But Quarto 1.4 is currently merging them _too aggressively_.

Again, this is something I would argue for a fix in 1.5, but I think it's good that we agree on the principle.

**Comment by mcanouil** [comment] 2024-01-09 17:55
I would go for 1.5 maybe an "early-in-release" mostly because: 
1. That's the first report
2. "Columns" is nearly the only layout option appearing in search in the documentation so I wouldn't expect this to impact a lot of users.
3. I am starting to think any changes regarding would be at the cost of postponing further away the 1.4 release which is kind of a 2.0 actually 😅

**Closed** 2024-10-08 20:38 UTC
Labels: bug, computations

**Comment by cderv** [comment] 2024-10-09 14:13
So this is what we get now 
![Image](https://github.com/user-attachments/assets/01479a05-ca6b-4b08-886d-17cb81700475)

We probably need to work now on 
- https://github.com/quarto-dev/quarto-cli/issues/6192

to explain different between layout and column outputs. 

As is, this layout feature does not seem useful to me as you can't really know which unmerged code cell is for which column unless you know to read the code. `layout` feature and code cells seems to require `echo: false` if we keep this merging for code cell inside Layout div syntax. (with what [Multicolumns with layout in pdf output don't work when a column contains a code cell #10981](https://github.com/quarto-dev/quarto-cli/issues/10981) is about IMO)

**Comment by cscheid** [comment] 2024-10-09 14:48
The fix here is for the particular ugliness of multi-language cells in a layout

> As is, this layout feature does not seem useful to me as you can't really know which unmerged code cell is for which column unless you know to read the code.

@jjallaire and @dragonstyle had this feature intentionally since the very beginning of the layout feature, so we're not going to change that.
