### ISSUE TITLE
Quarto + Docusaurus 3 rendering problems

### ISSUE THREAD

**Issue by krishaamer** [quarto-dev/quarto-cli#6310] opened 2023-07-22 12:16 UTC
### Bug description

Docusaurus 3 alpha has been release https://github.com/facebook/docusaurus/discussions/9073

In Docusaurus 2.4 https://github.com/quarto-dev/quarto-cli/issues/6046 Quarto integration regressed and citations stopped working.

In Docusaurus 3 alpha rendering MDX inside .qmd files breaks, being rendered as plain text not as components.

<img width="1036" alt="examples" src="https://github.com/quarto-dev/quarto-cli/assets/54409/a64db34b-3652-44f8-8d3c-a207379b5a8d">

I'm reporting this here as my understanding is Quarto controls how the text gets rendered inside Docusaurus.

### Steps to reproduce

Install the package.json with yarn and you should see the problems when rendering Docusaurus with quarto preview or inside VSCode. Here's Docusaurus 3 install documentation in case of any issues: https://docusaurus.io/community/canary

Here's the broken citations repo on Docusaurus 2.4: https://github.com/krishaamer/quarto-broken-citations-reproducible

And in this the branch the broken Docusaurus 3 alpha integration. I also tested the canary from 21/07/2023 and it's the same as the alpha.
https://github.com/krishaamer/quarto-broken-citations-reproducible/tree/docusaurus-3

### Expected behavior

Imports, code and citations should be transformed and rendered.

### Actual behavior

Nothing is transformed or rendered. Imports, code, and citations are displayed as play text.

### Your environment

```
MacOS Ventura 13.4 (22F66)

Visual Studio Code Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:23.298Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0

VSCode Quarto extension v1.90.0
Zotero 6.0.26
Docusaurus 3.0.0-alpha.0 (2023-06-15)
```

### Quarto check output

```
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.251
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /Users/krishaamer/anaconda3/bin/python
      Jupyter: 5.2.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK

```

**Comment by cscheid** [comment] 2023-09-05 17:47
For the Docusaurus 3 support, let's wait until after I merged #6620 so that we don't have to redo the work.

I'll open a separate issue for the Cite regression on 2.4

**Comment by cscheid** [comment] 2023-12-11 21:39
I'm out of my depth when it comes to docusaurus, but the markdown we generate looks good. Your broken.qmd file generates this .md file:

## broken.md

````
---
title: Broken Examples
bibliography: [ref.bib]
csl: chicago.csl
sidebar_position: 3
editor:
    render-on-save: false 
---

## MDX {#mdx}

**MDX remains untransformed and is shown as plain text**

``` text
import Image from "@theme/IdealImage";
import Runaround from './runaround.png'
```

``` mdx-code-block
import Image from "@theme/IdealImage";
import Runaround from './runaround.png'
```

``` mdx-code-block
<Image img={Runaround} alt="Runaround" />
```

## Citations {#citations}

**Citations remain unrendered even though they exist in the ref.bib**

Could a machine imitate a human being so well that one would be
deceived, without realizing one is talking to an AI?
@turingCOMPUTINGMACHINERYINTELLIGENCE1950.
````

This looks to match the syntax that [docusaurus expects](https://github.com/facebook/docusaurus/blob/main/website/docs/guides/markdown-features/markdown-features-code-blocks.mdx). Is it possible that in Docusaurus 3 these files need to have `.mdx` extension instead of `.md`?

**Comment by cscheid** [comment] 2023-12-11 21:45
> Is it possible that in Docusaurus 3 these files need to have .mdx extension instead of .md?

Yes, I think that's what's going on. 

@krishaamer Sorry for the delay on this. I got your project to at least compile, but now Docusaurus complains that 

```
Module not found: Error: Can't resolve '@theme/IdealImage' in '/Users/cscheid/Desktop/daily-log/2023/12/11/quarto-broken-citations-reproducible/research'
```

I see that your package.json installs `@docusaurus/plugin-ideal-image`, but I don't understand why that's not resolving properly. I get the same error if I simply `npm run start` from the root of your repo. Do you have any idea what might be going on?

**Comment by cscheid** [comment] 2023-12-20 22:39
I'm relatively sure this is fixed on `main` now, since I'm testing on Docusaurus 3.0.1. Please reopen if it doesn't address the problem for you. Thanks!

**Closed by cscheid** 2023-12-20 22:39 UTC
Labels: bug, docusaurus
