### ISSUE TITLE
Projects stored in subfolders inherit the rendering settings from the parent directory

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto-cli#3985] opened 2023-01-16 17:52 UTC
### Bug description

I'm not sure if this is an RStudio issue or a Quarto issue (it doesn't happen when using VS Code, so it might be an RStudio thing; but there also might be some setting in Quarto that I'm missing that could fix it).

*(This is all with Quarto 1.3.49 in RStudio 2022.12.0+353 on macOS Ventura 13.1)*

An RStudio Project in a subfolder in a Quarto project inherits the Quarto-ness of the parent directory, so that .Rmd files in the child directory are rendered with Quarto instead of `rmarkdown::render()`. 

As a reproducible example, consider a Quarto project folder structured like this:

```
.
├── _quarto.yml
├── child-project
│   ├── child-project.Rproj
│   └── rmd_document.Rmd
├── index.qmd
└── quarto-parent.Rproj
```

<img width="220" alt="image" src="https://user-images.githubusercontent.com/73663/212736802-4449b763-a712-4cbb-9edc-1a0f16624e1b.png">

**index.qmd**

```markdown
---
title: "Parent project"
---

This is a Quarto file in the overarching project. It gets rendered with Quarto.

```

**child-project/rmd_document.Rmd**

```markdown
---
title: "R Markdown document"
---

This is an R Markdown document. It should get rendered with `rmarkdown::render()`, but sometimes 
it gets rendered with Quarto
```

### Main problem

When the `child-project` folder is placed inside the `quarto-parent` folder, it inherits the fact that it's part of a larger Quarto project and when it is knit, it goes through Quarto instead of `rmarkdown::render()`. 

<img width="629" alt="image" src="https://user-images.githubusercontent.com/73663/212737680-f860317e-2530-46fd-a82f-eda4ceb75142.png">

The "Knit" button in RStudio is replaced with the "Render" button that appears with .qmd files

<img width="405" alt="image" src="https://user-images.githubusercontent.com/73663/212737707-1154603a-f7a0-498a-a5fe-182c353833bd.png">

When the `child-project` folder is placed elsewhere (i.e. if I move it to not be inside a Quarto folder), the document is built with `rmarkdown::render()` as expected…

<img width="630" alt="image" src="https://user-images.githubusercontent.com/73663/212738037-e67332f3-c2f5-4e61-8346-5d888f5cdec9.png">

…and RStudio shows a "Knit" button.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/73663/212737980-ade1e199-f89f-4482-b456-220ba18bb5d5.png">

### Why it's a problem

Often R Markdown files use specific output format options that aren't directly compatible with Quarto. For instance, in [this Quarto project](https://github.com/andrewheiss/evalsp23.classes.andrewheiss.com) I use Quarto to build a website, but the slides for the course are built using {{xaringan}} and are still .Rmd files. Those .Rmd files all live in a [slides subdirectory](https://github.com/andrewheiss/evalsp23.classes.andrewheiss.com/tree/main/slides), and each contains extra metadata in their YAML headers specifying that they should be rendered using {{xaringan}}:

```yaml
output:
  xaringan::moon_reader:
    ...
```

If I open `slides/evalsp23-slides.Rproj` and edit slide files there and then knit the document, Quarto takes over and tries to render the .Rmd file (and can't, since {{xaringan}} isn't one of Quarto's outputs). 

Right now, my workaround is to move that `slides` child directory outside of the main Quarto project folder (like to the Desktop), work on edits and knit documents there (so that R Markdown handles the knitting instead of Quarto), and then move the child directory back into the main Quarto project folder to build the website and upload it. It's a hassle, but it works.

It would be nice if child project directories didn't inherit the Quarto rendering properties of their parent folders so that .Rmd files in those child projects can be build with `rmarkdown::render()` instead of Quarto.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment] 2023-01-17 11:15
> The "Knit" button in RStudio is replaced with the "Render" button that appears with .qmd files

I believe this was an issue reported in IDE but it got missed and closed https://github.com/rstudio/rstudio/issues/11003
Maybe this needs to be reopen. 

Regarding nested project I don't know if this is currently well supported by IDE detections method when inside a project to adapt the UI. 

@jjallaire is this an expected behavior to have "Render" button in all Rmd in IDE ? Can it be deactivated for some to be rendered with **rmarkdown** ? 

> I use Quarto to build a website, but the slides for the course are built using {{xaringan}} and are still .Rmd files. Those .Rmd files all live in a [slides subdirectory](https://github.com/andrewheiss/evalsp23.classes.andrewheiss.com/tree/main/slides?rgh-link-date=2023-01-16T17%3A52%3A22Z), and each contains extra metadata in their YAML headers specifying that they should be rendered using {{xaringan}}

Regarding such situations, Quarto project has the concept of [Rendering Target](https://quarto.org/docs/projects/quarto-projects.html#render-targets) that allows to ignore a full folder explicitely, or just ignore any file and directory starting with `_`. 

This means this ignored folder can be rendered independently using [Quarto Project scripts](https://quarto.org/docs/projects/scripts.html) feature for example to automate a rendering as post render phase, or just using an external R script to render with R Markdown. 

As example you can look at https://datasciencebox.org/ source code with the `_slides` folder (https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides) containing **xaringan** slides. There are also other Rmd in folders. There is a R script [`render-materials.R`](https://github.com/rstudio-education/datascience-box/blob/main/course-materials/render-materials.R) to render the Rmd content. Then the `_slides` folder is listed as resources in the `_quarto.yml` (https://github.com/rstudio-education/datascience-box/blob/main/_quarto.yml#L5) and the Rmd won't be render by Quarto itself because the directory starts with a `_`.

Hope it helps.

**Comment by jjallaire** [comment] 2023-01-17 12:43
I agree that if we detect a file with an `output` metadata key (even when in a Quarto project) that it should use `rmarkdown::render()` (there is logic to detect `output` elsewhere but its obviously being overridden by the project context when it shouldn't be).

Agree with everything @cderv said about using an `_` prefaced directory, project scripts, etc. Inside the IDE though we need a fix which I've made here: https://github.com/rstudio/rstudio/commit/7e0900b4542547cd4e76a8ffb1405cc008ee16ec

**Comment by andrewheiss** [comment] 2023-01-17 14:28
Oh awesome, thanks for the IDE fix!

Right now I'm using the render setting in [`_quarto.yml`](https://github.com/andrewheiss/evalsp23.classes.andrewheiss.com/blob/main/_quarto.yml) to hide `slides/` from Quarto and make it skip the folder (and then [I use {targets} to render the Rmd files](https://github.com/andrewheiss/evalsp23.classes.andrewheiss.com/blob/main/_targets.R#L42) in that folder):

```yaml
project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
```

Functionally, that's the same as using an underscore (`_slides/`), correct? Or does the underscore preface do something extra?

**Comment by cscheid** [comment] 2023-02-27 16:45
If this wasn't closed by that RStudio fix, please feel free to reopen this; thanks!

**Closed** 2023-02-27 16:45 UTC
Labels: bug

**Comment by andrewheiss** [comment] 2023-02-27 16:47
The RStudio fix works and Rmd files now knit correctly. Thanks!
