### ISSUE TITLE
`help` doesn't list all commands

### ISSUE THREAD

**Issue by VladimirAlexiev** [quarto-dev/quarto-cli#5675] opened 2023-05-25 06:33 UTC
### Bug description

```
#  quarto help

  Usage:   quarto
  Version: 1.3.124

  Description:

    Quarto CLI

  Options:

    -h, --help     - Show this help.
    -V, --version  - Show the version number for this program.

  Commands:

    render          [input] [args...]     - Render files or projects to various document types.
    preview         [file] [args...]      - Render and preview a document or website project.
    serve           [input]               - Serve a Shiny interactive document.
    create          [type] [commands...]  - Create a Quarto project or extension
    create-project  [dir]                 - Create a project for rendering multiple documents
    convert         <input>               - Convert documents to alternate representations.
    pandoc          [args...]             - Run the version of Pandoc embedded within Quarto.
    run             [script] [args...]    - Run a TypeScript, R, Python, or Lua script.
    add             <extension>           - Add an extension to this folder or project
    install         [target...]           - Installs an extension or global dependency.
    publish         [provider] [path]     - Publish a document or project. Available providers include:
    check           [target]              - Verify correct functioning of Quarto installation.
    help            [command]             - Show this help or the help of a sub-command.
```
The above doesn't mention the `list` command described here: https://quarto.org/docs/output-formats/pdf-engine.html#managing-tex .

The command itself works fine:

```
# quarto list -h

  Usage:   quarto list <type>
  Version: 1.3.124

  Description:

    Lists an extension or global dependency.

  Options:

    -h, --help              - Show this help.
    --log         <level>   - Path to log file
    --log-level   <level>   - Log level (info, warning, error, critical)
    --log-format  <format>  - Log format (plain, json-stream)
    --quiet                 - Suppress console output.
    --profile               - Active project profile(s)

  Commands:

    help  [command]  - Show this help or the help of a sub-command.

  Examples:

    List installed extensions: quarto list extensions
    List global tools:         quarto list tools

# quarto list tools
[>] Inspecting tools

Tool        Status         Installed     Latest
tinytex     Up to date     v2023.05      v2023.05
```

Versions:
```
# uname
CYGWIN_NT-10.0

# quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 2.19.2: OK
      Dart Sass version 1.32.8: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.124
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: C:/Python310/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by VladimirAlexiev** [comment] 2023-05-25 06:38
`update` and `uninstall` from the same doc section are also not listed by `help`

**Comment by mcanouil** [comment] 2023-05-25 06:42
Thanks for the report.
Closing this as a duplicate of #5421.

**Closed by mcanouil** 2023-05-25 06:42 UTC
Labels: bug
