### ISSUE TITLE
Allow shortcodes expansion in `icon` attribute/YAML/code cell option

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#10004] opened 2024-06-14 08:26 UTC
For other Quarto components, you can use the `text: "{{< iconify octicon:issue-opened-16 >}} Opened Issues"` to get an icon from a shortcode in most places (instead of `icon: name`), but for value box, you can't do that as the icon gets a particular treatment for it to appear on the left of the content of the value box.

It would be nice to be able to use more icons than the limited set of Bootstrap in particular in value box in dashboard as there are no alternatives/workarounds:

````qmd
::: {.valuebox icon="{{< iconify octicon:log-24 >}}" color="blue"}
Articles per day

`{python} articles`
:::
````

The approach of allowing shortcode inside `icon` could also be expanded to all `icon` everywhere in Quarto.

**Comment by cderv** [comment] 2024-06-14 12:09
Is shortcode allowed on Div syntax attributes in general ? Your issue is quite specific to dashboard and valuebox, but I think using shortcodes on Fenced Div attributes is not working in general. 

Shortcode replacement for this happens in AST processing, but our reader does not see initially a Div. 

Take this 
````markdown
---
title: test
keep-md: true
format: html
---

::: {.custom title="{{< meta title >}}"}
Content
:::
````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/654b1306-f8ad-411e-a081-ef909e0077f4)


But using trace, the starting Doc is a Para first 
````
blocks:
  - t: "Para"
    content:
      - "::: {.custom title="
      - t: "Quoted"
        content:
          - "\""
          - t: "Span"
            attr: "('', ['quarto-shortcode__'], ['data-is-shortcode,1', 'data-raw,{{< meta title >}}'])"
            content:
              - t: "Span"
                attr: "('', ['quarto-shortcode__-param'], ['data-is-shortcode,1', 'data-value,meta', 'data-raw,meta'])"
                content: []
              - " "
              - t: "Span"
                attr: "('', ['quarto-shortcode__-param'], ['data-is-shortcode,1', 'data-value,title', 'data-raw,title'])"
                content: []
      - "}Content:::"
````

So I don't know enough about Shortcode handling to see how / if this could be supported

**Comment by mcanouil** [comment] 2024-06-14 12:22
The use case was indeed mostly the dashboard, but the enhancement could be more broad.

**Comment by cscheid** [comment] 2024-06-17 16:46
There's a few things to check here. One of them is that when using shortcodes inside attributes, we currently have a limitation where we expect the attributes to be specified with single quotes. So this works:

````
---
title: test
keep-md: true
format: html
---

::: {.custom title='{{< meta title >}}'}
Content
:::
````

However, I think that is _won't_ work for `iconify`, because we don't let extension shortcodes know the context in which they're resolving, and so `iconify` won't know that it's being called inside an attribute and so should return a string as result (rather than pandoc AST nodes).

**Comment by mcanouil** [comment] 2024-06-20 19:50
Hum the single quote "trick" does not seem to work at least in callouts.

<img width="653" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/82b2114f-07b6-40dc-bb54-20d0bd51f8bc">


````qmd
---
title: "Hello, Quarto"
format: html
---

::: {.callout-note title='{{< meta title >}}'}
A note
:::

````

**Comment by cscheid** [comment] 2024-07-02 20:12
## What's going on

Shortcodes are processed in the shortcodes filter:

https://github.com/quarto-dev/quarto-cli/blob/79bdce85bf5f0485aac9e4fd668bc7177f94cc1b/src/resources/filters/main.lua#L262

This shortcode filter _does_ process shortcodes inside attributes; the issue is that by the time we get to the shortcodes filter, the content is no longer inside an attribute. That happens because custom AST nodes are processed in `quarto_ast_pipeline`, which is part of the normalization stage of our filter chain, and happens before shortcode filters.

We need that specific order, because shortcodes in the main markdown body are actually custom AST nodes (we made that design choice to fix old bugs like `{{< video url--with_underscores_fails >}}`). But that means that if a callout has attributes with shortcodes, then those need to be processed before the content of the attribute is resolved into text.

I don't like the fact that we'll have shortcode resolution happening in different stages, but I don't think we can avoid that.

**Closed** 2024-07-03 16:36 UTC
Labels: enhancement, shortcodes
