### ISSUE TITLE
Problematic height=\textheight in \includegraphics when #| out-width only is fixed

### ISSUE THREAD

**Issue by EricMarcon** [quarto-dev/quarto-cli#4612] opened 2023-03-03 09:35 UTC
### Bug description

As mentioned in #2417,

`````
---
title: "Untitled"
format: latex
keep-md: true
---

```{r}
#| label: main-plot
#| out-width: 50%
plot(mtcars)
```
`````

generates the following in LaTeX (as of version 1.2.335, RStudio 2022.12.0 on Windows 11):
```
\includegraphics[width=0.5\textwidth,height=\textheight]{test_files/figure-latex/main-plot-1.pdf}
```

In a 2-column document, the figure is not formated as expected: it is wider than its column.

In R Markdown, the same options generated 
```
\includegraphics[width=0.5\textwidth]{test_files/figure-latex/main-plot-1.pdf}
```
which worked perfectly.

A temporary workaround is to divide the desired width by 2.

So I think `height=\textheight` should not be added if `#| out-height:` is not specified in the Quarto file: LaTeX does not need it and it does not allow correct format in 2-column documents.

Thanks!

**Comment by cscheid** [comment] 2023-03-08 17:54
It looks like there's (at least!) two things happening.

1. It seems that we shouldn't be outputting `,height=\textheight` when only `textwidth` is specified (although I don't know if this is doing damage)
2. It seems that we [should be outputting `linewidth` instead of `textwidth` anyway](https://www.google.com/search?q=latex+linewidth+vs+textwidth), since that is affected by two-column modes (and other contextual changes).

I don't want to introduce a subtle change like this late into our 1.3 prerelease, but we'll definitely make sure this works correctly.

**Comment by cderv** [comment] 2023-03-08 19:39
For context about this, this is added by Pandoc . Intermediate `.md` before conversion gets
```latex
![](test2_files/figure-latex/main-plot-1.pdf){width=50%}
```

and Pandoc converts to TeX adding the units
````latex
\includegraphics[width=0.5\textwidth,height=\textheight]{test2_files/figure-latex/main-plot-1.pdf}
````

This is on purpose and they explain the Why in there FAQ item 
https://pandoc.org/faqs.html#when-i-specify-an-image-width-of-50-and-convert-to-latex-pandoc-sets-the-height-to-textheight-and-the-aspect-ratio-isnt-preserved.-how-can-i-prevent-this

In knitr, for LaTeX, we handle the figure syntax creation in [`hook_plot_tex()`](https://github.com/yihui/knitr/blob/2df02ce3df1dc735e7d55ad210fcaf023b220f2b/R/hooks-latex.R#L38) and we create the units based in `width` and `height` provided (by [fixing options](https://github.com/yihui/knitr/blob/2df02ce3df1dc735e7d55ad210fcaf023b220f2b/R/utils.R#LL294)  for LaTeX) 

That is why you see a different behavior with R Markdown @EricMarcon 

In Quarto we unfix the option for the processing
https://github.com/quarto-dev/quarto-cli/blob/2f3507a1231e1e28cd0684259681938492f140ce/src/resources/rmd/hooks.R#L468-L471
and we let Pandoc do the figure syntax conversion from Markdow syntax
https://github.com/quarto-dev/quarto-cli/blob/2f3507a1231e1e28cd0684259681938492f140ce/src/resources/rmd/hooks.R#L580-L581

Something to look into considering all this context then. 

Hope it helps

**Comment by cderv** [comment] 2023-12-11 09:39
Before trying to take over Pandoc generation of the LaTeX for a figure, I want to understand better what is not working. 
It seems to be an issue for you in a two column layout only. 

> In a 2-column document, the figure is not formated as expected: it is wider than its column.

Can you share an example of this ? 

I get this in a single column document
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/c090e71f-e708-4907-a381-317134015083)

And this with a twocolumn class option 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/aae834f4-b495-4eb0-a82a-3b58cfda8807)

<details>
<summary>Code</summary>

````markdown
---
title: "Untitled"
format: pdf
classoption: twocolumn
keep-md: true
---

```{r}
#| label: main-plot
#| out-width: 50%
plot(mtcars)
```

````


</details>

And with text in the middle (using https://github.com/dragonstyle/lipsum)

````markdown
---
title: "Untitled"
format: pdf
classoption: twocolumn
keep-md: true
---

{{< lipsum 7 >}}

```{r}
#| label: main-plot
#| out-width: 50%
plot(mtcars)
```

{{< lipsum 7 >}}

```` 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/d4699df8-9ec8-42bb-a620-f84ed6e86703)

It seems ok to me. 

What is your expected results exactly ? 

It would help us having more details and an example of what is not working as expected exactly. 

Thanks.

**Comment by cderv** [comment] 2023-12-18 14:20
@EricMarcon Is this still an issue for you ? thanks !

**Comment by EricMarcon** [comment] 2023-12-19 08:29
It is.
As I understand it, the chunk options should not depend of the document template. 

I always build my documents both in HTML and PDF. If I want my figure to be 80% of the text width, I'll naturally set `#| out-width: 80%`. it will be fine in HTML but to make it fit in a 2-column PDF document, I"ll need to force `#| out-width: 40%`.
Note that if  `#| out-width:` is absent, it is equivalent to 100% in HTML and one-column PDF, but equivalent to 50% in two-column PDF. This is not consistent.

I modified the last example to set `#| out-width: 80%`:

`````
---
title: "Untitled"
format: pdf
classoption: twocolumn
keep-md: true
---

{{< lipsum 7 >}}

```{r}
#| label: main-plot
#| out-width: 80%
plot(mtcars)
```

{{< lipsum 7 >}}
`````

I obtain:

![2-col document](https://github.com/quarto-dev/quarto-cli/assets/29632125/2d9f1f55-8372-42b2-9a91-982d4217d0de)

The figure is wider than the column, while it is actually 80% of the text width in a single-column document:
`````
---
title: "Untitled"
format: pdf
keep-md: true
---

{{< lipsum 7 >}}

```{r}
#| label: main-plot
#| out-width: 80%
plot(mtcars)
```

{{< lipsum 7 >}}
`````

![1-col document](https://github.com/quarto-dev/quarto-cli/assets/29632125/81097ac5-826b-4135-8798-8985ab1d2798)


Thanks for your efforts.

**Comment by cderv** [comment] 2023-12-19 09:23
Great thanks for the example that explains it well. 

However, I don't think this is related to `\textheight`. If I add `keep-tex: true` to get the tex file, and remove it to get 
````
\includegraphics[width=0.8\textwidth]{index_files/figure-pdf/main-plot-1.pdf}
````
Then I compile this using xelatex directly, this is what I still get
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/7cfa1e04-dca6-4f96-a693-8afb0a75921f)

It seems using `\textwidth` as Pandoc is doing is not appropriate for `twocolumns` mode. 

I believe `\columnwidth` or `\linewidth` could be used here... It seems Pandoc does not support setting different type of size. 

We would need to take over the LaTeX figure rendering to allows different type of size.

**Comment by EricMarcon** [comment] 2023-12-19 15:04
You are right. I double-checked what RMarkdown did : the output was `\linewidth`, not `\textwidth`. Sorry for the confusion in my first comment.

Thank you.

**Comment by cderv** [comment] 2023-12-19 16:16
Yes this is **knitr** doing the work in that case. But for Quarto we do rely only on Markdown image syntax for Pandoc 
````markdown
![](img/path.png){width=80%}
````
and as discussed it does not support latex sizing. 

**rmarkdown** is relying on **knitr** plots hooks to handle the figures. Quarto will rely on Pandoc to generate the right LaTeX. 

So 

* Either this needs to be change in Pandoc
* Ether Quarto needs to generate the LaTeX code for image itself

**Comment by cscheid** [comment] 2023-12-19 16:23
my understanding is that Pandoc's latex writer tends to prefer 1-column layouts.

The problem is that the difference between one-column and two-column layouts is hard to detect from our side, since it depends on the template. I don't think it's something we can fix well enough in Quarto; I think article extensions will need to do some of the work here.

**Comment by cderv** [comment] 2023-12-19 16:47
This is also about Pandoc not supporting `width` with LaTeX units. So no way to pass attributes to `includegraphics` generated by Pandoc. 

Not sure if Pandoc can solves this...

**Comment by vtraag** [comment] 2024-01-31 20:58
> 2\. It seems that we [should be outputting `linewidth` instead of `textwidth` anyway](https://www.google.com/search?q=latex+linewidth+vs+textwidth), since that is affected by two-column modes (and other contextual changes). [🔗](https://github.com/quarto-dev/quarto-cli/issues/4612#issuecomment-1460594356)

It seems that this is the crux of the issue. I'm now running into exactly this issue when rendering a simple image to a two-column PDF.

I haven't found an issue on https://github.com/jgm/pandoc, is it worth opening one?

Alternatively, is it planned that Quarto directly generates LaTeX code itself?

Finally: does anyone have a suggestion for a workaround?

**Comment by vtraag** [comment] 2024-01-31 20:59
> The problem is that the difference between one-column and two-column layouts is hard to detect from our side, since it depends on the template. I don't think it's something we can fix well enough in Quarto; I think article extensions will need to do some of the work here.

I believe `'\linewidth` should always work, and should generally be preferred to `\textwidth`. That is, using `\linewidth` also works correctly in single column mode.

**Comment by cderv** [comment] 2024-02-01 09:46
> I haven't found an issue on [jgm/pandoc](https://github.com/jgm/pandoc), is it worth opening one?

I think it is worth it if you can share with them an example where their default choice causes issues. As they justify their choices in their FAQ, I am unsure exactly what to report. So please, open an issue if you have the necessary input.

Maybe Pandoc should use `linewidth` and not `textwidth` in the first place. 

> Alternatively, is it planned that Quarto directly generates LaTeX code itself?

This will probably be the only way to fix this issue if this does not change in Pandoc. We'll see that for 1.5.

**Comment by vtraag** [comment] 2024-02-01 11:17
> I think it is worth it if you can share with them an example where their default choice causes issues. As they justify their choices in their FAQ, I am unsure exactly what to report. So please, open an issue if you have the necessary input.
> 
> Maybe Pandoc should use `linewidth` and not `textwidth` in the first place.

Yes, I believe indeed that Pandoc should use `linewidth`, not `textwidth`. I've opened an issue here: https://github.com/jgm/pandoc/issues/9396

**Comment by EricMarcon** [comment] 2024-02-02 13:42
Thanks!

**Comment by mcanouil** [comment] 2024-02-02 13:48
Let's keep this open until the upstream issue is closed:
- https://github.com/jgm/pandoc/issues/9396

**Comment by vtraag** [comment] 2024-10-04 11:26
Note that the upstream issue is now closed. I haven't yet tested it, but I assume this would also solve this issue, so that it could be closed.

**Comment by mcanouil** [comment] 2024-10-04 12:08
it's in Pandoc 3.2.1 apparently.

Quarto 1.6 pre-release is currently using Pandoc 3.4, so this should be fixed.

**Comment by cderv** [comment] 2024-10-04 15:33
With latest 1.6 we do produce with `\linewidth`
````latex
\includegraphics[width=0.5\linewidth,height=\textheight,keepaspectratio]{index_files/figure-latex/main-plot-1.pdf}
````

The [two columns example](https://github.com/quarto-dev/quarto-cli/issues/4612#issuecomment-1862323570) is now ok
![Image](https://github.com/user-attachments/assets/07340672-296c-463c-9217-475935f02dd7)

So we can say it is fixed yes.

**Closed** 2024-10-04 15:33 UTC
Labels: bug, verify-fixed, latex, figures, pandoc
