### ISSUE TITLE
Getting Started Python example doesn't work on Windows

### ISSUE THREAD

**Issue by JanPalasek** [quarto-dev/quarto-cli#4138] opened 2023-01-28 19:19 UTC
### Bug description

# Introduction
After installing quarto on Windows 11, I couldn't get the example working from [this url](https://quarto.org/docs/get-started/hello/vscode.html).

# How to reproduce the issue

1. Install Quarto version 1.2.313
2. Create the example document and name it `test.qmd`
  ```md
  ---
  title: "Quarto Basics"
  format:
    html:
      code-fold: true
  jupyter: python3
  ---
  
  For a demonstration of a line plot on a polar axis, see @fig-polar.
  
  ```{python}
  #| label: fig-polar
  #| fig-cap: "A line plot on a polar axis"
  
  import numpy as np
  import matplotlib.pyplot as plt
  
  r = np.arange(0, 2, 0.01)
  theta = 2 * np.pi * r
  fig, ax = plt.subplots(
    subplot_kw = {'projection': 'polar'} 
  )
  ax.plot(theta, r)
  ax.set_rticks([0.5, 1, 1.5, 2])
  ax.grid(True)
  plt.show()
  ```
3. Go to the directory where the document is and install the packages into a separate venv (in Powershell):
```
cd /directory/with/test/qmd/file
python -m venv "venv"
./venv/Scripts/Activate.ps1
python -m pip install jupyter matplotlib plotly
```
4. Run the following command with the activated venv:
```
quarto render test.qmd --to html
```

# What does happen
The command freezes and doesn't do anything. I doesn't write anything on the output. I noticed that it creates a correct `test.ipynb` file, but doesn't manage to execute it (the file doesn't have output cells).

Btw I also tried to run `quarto check jupyter` and it outputs the following:

![image](https://user-images.githubusercontent.com/26582151/215287233-77b688ce-ce76-40fa-a471-7341661c8e72.png)

It freezeson `Checking Jupyter engine render....`

# What should happen
It should render the html into `test.html`.

# Versions
## requirements.txt

<details>
<summary>Content of requirements.txt</summary>

```sh
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
attrs==22.2.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==6.0.0
cffi==1.15.1
colorama==0.4.6
comm==0.1.2
contourpy==1.0.7
cycler==0.11.0
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
executing==1.2.0
fastjsonschema==2.16.2
fonttools==4.38.0
fqdn==1.5.1
idna==3.4
importlib-metadata==6.0.0
ipykernel==6.20.2
ipython==8.9.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.4.4
jupyter-events==0.6.3
jupyter_client==8.0.1
jupyter_core==5.1.5
jupyter_server==2.1.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
kiwisolver==1.4.4
MarkupSafe==2.1.2
matplotlib==3.6.3
matplotlib-inline==0.1.6
mistune==2.0.4
nbclassic==0.5.1
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.24.1
packaging==23.0
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==2.6.2
plotly==5.13.0
prometheus-client==0.16.0
prompt-toolkit==3.0.36
psutil==5.9.4
pure-eval==0.2.2
pycparser==2.21
Pygments==2.14.0
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.4
pywin32==305
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.0.0
qtconsole==5.4.0
QtPy==2.3.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
Send2Trash==1.8.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.2
tenacity==8.1.0
terminado==0.17.1
tinycss2==1.2.1
tornado==6.2
traitlets==5.8.1
uri-template==1.2.0
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.5.0
widgetsnbextension==4.0.5
zipp==3.12.0
```

</details>

## Python
```
Python 3.9.13
```

## Quarto

```
1.2.313
```

## Windows

Windows 11 Pro, Version 22H2, OS build 22621.1105

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2023-01-29 00:25
Duplicate of #4122 (it's a bug on [jupyter_client](https://github.com/jupyter/jupyter_client/issues/922#event-8380392214)). We have a workaround in place for 1.3 prerelease and are working on a 1.2 backport.

**Closed by cscheid** 2023-01-29 00:25 UTC
Labels: bug

**Comment by cscheid** [comment] 2023-01-29 00:27
Links to the releases

- [1.2.329](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.2.329)
- [1.3.140](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.3.140)
