### ISSUE TITLE
link-external-icon wrapping has unexpected breaks

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#5639] opened 2023-05-23 13:52 UTC
### Bug description

Using Quarto 1.3.340 on macOS.

````markdown
---
title: external
format:
  html:
    link-external-icon: true
---

This is a fairly lengthy sentence that has an external link to the website of the [Quarto project](https://quarto.org/).
````

When rendered, things look just fine at first:

<img width="749" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/f4a0c98b-72e8-4f4c-b9d7-b2a2c4d57610">

With a slightly different screen size, the period wraps by itself:

<img width="747" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/8037d3a8-3b34-4e5c-bdc8-50180937bafc">

Even narrower sees the external-link icon wrap apart from the link text:

<img width="749" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/53bca89e-a194-4fd8-87e4-98d76024b2b0">

I did not expect that the link text, the external link icon, and the trailing period would be splittable.

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 3.6.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/3.6/Resources/library
      knitr: 1.42.8
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by rich-iannone** [comment] 2023-06-13 19:15
Duplicate of https://github.com/quarto-dev/quarto-cli/issues/4619.

**Closed** 2023-06-14 18:12 UTC
Labels: bug, good-first-issue, html
