### ISSUE TITLE
mermaid diagrams do not render inside a tabset

### ISSUE THREAD

**Issue by webscale** [quarto-dev/quarto-cli#9031] opened 2024-03-10 18:01 UTC
Tried this on Python and on R. does not work

The mermaid inside the Tabset of flowchart does not render. But the Mermaid outside of Tabset renders.

`# Segments with Concerns

Showing the SAS Code Segments and the diagram of the code segments

::: {.callout-note title="Code Segment: 1"}
`\nlibname vitra oracle user=admin password=fancy51$ path=//245.23.45.22:1521/dbservice;\n`
:::

::: {#recommendations .panel-tabset}
## Viya Recommendations {#viya}

Viya Recommendations for the code segment <br/> **Issue 1** : usernm-password<br/> **Recommendation** : </br> <b>Suggestion for usernm-password : </b> <br>`\n%let usr = admin;\n%let pwd = fancy51$;\n\nlibname vitra oracle user="&usr" password="&pwd" path=//245.23.45.22:1521/dbservice;\n` <br/> **Issue 2** : connection-string<br/> **Recommendation** : </br> <b>Suggestion for connection-string : </b> <br>`\n%let pwd = fancy51$;\n\nlibname vitra oracle user=admin password="&pwd" path=//245.23.45.22:1521/dbservice;\n`

## Psedocode {#psedocode}

<br/><br/>**Step 1**: Define a library reference (libref) named 'vitra'. This is done using the 'libname' statement in SAS. <br/><br/>**Step 2**: Connect to an Oracle database using the libref. The connection details are provided as follows:<br/><br/>- 'user=admin' specifies the username for the database connection.<br/>- 'password=fancy51\$' specifies the password for the database connection.<br/>- 'path=//245.23.45.22:1521/dbservice' specifies the path to the database service. This includes the IP address (245.23.45.22), port number (1521), and the service name (dbservice).<br/><br/>**Brief Description**: This SAS code segment is used to connect to an Oracle database. The 'libname' statement in SAS is used to assign a libref (library reference) to a database, which can then be used to read from or write to the database. In this case, the libref 'vitra' is being assigned to an Oracle database with the specified connection details.

## Flow Chart {#flowchart}

Flow Chart of the code segment

```{mermaid}
graph TD
  A[Start] --> B[Step 1: Define a library reference libref named 'vitra']
  B --> C[Step 2: Connect to an Oracle database using the libref]
  C --> D{Connection Details}
  D --> E[User: admin]
  D --> F[Password: fancy51$]
  D --> G[Path: //245.23.45.22:1521/dbservice]
  G --> H
  H[End]

```
:::

## Mermaid

```{mermaid}
graph TD
  A[Start] --> B[Step 1: Define a library reference libref named 'vitra']
  B --> C[Step 2: Connect to an Oracle database using the libref]
  C --> D{Connection Details}
  D --> E[User: admin]
  D --> F[Password: fancy51$]
  D --> G[Path: //245.23.45.22:1521/dbservice]
  G --> H
  H[End]
```
`

**Comment by cderv** [comment] 2024-03-11 14:03
This is a duplicate of 
* https://github.com/quarto-dev/quarto-cli/issues/5145

````markdown
---
title: "Untitled"
format: html
keep-md: true
---

::: {.panel-tabset}

## Tab 1 

```{mermaid}
graph TD
  A[Start] --> B[Step 1: Define a library reference libref named 'vitra']
  B --> C[Step 2: Connect to an Oracle database using the libref]
  C --> D{Connection Details}
  D --> E[User: admin]
  D --> F[Password: fancy51$]
  D --> G[Path: //245.23.45.22:1521/dbservice]
  G --> H
  H[End]
```

## Tab 2

```{mermaid}
flowchart TD
three---four
```

:::

````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/de339a73-940e-4828-8865-ba3d9640a338)

**Closed** 2024-03-11 14:04 UTC
Labels: bug, mermaid, tabsets
