### ISSUE TITLE
Using metadata under `book` key cannot be referenced anymore

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2148] opened 2022-08-26 15:25 UTC
the solution from that thread  https://github.com/quarto-dev/quarto-cli/discussions/2060#discussioncomment-3455375 no longer works with the latest version 1.1.132. I've uninstalled that version and gone back to 1.1.57 which works fine with the `book.isbn` solution from the windows terminal. That's a workaround for me now.

_Originally posted by @jpmorr in https://github.com/quarto-dev/quarto-cli/issues/2143#issuecomment-1228607822_

**Comment by cderv** [comment] 2022-08-26 15:27
@jpmorr I have open a new issue to not clutter the other one. 

Please give more context and possible a reproducible example about the issue from the thread. 

My understanding is that you tried 

````
book:
  title: "My book"
  subtitle: "A really good book" 
  edition: "Third"
  isbn: xxx-xxxxxxxx
  author:
   - name: Mr. Jones
````

Then use `$book.isbn$` in your custom template. And that does not work anymore. Is that the complete issue ?

**Comment by jpmorr** [comment] 2022-08-26 15:33
> Then use $book.isbn$ in your custom template. And that does not work anymore. Is that the complete issue ?

Yes, after updating to 1.1.132, this no longer works. It complains of a failed validation check as soon as it reads the `edition` keyword. Rolling back to 1.1.57 allows it to recompile for both html and pdf.

It seems that custom keywords may no longer be supported in the book project in the most recent release.

**Comment by cderv** [comment] 2022-08-26 15:49
@dragonstyle @cscheid did we validate more thoroughly than before our keys in `_quarto.yml` than before ? 
I thought doing this kind of variable addition was possible, but I understand why we would make that more contraint to avoid conflicts. 

@jpmorr is setting your custom variables in there own file and using [`metadata-file`  include](https://quarto.org/docs/reference/formats/html.html#includes) or just fields on they own in YAML file not an option ? 
I think it would work ok that way, and would prevent conflict with Quarto own key value pairs used for Project configuration.

**Comment by cscheid** [comment] 2022-08-26 15:51
@jpmorr sorry you were caught by this.

That change was intentional: we have had a number of other issues from users placing keys in the project field when they belonged elsewhere, so we decided to make the project schemas closed now to avoid larger impact in the future.

Is it practical for you to use a different key from `book`?

**Comment by jpmorr** [comment] 2022-08-26 16:12
Thanks, it's OK. My previous attempt was about adding some book specific meta-data that I thought should be available by default - most books have a `edition`, `isbn` and `doi` attached and I thought it should be available for use with both the html and pdf formatting, so it was natural to add as keys in the book field. 

I'm OK with it being in a metadata-file even if it's not the most obvious place for these specific keys. I haven't explored or read about metadata fields properly yet though but assume it will work.

**Comment by cscheid** [comment] 2022-08-26 16:24
@jpmorr We agree that it's very natural to add those there!

@jjallaire @dragonstyle Maybe we should just allow those fields in the book project schema...

**Comment by jpmorr** [comment] 2022-09-09 20:41
I've just noticed that the `yaml` metadata validation for project keys has re-introduced the stricter checking as using the `edition` keys within `book`  breaks as soon as that key is parsed. 

I think I need to set-up some `metadata-files` for variables like `edition` but not sure how to do it - I couldn't find any example in the documentation. Could someone point me in the direction of an example using `metadata-files`?

**Comment by jjallaire** [comment] 2022-09-10 18:23
@cscheid I thought we added `edition` to the book schema? @jpmorr Is this a regression from a previous version of v1.1 or v1.2? 

Here are some docs on `metadata-files`: https://quarto.org/docs/projects/quarto-projects.html#metadata-includes (note though that I don't think this gets you out of schema validation as those files are also validated)

**Comment by jpmorr** [comment] 2022-09-10 19:34
@jjallaire, @cscheid Both `doi` and `isbn` seem fine but `edition` seems to be kicking up a fuss. I'm on v1.2.71 on my computer and everything is building fine. 

However, I finally moved my code to a repo and I'm using `GitLab Pages` to build things. That pipeline is  just making a clone of the latest quarto, building and then rendering the html pages and pdf. Everything was building OK on Thursday with `edition` in the `_quarto.yml`, but the build on Friday from a new commit failed the validation check. 

```
          at readAndValidateYamlFromFile (file:///builds/jpmorr/uoe-bbm-documentation/quarto-cli/src/core/schema/validated-yaml.ts:52:11)
    at async projectContext (file:///builds/jpmorr/uoe-bbm-documentation/quarto-cli/src/project/project-context.ts:130:28)
    at async render (file:///builds/jpmorr/uoe-bbm-documentation/quarto-cli/src/command/render/render-shared.ts:59:19)
    at async Command.fn (file:///builds/jpmorr/uoe-bbm-documentation/quarto-cli/src/command/render/cmd.ts:187:26)
    at async Command.execute (file:///builds/jpmorr/uoe-bbm-documentation/quarto-cli/src/vendor/deno.land/x/cliffy@v0.24.2/command/command.ts:1275:7)
    at async quarto (file:///builds/jpmorr/uoe-bbm-documentation/quarto-cli/src/quarto.ts:119:3)
    at async file:///builds/jpmorr/uoe-bbm-documentation/quarto-cli/src/quarto.ts:146:5
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```

I've since removed the `edition`  variable and was looking for an alternative way. If it's likely to fail in `metadata-files` would making it a top-level variable in the `yaml` be ok or would that fail the validation check as well?

**Comment by jjallaire** [comment] 2022-09-10 20:15
Adding it to the top level would indeed evade the schema check

**Comment by jpmorr** [comment] 2022-09-10 20:28
@jjallaire OK thanks for the info. Not as neat, but happy if that works. Will try tomorrow.

**Comment by cscheid** [comment] 2022-09-12 16:24
This is potentially a regression of which #2398 is a duplicate. We'll fix right it sometime this week.

**Comment by cscheid** [comment] 2022-09-12 21:12
We're about to merge a fix to this, by allowing `book` to take any entries in the [CSL data schema](https://github.com/citation-style-language/schema/blob/master/schemas/input/csl-data.json)

Do note, however, that in your case, you'll have to capitalize `ISBN` and `DOI`, though not `edition`.

**Comment by jpmorr** [comment] 2022-09-13 09:47
@cscheid  the CSL data schema link is really helpful, thanks. Capitalising is an easy fix. I'll wait until the change is merged and will test later in the week.

**Closed** 2022-09-14 15:50 UTC
Labels: yaml-validation
