### ISSUE TITLE
Lists in blockquotes in revealjs become`incremental` not blockquoted

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#10405] opened 2024-07-28 17:41 UTC
Quarto 1.5.55.

Reprex:

````markdown
---
format: 
  revealjs:
    incremental: false
---

## Items incremental + not styled as blockquote

Itemized:

> -   hi
> -   hello
> -   mello

Enumerated:

>1.  hi
>2.  hello
>3.  mello

## Items non-incremental, as expected

Itemized:

-   hi
-   hello
-   mello

Enumerated:

1.  hi
2.  hello
3.  mello
````

**Comment by mcanouil** [comment] 2024-07-28 20:40
That's not a bug. That's a Pandoc feature.

https://pandoc.org/MANUAL.html#incremental-lists

The solution is documented:

````qmd
**> ::: wrapper
> - a
> - list in a quote
> :::**
`````

**Comment by cderv** [comment] 2024-07-29 10:28
It is among documentation update to-do list 😞 
- https://github.com/quarto-dev/quarto-cli/issues/7715

I'll close this one and be sure to deal with the other one in next documentation batch

**Closed by cderv** 2024-07-29 10:28 UTC
Labels: support
