### ISSUE TITLE
Text is blurry for Reveal.js when `incremental: true` in Safari

### ISSUE THREAD

**Issue by cbrnr** [quarto-dev/quarto-cli#11297] opened 2024-11-04 10:37 UTC
When creating a Reveal.js presentation with `incremental: true`, text is blurry in Safari:

![Image](https://github.com/user-attachments/assets/2a84e11d-3c00-45ac-92e1-b606ce921d53)

This is not the case in Chrome:

![Image](https://github.com/user-attachments/assets/a1cb39c8-bb4c-4532-bdda-a0a244b1decd)

Here's an example to reproduce:

```
---
title: "Test"
format:
  revealjs:
    theme: default
    incremental: true
---

## Quick intro

- First bullet point
- Another bullet point
- Yet another bullet point
```

Run `quarto` on this example and open the HTML in Safari and Chrome. Note that the text is rendered perfectly OK when `incremental: False` in Safari. I'm not sure if this is a Quarto issue, but at least in the [Reveal.js demo](https://revealjs.com/#/fragments/0), fragments (text rendered incrementally) are rendered correctly in Safari.

**Comment by mcanouil** [comment] 2024-11-04 11:27
Thank you, but please search amongst other issues and use the bug report template in the future tyo provide the requested and needed information.

- https://github.com/quarto-dev/quarto-cli/issues/10996
- https://github.com/quarto-dev/quarto-cli/issues/10842

**Comment by cbrnr** [comment] 2024-11-04 11:44
Thanks for the quick response and sorry for the noise.

**Comment by mcanouil** [comment] 2024-11-04 12:02
In case, I missed something but I cannot reproduce using `main`.

![Image](https://github.com/user-attachments/assets/7119b255-f225-4ad3-b5c0-1581edb28ce0)

Note that the bug report template include a section to let us know your environment in addition to the `quarto check` outputs.

I am on Sequoia with Safari version 18.1 (20619.2.8.11.10)

**Comment by cbrnr** [comment] 2024-11-04 12:29
Here's my environment:

- IDE: Visual Studio Code 1.95.1 with Quarto Extension 1.116.0
- OS: macOS Sequoia 15.1
- Browser: Safari 18.1 (20619.2.8.11.10)

Output of `quarto check`:

<details>

```
Quarto 1.6.32
[✓] Checking environment information...
      Quarto cache location: /Users/clemens/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.32
      Path: /Users/clemens/Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/clemens/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```
</details>


I also tried `main`, but text still shows up blurry for me 😢. Can you try enlarging the Safari window? The issue is only really visible when the canvas is large enough.

**Comment by mcanouil** [comment] 2024-11-04 12:48
The blurry effect only appears when I zoom in/out quickly (I mean really quickly) which is very unlikely a thing that will happen in real life.

**Comment by cbrnr** [comment] 2024-11-04 12:57
That's really weird, I only have the AdGuard extension, which I just disabled, but the text remains blurry.

**Comment by cbrnr** [comment] 2024-11-04 13:09
It works fine on my iPad, here's a link to the rendered test presentation if anyone else wants to try it in Safari:

https://blurry-quarto.netlify.app/#/title-slide

**Comment by mcanouil** [comment] 2024-11-04 13:41
No blurry effects using your deployed slides.

**Comment by cderv** [comment] 2024-11-04 14:00
@cbrnr I can't reproduce either in playwright test suite using webkit. 

What you can do to help is opening inspect mode and try to find if there is a CSS rules that does somehow create the blur you see. Opting in / out the rule would show / unshow the blur. 

This way we can then try to understand what is happening. 



> Thank you, but please search amongst other issues and use the bug report template in the future tyo provide the requested and needed information.
> 
> * [Revealjs Slides Blurry in Safari #10996](https://github.com/quarto-dev/quarto-cli/issues/10996)
> * [blurry slides with chalkboard+revealjs bug on safari  #10842](https://github.com/quarto-dev/quarto-cli/issues/10842)

Regarding the above it was related to chalkboard being active, which is not in your example. The rule in question was `backdrop-filter: blur( 6px );` which required a `-webkit-backdrop-filter` in the chalkboard extension for support in older safari. 

If this can give you hint, so I don't know if this is directly related.

**Comment by cbrnr** [comment] 2024-11-04 14:29
Thanks @cderv, I don't really see any CSS rules that might be responsible for the blur.

However, I just noticed that the issue only appears when viewing on my external monitor. So if anyone want to try to reproduce please open that example on an external screen.

**Comment by cscheid** [comment] 2024-11-04 14:47
I think this is not a _blur_ issue; it's an issue with the font rendering algorithm, and Safari's font hinting is configured differently from that of Firefox and Chrome

**Comment by cderv** [comment] 2024-11-04 15:03
Thanks @cscheid ! Do you think there is anything we can improve ? I am not really sure as I am not Safari user to see the differences.

**Comment by mcanouil** [comment] 2024-11-04 16:10
> However, I just noticed that the issue only appears when viewing on my external monitor. So if anyone wants to try to reproduce please open that example on an external screen.

I am not even sure in the end it's HTML/CSS issue or even a Safari issue. Screen display has no way (to my knowledge) to interfere with browser reading/interpreting/displaying HTML/CSS.

**Comment by cscheid** [comment] 2024-11-04 17:12
We should try to confirm this behavior on Safari + macOS + revealjs only (outside of Quarto). If it only happens in Quarto's `revealjs` format, then I'd consider it a bug worth tracking down and fixing. If it happens outside of Quarto, then we should forward the report upstream to the revealjs repo and wait for their resolution.

**Comment by jimjam-slam** [comment] 2024-11-05 03:39
FWIW Safari has had a long-standing (like, for a decade) bug that causes small text blown up with `transform: scale()` to not be re-rasterised. It was very visible for us developing Closeread because we often blow up text when zooming in on poems and code.

One thing that made the bug very frustrating to diagnose was that it often required particular combinations of scale and other effects in order to reliably trigger.

We tried a lot of engineering to write around it but ultimately decided it wasn't worth it and abandoned our efforts, choosing to use `transform` and accept the trade-off for Safari.

However, in our last 2 or so of development I've seen Safari reliably re-rasterise text when scaled in our examples (examples that previously exhibited the bug). I'm wondering if Apple finally improved its behaviour with macOS 15.

For Reveal, the best way to deal with it in my experience is to set a large slide `width` and a large font size, so that Reveal scales down rather than up most of the time. I'm not sure there's much the Reveal folks can do about the bug since it's essentially Safari's problem (short of completely rewriting their scaling engine), but it'd be good to know if there's been a Safari update that does indeed fix the issue.

My notes on this bug are scattered a bit around the Closeread repo (I'm sure I've linked to the original Safari issue _somewhere_), but maybe these links will help:

- https://github.com/qmd-lab/closeread/pull/23
- https://github.com/qmd-lab/closeread/pull/24#issuecomment-2092078577

**Comment by jimjam-slam** [comment] 2024-11-05 03:40
Ah! Here's the bug: https://bugs.webkit.org/show_bug.cgi?id=27684

And here's an SO comment that discusses the class of issues in Safari: https://stackoverflow.com/a/55916005/3246758

**Comment by cbrnr** [comment] 2024-11-05 07:55
Oh wow, that's a bummer! Thanks for linking this bug! This also explains why I don't get any blur on the internal retina display (macOS is scaling up and down to create larger UI elements).

So I guess there is not much we can do, given that this bug has existed for ages. However, they obviously improved _something_ recently, so maybe there is still hope they'll eventually add a proper fix. @jimjam-slam since you have insights into the bug that I don't have, would you be willing to leave a comment in case they're still missing important information?

**Comment by cscheid** [comment] 2024-11-05 13:22
Feel free to continue the discussion here, but since this isn't a Quarto bug, I'm going to close the issue.

**Closed by cscheid** 2024-11-05 13:22 UTC
Labels: needs-repro, needs-discussion, revealjs

**Comment by jimjam-slam** [comment] 2024-11-05 22:46
> Oh wow, that's a bummer! Thanks for linking this bug! This also explains why I don't get any blur on the internal retina display (macOS is scaling up and down to create larger UI elements).
> 
> So I guess there is not much we can do, given that this bug has existed for ages. However, they obviously improved _something_ recently, so maybe there is still hope they'll eventually add a proper fix. [@jimjam-slam](https://github.com/jimjam-slam) since you have insights into the bug that I don't have, would you be willing to leave a comment in case they're still missing important information?

I'd definitely be interested to know whether you'd upgraded to Sequoia (and Safari 18) before seeing this!

But yeah, the short term fix I think is to set a high width (eg. `1800`) and a high font size so that Reveal brings it down rather than up.

You could also try setting `transition: none` on your `.incremental` elements — you'd lose the fade transition, but since I think it's specifically a problem with the interaction between scale and transition, it might help.

As far as the reveal folks go, I'd say [this issue](https://github.com/hakimel/reveal.js/issues/2783) is the same issue (makes sense that setting `will-change` would trigger this).

**Comment by cbrnr** [comment] 2024-11-07 07:23
> I'd definitely be interested to know whether you'd upgraded to Sequoia (and Safari 18) before seeing this!

I noticed this on previous versions, but yes, I'm on 15.1 and the latest Safari.
