### ISSUE TITLE
Computations figs 1a and 1b occupy 1 col, not 2

### ISSUE THREAD

**Issue by kschulzke** [quarto-dev/quarto-cli#9111] opened 2024-03-16 20:22 UTC
### Bug description

In the R tutorial at https://quarto.org/docs/get-started/computations/rstudio.html, Figs. 1a and 1b appear stacked, in a single column, one on top of the other. See pic. 

![image](https://github.com/quarto-dev/quarto-cli/assets/8713058/ae8b97e4-558e-4cc9-a43c-a8af96172a01)

### Steps to reproduce

Start with the Quarto tutorial file, computations.qmd, and add these chunks, per the tutorial instructions:

```{r}
#| label: load-packages
library(ggplot2)
```

The plots in @fig-mpg show the relationship between city and highway mileage for 38 popular models of cars. In @fig-mpg-1 the points are colored by the number of cylinders while in @fig-mpg-2 the points are colored by engine displacement.

```{r}
#| label: fig-mpg
#| fig-cap: "City and highway mileage for 38 popular models of cars."
#| fig-subcap:
#|   - "Color by number of cylinders"
#|   - "Color by engine displacement, in liters"
#| layout-ncol: 2
#| column: page

ggplot(mpg, aes(x = hwy, y = cty, color = cyl)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_viridis_c() +
  theme_minimal()

ggplot(mpg, aes(x = hwy, y = cty, color = displ)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_viridis_c(option = "E") +
  theme_minimal()
```
```
See https://quarto.org/docs/get-started/computations/rstudio.html.

### Expected behavior

Figs 1a and 1b should appear in the Preview pane in two columns, side-by-side, given this code:

``` {r}
#| label: fig-mpg
#| fig-cap: "City and highway mileage for 38 popular models of cars."
#| fig-subcap:
#|   - "Color by number of cylinders"
#|   - "Color by engine displacement, in liters"
#| layout-ncol: 2
#| column: page

ggplot(mpg, aes(x = hwy, y = cty, color = cyl)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_viridis_c() +
  theme_minimal()

ggplot(mpg, aes(x = hwy, y = cty, color = displ)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_viridis_c(option = "E") +
  theme_minimal()

```

### Actual behavior

The figures actually stack on top of each other, as in the screen shot shown here.

![image](https://github.com/quarto-dev/quarto-cli/assets/8713058/ebdd4fdd-2bd0-4e94-9693-d471cdcc61d7)

### Your environment

Edition	Windows 11 Home
Version	23H2
Installed on	‎4/‎18/‎2023
OS build	22631.3296
Experience	Windows Feature Experience Pack 1000.22687.1000.0
RAM 16 GB

RStudio 2023.12.0+369 "Ocean Storm" Release (33206f75bd14d07d84753f965eaa24756eda97b7, 2023-12-17) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.0+369 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

R version 4.3.3 (2024-02-29 ucrt)

### Quarto check output

Quarto 1.4.551
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.551
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: C:/Users/kurts/AppData/Local/Programs/Python/Python312/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.3
      Path: C:/PROGRA~1/R/R-43~1.3
      LibPaths:
        - C:/Users/kurts/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.3/library
      knitr: 1.45
      rmarkdown: 2.26

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment] 2024-03-16 20:43
Thanks for the report.

Duplicate of https://github.com/quarto-dev/quarto-cli/issues/8763

**Closed by mcanouil** 2024-03-16 20:43 UTC
Labels: bug
