### ISSUE TITLE
Autocomplete is broken for some chunk options

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#1407] opened 2022-07-15 12:21 UTC
### Bug description

* Open a new quarto document from RStudio IDE

* Try adding some chunk option like `eval` , `include`, `echo` using autocomplete after `#|` - the options are not suggested anymore. 

There my be other but that is the one found by user (reported on internal slack)

Using last dev version of Quarto in last daily version of IDE

**Comment by jjallaire** [comment] 2022-07-15 12:38
@cscheid If the fix for this is straightforward we should definitely take it. As things currently stand if you type e.g. `inc` or `ech` you get no suggestions (and then the IDE ends up flagging as an error). For me at least I do get suggestions for the actual completion values.

**Comment by cderv** [comment] 2022-07-15 14:20
> For me at least I do get suggestions for the actual completion values.

Yes I should have been more precise. I confirm that I also go get autocompletion when after the `:` but not of the option name after `#|` or after partially writing the name.

**Comment by cscheid** [comment] 2022-07-15 16:33
@jjallaire this is once again the logic behind the “execute-only” tag tripping me up.

I'll describe what's happening and my proposed fix, but there's a non-zero chance this will introduce regressions.

We have logic in autocompletion that detects whether or not to provide some "execute-only" completions. If you search for `execute-only: true`, you'll see these are exactly the ones that are being hidden here. They are being hidden "on purpose", because we explicitly have code that only shows this prediction if the instance path in the YAML is prefixed by `execute`.

IIRC, this exists so that front-matter completions _accept_ `echo`, `error`, `warning`, and other "generic-sounding" keys on the top level, but we never actually suggest completions for them. We only suggest completions under the `execute` key. Up until now we never checked if we should follow the same logic in code-cell completions as in plain YAML metadata.

My suggestion is that `execute-only` logic should only trigger in yaml metadata completions, and not in code-cell completions.

**Closed** 2022-07-15 18:10 UTC
Labels: bug

**Comment by jjallaire** [comment] 2022-07-16 14:39
I think its worth the risk b/c the `execute-only` cell options are in fact the most commonly used ones (and the tactile experience of no completions when you are accustomed to getting them makes it feel like you've got the syntax wrong).
