### ISSUE TITLE
Figure caption missing in Jupyter notebook

### ISSUE THREAD

**Issue by lexnederbragt** [quarto-dev/quarto-cli#4435] opened 2023-02-20 12:53 UTC
### Bug description

The following qmd file:

```
---
format: html
---

![An Elephant](elephant.png){#fig-elephant}

This is illustrated well by @fig-elephant.
```

after rendering results in a notebook with a single markdown cell with this content:

```
# 

![Figure 1: An Elephant](attachment:elephant.png)

This is illustrated well by [Figure 1](#fig-elephant).
```

Here, the figure caption is missing.

Screenshot:

![image](https://user-images.githubusercontent.com/1122351/220110592-af16bd23-1915-4afc-ab23-829e01371af9.png)

While this version, using a figure div:

```
---
format: html
---

::: {#fig-elephant}

![](elephant.png){#fig-elephant}

An Elephant
:::

This is illustrated well by @fig-elephant.
```

renders to a notebook with a single markdown cell with this content:

```
# 

![(a)](attachment:elephant.png)

Figure 1: An Elephant

This is illustrated well by [Figure 1](#fig-elephant).
```

Screenshot:

![image](https://user-images.githubusercontent.com/1122351/220110374-633d4bd6-ea97-4368-a386-2c75c21bb0c0.png)

The figure caption is now present.

Desired outcome: figure caption present in both cases. 

I considered using a figure div for my use case, but when combined with `{#fig-elephant fig-width=400 fig-alt="Drawing of an elephant."}` this crashes in during conversion to PDF with a `not in outer par mode` error, probably related to #4142.

Note that also, in both cases, the anchor to the figure does not work (there is no target for the link), but this may be related to #4178.

I am using VSCode to write qmd files, but render them on the command line (Mac OS 11.7), using quarto installed directly from the GitHub repo, commit id #82eae91a0 (which is why quarto --version gives 99.9.9).

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2023-02-20 15:34
That commit is [more than a month old](https://github.com/quarto-dev/quarto-cli/commit/82eae91a0); have you tried updating quarto to HEAD?

**Comment by lexnederbragt** [comment] 2023-02-21 11:01
Fair point. I just tried and using [#40f7d6fd9](https://github.com/quarto-dev/quarto-cli/commit/40f7d6fd91f947658b360a02aa1ccbe54e76b8a0) does not seem to make a difference.

**Comment by cscheid** [comment] 2023-03-09 21:37
Sorry for the delay in the reply. I have a few followup questions:

> after rendering results in a notebook

What do you mean by this? If you're using a command different from `quarto render`, can you please share the entirety of the steps that it takes you to produce the unexpected answer? (I ask because the file you shared renders to .html by default) Do you mean your _input_ is a notebook, or do you mean that your _output_ is a notebook? (Those two cases are possible in quarto, and we need to know the difference).

> I considered using a figure div for my use case, but when combined with {#fig-elephant fig-width=400 fig-alt="Drawing of an elephant."} this crashes in during conversion to PDF

I'm having a hard time following this as well. It's easier for us to track down these problems if you provide a full .qmd file showing the problem, together with the command you used to cause the problem to appear.

**Comment by lexnederbragt** [comment] 2023-03-10 11:52
Apologies for the confusion. Here is a full minimal workflow.

## file `test.qmd`:

```
---
format:
    ipynb: default
    html: default
    pdf: default
---

![An Elephant](elephant.png){#fig-elephant}

This is illustrated well by @fig-elephant.
```

Command `quarto render test.qmd`

Outputs:
1) test.html, screenshot:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/1122351/224305327-70357a75-74a8-4459-99b1-bf0b3191a082.png">

--> Figure has caption, as expected

2) test.ipynb, screenshot:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/1122351/224305428-aba88171-1c84-4e3d-9742-fea427836c75.png">

--> No figure caption.

Screenshot of the raw markdown in the notebook:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/1122351/224305510-bf445d40-f32d-435b-b903-ee3fbc3669ff.png">


3) test.pdf, screenshot:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/1122351/224308296-b87c8d3a-e0a0-44ff-8b73-127c25eff790.png">


--> Figure has caption, as expected

## file `test2.qmd`:

```
---
format:
    ipynb: default
    html: default
    pdf: default
---

::: {#fig-elephant}

![](elephant.png){#fig-elephant}

An Elephant
:::

This is illustrated well by @fig-elephant.

```

Command `quarto render test2.qmd`

Outputs:
1) test2.html, screenshot:

<img width="976" alt="image" src="https://user-images.githubusercontent.com/1122351/224305574-b7e8d3d1-d591-45af-a6e4-58f60f868b00.png">

--> Looks good, but where does the (a) come from?

2) test2.ipynb, screenshot:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/1122351/224308469-a0caa3f0-c3f9-4e72-98d8-9e8416a30c68.png">

--> Now there is a figure caption in the notebook.

Screenshot of the raw markdown in the notebook:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/1122351/224305673-b8174839-24fc-4cca-82c3-9103298789fb.png">

--> note that the hyperlink `[Figure 1](#fig-elephant)`, does not link to any target, as also noted in #4178.

3) test2.pdf

Rendering failed. Relevant part of the output from the command:

```
pandoc
  to: html
  output-file: test2.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en

pandoc
  to: latex
  output-file: test2.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf

metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true

running xelatex - 1
  This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages

compilation failed- error
LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.160


see test2.log for more information.
ERROR: Error
    at renderFiles (file:///Users/alexajo/github/quarto-cli/src/command/render/render-files.ts:532:23)
    at async render (file:///Users/alexajo/github/quarto-cli/src/command/render/render-shared.ts:101:18)
    at async Command.fn (file:///Users/alexajo/github/quarto-cli/src/command/render/cmd.ts:210:26)
    at async Command.execute (file:///Users/alexajo/github/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///Users/alexajo/github/quarto-cli/src/quarto.ts:119:3)
    at async file:///Users/alexajo/github/quarto-cli/src/quarto.ts:151:5

I assume this is the same problem as mention in #4142.

**Comment by cscheid** [comment] 2023-03-15 17:04
Let me get to one report at a time (in general it's easier for us to respond quickly if we keep to a single problem per issue, just as a heads up)

## test2.qmd

````
---
format:
    ipynb: default
    html: default
    pdf: default
---

::: {#fig-elephant}

![](elephant.png){#fig-elephant}

An Elephant
:::

This is illustrated well by @fig-elephant.
````

The problem here, I think, is that you have multiple definitions of `#fig-elephant`, and that's confusing quarto. If you want to use the div figure syntax, then the image shouldn't have a label. If you want the use the image-with-label syntax, then the caption should be in the image element.

**Comment by cscheid** [comment] 2023-03-15 17:08
## caption inconsistency in .ipynb for `test.qmd`

This is something we should either do or document better the fact that it's not supported. Let me confirm which case it should be and I'll get back to you.

**Comment by cscheid** [comment] 2023-03-15 17:20
I'm back to thinking this isn't a bug. I'm going to go ahead and close this one; my reproductions are below.

Feel free to reopen this with a new minimal example if this doesn't solve your problem. But make sure you're running the latest quarto pre-releases in that case. Thanks!

# (Non-)repros

Here's the correct figure syntax and output on the latest prerelease for either of your cases:

## test.qmd
````
---
title: issue-4435
---

::: {#fig-elephant}

![](elephant.png)

An Elephant
:::

An elephant in @fig-elephant.
````

### html
<img width="830" alt="image" src="https://user-images.githubusercontent.com/285675/225388887-3b930b6d-fb56-4b40-a622-4bf7bd505428.png">

### ipnyb
```json
{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# issue-4435\n",
        "\n",
        "![](attachment:elephant.png)\n",
        "\n",
        "Figure 1: An Elephant\n",
        "\n",
        "An elephant in [Figure 1](#fig-elephant)."
      ],
      "attachments": { ... } } ] }
```

### pdf

<img width="834" alt="image" src="https://user-images.githubusercontent.com/285675/225389222-d15c711c-4d90-4c3f-8148-2a7bd463d3a7.png">

## test2.qmd

````
---
title: issue-4435
---

![An Elephant](elephant.png){#fig-elephant}

An elephant in @fig-elephant.
````

### html
<img width="822" alt="image" src="https://user-images.githubusercontent.com/285675/225389298-722fa270-2bfe-4d05-af8f-be0e9356ac12.png">

### ipnyb

```json

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# issue-4435\n",
        "\n",
        "![Figure 1: An Elephant](attachment:elephant.png)\n",
        "\n",
        "An elephant in [Figure 1](#fig-elephant)."
      ],
      "attachments": {
        "elephant.png": { ... } } } ] }
```

### pdf

<img width="859" alt="image" src="https://user-images.githubusercontent.com/285675/225389535-61e4df71-b2c5-40b5-aa30-5808ebbbfd18.png">

**Closed by cscheid** 2023-03-15 17:20 UTC
Labels: bug, need-repro

**Comment by lexnederbragt** [comment] 2023-03-16 13:54
Thanks for testing! I now finally understand the root cause of my problem.

I can confirm that your `test2.qmd` file

```
---
title: issue-4435
---

![An Elephant](elephant.png){#fig-elephant}

An elephant in @fig-elephant.```
```

with command `quarto render test2.qmd --to ipynb`

gives this in the `.ipynb` file:

```
{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# issue-4435\n",
        "\n",
        "![Figure 1: An Elephant](attachment:elephant.png)\n",
        "\n",
        "An elephant in [Figure 1](#fig-elephant)."
      ],
      "attachments": {
        "elephant.png": { ... } } } ] }
```

However, while quarto uses the pandoc convention to use the alt-text (here `Figure 1: An Elephant`) as text for the caption in html and pdf, in the notebook, this does not work. So the raw markdown `![Figure 1: An Elephant](attachment:elephant.png)` renders in the notebook as an image without caption:

![image](https://user-images.githubusercontent.com/1122351/225636576-a94f926e-2b2b-41a5-9409-65882045e35d.png)

This is a feature, and not a bug. Solutions I found are to use the html `<img>` tag, or even better, the `<figcaption>` tag. Or placing the caption as a separate line under the figure, as for the Figure Divs.

So I guess my issue now boils down to whether you consider this a bug now and are willing to fix it along one of the solutions (or another one) listed above, so that the desired output becomes like this:

![image](https://user-images.githubusercontent.com/1122351/225638455-fed62296-6931-401e-a236-2bbe75a12a3d.png)
