### ISSUE TITLE
"number-depth" option in book project causes _quarto.yml validation error

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#4936] opened 2023-03-23 17:38 UTC
### Bug description

After upgrading from v. 0.9.515 to v. 1.3.282, a previously working book project failed to render via quarto preview with message "property name number-depth is invalid"

Option "number-depth" is still included in the guide as a valid option for a book project.

Kubuntu 20.04

To reproduce:

Create a new book project:

````
$ quarto create-project mybook --type book
````

Edit generated _quarto.yml to add "number-depth" option:

````
project:
  type: book

book:
  title: "mybook"
  author: "Norah Jones"
  date: "3/23/2023"
  number-depth: 0
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
````

Start quarto preview:

````
$ quarto preview mybook
ERROR: Project _quarto.yml validation failed.

In file mybook/_quarto.yml
(line 8, columns 3--15) property name number-depth is invalid
7:   date: "3/23/2023"
8:   number-depth: 0
    ~~~~~~~~~~~~~
9:   chapters:
ℹ The error happened in location book:number-depth.


Error: Project _quarto.yml validation failed.

In file mybook/_quarto.yml
(line 8, columns 3--15) property name number-depth is invalid
7:   date: "3/23/2023"
8:   number-depth: 0
    ~~~~~~~~~~~~~
9:   chapters:
ℹ The error happened in location book:number-depth.

    at readAndValidateYamlFromFile (file:///opt/quarto/bin/quarto.js:20541:15)
    at async file:///opt/quarto/bin/quarto.js:60660:26
    at async projectContext (file:///opt/quarto/bin/quarto.js:60515:26)
    at async serveProject (file:///opt/quarto/bin/quarto.js:107564:19)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:108162:13)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:127272:5)
    at async file:///opt/quarto/bin/quarto.js:127290:9
````

quarto check output:

````
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.282
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.37
      rmarkdown: 2.11

[✓] Checking Knitr engine render......OK
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment] 2023-03-23 17:58
Thanks for the report.

Quarto is expecting this parameter to be inside a format block or at the document level, not at the book level. I agree with you that the documentation should make this clearer. (@jjallaire, is this just a schema bug, and our book schema _should_ support this?)

As an immediate workaround, you can add this under the `html` and `pdf` entries in your _quarto.yml, and things should just work.

**Comment by jjallaire** [comment] 2023-03-23 18:54
Yes it is indeed by design (`book` options don't include format options --- I agree this can indeed be confusing though)

**Comment by cwickham** [comment] 2023-04-13 22:23
Closing to split into two separate doc issues: Improving book docs #5186, Improving understanding of context #5187

**Closed by cwickham** 2023-04-13 22:23 UTC
Labels: documentation
