### ISSUE TITLE
Preview says it's watching files but it may be not

### ISSUE THREAD

**Issue by memeplex** [quarto-dev/quarto-cli#8572] opened 2024-02-02 20:45 UTC
### Bug description

Running `quarto preview` with `--no-watch-inputs` shows `Watching files for changes`. This may be plain wrong or may just be an unfortunate wording, IDK, please take a look at the discussion starting here: https://github.com/quarto-dev/quarto/issues/307#issuecomment-1924536196

### Steps to reproduce

1. Create test.qmd file
2. Run `quarto preview test.qmd --no-watch-inputs`

### Expected behavior

If it's not watching any kind of files, of course the message should be removed. If it's still watching output files, it may be as well removed to avoid confusion or changed to something like `Watching output files for changes`.

### Actual behavior

It puts `Watching files for changes` but if I change test.qmd and save it nothing happens.

### Your environment

quarto CLI 1.4.549
MacOS Sonoma 14.3

### Quarto check output

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /private/tmp/cb/lib/python3.11/site-packages/quarto_cli/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /private/tmp/cb/bin/python3
      Jupyter: 5.7.1
      Kernels: jampp, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /opt/homebrew/Cellar/r/4.3.2/lib/R
      LibPaths:
        - /Users/carlos/.rlib
        - /Users/carlos/.rlib/base
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.2/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2024-02-02 21:17
Indeed, the message is independent of the flags:
- https://github.com/quarto-dev/quarto-cli/blob/88d695eddd77a3de3af3ad53a575cdba4dd437db/src/command/preview/preview.ts#L433-L435

**Comment by memeplex** [comment] 2024-02-02 21:22
But does it mean that it's not actually watching anything? Or that "files" should be understood as "input+output" or just "output" depending on the flag.

**Comment by mcanouil** [comment] 2024-02-02 21:40
The message is not associated with the fact that Quarto watches or not, it's independent, thus displayed no matter what.
This is controlled by `--watch-inputs` and `--no-watch-inputs`.

**Comment by cscheid** [comment] 2024-02-02 22:05
We have a duplicate of this issue somewhere. The problem is that this line can't be removed from our codebase until some downstream tooling (RStudio) is sufficiently updated. RStudio monitors that specific string internally, and so we can't fix this bug.

**Comment by mcanouil** [comment] 2024-02-02 22:09
Found it (really bad title :/):
- #848

**Closed** 2024-02-02 22:10 UTC
Labels: bug, duplicate

**Comment by cscheid** [comment] 2024-02-02 22:23
Done, thanks.
