### ISSUE TITLE
OJS Error. RequireError$1: invalid module. 

### ISSUE THREAD

**Issue by neocarto** [quarto-dev/quarto-cli#943] opened 2022-05-19 08:37 UTC
I have noticed some errors concerning the import of libraries.  For example, require("bertin") does'nt work in [Quarto](https://quarto.org/docs/tools/rstudio.html). The following error is returned: OJS Error. RequireError$1: invalid module. To import bertin, I have to write: bertin = import('https://cdn.skypack.dev/bertin@0.9'). However, require("bertin") works in Observable. Within rstudio, preview in Viewer Pane works. Preview in window doesn't work. Similarly, the html file rendered via quarto render works. 
![Screenshot from 2022-05-19 10-53-08](https://user-images.githubusercontent.com/8111373/169254224-e7006ba1-9b00-4bec-afde-a08ab8e77fe9.png)

Code to reproduce the bug (within an ojs cell).
(ubuntu 22.04, Rstudio 2022.06.0-daily+420, Quarto 0.9.434)

````
```{ojs}
bertin = require("bertin@0.9.16")
```
````

**Comment by cscheid** [comment] 2022-05-20 14:30
Ok, I can reproduce the issue, thanks for reporting!

Notably, it only appears to happen inside the RStudio IDE, but not on VS Code or running on standalone.

**Comment by cscheid** [comment] 2022-05-20 14:54
Ok, I know what this is. Unfortunately, it's going to be impractical to fix in the short term. (We expect to have this problem fixed by the end of the year.)

The issue is that the current RStudio IDE runs an old version of Chrome (Chrome 69, via QtWebEngine), and it doesn't support ES6. bertin is built with ES6 language features. For example, I see the nullish coalescing operator in `n2.strokeLinecap ?? "round"`.

**Comment by neocarto** [comment] 2022-05-20 15:00
Ok. Thank you.

**Closed** 2022-05-20 15:00 UTC
Labels: bug, wontfix, ojs-engine

**Comment by cscheid** [comment] 2022-05-20 15:06
@neocarto If you're willing to run a pre-release version of RStudio which _does_ fix the problem, the Electron builds are available on the [the daily builds page](https://dailies.rstudio.com/). Look for the rightmost column ("RStudio Desktop Electron"). That worked fine for me!

<img width="1911" alt="image" src="https://user-images.githubusercontent.com/285675/169557417-cc31b52c-d577-43fb-8ecd-3071d1fb713b.png">

**Comment by neocarto** [comment] 2022-05-20 15:17
It works! 
Thank you for your time.
