### ISSUE TITLE
Doc inconsistency / bug

### ISSUE THREAD

**Issue by dense-set** [quarto-dev/quarto-cli#5885] opened 2023-06-12 03:34 UTC
### Bug description

The [Subfigures](https://quarto.org/docs/authoring/figures.html#subfigures) section claims that the code mentioned therein produces the image therein **in HTML** target format. However, the main image caption should be **left-aligned** (as I run the code on my machine with Quarto 1.3.361) rather than centred as is being showed in the documentation.

The shown figure does however show the expected behaviour in the PDF format.

**Comment by dense-set** [comment] 2023-06-12 03:44
Same issue in the displayed image in the [Multiple rows](https://quarto.org/docs/authoring/figures.html#multiple-rows) section.

**Comment by mcanouil** [comment] 2023-06-12 05:09
This is a duplicate of #2306.
Closing this in favour of the older opened issue.

**Closed** 2023-06-12 05:17 UTC
Labels: documentation
