### ISSUE TITLE
[documentation] Fix example for LaTeX custom environments

### ISSUE THREAD

**Issue by dense-set** [quarto-dev/quarto-cli#5886] opened 2023-06-12 04:41 UTC
In Guide > Authoring > Figures > LaTeX figures > [Environments](https://quarto.org/docs/authoring/figures.html#environments), the following code is provided:

````qmd
---
title: "Sidenotes"
format:
  pdf:
    include-in-header: 
      text: |
        \usepackage{mdframed}
---

![Elephant](elephant.png){fig-env="mdframed"}
````

However, running this on my system produces a `\caption outside float` error. This is the generated log file: [test.log](https://github.com/quarto-dev/quarto-cli/files/11717821/test.log).

---
Quarto v1.3.361 on VS Code
macOS Ventura
MacTeX 2023

**Comment by cscheid** [comment] 2023-06-12 15:17
Same here, thanks for the report.

I can't render this with any versions of quarto since at least 1.0.

For a bit more context, the issue is that `mdframed` does not define a float environment, and the `caption` package expects a caption to be inside a float. This is not the kind of problem we will be able to solve in general when users choose to use `fig-env`, since in this case the latex that's being produced can be arbitrarily weird.

None of that means that we should be providing a broken example, of course.

**Comment by mcanouil** [comment] 2023-06-12 20:36
FYI, `mdframed` uses `\captionof` not `\caption`.

**Comment by cscheid** [comment] 2023-06-12 21:24
But `fig-env` doesn't know about that, and can't know what packages use what subcommands in general. The `\caption` command is emitted produced by pandoc. We could try to insert ourselves in this handling in general, but I'd prefer our code to not get into it. I don't think we fundamentally can do a good job, so we should try to do something mediocre and ultimately even more confusing. If someone wants to use `mdframed`, they should be on the hook for producing the entire latex raw block. (And our example should pick an environment that actually produces a latex float)

**Comment by mcanouil** [comment] 2023-06-12 21:47
I agree.

Here a workaround.

````qmd
---
title: "Sidenotes"
format:
  pdf:
    include-in-header: 
      text: |
        \usepackage{mdframed}
---

```{=latex}
\begin{mdframed}
\centering
\includegraphics{elephant.png}
\captionof{figure}{\label{fig-elephant}An Elephant}
\end{mdframed}
```

An elephant in `\ref{fig-elephant}`{=latex}.
````

**Comment by cscheid** [comment] 2023-06-12 22:28
But that's not a workaround for the [documentation bug being reported](https://quarto.org/docs/authoring/figures.html#environments). The documentation is about `fig-env`, not about `mdframed`.

**Comment by mcanouil** [comment] 2023-06-12 22:32
It's a workaround to use mdframed.
Indeed, it does not change the fact the documentation has a not working example for `fig-env`.

I did not mean to imply anything else. Simply to provide additional information for users that might this issue and wanted mdframed (even if no longer in the documentation in the future).

**Comment by mcanouil** [comment] 2023-06-12 23:12
A suggestion, to update the documentation:

> In addition to the default `figure` environment, there are variants, _e.g._ `figures*`. A number of LaTeX packages also provide custom figure environments. For example, `figures*` environment is similar to the figure environment, but it is wider and can be used to include larger figures or multiple smaller figures side-by-side. The `figure*` environment is typically used in documents that have a two-column layout, such as academic papers or technical reports. By default, Quarto uses the standard figure environment, but you can use the fig-env attribute to specify a custom one. For example:

````qmd
---
title: "Sidenotes"
format:
  pdf:
    classoption: twocolumn
    include-in-header:
      - text: |
          \usepackage{stfloats} % to support "b" position
keep-tex: true
---

![An Elephant](elephant-small.png){fig-env=figure* fig-pos="b"}

## Section 1

Lorem ipsum dolor sit amet, consectetur adipiscing elit. In finibus sem quis sapien lacinia fermentum. Aliquam ut ornare ex. Mauris sed lectus hendrerit, eleifend dolor non, tempor felis. Vestibulum ac diam eget eros dignissim ultricies at quis nulla. Aliquam vitae lectus maximus nulla ullamcorper posuere vel non justo. In iaculis nibh id ex elementum tempus. Donec nec sapien ullamcorper, vestibulum nibh vel, semper nunc. Fusce venenatis maximus turpis non rutrum. Suspendisse bibendum erat eu nisi efficitur ultricies ut eget est. Aliquam faucibus erat nisl, sit amet ornare ligula elementum a. Quisque auctor dui sapien, vulputate placerat nibh dignissim sed. Pellentesque eleifend nulla sit amet est posuere convallis.

Aliquam tempus pellentesque ante, vel mattis metus convallis ac. Pellentesque mattis turpis ex, ut porttitor urna porta sed. Nullam varius iaculis urna et porttitor. Sed rhoncus mauris ex, dapibus semper ante facilisis vitae. Suspendisse tincidunt urna in ligula maximus mattis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sit amet pellentesque eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec viverra sit amet mi sit amet imperdiet. Cras eget malesuada eros. Fusce tortor neque, semper ut enim quis, bibendum sollicitudin risus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent at libero eu odio pellentesque consectetur. Morbi non urna nec enim convallis blandit.
````

<img width="729" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/f7dcee96-ef8b-4d84-bf4d-0eaa8947aeaf">

**Comment by cscheid** [comment] 2023-06-13 00:38
I like switching to `figure*`.

**Comment by cderv** [comment] 2023-06-13 13:00
> But fig-env doesn't know about that, and can't know what packages use what subcommands in general. The \caption command is emitted produced by pandoc.

@cscheid Are you sure of this ? I was under the impression we are completely taking over the caption production, and we already use either `\caption` or `\sidecaption` depending if this is a margin figure or not. 

See `latex.lua` where we have some functions like 
https://github.com/quarto-dev/quarto-cli/blob/67f8577a1539ef21238db47c8d30f4d5e5335154/src/resources/filters/layout/latex.lua#L211-L223

https://github.com/quarto-dev/quarto-cli/blob/67f8577a1539ef21238db47c8d30f4d5e5335154/src/resources/filters/layout/latex.lua#L203-L209

that we use to render figure in LaTeX 
https://github.com/quarto-dev/quarto-cli/blob/67f8577a1539ef21238db47c8d30f4d5e5335154/src/resources/filters/layout/latex.lua#LL166C21-L166C21

All this related to our extended figure support 
https://github.com/quarto-dev/quarto-cli/blob/67f8577a1539ef21238db47c8d30f4d5e5335154/src/resources/filters/layout/figures.lua#L7-L41


I am sharing all this because I was thinking we could also allow maybe a `fig-caption-env` option maybe to allow configuring an environment for caption that would go with a `fig-env` ? 

Though we don't have this level of customization in **knitr**,  so maybe not be that useful outside of this `mdframed` environment. 🤔

**Comment by cscheid** [comment] 2023-06-13 14:24
@cderv You're right. I tested this incorrectly and said something stupid 🤦 I can actually try to do this in the new FloatCrossref AST nodes.

**Comment by cscheid** [comment] 2023-09-22 16:46
Revisiting this. We shouldn't be using `mdframed` because it doesn't support the standard caption commands, and making that simple example work is not really possible. I think we should just switch to the simplest `figure*` example and be done with this.

**Comment by cscheid** [comment] 2023-09-22 16:51
This is now fixed on quarto-web.

**Closed by cscheid** 2023-09-22 16:51 UTC
Labels: bug, documentation, latex
