### ISSUE TITLE
dygraph htmlwidget show unexpected scrollbar

### ISSUE THREAD

**Issue by archymedes** [quarto-dev/quarto-cli#3680] opened 2022-12-15 16:43 UTC
### Bug description

Rendering a dygraph htmlwidget on quarto document, shows an unexpected scrollbar on right side (and sometimes on bottom part too). It causes impossible to hover over last data point.
It happens on RStudio's Viewer Pane or with web-browsers like Firefox, Chrome or MS-Edge. Not allways with other web-browsers like Falkon or Konqueror.
You can see this issue on [quarto-htmlwidget page](https://quarto.org/docs/interactive/widgets/htmlwidgets.html) or rendering a new document.
I've tried with different figure widths and heights and cannot fix it.
The scrollbar does not appear rendering over a Rmarkdown document

### Reporducible example
```{r}
library(dygraphs)
dygraph(ldeaths, "All Deaths")
```

### Version

- Quarto-cli on OS: 1.2.280
- R Quarto package: 1.2
- RStudio: 2022.07.2.576

![dygraph](https://user-images.githubusercontent.com/6970897/207917921-5d6cdfb4-09da-465a-90f5-6035ed2baa84.png)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2023-01-09 15:51
Duplicate of #3894

**Closed by cscheid** 2023-01-09 15:51 UTC
Labels: duplicate
