### ISSUE TITLE
Cannnot import external javascript modules in windows

### ISSUE THREAD

**Issue by ssaket** [quarto-dev/quarto-cli#1950] opened 2022-08-17 17:38 UTC
### Bug description

*Usecase and background*:
I have some external javascript modules that I would like to use/re-use in my quarto notebook's observable (ojs) block. I am using window 11 and Powershell to run `quarto preview` command

*Expected outcome*:
I could import the external modules as per the example in the [official docs](https://quarto.org/docs/interactive/ojs/code-reuse.html)

*Actual outcome*:
I get the error:
![image](https://user-images.githubusercontent.com/27828189/185203832-c4bdec93-bdae-46c9-8217-0caeb6f22ef9.png)

*File for reproducing the error*
[github_issue.zip](https://github.com/quarto-dev/quarto-cli/files/9364978/github_issue.zip)

### `quarto check` Output

```bash
(base) C:\Users\Saket Saurabh\Projects\Misc>quarto check
FINDSTR: Cannot open Saurabh

[>] Checking Quarto installation......OK
      Version: 1.0.38
      Path: C:\Users\Saket Saurabh\AppData\Local\Programs\Quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: C:/Users/Saket Saurabh/miniconda3/python.exe
      Jupyter: 4.10.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### `quarto tools check` Output

```bash
(base) C:\Users\Saket Saurabh\Projects\Misc>quarto tools check
FINDSTR: Cannot open Saurabh
[>] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.08

```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment] 2022-08-17 17:41
@cscheid Probably another example of where we need to create URL friendly versions of paths on Windows? (I know we do that for some of our own dynamic imports)

**Comment by cscheid** [comment] 2022-08-17 17:45
That seems correct to me. I am pretty sure I fixed a related bug to this in our prerelease already, but I don't see the entry in changelog.

@ssaket Thank you for the report! Can you try installing our prerelease build https://github.com/quarto-dev/quarto-cli/releases/tag/v1.1.78 and check if the issue persists? Thank you.

**Comment by ssaket** [comment] 2022-08-17 17:53
@cscheid Thanks a lot for such a prompt response :)  
It works perfectly fine on v1.1.78 🎉 If you want, you can close this issue. Thanks again.

**Comment by cscheid** [comment] 2022-08-17 19:11
Duplicate of #1605

**Closed** 2022-08-17 19:14 UTC
Labels: duplicate
