### ISSUE TITLE
single quote + math equation in fig.cap, unhelpful error message

### ISSUE THREAD

**Issue by edzer** [quarto-dev/quarto-cli#2317] opened 2022-09-06 15:42 UTC
### Bug description

If I have an R figure section with
```
```{r fig-xyz}
#| fig.cap: "Local Moran's I at $\alpha=0.005$"
plot(1)
```

(the closing back-quotes won't render) it errors with: `ERROR: SyntaxError: Unexpected token a in JSON at position 22` (not pointing to file/line). I would like to actually use that feature: with a single quote and a math equation. If I remove the math $ symbols, things work.
This is with RStudio 2022.07.1 Build 554, quarto command line 1.0.38. Ubuntu 20.04 (or 22.04, don't know).

[xx.qmd.zip](https://github.com/quarto-dev/quarto-cli/files/9498511/xx.qmd.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2022-09-06 17:51
This isn't a bug; instead, it's unintuitive behavior from YAML strings. The following works:

````
```{r fig-xyz}
#| fig.cap: "Local Moran\\'s I at $\\alpha=0.005$"
plot(1)
````

<img width="865" alt="image" src="https://user-images.githubusercontent.com/285675/188705117-c0e5a37f-4a0e-46dd-a1db-24f497e809bd.png">

**Comment by edzer** [comment] 2022-09-06 17:57
Oh, cool! Then my only question is whether this is documented, and whether a helpful error message could be generated... Thanks in any case!

**Comment by cscheid** [comment] 2022-09-06 19:20
This is documented in the sense that we document that code cell options are YAML, and unfortunately that means users need to learn YAML. The error message could be improved, agreed.

**Comment by cscheid** [comment] 2022-09-07 21:58
I'm following up on this, and I'm having a hard time reproducing your error. The errors I'm seeing do not come from quarto, but instead from the LaTeX and MathJax rendering engines failing to compile that equation.

On second read of that error message, I believe this to be a duplicate of #1838, and the error should be improved if you upgrade your quarto install.

**Closed by cscheid** 2022-09-07 21:58 UTC
Labels: enhancement, yaml-validation

**Comment by edzer** [comment] 2022-09-08 10:47
Confirmed!

**Comment by dmi3kno** [comment] 2023-02-02 20:59
Sorry for reopening this closed issue, but here's a warning message which does not make much sense
```r 
```{r}
#| label: fig-mylab
#| fig-cap: "mtcars rows sampled n=3"
plot(mpg~hp, mtcars[sample(nrow(mtcars),3),])

#>Warning messages:
#>1: In value[[3L]](cond) : Failed to parse chunk options in body:
#>Error in parse(text = code, keep.source = FALSE): <text>:1:25: unexpected symbol
#>1: alist( label: fig-mylab fig
```
Even when the "=" sign is backslashed the warning persists 


```r
```{r}
#| label: fig-mylab
#| fig-cap: "mtcars rows sampled n\\=3"
plot(mpg~hp, mtcars[sample(nrow(mtcars),3),])

#>Warning messages:
#>1: In value[[3L]](cond) : Failed to parse chunk options in body:
#>Error in parse(text = code, keep.source = FALSE): <text>:1:25: unexpected symbol
#>1: alist( label: fig-mylab fig
                            ^

#>2: In opts$engine <- unlist(strsplit(rmdChunkOpts, split = "(\\s|,)+"))[[1]] :
#>  Coercing LHS to a list

```
Other stings tried (warning persists)
```
#| fig-cap: "mtcars rows sampled $n=3$"
#| fig-cap: "mtcars rows sampled n\\\\=3"
```

The problem goes away if the `=` sign is removed or if the explicit LaTeX command is used such as 
```
#| fig-cap: "mtcars rows sampled n\\\\=3"
```
of course, there's no "=" command in LaTeX

**Comment by cscheid** [comment] 2023-02-02 21:10
@dmi3kno Can you please share a full, small, fully reproducible .qmd file that triggers the issue you're seeing?
