### ISSUE TITLE
Caption placed outside image link when rendering to markdown

### ISSUE THREAD

**Issue by dpprdan** [quarto-dev/quarto-cli#6118] opened 2023-07-06 07:40 UTC
### Bug description

When I render 

```qmd
---
title: "Captions"
format: gfm
---

![Caption](elephant.png)

[![Caption](elephant.png)](https://quarto.org)
```

to markdown (`gfm` or `commonmark`, does not matter), the first link is rendered unaltered (`![Caption](elephant.png)`), but on the second becomes

```md
<div>

[![](elephant.png)](https://quarto.org)

Caption

</div>
```

The latter is a bug, I think?

### Steps to reproduce

Render abovementioned document.

### Expected behavior

`[![Caption](elephant.png)](https://quarto.org)` ought to render as `[![Caption](elephant.png)](https://quarto.org)`

### Actual behavior

`[![Caption](elephant.png)](https://quarto.org)` renders as

```md
<div>

[![](elephant.png)](https://quarto.org)

Caption

</div>
```

### Your environment

Both VSCode and RStudio on Windows 10.

<details>
<summary>Editors</summary>

VSCode 
```
Version: 1.79.2 (system setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
``` 

```
RStudio 2023.06.0+421 "Mountain Hydrangea" Release (583b465ecc45e60ee9de085148cd2f9741cc5214, 2023-06-05) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.0+421 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
```
</details>

### Quarto check output

<details>
<summary>quarto check from VSCode</summary>

```
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.433
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.12 (Conda)
      Path: C:/Users/Daniel.AK-HAMBURG/AppData/Local/mambaforge/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

(/) Checking R installation...........Das System kann den angegebenen Pfad nicht finden.
[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

</details>

<details>
<summary>quarto check from RStudio</summary>

```
$ quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.433
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/Daniel.AK-HAMBURG/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.43
      rmarkdown: 2.23

[>] Checking Knitr engine render......OK
```

</details>

**Comment by dpprdan** [comment] 2023-07-06 07:46
(Perhaps) interestingly 

```
<!-- badges: start -->
[![Caption](elephant.png)](https://quarto.org)
<!-- badges: end -->
```

renders as

```
<!-- badges: start -->

[![Caption](elephant.png)](https://quarto.org) <!-- badges: end -->
```

But only when there are no newlines between the comments and the image link.

(This whole thing came up when I tried to add a CI badge like 
```
[![Build Installers](https://github.com/quarto-dev/quarto-cli/actions/workflows/create-release.yml/badge.svg)](https://github.com/quarto-dev/quarto-cli/actions/workflows/create-release.yml)
```

to a README.qmd).

**Comment by mcanouil** [comment] 2023-07-06 08:05
FYI, Pandoc renders this as:

```markdown
<figure>
<img src="elephant.png" alt="Caption" />
<figcaption aria-hidden="true">Caption</figcaption>
</figure>

[![Caption](elephant.png)](https://quarto.org)
```

**Comment by dpprdan** [comment] 2023-07-06 08:57
@mcanouil yeah, the conversion to html also looks weird (it only happens from `markdown` to `gfm` or `commonmark`, but not in any other Markdown flavour to Markdown flavour, AFAICT). Anyway, that's outside the scope of this issue.

**Comment by cscheid** [comment] 2023-07-06 09:59
This is by design in the sense that what you're seeing is the format that quarto uses for figures in general: a paragraph at the end of a div. We cannot simply use the `img` element because the payload of some figures isn't actually an image, but something else.

> `[![Caption](elephant.png)](https://quarto.org)` ought to render as `[![Caption](elephant.png)](https://quarto.org)`

This, unfortunately, is significantly harder said than done, because of the requirements we have on multiple-format rendering and our syntax conventions. If you absolutely need content to be passed through untouched, the general recommendation is to use raw blocks:

````
```{=markdown}
this will not be touched
```
````

**Comment by dpprdan** [comment] 2023-07-06 11:42
Without further context this sound like a serious hack, TBH, (especially with the "uh, and when there are html comments around the image link, then let's not put in the div tags" workaround). 🙈 😄 

I don't see why there couldn't be another "and when the `format:` is some form of markdown let's drop the divs as well - and let's not move the caption outside the link". Again without further context...

> requirements we have on multiple-format rendering and our syntax conventions

But this is essentially markdown to markdown and what you describe sounds like (intermediate) markdown to all other formats?

**Comment by cderv** [comment] 2023-07-06 12:20
@cscheid I understand the design for most format, but for Markdown output is this really what we want ? 

It seems for 
````markdown
![Caption](elephant.png)
````
we don't create a Div. So we don't apply "a paragraph at the end of a div.", which is the general case you described. 

So why do we expect linked figures
````markdown
[![Caption](elephant.png)](https://quarto.org/)
````
to generate a Figure Div, while for same format in which non-linked figure are not a Div ? 

Should Markdown output likes `gfm` or `commonmark` a special case ? 

Currently all our markdown based format behave likes this, but it does not seem consistent between linked and non-linked figures for those documents. 

Is this because we need to move the `Img` out of the `Link` so that our Figure processing can apply (`extended_figure` in [figures.lua](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/filters/layout/figures.lua) ?)

> If you absolutely need content to be passed through untouched, the general recommendation is to use raw blocks

Only drawbacks here is that you can produce multi format document without using conditional feature and duplicating. 
````markdown
::: {.content-visible when-format="markdown"}
```{=markdown}
[![Caption](elephant.png)](https://quarto.org)
```
:::
::: {.content-visible when-format="html"}
[![Caption](elephant.png)](https://quarto.org)
:::
````
but working workaround nonetheless.

**Comment by cscheid** [comment] 2023-07-06 12:50
> Is this because we need to move the `Img` out of the `Link` so that our Figure processing can apply (`extended_figure` in [figures.lua](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/filters/layout/figures.lua) ?)

Yes, in general that's the reason. Crossreferenceable artifacts require a specific "shape" in the AST, and will in general be transformed.

After the new crossref work is merged, it will be easier to revisit an issue like this as an enhancement request. But the general pattern of the problem remains: our markdown output isn't really designed to be "pass-through" for every markdown input, and generally won't be.

**Comment by cderv** [comment] 2023-07-06 13:03
I understand all this for the generic case. But for markdown it seems inconsistent currently. 

Here we have Figures and Linked Figures handled differently - it is not just a matter of pass-through Markdown intact. 
And here we don't have cross reference on the linked figure that would require a specific crossref processing. 

Example: 

````markdown
---
title: "Captions"
format: 
  gfm:
    preview-mode: raw
---

![caption](elephant.png){#fig-1}

Look at Fig @fig-1

[![caption](elephant.png){#fig-2}]()

Look at Fig @fig-2
````

First case is just an image, with a Caption and an id to trigger cross reference. We get this 
````html
<img src="elephant.png" id="fig-1" alt="Figure 1: caption" />

Look at Fig <a href="#fig-1" class="quarto-xref">Figure 1</a>
````
No div, but still and cross reference to the id, and then the Caption set as a alt-text 

Second case with the Linked figure will give us 
````html
<div id="fig-2">

[![](elephant.png)]()

Figure 2: caption

</div>

Look at Fig <a href="#fig-2" class="quarto-xref">Figure 2</a>
````

Now we get a Div and the Caption is no more a alt text but a Caption below the image. Cross ref still exists. 

It seems to me this would have been the output similar to non-linked figure. 
````html

<a href=""><img src="elephant.png" id="fig-2" alt="Figure 2: caption" /></a>

Look at Fig <a href="#fig-2" class="quarto-xref">Figure 2</a>
````


I am sharing all this so that we all agree this is no ideal behavior. We can definitely deal with that after the cross ref work. 

Or maybe I missing the point why the two cases (non-Linked  and Linked figures) are different. If that the case, sorry to be insistent... I like to understand 😅

**Comment by cscheid** [comment] 2023-07-06 14:02
> Or maybe I missing the point why the two cases (non-Linked and Linked figures) are different. If that the case, sorry to be insistent... I like to understand 😅

My understanding is that they are currently different for no great reason. I don't have first-hand knowledge here, but I think that emitting "clean" markdown was never a design goal for quarto's markdown output. We generally transform the AST as an intermediate format, and in that format, it's easier to handle the linked figure by wrapping it in a div. Then, when we emit markdown, we make no effort to "backtransform" into the original clean linked figure.

In the `feature/float-crossref` branch, both cases are treated uniformly, although the AST output is significantly more complicated. In that case, though, we can make the markdown renderer emit whatever we want.

I'm going to reopen this so we can discuss.

**Comment by dpprdan** [comment] 2023-07-07 09:53
Thank you both! I understand the reasoning behind the current implementation a little bit better now.

> emitting "clean" markdown was never a design goal for quarto's markdown output

But wouldn't that be a requirement for `gfm` et al. to be considered first-class output formats?

**Comment by cscheid** [comment] 2023-07-07 12:32
> But wouldn't that be a requirement for `gfm` et al. to be considered first-class output formats?

Yes, totally. (And now I'm speaking from partial experience since I wasn't working on quarto at the very start. With that said,) I think the focus of our early releases were single-page html, single-page pdf, html+pdf books, and to a lesser extent, formats like docx and gfm. We've now built a more general infrastructure to support asciidoc, confluence, etc, and haven't paid enough attention to our `gfm` output. We should definitely revisit that in the future.

**Comment by cscheid** [comment] 2023-12-14 18:25
This is interesting. With the pandoc version we ship with 1.4, the GFM renderer now produces HTML for the first version of the output:

````
$ quarto pandoc 6118.qmd -f markdown -t gfm
<figure>
<img src="elephant.png" alt="Caption" />
<figcaption aria-hidden="true">Caption</figcaption>
</figure>

[![Caption](elephant.png)](https://quarto.org)
````

I believe this is happening because Pandoc now recognizes the first entry as a `Figure`:

````
$ quarto pandoc 6118.qmd -f markdown -t native
[ Figure
    ( "" , [] , [] )
    (Caption Nothing [ Plain [ Str "Caption" ] ])
    [ Plain
        [ Image
            ( "" , [] , [] ) [ Str "Caption" ] ( "elephant.png" , "" )
        ]
    ]
, Para
    [ Link
        ( "" , [] , [] )
        [ Image
            ( "" , [] , [] ) [ Str "Caption" ] ( "elephant.png" , "" )
        ]
        ( "https://quarto.org" , "" )
    ]
]
````

Quarto 1.4 currently produces the following document for this input:

````
# Captions


<figure>
<img src="elephant.png" alt="Caption" />
<figcaption aria-hidden="true">Caption</figcaption>
</figure>

<figure>
<a href="https://quarto.org"><img src="elephant.png"
alt="Caption" /></a>
<figcaption>Caption</figcaption>
</figure>
````

Now, this looks _weird_, but GitHub actually renders it "not horribly". See:

----

# Captions


<figure>
<img src="elephant.png" alt="Caption" />
<figcaption aria-hidden="true">Caption</figcaption>
</figure>

<figure>
<a href="https://quarto.org"><img src="elephant.png"
alt="Caption" /></a>
<figcaption>Caption</figcaption>
</figure>

----

(ignore the broken links, ofc) The main issue is the repeated captions, which appears even if I remove the `alt` attribute from the image.

**Comment by cscheid** [comment] 2023-12-14 18:38
Actually, it's easy enough for us to restore the previous (IMO, better) Pandoc behavior, so we're going to do that instead.

**Closed** 2023-12-14 18:41 UTC
Labels: enhancement, crossref
