### ISSUE TITLE
[Docusaurus] Callout block placed at the top of the tab item does not work

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#5103] opened 2023-04-05 15:42 UTC
### Bug description

When the following qmd file is rendered in the Docusaurus project, the first callout block is not rendered correctly.

````qmd
---
title: foo
---

## test

::::{.panel-tabset}

### Not work

:::{.callout-important}

This is important

:::

foo

### Work

bar

:::{.callout-important}

This is important

:::

::::

````

It seems that a blank line is required between `<TabItem value="Not work">` and `:::important`.

````md
---
title: foo
---

import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

## test {#test}

<Tabs>
<TabItem value="Not work">
:::important

This is important

:::

foo

</TabItem>
<TabItem value="Work">

bar

:::important

This is important

:::
</TabItem>
</Tabs>

````

![image](https://user-images.githubusercontent.com/50911393/230131895-b5ef8df9-98f6-4fea-a066-28bbc14deafb.png)

I tested it with 1.2 and the edge unreleased version on Debian Linux.

```sh
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /tmp/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.2
      Path: /usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment] 2023-04-05 17:29
@eitsupi thanks for the report as always. I was having a hard time reproducing your bug, but mostly because there was a different bug. JJ and I did fix the spacing issue you saw, but locally I'm seeing a larger problem, which is that a tabset inside a callout wouldn't get rendered at all.

On `main`, I see this as the .md output for your file:

````
---
title: foo
---

import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

## test {#test}

<Tabs>
<TabItem value="Not work">

foo

</TabItem>
<TabItem value="Work">

bar

</TabItem>
</Tabs>
````

After my fix, I see this:

````
---
title: foo
---

import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

## test {#test}

<Tabs>
<TabItem value="Not work">

:::important

This is important

:::

foo

</TabItem>
<TabItem value="Work">

bar

:::important

This is important

:::

</TabItem>
</Tabs>

````

(Note the correct spacing, though!) Thanks for the continued patience on this. v1.3 has a large structural change in our filters, and custom formats took a bigger hit than we had envisioned.

**Comment by eitsupi** [comment] 2023-04-06 11:27
Thank you for working on fixing this immediately!

> I was having a hard time reproducing your bug, but mostly because there was a different bug. JJ and I did fix the spacing issue you saw, but locally I'm seeing a larger problem, which is that a tabset inside a callout wouldn't get rendered at all.

Sorry for not reporting that. I didn't report it because it seemed to have been fixed while going back and forth between the 1.2 and dev versions on my local, but on second thought I think I may have just been looking at a 1.2 converted md file...
So, this bug is in 1.2, and as you discovered, there was a bigger bug in 1.3...

**Comment by cscheid** [comment] 2023-04-06 15:32
This should be fixed now on `main`, from https://github.com/quarto-dev/quarto-cli/commit/35fd0b30b90b6c0327c11a91120934a353a5e27f

**Closed by cscheid** 2023-04-06 15:32 UTC
Labels: bug, docusaurus

**Comment by eitsupi** [comment] 2023-04-07 12:29
Works fine, thanks!
