### ISSUE TITLE
ToC does not play well when sections are numbered

### ISSUE THREAD

**Issue by astamm** [quarto-dev/quarto-cli#1145] opened 2022-06-14 07:39 UTC
### Bug description

When both `toc: true` and `number-sections: true` are set, the section number is added twice in the ToC, resulting in dead links when one clicks on them in the ToC.
Small reproducible example (running under quarto `v0.9.566` and RStudio `2022.02.3 Build 492` on macOS Monterey)
```
---
title: "toc-gfm-numbered-sections"
author: "Aymeric Stamm"
format:
  gfm: default
  html: default
editor: visual
toc: true
number-sections: true
---

## H1

### Sub-H1

## H2
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cderv** [comment] 2022-06-14 09:34
Hi @astamm can you reformat your issue correctly  ? https://yihui.org/issue/#please-format-your-issue-correctly

I assume you used level-1 headers in the doc but we don't have them, and I assume code chunks have backticks too. 
Also I assume the issue is with **gfm** format, right ? it is working well for HTML ? 

Small reproducible example I have 
````markdown
---
title: "toc-gfm-numbered-sections"
format: gfm
toc: true
number-sections: true
---

# H 1

## Sub 1

# H2
````

will output 
````markdown
toc-gfm-numbered-sections
================

-   <a href="#h-1" id="toc-h-1"><span class="toc-section-number">1</span>
    <span class="header-section-number">1</span>. H 1</a>
    -   <a href="#sub-1" id="toc-sub-1"><span
        class="toc-section-number">1.1</span> <span
        class="header-section-number">1.1</span> Sub 1</a>
-   <a href="#h2" id="toc-h2"><span class="toc-section-number">2</span>
    <span class="header-section-number">2</span>. H2</a>

# <span class="header-section-number">1</span>. H 1

## <span class="header-section-number">1.1</span> Sub 1

# <span class="header-section-number">2</span>. H2
````

For the record, there was a change in Pandoc 2.18 regarding adding id to TOC elements (https://github.com/jgm/pandoc/pull/7913) and this had the effect on `gfm` formats to use html for TOC with id attributes.
So we may need to handle that correctly. 

This is what we got with bare Pandoc
````powershell
❯ quarto pandoc --to gfm -f markdown --toc -s
# Head

Content
^Z
-   <a href="#head" id="toc-head">Head</a>

# Head

Content

❯ quarto pandoc --to gfm -f markdown --toc -s --number-sections
# Head

content
^Z
-   <a href="#head" id="toc-head"><span class="toc-section-number">1</span>
    Head</a>

# Head

content
````

**Comment by cderv** [comment] 2022-06-14 09:55
In fact it may just be something related to our number section handling 

We are adding the class using a Span
https://github.com/quarto-dev/quarto-cli/blob/2449933e90fe5e0b91a8286278ec0b8a78adb1f6/src/resources/filters/crossref/sections.lua#L59-L62

before
````
1: Str ". "
2: Str "H"
3: Space
4: Str "1"
````

after
````
1: Span ("",["header-section-number"],[]) [Str "1"]
2: Str ". "
3: Str "H"
4: Space
5: Str "1"
````

So it gets doubled down by Pandoc which will also add a Span for the numbering section.  

Do we need to do that for markdown outputs too ? 

* We could either not add the Span ourself when FORMAT output is a markdown format
* Or just post process the output to remove what Pandoc is adding (as it is one for HTML document it seems 
https://github.com/quarto-dev/quarto-cli/blob/23d0feb453cccf8b9b7d0685c08b19f822d6a85a/src/format/html/format-html.ts#L367-L375

**Comment by jjallaire** [comment] 2022-06-16 19:31
There are a handful of underlying issues here. Here's the test document I'll be basing examples on:

````markdown
---
title: "toc-gfm-numbered-sections"
---

# H

## Sub

# H2
````

As of Pandoc 2.18 the table of contents in `gfm` output now uses raw HTML as follows:

```bash
pandoc toc.md --to gfm --standalone --toc
```

```markdown
-   <a href="#h" id="toc-h">H</a>
    -   <a href="#sub" id="toc-sub">Sub</a>
-   <a href="#h2" id="toc-h2">H2</a>

# H

## Sub

# H2
```

If this isn't considered desirable then an issue should be filed with Pandoc to make this optional and/or disabled by default (not sure what their position on that would be though).

Numbering of section headings is not formally supported by Pandoc for markdown formats (see the docs here on what formats are supported: https://pandoc.org/MANUAL.html#option--number-sections).  However, if you add `--number-sections` along with `--toc` for `gfm` output Pandoc will number the TOC but _will not_ number the section headings:

```bash
quarto pandoc toc.md--to gfm --standalone --toc --number-sections
```

```markdown
-   <a href="#h" id="toc-h"><span class="toc-section-number">1</span> H</a>
    -   <a href="#sub" id="toc-sub"><span class="toc-section-number">1.1</span>
        Sub</a>
-   <a href="#h2" id="toc-h2"><span class="toc-section-number">2</span>
    H2</a>

# H

## Sub

# H2
```

The problem reported here (the doubling of the section numbers in the TOC) results from Quarto attempting to number the heading manually, then subsequently Pandoc doing its own numbering in the TOC (and picking up our numbers). I think given this behavior we are out of school doing manual numbering for markdown formats, so I've disabled that (now we behave identically to pandoc). Here is that change: https://github.com/quarto-dev/quarto-cli/commit/8875ec637cad089f417538fb9238eea5c9244ec0

I think if you want heading numbering to work for Pandoc `gfm` output that may be a worthwhile thing requesting on the Pandoc repo. Once this works then presumably the doubling of section numbers in the TOC would go away (as there would be an expectation in the Pandoc writer that headings already have a number so an additional one wouldn't be added when building the TOC).

**Comment by cderv** [comment] 2022-06-17 06:52
> If this isn't considered desirable then an issue should be filed with Pandoc to make this optional and/or disabled by default (not sure what their position on that would be though).

Regarding the raw HTML for TOC, as mentioned this is due to the change in https://github.com/jgm/pandoc/pull/7913 which was intentional. It adds `id` on TOC element and GFM output can handle that only by writing raw HTML, as it does not support attributes in markdown syntax. I had raised a question about this change in the past which remained unanswered https://groups.google.com/g/pandoc-discuss/c/gQZrKunCvB4/m/j7177M-3BwAJ

I think I will open an issue to bring attention to this. I'll report back. cc @tarleb as you may have context.

**Comment by astamm** [comment] 2022-06-17 08:14
> Hi @astamm can you reformat your issue correctly ? https://yihui.org/issue/#please-format-your-issue-correctly

Thanks for looking into this. @cderv I edited the original post to format the issue correctly.

**Comment by cderv** [comment] 2022-12-20 21:48
Just a heads up that https://github.com/jgm/pandoc/issues/8131 has been merged, so this will probably be better in next Pandoc version. This is to follow.

**Comment by cderv** [comment] 2023-03-22 14:56
Now that our pre release 1.3 is based on newer pandoc with jgm/pandoc#8131 merged, we get the following with your example 

````
---
title: "toc-gfm-numbered-sections"
author: "Aymeric Stamm"
format:
  gfm: default
  html: default
editor: visual
toc: true
number-sections: true
---

## H1

### Sub-H1

## H2
````

````
# toc-gfm-numbered-sections
Aymeric Stamm

- [<span class="toc-section-number">1</span> H1](#h1)
  - [<span class="toc-section-number">1.1</span> Sub-H1](#sub-h1)
- [<span class="toc-section-number">2</span> H2](#h2)

## H1

### Sub-H1

## H2
````

Somehow, it seems we are missing the numbers on the actual headers now. 🤔

**Comment by cderv** [comment] 2023-03-24 18:01
@cscheid I think the numbering does not work anymore for Markdown output. Numbering of section is part of crossref, so maybe you want to look at that in 1.4 ? 

We can also close this issue (which is fixed regarding the TOC) and open a new one for newest regression mentioned in https://github.com/quarto-dev/quarto-cli/issues/1145#issuecomment-1479718573

````markdown
---
title: "test"
format: gfm
number-sections: true
---

## H1

### Sub-H1

## H2

````

**Comment by dragonstyle** [comment] 2024-01-08 19:04
We need to roll this back as the current fix results in duplicate numbering in the TOC. We'll take another look in Quarto 1.5.

**Closed** 2024-01-08 19:06 UTC
Labels: bug, crossref

**Comment by dragonstyle** [comment] 2024-01-08 19:07
Please be sure not to cause https://github.com/quarto-dev/quarto-cli/issues/8113 when fixing this.
