### ISSUE TITLE
Markdown tables use different style than code (kable) tables

### ISSUE THREAD

**Issue by cbrnr** [quarto-dev/quarto-cli#922] opened 2022-05-18 14:11 UTC
Consider the following reprex (tested with quarto 0.9.424):

````markdown
---
title: "Table vs. kable"
engine: knitr
---

A Markdown table is *not* striped:

|  a|  b|  c|
|--:|--:|--:|
|  1|  6| 11|
|  2|  7| 12|
|  3|  8| 13|
|  4|  9| 14|
|  5| 10| 15|

But a table generated with `knitr::kable()` is striped (besides other minor differences):

```{r}
data.frame(a=1:5, b=6:10, c=11:15) |> knitr::kable()
```
````

Although the output of the code cell is exactly equal to the Markdown table in the example (the first table), the output look different, most notably only the `kable` is striped:
<img width="869" alt="Screen Shot 2022-05-18 at 16 09 29" src="https://user-images.githubusercontent.com/4377312/169061668-34f3e2d9-ed67-481e-86fe-8db4b02648ec.png">

I would have expected that the tables use the same style by default. If this is not desired, is there a way I can make them the same?

**Comment by jjallaire** [comment] 2022-05-18 18:41
It's on our short list to make this configurable, but right now tables from data frames are striped (and more compact) and tables within content are not.

**Comment by mcanouil** [comment] 2023-07-18 00:21
To note, this can easily be solved:

````qmd
---
title: "Table vs. kable"
engine: knitr
keep-md: true
---

A Markdown table is *not* striped:

|  a|  b|  c|
|--:|--:|--:|
|  1|  6| 11|
|  2|  7| 12|
|  3|  8| 13|
|  4|  9| 14|
|  5| 10| 15|

But a table generated with `knitr::kable()` is striped (besides other minor differences):

```{r}
#| output: asis
data.frame(a=1:5, b=6:10, c=11:15) |> knitr::kable()
```

````

Also, Quarto table processing can be disable, see <https://quarto.org/docs/authoring/tables.html#disabling-quarto-table-processing>.

**Comment by cderv** [comment] 2023-07-18 11:03
I am surprised by this trick of using `output: asis` on the `kable()` results to modify the default behavior that we apply on computation tables.

Striped tabled is indeed a default we set for computational table 
https://github.com/quarto-dev/quarto-cli/blob/ecf2a082652784ffb22faa52e5980836b7481a6f/src/format/html/format-html-bootstrap.ts#L390-L398

which is different than our default for non computational table. 

> but right now tables from data frames are striped (and more compact) and tables within content are not.

@jjallaire what is the reason to make the two style different ?  (0a352d65b52ff1bd2a8dd33f1a63f876cfa2b0ae and 42305132f781c546893aa6ce09e9493145f88d3e) 


> most notably only the kable is striped

With new feature in 1.3 (https://quarto.org/docs/prerelease/1.3/tables.html), one can now apply striped to Markdown table easily 

This example would be the other counterpart to make the Markdown table use the same style as the computational table 
````markdown
---
title: "Table vs. kable"
engine: knitr
---

A Markdown table is *not* striped:

|  a|  b|  c|
|--:|--:|--:|
|  1|  6| 11|
|  2|  7| 12|
|  3|  8| 13|
|  4|  9| 14|
|  5| 10| 15|

: {.striped .sm .small}

But a table generated with `knitr::kable()` is striped (besides other minor differences):

```{r}
data.frame(a=1:5, b=6:10, c=11:15) |> knitr::kable()
```
````

> Also, Quarto table processing can be disable, see [quarto.org/docs/authoring/tables.html#disabling-quarto-table-processing](https://quarto.org/docs/authoring/tables.html#disabling-quarto-table-processing).

@mcanouil Not sure kable processing happens here for **knitr** output. Are you suggesting to apply that for the Markdown table ?

**Comment by mcanouil** [comment] 2023-07-18 11:07
Indeed it not not in this case, Quarto processing would mostly matters when using `format = "html"` and in combination of `kableExtra`.
The trick (because it's really is a trick) with `output: asis` allow to avoid Quarto processing when the markdown table is inside a "cell" div.

**Comment by jjallaire** [comment] 2023-07-18 12:09
The reason they are different is that data looks dramatically better w/ condensed/striped presentation, whereas content often looks worse (they are really two different use cases of table). The solution should be allowing uses to override the default (which I believe we were slated to do in v1.3, not sure if we exposed every required knob).

**Comment by cderv** [comment] 2023-07-18 12:13
> that data looks dramatically better w/ condensed/striped presentation, whereas content often looks worse (they are really two different use cases of table).

Oh I see. Did not think of that. Thanks for the precision.

**Comment by mcanouil** [comment] 2023-07-18 12:56
Since it is by design, do we keep this open?

**Comment by cderv** [comment] 2023-12-27 11:00
Let's close this and follow work for opting out in #6945

**Closed by cderv** 2023-12-27 11:00 UTC
Labels: enhancement, tables
