### ISSUE TITLE
Code chunks in lists again

### ISSUE THREAD

**Issue by lahvak** [quarto-dev/quarto-cli#789] opened 2022-05-03 16:27 UTC
With version `0.9.347` (2 hours old), I get a strange behavior of code chunks in lists (only tested with knitr engine):

The first code chunk in list is rendered badly.  The following qmd file:

````
---
title: Blah 
---

Blah blah

```{r}
1 + 1
```

*   The same in a list:

    ```{r}
    1 + 1
    ```

*   The same in a list again:

    ```{r}
    1 + 1
    ```
````

correctly renders the first and the third code chunk, but the second one is shown as

```
    1 + 1 ```
```

The relevant part of the generated html is

```
<p>Blah blah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">+</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<ul>
<li><p>The same in a list:</p>
<p>1 + 1 ```</p></li>
<li><p>The same in a list again:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">+</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div></li>
</ul>
```

It may be related to #74.

I also got some really strange issues with code chunks in lists when the list had some lines that were indented by less than 4 spaces. The lists rendered correctly, and so did the code chunks, but the rendered code chunks in the html file were surrounded by `:::{some text here}:::{some other text}` and `::: :::` or some similar text like this, however, I cannot reproduce that in a MWE.

**Comment by cderv** [comment] 2022-05-03 20:45
Thanks for the report. I can reproduce. A `git bisect` points the regression to this specific commit 4a96a3741a56f60af10f4dfd418de5cd999a5081
We now need to find what introduced this change of behavior. @cscheid, as you worked on the change in the commit in question, maybe you know directly from look at this issue  ?

**Comment by cderv** [comment] 2022-05-03 21:30
It is possible the parsing of `mdCells` by `breakQuartoMd()` is not correct for code chunks inside indented list.
It seems that the parsing does not identified those blocks as `cell_type:{language: 'r'}` but `cell_type: 'markdown'`

This leads to the markdown value passed in 

https://github.com/quarto-dev/quarto-cli/blob/91dc07e08cde60bc059b304048953990d6744935/src/execute/rmd.ts#L86

to be different from the source `.qmd`: 

````markdown
---
title: Blah
format:
  html:
    keep-md: true
---


Blah blah


```{r}
1 + 1
```


-   The same in a list:


    1 + 1
    ```

-   The same in a list again:

    ```{r}
    1 + 1
    ```
````

This value seems to be used now as the input file 

https://github.com/quarto-dev/quarto-cli/blob/91dc07e08cde60bc059b304048953990d6744935/src/resources/rmd/execute.R#L19-L21

Something does not feel right here. The document on which `rmarkdown::render()` will be applied is not the input one. Somehow the chunk is modified. 

It feels like the change in 91dc07e08cde60bc059b304048953990d6744935 has unveil an issue in the cell parsing 🤔

**Comment by cscheid** [comment] 2022-05-03 21:52
Yes, you're right that the .qmd is no longer the same: we need that for some of the shortcode support: `{{< include file >}}` might have `{r}` cells and those need to be visible to rmarkdown. So, in general, they really won't be the same anymore

With that said, I believe your suspicions about `breakQuartoMd` messing up the markdown are correct. Let me investigate.

**Comment by cderv** [comment] 2022-05-03 21:52
Looking into this closer, I don't know if we support correctly indented code blocks with our regex
https://github.com/quarto-dev/quarto-cli/blob/b0ab191e89022465a882f62c5f59242f4247d88a/src/core/lib/break-quarto-md.ts#L40-L47

We don't have a end code cell regex that supports indent spaces. It seems supporting that is enough to fix the issue 
````diff
diff --git a/src/core/lib/break-quarto-md.ts b/src/core/lib/break-quarto-md.ts
index cf56a696f..3e797d388 100644
--- a/src/core/lib/break-quarto-md.ts
+++ b/src/core/lib/break-quarto-md.ts
@@ -43,7 +43,7 @@ export async function breakQuartoMd(
     "^\\s*```+\\s*\\{([=A-Za-z]+)( *[ ,].*)?\\}\\s*$",
   );
   const startCodeRegEx = /^```/;
-  const endCodeRegEx = /^```+\s*$/;
+  const endCodeRegEx = /^\s*```+\s*$/;
   const delimitMathBlockRegEx = /^\$\$/;

   let language = ""; // current language block
````

does this change can have side effect ?

**Comment by cscheid** [comment] 2022-05-03 21:56
As you will have noticed, `breakQuartoMd` is already very much a best-effort thing (and it's on the short list for replacing with a real parser, though we're short on time).

Your suggestion might work for this case but I think that ideally, we'd be checking for the indentation of the opening and closing code statements to match.

**Closed** 2022-05-03 22:14 UTC
Labels: bug

**Comment by cscheid** [comment] 2022-05-03 22:17
This was indeed a bug, and @cderv's suggestion fixed it. Sorry about that! This is the output I'm seeing now:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/285675/166575479-87c10174-dabc-4fc3-a644-f7ad9fe81725.png">

Let us know if the problem persists for you!

**Comment by cderv** [comment] 2022-05-04 06:49
Thanks for the report @lahvak !
