### ISSUE TITLE
Better error when extension filter is not found

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2207] opened 2022-08-30 09:06 UTC
### Bug description

I have see this type of issue several time already: https://github.com/quarto-ext/lightbox/issues/9

````
Error running filter lightbox:
Could not find executable lightbox
````

It seems it is confusing for user what this means, especially as they tried to use an extension and the error does not mention anything. When you know filter can also be JSON filter, the error message makes sense: Extension was not found somehow. 

What about making this error more clear to user ? We don't have specific syntax to know the filter asked is supposed to be in an extension, but we can assume most of the time that will be the usage (instead of JSON filter for Pandoc). 

Maybe we can improve the error message saying. "If you tried to use an extension, please do check the extension is correctly installed for your project", or something like that. 

Just an idea and opening this issue to get feedback on this situation when that happens. 

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment] 2022-08-30 18:19
Duplicate of #1570.

**Closed by cscheid** 2022-08-30 18:19 UTC
Labels: duplicate

**Comment by cderv** [comment] 2022-08-30 20:47
Thank you. I looked it up, but must have used the wrong keywords. Sorry.
