### ISSUE TITLE
auto indenting after using::: operator in Rstudio

### ISSUE THREAD

**Issue by jrob95** [quarto-dev/quarto-cli#9783] opened 2024-05-28 07:00 UTC
### Bug description

When editting in source (not visual) mode after using a ::: operator, auto indentation does not work in subsequent chunks. This may also be an issue with R studio so I will submit there also.

### Steps to reproduce

```` quarto
---
title: "div error"
format: html
editor: source
---

::: {.panel-tabset .nav-pills}
## Tab 1
```{r}
library(tidyverse)
hello <- cars %>%
mutate(double_speed = speed *2)
```


## Tab 2


```{r}
hello <- cars %>%
mutate(double_speed = speed *2)
```
:::

```{r}
sessionInfo()
```


````

### Expected behavior

When making a new line after `hello <- cars %>%` I would expect automatic indentation

### Actual behavior

Cursor goes to the start of the new line.

### Your environment

IDE: R studio 2024.4.1.748
R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

### Quarto check output

```
$ quarto check
Quarto 1.4.553
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.553
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\user\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: C:/ProgramData/Anaconda3/python.exe
      Jupyter: 4.11.1
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Program Files\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Program Files\Quarto\share\jupyter\notebook.py", line 18, in <module>
    from nbclient import NotebookClient
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\__init__.py", line 6, in <module>
    from .client import NotebookClient, execute  # noqa: F401
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 14, in <module>
    from jupyter_client import KernelManager
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\__init__.py", line 103, in <module>    from zmq import backend
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing _device: The specified module could not be found.
[>] Checking Jupyter engine render....OK
```

**Comment by cderv** [comment] 2024-05-28 07:58
![rstudio_rtbsIZUtKV](https://github.com/quarto-dev/quarto-cli/assets/6791940/ae0a85aa-ed94-4ede-ac47-93d980d0a9bf)

As you can see I can't reproduce, going to newline correctly indent on my side. 

Anyhow, source editor experience is from the IDE, so I will close this and you can open there. 

Thanks!

**Closed by cderv** 2024-05-28 07:58 UTC
Labels: bug

**Comment by jrob95** [comment] 2024-05-29 00:29
Thanks,
I have just now seen this is mentioned in https://github.com/rstudio/rstudio/issues/14739

Cheers,
Jack
