### ISSUE TITLE
Website sitemap.xml does not include aliases

### ISSUE THREAD

**Issue by dfolio** [quarto-dev/quarto-cli#6543] opened 2023-08-16 10:00 UTC
### Bug description

When rendering a website with pages with aliases  (i.e. [redirects](https://quarto.org/docs/websites/website-navigation.html#redirects)), the generated `sitemap.xml` does not contain the alias entries.

### Steps to reproduce

For instance, let consider a quarto document `posts/posts.qmd`  with the following yaml frontmatter:

```{yaml}
---
title: "Posts"
aliases: 
  - /posts/index.html
---
```

Then render your website.

### Expected behavior

The generated sitemap.xml does not include

```{xml}
<url>
<loc>https://dfolio.fr/posts/index.html</loc>
<lastmod>2023-08-16T11:44:09.435Z</lastmod>
</url>
```

### Actual behavior

The generated sitemap contain **only** the `posts.html` entry:

```xml
<url>
  <loc>https://dfolio.fr/posts/posts.html</loc>
  <lastmod>2023-08-16T11:44:09.435Z</lastmod>
</url>
```

But, the alias entries are not present in the `sitemap.xml`.
This does not impact the site, but the referencer complains about it.

### Your environment

- IDE: Rstudio 2023.06.0 (build 421)
- OS: Linux

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.353
      Path: /opt/quarto-1.3.353/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/lib/python-exec/python3.10/python3
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/lib64/R
      LibPaths:
        - /home/XXX/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/lib64/R/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK
```

**Comment by dragonstyle** [comment] 2023-11-28 16:50
I believe this is not a bug, so I'm closing. Please feel free to re-open if there are additional changes you think should be made.

**Closed by dragonstyle** 2023-11-28 16:50 UTC
Labels: bug, websites, html
