### ISSUE TITLE
No syntax highlighting for code listing with executable code block with the `lst-label` and `lst-cap` options

### ISSUE THREAD

**Issue by marklhc** [quarto-dev/quarto-cli#8747] opened 2024-02-15 19:03 UTC
### Bug description

When I cross reference code listing from an executable code block using the `lst-label` and `lst-cap` options, syntax highlighting is applied in HTML, but not some other formats like `pdf`, `gfm`, and `docx`. Syntax highlighting is applied when it is not an executable block, or when I use the div syntax for the executable block.

### Steps to reproduce

````qmd
---
title: "Untitled"
format:
  html: default
  pdf: default
  docx: default
  gfm: default
---

```{r}
#| lst-label: lst-1
#| lst-cap: One plus one
x <- 1
```

@lst-1 does not have highlight in PDF

::: {#lst-2}

```{.r}
x <- 1
```

One plus one

:::

@lst-2 has highlight in PDF

::: {#lst-3}

```{r}
x <- 1
```

One plus one

:::

@lst-3 has highlight in PDF
````

### Expected behavior

All three examples (`lst-1`, `lst-2`, and `lst-3`) have consistent output with syntax highlighting. 

### Actual behavior

Syntax highlighting not applied in `lst-1` except for HTML output.

HTML: 
![image](https://github.com/quarto-dev/quarto-cli/assets/6175332/892b1520-6a91-407c-94ca-9be3a3b85d57)

PDF: 
![image](https://github.com/quarto-dev/quarto-cli/assets/6175332/e7cd5cc1-7a41-452c-a0f9-99c98ece3b1e)

Markdown

````markdown
# Untitled


    x <- 1

<a href="#lst-1" class="quarto-xref">Listing 1</a> does not have
highlight in PDF

``` r
x <- 1
```

<a href="#lst-2" class="quarto-xref">Listing 2</a> has highlight in PDF

``` r
x <- 1
```

<a href="#lst-3" class="quarto-xref">Listing 3</a> has highlight in PDF
````

### Your environment

- IDE: I just used `quarto render` in the terminal
- OS: Ubuntu 20.04

### Quarto check output

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/hokchiol/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in .dbus. Did you forget to activate it?

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib/R
      LibPaths:
        - /home/hokchiol/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

```

**Comment by marklhc** [comment] 2024-02-15 19:09
Update: the difference seems to have to do with whether to use the div syntax or not, as using the [old syntax](https://quarto.org/docs/authoring/cross-references.html#code-listings) for non-executable block also results in no syntax highlighting

````qmd
---
title: "Untitled"
format:
  html: default
  pdf: default
  docx: default
  gfm: default
---

```{r}
#| lst-label: lst-1
#| lst-cap: One plus one
x <- 1
```

@lst-1 does not have highlight in PDF

```{#lst-2 .r lst-cap="One plus one"}
x <- 1
```

@lst-2 does not have highlight in PDF

::: {#lst-3}

```{.r}
x <- 1
```

One plus one

:::

@lst-3 has highlight in PDF

::: {#lst-4}

```{r}
x <- 1
```

One plus one

:::

@lst-4 has highlight in PDF
````

**Comment by mcanouil** [comment] 2024-02-15 19:43
Duplicate of #8669

**Closed by mcanouil** 2024-02-15 19:43 UTC
Labels: bug
