### ISSUE TITLE
Nested tabsets no longer work

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto-cli#4104] opened 2023-01-26 05:38 UTC
### Bug description

By chance, [I stumbled across the fact](https://fediscience.org/@andrew/109730300221529378) that Quarto (at least as of v1.3.56) supports nested tabsets, where a document like this:

````
---
title: Tabsets inside tabsets
---

:::: {.panel-tabset}
## A section

::: {.panel-tabset}
### A section within a section

### Another section inside a section

Neato.

:::

## Another section
::::

````

…would render like this, with a tabset inside the parent tabset:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/73663/214765075-c9703d09-f4f3-4912-9f7c-ebde3d62c8ef.png">

Somewhere between v1.3.56 and v1.3.129, though, this broke. Using v1.3.129, that same example document renders like this, only showing the parent tabset:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/73663/214765412-87b9e435-3880-4c0d-8839-303ec6096584.png">

I'm not sure when/at which version exactly the regression happened, or if it even counts as a regression since nested tabsets were never formally documented and perhaps never meant to be supported? I think it is a useful to have in more complicated notebook-type documents (checking lots of Bayesian diagnostic plots for a bunch of models in a compact way, for example—[see here for another use case](https://fediscience.org/@andrew/109730391347236604))

---

(This is all with R 4.2.2 on macOS Ventura 13.1 with Quarto v1.3.129)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by Pierre9344** [comment] 2023-01-26 11:24
Hello,

It is the same problem as the one I posted [previously](https://github.com/quarto-dev/quarto-cli/issues/4068). It will be corrected with the full release of quarto 1.3.
For now, we can use nested tabset by downgrading quarto to the 1.2 version.

**Comment by cderv** [comment] 2023-01-26 12:03
Thanks - closing in favor of #4068 - we'll fix this for 1.3

**Comment by cderv** [comment] 2023-01-26 12:03
Duplicate of #4068

**Comment by cscheid** [comment] 2023-01-26 17:49
@andrewheiss I think I jinxed it with my Mastodon comment the other day :) Sorry about this, we'll make sure to fix it!

**Comment by cscheid** [comment] 2023-01-26 19:23
@cderv we can keep this one closed, it's def a duplicate.

**Closed by cscheid** 2023-01-26 19:23 UTC
Labels: bug

**Comment by cscheid** [comment] 2023-01-27 04:58
This should be fixed on `main`. I'll make new installers when I've confirmed everything is working as it should.

**Comment by ShanSabri** [comment] 2023-04-19 01:06
I'd like to use nested tabsets and was wondering if anyone has ideas as to why the end of my first tabset shows NULL? 
![image](https://user-images.githubusercontent.com/4357318/232939815-c3510819-4566-432f-9239-b394a2990dec.png)

Code: 

```
:::: panel-tabset
# ```{r, show_summary, results = "asis", eval = TRUE, echo = FALSE}  # <--- commenting out for readability
sapply(refs, function(r){
  singler_umap <- file.path("path/to/fig1.png")
  singler_sample_props <- file.path("path/to/fig2.png")
  cat(sprintf("\n## %s\n", r))
  cat(sprintf("::: panel-tabset
### UMAP
![](%s)

### Sample proportions
![](%s)
:::",
  singler_umap,
  singler_sample_props
  ))
  cat(":::\n\n")
})
# ``` # <--- commenting out for readability
::::

```

**Comment by ShanSabri** [comment] 2023-04-19 01:35
Ignore -- the `NULL` was produced from the output of `sapply`. Setting an output variable to catch the `NULL` removes it.

**Comment by mr4909** [comment] 2023-07-17 22:16
Is there a way to style the two different tabsets differently?

**Comment by mcanouil** [comment] 2023-07-17 22:21
See:

- https://github.com/quarto-dev/quarto-cli/discussions/5991

PS: don't comment on closed issues unless it is about the issue itself.
