### ISSUE TITLE
LaTeX equation line break operator stopped working for book project

### ISSUE THREAD

**Issue by ercbk** [quarto-dev/quarto-cli#8121] opened 2024-01-04 14:08 UTC
### Bug description

After updating to Quarto 1.3.340, the latex equation line break operator, `\\`, stopped working in "display math" blocks for my book project. Inside the RStudio visual editor, the line break operator still works as intended, but after rendering the document, the equations are inline instead of multiline. 

### Steps to reproduce

````
$$
B y_t = y_{t-1} \\
B^2 y_t = y_{t-2}
$$
````

### Expected behavior

$$
\begin{aligned}
B y_t = y_{t-1} \\
B^2 y_t = y_{t-2}
\end{aligned}
$$

### Actual behavior

$$
B y_t = y_{t-1} \\
B^2 y_t = y_{t-2}
$$

### Your environment

-  IDE: RStudio 2023.12.0 Build 369
-  OS: Windows 10 Pro, Version 22H2

### Quarto check output

``` bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.340
      Path: C:\Users\tbats\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.11
      Path: C:/Users/tbats/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/tbats/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment] 2024-01-04 14:56
Can you try updating to the 1.4 prereleases? https://github.com/quarto-dev/quarto-cli/releases

**Comment by mcanouil** [comment] 2024-01-04 15:06
In case you reproduce using 1.4, please share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.
For instance, books can be from LaTeX or HTML, you did not specified in which your issue occurred.
Because, and if I am not mistaken, the equation mechanism is independent of book project, thus a simple document should display the same issue.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

**Comment by ercbk** [comment] 2024-01-04 20:12
Yes, the behavior is still present in 1.4, and I'm rendering a HTML document. The book is in a [repo](https://github.com/ercbk/Data-Science-Notebook/tree/main), and the example that I used is [here](https://github.com/ercbk/Data-Science-Notebook/blob/08dc2f763afc8f39d48afba3ba55312cf8ad91fa/qmd/forecasting-statistical.qmd#L87). 

````qmd 
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

$$
B y_t = y_{t-1} \\
B^2 y_t = y_{t-2}
$$ 
````

**Comment by cscheid** [comment] 2024-01-04 20:16
By inspecting the source of your own "expected behavior" vs "observed behavior", you had to add `\begin{aligned}` in order for the line breaks to appear in the HTML rendering (and they don't without them, on GitHub as well). I believe this comes from a MathJax update, so it's "working as intended", as in "we're using MathJax". Is there a reason you can't use `\begin{aligned}`?

**Comment by ercbk** [comment] 2024-01-04 20:19
Yeah, I can use that, but it's kind of a hack. I think the {aligned} purpose is to align multiple equations. It also means that the places I haven't used {aligned} in the book will be effected if I ever edit and re-render them.

**Comment by cderv** [comment] 2024-01-04 22:09
It seems you are targeting HTML output right ? 

The linebreak issue with Mathajx is a known MathJax 3 limitation
* https://github.com/mathjax/MathJax/issues/2312

It was discussed previously in this repo 
* https://github.com/quarto-dev/quarto-cli/discussions/4916
and also on the web
* https://stackoverflow.com/questions/62583406/why-doesnt-display-a-newline-in-mathjax

I am surprised this was working for you with a previous quarto version unless you where somehow using Mathjax 2. 

Regarding the use of `//` in equation environment, I don't even think this works in LaTeX itself. You would have to use **amsmath** package for example, and special environment like `split` or `align`. Or `aligned` also as adviced. 

Probably this will be fixed in HTML with Mathjax v4

In the meantime, you could also switch to KaTeX for math rendering in HTML as I think it supports `//` (but you may lack other things maybe 🤔 )

So considering all this, I am curious how this worked on your side with Mathjax. 

Do you still have a page in your book rendered with previous Quarto version ? 
Or know when your website did have a working version so that we could look at the produced HTLM at the time in your `gh-pages` branch ?

**Comment by ercbk** [comment] 2024-01-04 22:50
Geez. I'm feeling a little gaslit 😅. I can't find me using it like I'm describing anywhere! Every place where I have multiline equation blocks, I'm always aligning them anyways. I know I've wanted to do it without aligning at least twice in the last week or so, and I just ended up splitting them into separate blocks. I guess maybe I'm remembering doing it that way back when I was creating equation image files with quicklatex or something. Evidently it's not that big of a deal (for me at least). Sorry for the fuss 😬.

**Comment by cderv** [comment] 2024-01-04 22:55
No worries ! Thanks for reaching out ! 

I'll close this if you don't mind - this is really a Mathjax 3 limitation for now and the behavior will depend on its evolution, and then Quarto / Pandoc support.

**Closed by cderv** 2024-01-04 22:55 UTC
Labels: third-party
