### ISSUE TITLE
label fig-xxx for knitr::include_url

### ISSUE THREAD

**Issue by xtimbeau** [quarto-dev/quarto-cli#5718] opened 2023-05-27 15:53 UTC
### Bug description

fig-xxx for an included_url (such as an interactive graph or a leaflet map) is not accepted as a figure by quarto (bookdown seems to work that way [https://bookdown.org/yihui/rmarkdown-cookbook/include-url.html](https://bookdown.org/yihui/rmarkdown-cookbook/include-url.html)). 

More generally it would be nice to allow user to include any content (if aware) as a figure or a table 
(a table can sometime be rendered as an image ?).

here is a reprex:
````qmd

---
title: "fig"
format: html
editor: visual
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

here is a map [@fig-map], working as expected, but html saved is not a figure [@fig-maphtml]

```{r}
#| label: fig-map
#| fig-cap: a leaflet interactive map
leaflet::leaflet() |> leaflet::addTiles()
```

```{r}
#| label: fig-maphtml
#| fig-cap: a leaflet interactive map
leaflet::leaflet() |> leaflet::addTiles() |> htmlwidgets::saveWidget("map.html")
knitr::include_url("map.html")
```
the end.
````

**Comment by mcanouil** [comment] 2023-05-27 17:02
Thanks for the report!

Could you format your example to be reproducible? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by xtimbeau** [comment] 2023-05-27 17:44
I think I got it right !

**Comment by mcanouil** [comment] 2023-05-28 09:49
What you want to achieve, _i.e._, forcing content to be seen by Quarto as a figure is not currently possible, but Quarto team is working on cross-reference for 1.4 which should allow this in the future.

**Comment by xtimbeau** [comment] 2023-05-29 13:47
great!

Le lun. 29 mai 2023 à 15:46, Mickaël Canouil ***@***.***> a
écrit :

**Comment by cderv** [comment] 2023-05-30 14:08
> More generally it would be nice to allow user to include any content (if aware) as a figure or a table
(a table can sometime be rendered as an image ?).

@mcanouil I think [Figure Divs](https://quarto.org/docs/authoring/figures.html#figure-divs) is the answer to this, and not just a workaround. Do you think there should be more ? 

Otherwise, I think we can close

**Comment by mcanouil** [comment] 2023-05-30 15:14
I think that's a general solution yes.

I said "workaround" because of a comment by @cscheid about cross-reference resdesign/refactoring which should allow to force anything to be read as anything for cross-reference, _i.e._, in this case, "html" as a "figure".
Partly, why I triaged this to him.
I let him decide 😇

**Comment by cscheid** [comment] 2023-05-30 17:29
> I said "workaround" because of a comment by @cscheid about cross-reference resdesign/refactoring which should allow to force anything to be read as anything for cross-reference, i.e., in this case, "html" as a "figure".

Thanks, and I agree. There's too many open issues that are related to this (see the fifth bullet item in https://github.com/quarto-dev/quarto-cli/issues/4944); I'm going to leave this one open, and check back when those features are ready to see if they solve this issue.

**Comment by cscheid** [comment] 2023-12-14 18:15
Ok, this style of crossreferenceable element is now documented and advertised, so we're good with closing this.

**Closed by cscheid** 2023-12-14 18:15 UTC
Labels: crossref
