### ISSUE TITLE
Jupyter kernel needed for publish github action when freeze: auto is set

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#4252] opened 2023-02-07 08:52 UTC
Test I did based on discussion below: 

* Clone project https://github.com/dmbates/plotdemo which has a `_freeze` folder and use Julia. 
* Delete the `docs` folder which is the output to recreate and I don't have Julia setup on my environment. 
* Rendering locally with `quarto preview` -> Julia is not needed. The freezing works - HTML file is created and I can preview result
* Trying to publish using `quarto publish quarto-pub` => **Rendering using Julia is happening** - It errors on my side as not setup. 

So we have an issue here I believe in our publish workflow. 

Side note : Trying to publish with `--no-render` fails also 
````
quarto publish quarto-pub --no-render
? Publish with account christophe.dervieux@gmail.com (Y/n) » Yes
? Publish with name 'plots-demo-5bc8'? (Y/n) » Yes

[>] Creating quarto-pub document

ERROR: Output file plotdemo.html does not exist.

Error: Output file plotdemo.html does not exist.
    at renderForPublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/publish.ts:235:19)
    at renderForPublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/common/publish.ts:248:28)
    at handlePublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/common/publish.ts:117:30)
    at async publishDocument (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/publish.ts:260:36)
    at async publish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:282:9)
    at async doPublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:195:7)
    at async publishAction (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:258:7)
    at async Command.fn (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:153:11)
    at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:111:3)
````

Probably related to how the document are supposed to be rendered and why `freeze` does not work. Or another issue

cc @cscheid 

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/4237

<div type='discussions-op-text'>

<sup>Originally posted by **dmbates** February  5, 2023</sup>
I have been looking at the way that I currently have a Quarto book with Julia code chunks being rendered to gh-pages.  (Book is at https://JuliaMixedModels.github.io/EmbraceUncertainty).

If I understand the documents at https://quarto.org/docs/publishing/github-pages.html#freezing-computations correctly then setting `freeze: auto` in `_quarto.yml` and rendering the book will save the output of the code chunks in the `_freeze` directory (which I do have committed in the repository).

I was hoping that I could then render the book in a github action without the need to configure Jupyter and a Julia kernel.    However, the render and publish step fails because it can't access the kernel. (I am actually experimenting on another, private repository but can pull back the curtains if my description is too vague.)

Should this be happening or have I misconfigured the github action?  In other words, is there a way I can configure the github action so that Quarto recognizes that it will use the results in the _freeze directory and can ignore the jupyter specification in the files?

An alternative approach, although perhaps less efficient, would be to get a recipe for configuring a Julia kernel in Jupyter for the github action.</div>

**Comment by dmbates** [comment] 2023-02-07 14:39
@cderv Thank you for creating this issue.  Please let me know if there is anything I can do to help.

**Comment by cscheid** [comment] 2023-02-28 22:31
I believe this is a duplicate of #3628. We definitely want to fix it! But I'll track it over there.

**Closed** 2024-03-20 23:19 UTC
Labels: duplicate
