### ISSUE TITLE
"Copy to Clipboard" button moves with the slidebar in html pages

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#307] opened 2022-02-04 11:18 UTC
Thank you for continuing to develop great products.

I don't know if this is a problem with quarto, but I noticed that the buttons are misaligned in the html file created from the following qmd file.

````qmd
---
title: test
format:
  html:
    self-contained: true
jupyter: python3
---

## test

```{python}
print("loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong")
```
````

![image](https://user-images.githubusercontent.com/50911393/152519634-b808f805-967a-4bd6-86c6-2eec0b76ef15.png)

**Comment by jjallaire** [comment] 2022-02-04 11:30
Yeah that is unfortunately expected behavior given the way we currently position the copy button. We've looked at a couple of alternative methods and hopefully we'll settle on one of them soon.

**Comment by mcanouil** [comment] 2023-07-17 23:29
Using the latest development version it does seem to be fixed.

<img width="953" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/97c2baaf-2c4c-48e9-ad14-0ed8b6f913c0">

**Comment by cderv** [comment] 2023-07-18 12:11
@mcanouil I can't reproduce this with dev version

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/57aaa08a-c514-4a3e-9545-bec383997fde)

I am on Windows and using Chrome

**Comment by mcanouil** [comment] 2023-07-18 12:14
On Mac using Brave (Chrome):

https://github.com/quarto-dev/quarto-cli/assets/8896044/ec6a2083-62ae-4611-abff-7a5c1e5abbe3

**Comment by cderv** [comment] 2023-07-18 12:16
Awesome ! thanks. I can see it now too. Sorry. I wanted to be sure it was not a MacOS  / Safari issue. We had a few of those already !

**Comment by mcanouil** [comment] 2023-08-07 13:25
Closing this in favour of:

- #5538

**Closed by mcanouil** 2023-08-07 13:25 UTC
Labels: bug
