### ISSUE TITLE
Unable to generate PDF file from a notebook with Python NameError.

### ISSUE THREAD

**Issue by LaoHuangY** [quarto-dev/quarto-cli#10708] opened 2024-09-04 08:04 UTC
### Bug description

Unable to generate PDF file from a notebook with Python NameError.

This is the screen shot of my jupyter notebook file showError.ipynb. I want to show what makes an NameError in Python. 
![image](https://github.com/user-attachments/assets/24f8209b-db6b-4667-9295-32aacfcd7fb7)

I used `quarto render showError.ipynb --to pdf` , but failed. The error message shows
ERROR:
compilation failed- error
Text line contains an invalid character.
l.210 ^^[
         [1;31m-------------------------------------------------------------...

see showError.log for more information.

Then I check the .tex file generated, and found some invisible characters <0x1b> in the lines from l.210 . Maybe it is the reason why XeTeX fails.

Please check the screenshot below.
![image](https://github.com/user-attachments/assets/a2d403eb-f20c-441d-9b89-5925503de110)

### Steps to reproduce

Open Jupyterlab, Create a new Python notebook.

In a code cell, write code `print(a)` , and press Shift+Enter to execute this cell. An NameError message will show.

Save this notebook as showError.ipynb.

In the Anaconda Prompt, type `quarto render showError.ipynb --to pdf` , then it will report Error.

### Expected behavior

Generate a PDF file successfully.

### Actual behavior

pandoc
  to: latex
  output-file: showError.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf

metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true

Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages
ERROR:
compilation failed- error
Text line contains an invalid character.
l.210 ^^[
         [1;31m-------------------------------------------------------------...

see showError.log for more information.

### Your environment

- IDE: JupyterLab
- OS: Windows 10
- Quarto -V: 1.5.57

### Quarto check output

Quarto 1.5.57
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.57
      Path: C:\Users\hH\AppData\Local\Programs\Quarto\bin
      CodePage: 936

[>] Checking tools....................OK
      TinyTeX: v2024.09
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\hH\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.3 (Conda)
      Path: D:/ProgramFiles/miniconda3/python.exe
      Jupyter: 5.7.2
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by mcanouil** [comment] 2024-09-04 10:31
Could you share a **small self-contained "working" (reproducible)** example to work with, _i.e._, a complete Quarto document or a Git repository? The goal is to make it as easy as possible for us to recreate your problem so that we can fix it: please help us help you! Thanks.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by cderv** [comment] 2024-09-04 14:14
duplicate of 
- https://github.com/quarto-dev/quarto-cli/issues/10347

**Closed** 2024-09-04 14:15 UTC
Labels: bug, duplicate, needs-repro
