### ISSUE TITLE
Newlines are removed from listing fields

### ISSUE THREAD

**Issue by gadenbuie** [quarto-dev/quarto-cli#7761] opened 2023-12-01 19:16 UTC
### Bug description

I've put together an example repo with a website that demonstrates the issue: https://github.com/gadenbuie/quarto-reprex-listing-chomp.

This site uses a custom listing that uses this template:

````markdown
<% for (const item of items) { %>
<h3><%= item.title %></h3>

```<%= item.codeLanguage %>
<%= item.code %>
```
<% } %>
````

and it has posts with YAML like this:

````markdown
---
title: "R code"

codeLanguage: r
code: |
  # Is there a line below this?

  fizz_buzz <- function(fbnums = 1:50) {
    # ...
  }

  # Is there a line above this?
---
````

When rendered, the newlines in `item.code` are lost.

### Steps to reproduce

See https://github.com/gadenbuie/quarto-reprex-listing-chomp

### Expected behavior

The rendered page should have code that looks like this:

```r
# Is there a line below this?

fizz_buzz <- function(fbnums = 1:50) {
  output <- dplyr::case_when(
    fbnums %% 15 == 0 ~ "FizzBuzz",
    fbnums %% 3 == 0 ~ "Fizz",
    fbnums %% 5 == 0 ~ "Buzz",
    TRUE ~ as.character(fbnums)
  )
  print(output)
}

# Is there a line above this?
```

### Actual behavior

http://pkg.garrickadenbuie.com/quarto-reprex-listing-chomp/

![image](https://github.com/quarto-dev/quarto-cli/assets/5420529/02245f60-0619-45ef-bcb2-773b2c3d3920)

### Your environment

- OS: MacOS 14.1
- IDE: Terminal

### Quarto check output

```
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Users/garrick/.local/share/qvm/versions/v1.3.450/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /Users/garrick/.pyenv/versions/3.11.4/bin/python
      Jupyter: 5.5.0
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Users/garrick/.local/share/qvm/versions/v1.3.450/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Users/garrick/.local/share/qvm/versions/v1.3.450/share/jupyter/notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK
```

**Comment by dragonstyle** [comment] 2023-12-04 13:02
Thanks for sharing such a great repro repo. I just checked this against the latest version of the pre-release and can't reproduce the issue (so it is likely that we fixed this somewhere in the release, though I don't remember explicitly dealing with it).

I'm going to mark this closed since it appears to be resolved in 1.4, but if you see this in the pre-release or think there is something else we should take a closer look at, please feel free to re-open this issue!

**Closed by dragonstyle** 2023-12-04 13:02 UTC
Labels: bug, triaged-to, listings
