### ISSUE TITLE
Figure layouts broken in LaTeX/PDF

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto-cli#7017] opened 2023-09-26 16:29 UTC
### Bug description

Custom figure layouts cause this error when rendering to PDF:

```
ERROR: 
compilation failed- error
LaTeX Error: Not in outer par mode.
```

### Steps to reproduce

````qmd
---
title: "Layout test"
format: 
  pdf:
    keep-tex: true
---

```{r}
#| label: fig-charts
#| fig-cap: "Charts"
#| layout: "[1, 1]"

plot(cars)
plot(pressure)
```
````

The .tex file has this:

```tex
\begin{figure}
\begin{minipage}[t]{0.50\linewidth}
\begin{figure}
\centering{
\includegraphics{testing_files/figure-pdf/fig-charts-1.pdf}
}
\caption{\label{fig-charts-1}Charts}
\end{figure}%
\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}
\begin{figure}
\centering{
\includegraphics{testing_files/figure-pdf/fig-charts-2.pdf}
}
\caption{\label{fig-charts-2}Charts}
\end{figure}%
\end{minipage}%
\end{figure}%
```

Based on a quick naive search, [this StackExchange post](https://tex.stackexchange.com/questions/124346/latex-error-not-in-outer-par-mode) says that adding a `[H]` to the inside-the-`minipage`-figure environments will fix it, and it does. If I edit the .tex file like so and compile it outside of Quarto, it works:

```tex
\begin{figure}
\begin{minipage}[t]{0.50\linewidth}
\begin{figure}[H]
\centering{
\includegraphics{testing_files/figure-pdf/fig-charts-1.pdf}
}
\caption{\label{fig-charts-1}Charts}
\end{figure}%
\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}
\begin{figure}[H]
\centering{
\includegraphics{testing_files/figure-pdf/fig-charts-2.pdf}
}
\caption{\label{fig-charts-2}Charts}
\end{figure}%
\end{minipage}%
\end{figure}%
```

<img width="873" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/6a958b09-aba2-4b81-bac6-58eb0ba8dbf6">

But I don't know if that's the true solution or how it worked in previous versions. Quarto 1.3 worked fine—some sort of regression happened at some point 🤷‍♂️

### Expected behavior

Side-by-side plots should appear

### Actual behavior

Nothing :)

### Your environment

- IDE: RStudio 2023.06.2+561
- OS: macOS Ventura 13.5.2

### Quarto check output

```
Quarto 1.4.382
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.382
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/andrew/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment] 2023-09-26 17:01
> LaTeX Error: Not in outer par mode.

I'm just going to leave [this here](https://github.com/cscheid/2023-posit-conf-talk/blob/main/talk.qmd#L3) 😭

**Comment by andrewheiss** [comment] 2023-09-26 17:03
lol I've had like 10 typst-related tabs open for a week now, hoping to get around to figuring it out. Guess it's time 😂

**Comment by andrewheiss** [comment] 2023-09-26 17:07
ha just found a new issue when using typst, though, using the same reprex:

````qmd
---
title: "Layout test"
format: typst
---

```{r}
#| label: fig-charts
#| fig-cap: "Charts"
#| layout: "[1, 1]"

plot(cars)
plot(pressure)
```
````

```
FATAL (/Applications/quarto/share/filters/main.lua:17675) An error occurred:
PanelLayout renderer requires a float in typst output
This is a quarto bug. Please consider filing a bug report at https://github.com/quarto-dev/quarto-cli/issues
Error running filter /Applications/quarto/share/filters/main.lua:
/Applications/quarto/share/filters/main.lua:2009: attempt to call a nil value (global 'crash_with_stack_trace')
stack traceback:
	/Applications/quarto/share/filters/main.lua:1590: in function 'fail'
	/Applications/quarto/share/filters/main.lua:1582: in function 'fail_and_ask_for_bug_report'
	/Applications/quarto/share/filters/main.lua:17675: in field 'render'
	/Applications/quarto/share/filters/main.lua:670: in local 'filter_fn'
	/Applications/quarto/share/filters/main.lua:226: in function </Applications/quarto/share/filters/main.lua:216>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	/Applications/quarto/share/filters/main.lua:148: in function </Applications/quarto/share/filters/main.lua:138>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:725: in local 'callback'
	/Applications/quarto/share/filters/main.lua:738: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:773: in function </Applications/quarto/share/filters/main.lua:770>
stack traceback:
	/Applications/quarto/share/filters/main.lua:148: in function </Applications/quarto/share/filters/main.lua:138>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:725: in local 'callback'
	/Applications/quarto/share/filters/main.lua:738: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:773: in function </Applications/quarto/share/filters/main.lua:770>
```

**Comment by cscheid** [comment] 2023-09-26 17:09
That one is a duplicate of https://github.com/quarto-dev/quarto-cli/issues/6965 :)

**Comment by cscheid** [comment] 2023-09-26 20:44
Turns out this is broken in HTML as well:

````
---
title: "Layout test"
format: html
keep-md: true
---

```{r}
#| label: fig-charts
#| fig-cap: "Charts"
#| layout: "[1, 1]"

plot(cars)
plot(pressure)
```

See @fig-charts.
````

Busted output and missing crossrefs:

<img width="799" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/5e6eae15-6926-489a-9d3f-3b0d58f958e3">
**

**Comment by cscheid** [comment] 2023-09-26 20:49
Hmmm. @cderv, this is the keep-md output for that HTML example. It doesn't look right to me (there's no `fig-charts` reference and the caption is repeated across the subfigures). Could this be a knitr bug or a bug in quarto's rmd.R?

## .qmd

````
---
title: "Layout test"
format: html
keep-md: true
---

```{r}
#| label: fig-charts
#| fig-cap: "Charts"
#| layout: "[1, 1]"

plot(cars)
plot(pressure)
```

See @fig-charts.

````

## .html.md

````
---
title: "Layout test"
format: html
keep-md: true
---


::: {.cell layout="[1, 1]"}

```{.r .cell-code}
plot(cars)
plot(pressure)
```

::: {.cell-output-display}
![Charts](7017_files/figure-html/fig-charts-1.png){#fig-charts-1 width=672}
:::

::: {.cell-output-display}
![Charts](7017_files/figure-html/fig-charts-2.png){#fig-charts-2 width=672}
:::
:::


See @fig-charts.

````

**Comment by ptram** [comment] 2023-09-29 16:21
> but it seems there should always be a label right ?

A quick user intrusion, here: academic and scientific styles usually require figures to have a caption, made of a `Figure [#]` premise and a `descriptive caption`. Something like:

`Figure 2: My beautiful plot`

Other styles, like the one required for end-user manuals, don't require it. The figure can only include images, but have no captions (being an extensive description the core of the preceding or following text).

In my view, an empty caption (`![](my-image.png)`) should result in a figure with no caption. In Typst, it could be something like (if I'm using the correct syntax):

```
#figure(
  image("my-image.png", width: 80%),
  caption: none,
) <my-image>

```

**Comment by cscheid** [comment] 2023-09-29 16:35
@ptram that is working on `typst` now in `main`:

<img width="794" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/44910d10-76e8-41cc-9b54-fbde5f91c450">

````
---
title: test
format: typst
---

An elephant:

![](./elephant.jpg)

Other stuff.
````

**Comment by cscheid** [comment] 2023-09-29 20:24
In the meantime, the following workaround syntax works:

````
---
title: "Layout test"
format: 
  pdf:
    keep-tex: true
---

::: {#fig-charts layout="[3, 1]"}

```{r}
#| echo: false
plot(cars)
```

```{r}
#| echo: false
plot(pressure)
```

Charts

:::
````

Producing this:

<img width="713" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/67e2b644-cf25-4ff4-87de-aacc4f19920a">

**Comment by cscheid** [comment] 2024-05-08 16:30
We've had other reports of users who now expect the empty captions, so I think this bug has officially become a feature. :tada: 🫠

**Closed by cscheid** 2024-05-08 16:30 UTC
Labels: bug, crossref, figures
