### ISSUE TITLE
ERROR: Invalid jupyter YAML metadata found in file (must be string or object)

### ISSUE THREAD

**Issue by sje30** [quarto-dev/quarto-cli#2020] opened 2022-08-20 22:28 UTC
Hi,
just getting started with quarto (thanks), and not sure I've got the jupyter side of things sorted out.  I think I've installed the irkernel for R okay. but am struggling to convert a .qmd file to .ipynb. 

Running 'quarto check' in the folder I see the error (at bottom):

```
stephen@blur estimateq % quarto check          

[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /opt/homebrew/opt/python@3.10/bin/python3.10
      Jupyter: 4.11.1
      Kernels: ir

[✓] Checking Jupyter engine render....OK

ERROR: Invalid jupyter YAML metadata found in file (must be string or object)
```

where might I find the invalid YAML?  If the check script knows the location (file/line number) of the error, is there any chance it could report that?

As far as I can tell, the only yaml file I've got in the folder is the following

```
---
title: "Example quarto document: estimating PI"
author: "Stephen J Eglen"
date: "2022-08-20"
bibliography: refs.bib
format: 
  html:
    code-fold: false
---
```

(what I'd like to do is specify the ir kernel).

(As a minor aside, when I saw the rstudioconf talk that quarto was 'batteries included', I had falsely assumed that it would include all the python/jupyter machinery.  but I don't think it did, so I've done the following:

```
python3 -m pip install jupyter
```

and from the R side, installed the irkernel package and installed the kernel

```
install.packages('IRkernel')  # Don’t forget step 2/3!
IRkernel::installspec()
```
)

**Comment by jjallaire** [comment] 2022-08-20 23:31
Hi @sje30, great to see you here!

`quarto check` is actually trying to render a simple (internally constructed) jupyter document using the `python3` kernel but this system happens to have just the R kernel. The error you are seeing is a bug which should be fixed in our v1.1 pre-release version: https://quarto.org/docs/download/prerelease.html

Yeah we can't easily include the Python/Jupyter bits because this would create _yet another_ version of Python on the users system that they need to sort out interacting with / installing packages into. This is something that we unfortunately need to leave to the users.

Not sure if you have a particular reason to use the IRKernel but I will say that using Knitr w/ R will be much more feature rich (and the requires no prereqs save for R and the rmarkdown package).

**Comment by jjallaire** [comment] 2022-08-21 01:26
@sje30 I've confirmed locally that this error no longer happens in v1.1 so I'm closing the issue.

**Closed by jjallaire** 2022-08-21 01:26 UTC

**Comment by sje30** [comment] 2022-08-21 07:13
Thanks @jjallaire for your quick reply.  I had to come try quarto given all the high praise about it.  Am now working on updating my slides for next year.

I was naively hoping that quarto would solve the version hell that is python... but there's no escaping it, so I had better get on and learn it.  Do you have a recommendation for how to setup python and packages?  (Is 'mamba' the tool of choice still?  I saw Jeremy Howard recommended it.)

The reason for the IRkernel was simply that I wanted to test the notebook interface; I really like the idea of .qmd being the source, rather than relying on .ipynb as the source.  In this way I can stay in Emacs and use quarto tools to generate notebooks etc.

**Comment by jjallaire** [comment] 2022-08-21 13:02
I was just talking with Jeremy the other day and he was saying that he now recommends that students just use a single global Python environment where all requires packages are installed (e.g. `base` in Conda or just the global library w/ `pip`). I have to say that after years of wrestling with Python environments that I think we shouldn't be recommending that beginners use virtual environments as they result in huge amounts of confusion and seemingly "broken" configuration.

I believe you could still just as well use Knitr and have a notebook be generated (I don't think it would support htmlwidgets but most stuff would still work). Note we also have a polymode that can integrate w/ ESS: https://github.com/quarto-dev/quarto-emacs

**Comment by sje30** [comment] 2022-08-22 08:07
Thanks... after looking around, I've gone with pip for now, and pyenv in case I need to switch python versions.

and yes, am enjoying using your quarto-emacs mode, thanks very much!
