### ISSUE TITLE
Persistent error "Authorization for Confluence is no longer valid"

### ISSUE THREAD

**Issue by jhunter-aof** [quarto-dev/quarto-cli#5548] opened 2023-05-15 16:20 UTC
### Bug description

When following [the instructions for publishing a Quarto document ](https://quarto.org/docs/publishing/confluence.html)on my company's Atlassian Confluence cloud I was given the following response after providing the 'Space or Parent Page URL':

`The authorization saved for Confluence is no longer valid. Please be sure you are logged into the correct Confluence account in your default web browser, then press Enter to re-authorize.`

I have ensured that I am logged in to the proper Confluence account on my default browser, but the error persists. Since I am able to get to the 'Space or Parent Page' prompt, I assume that my Confluence account email and API tokens are being accepted in this process.

I am running RStudio 2023.03.0 Build 386 on Windows 10 Pro. Below is the output from `quarto check`.

```
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.319
      Path: C:\Users\jhunter\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.7 (Conda)
      Path: C:/Users/jhunter/Anaconda3/python.exe
      Jupyter: 4.8.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/Users/jhunter/AppData/Local/Programs/R/R-4.2.1
      LibPaths:
        - C:/Users/jhunter/AppData/Local/Programs/R/R-4.2.1/library
      knitr: 1.41
      rmarkdown: 2.17

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2023-05-15 16:25
Did you try to use your token to access your Confluence space outside of Quarto, following <https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/>?

**Comment by jhunter-aof** [comment] 2023-05-15 16:59
Yes, I ran the example from https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/ with my API token and got a verbose response.

**Comment by allenmanning** [comment] 2023-05-16 08:01
@jhunter-aof Thanks for posting.

What you are reporting seems similar to a recent bug here https://github.com/quarto-dev/quarto-cli/issues/5299.

Can you please try and reproduce by publishing a single doc using the following debug command: `quarto publish --log-level debug`. Can you then save the log to a file (sanitize it as needed) and attach it to this discussion using the below template.

This will help us diagnose the issue.

## Description: 

## Steps to Reproduce:

### Expected Result:

### Actual Result:

**Comment by jhunter-aof** [comment] 2023-05-16 15:06
You're welcome for posting. Thanks for the help @allenmanning !

Yes, #5299 seems to be exactly my problem. I've attached my log output in this file, but I'll also put it in the Actual Result: [quarto issue 5548 log output.txt](https://github.com/quarto-dev/quarto-cli/files/11488788/quarto.issue.5548.log.output.txt)

## Description:

Attempting to publish Quarto to company Confluence ends up creating a test document in root Confluence space and places the RStudio user in an endless loop of account reauthorization.

## Steps to Reproduce:

(I have not reproduced this outside of my relevant example, so I'm copying from #5299 here)
- Configure a Confluence space where the logged in publisher has no delete rights (only archive for example)
- Publish a quarto document to this space

### Expected Result:

Document published

### Actual Result:

Document is not published, and instead a blank test document is published to the parent space with a name like `quarto-permission-test-ff3807b9-22b4-4681-bbce-8472cf47b438`.

Additionally, RStudio terminal gives this error:

`
The authorization saved for Confluence is no longer valid.
  Please be sure you are logged into the correct Confluence account in your
  default web browser, then press Enter to re-authorize.
`

The log output is attached here: [quarto issue 5548 log output.txt](https://github.com/quarto-dev/quarto-cli/files/11488788/quarto.issue.5548.log.output.txt)

**Comment by allenmanning** [comment] 2023-05-22 07:23
@jhunter-aof Many thanks for clarifying.  I think that this issue is likely a duplicate of https://github.com/quarto-dev/quarto-cli/issues/5299.  Can you please download the pre-release and see if this fixes your issue.  Please let me know.

![image](https://github.com/quarto-dev/quarto-cli/assets/674792/608f8783-99f2-493f-8d9c-213d39c16daa)

**Comment by ledemocrate** [comment] 2023-07-27 14:45
I had the same problem.
 The pre-release fixes the issue (in my case).
Thanks a lot 👍

**Closed** 2023-07-27 14:49 UTC
Labels: bug, publishing-confluence
