### ISSUE TITLE
Table `#| label` is visible in `.panel-tabset`

### ISSUE THREAD

**Issue by sda030** [quarto-dev/quarto-cli#6804] opened 2023-09-12 11:21 UTC
### Bug description

This bug occurs for both the `df-print: kable`, default, paged option, and using `gt::gt(mtcars[1:4, ])` approach. Either way, the label is displayed in the rendered document. 

### Steps to reproduce

````qmd
---
format: html
execute:
  echo: false
title: Test
---

::: panel-tabset
##### A
```{r, 'tbl-A'}
#| label: 'tbl-A'
#| tbl-cap: 'CaptionA'
gt::gt(mtcars[1:4,])
```

##### B
```{r, 'tbl-B'}
#| label: 'tbl-B'
#| tbl-cap: 'CaptionB'
gt::gt(mtcars[1:4,])
```
:::
````

### Expected behavior

CaptionA
mpg	cyl	disp	hp	drat	wt	qsec	vs	am	gear	carb
21.0	6	160	110	3.90	2.620	16.46	0	1	4	4
21.0	6	160	110	3.90	2.875	17.02	0	1	4	4
22.8	4	108	93	3.85	2.320	18.61	1	1	4	1
21.4	6	258	110	3.08	3.215	19.44	1	0	3	1

### Actual behavior

CaptionA {#tbl-A}
mpg	cyl	disp	hp	drat	wt	qsec	vs	am	gear	carb
21.0	6	160	110	3.90	2.620	16.46	0	1	4	4
21.0	6	160	110	3.90	2.875	17.02	0	1	4	4
22.8	4	108	93	3.85	2.320	18.61	1	1	4	1
21.4	6	258	110	3.08	3.215	19.44	1	0	3	1

### Your environment

- IDE: RStudio 2023.06.1 Build 524
- Windows 11 (all updates)

### Quarto check output

```bash
Quarto 1.4.358
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.7: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.358
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Users/py128/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/py128/AppData/Local/R/win-library
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.43
      rmarkdown: 2.24

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2023-09-12 11:33
Thanks for the report which I can reproduce and seems to be a conflict between the cross-reference system and the tabset system.

Please note that you are setting the label twice, choose the YAML syntax (highly recommended in Quarto) or the inline R syntax, not both, nor a mix of both.

<table>
<tr><th>YAML</th><th>Inline</th></tr>
<tr>
<td>

````qmd
```{r}
#| label: 'tbl-A'
<code>
```
````

</td>
<td>

````qmd
```{r, 'tbl-A'}
<code>
```
````

</td>
</tr>
</table>

**Comment by cscheid** [comment] 2023-09-12 14:53
````
```{r, 'tbl-A'}
#| label: 'tbl-A'
#| tbl-cap: 'CaptionA'
gt::gt(mtcars[1:4,])
```
````

Like @mcanouil said, this isn't syntax we intend to support. In quarto you should really prefer the YAML `#| label: tbl-A` syntax unless there's no way around using knitr chunk options. I'll take a look at this later today, but this isn't exactly a bug.

**Comment by cscheid** [comment] 2023-09-12 15:10
We'll fix this once #6620 is merged.

**Comment by sda030** [comment] 2023-09-12 18:15
Ah, yes, I had tried various options for the reprex and forgot to remove the `{r, 'notation'}`. 
Soo looking forward to the Crossref Overhaul by the way, will be a one-man party in front of my office desk.

**Comment by cscheid** [comment] 2023-11-30 20:22
This is fixed on `main`.

**Closed by cscheid** 2023-11-30 20:22 UTC
Labels: bug, crossref, triaged-to, tabsets
