### ISSUE TITLE
missing reference for gt table in word document

### ISSUE THREAD

**Issue by rmflight** [quarto-dev/quarto-cli#3600] opened 2022-12-08 16:22 UTC
### Bug description

````
---
title: "gt missing reference"
format: docx
---


```{r}
#| label: load_data
data(cars)

library(gt)
```

Now lets try a table in our word document. This should be @tbl-cars.

```{r}
#| label: tbl-cars
#| tbl-cap: Something about cars.
cars |>
  dplyr::slice_head(n = 5) |>
  gt()
```
````
[gt_missing_reference.docx](https://github.com/quarto-dev/quarto-cli/files/10187371/gt_missing_reference.docx)

Rendering the above document (RStudio render button) results in the table reference looking like `?@tbl-cars`, and there is no caption.

If I force HTML output (`quarto::quarto_render(..., output_format = "html")`), I get the expected output of `Table 1`, as well as the caption.

Software details:

* R 4.2.1
* RStudio 2022.12.0-preview+348
* quarto 1.3.47
* gt rstudio/gt@d638baa
* Linux, Pop! OS 22.04 (skinned version of Ubuntu 22.04)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by aminadibi** [comment] 2023-03-28 22:36
Same issue in Windows 11, R 4.2.3, quarto v1.3.294.

**Comment by cscheid** [comment] 2023-03-29 00:13
@aminadibi we're aware, thank you. We're going to fix this in 1.4.

**Comment by dakotakliam** [comment] 2023-10-21 00:59
Is there any kind of workaround for this issue in the meantime?

**Comment by cscheid** [comment] 2023-10-22 20:14
@dakotakliam This is working right now on 1.4 prereleases: go [here](https://quarto.org/docs/download/) and click on "Pre-release" to download an installer. With this version of quarto, I get the following output:

<img width="550" alt="3600" src="https://github.com/quarto-dev/quarto-cli/assets/285675/0cda3889-cf3f-4f36-89d4-e62e162c9645">

**Comment by mcanouil** [comment] 2023-11-26 21:37
What version of Quarto and gt are you using exactly?

**Comment by schwa021** [comment] 2023-11-27 13:54
> What version of Quarto and gt are you using exactly?

Quarto: 1.4.487
gt: 0.10.0
R: 4.2.2

**Comment by mcanouil** [comment] 2023-11-27 16:02
I can reproduce.
The document is malformed.

**Comment by schwa021** [comment] 2023-11-27 16:06
> I can reproduce. The document is malformed.

I'm not sure what this means... is there a problem with quarto, gt, or am I doing something wrong?

**Comment by rmflight** [comment] 2023-11-27 16:09
OK, I thought this is the same issue over in #7151 and #7321. Or am I wrong. It looks like the same thing, where the XML reference gets borked, but it is present, and the table is messed up according to Word.

**Comment by mcanouil** [comment] 2023-11-27 16:13
Indeed, thanks @rmflight (I was looking for them after checking the issue was from gt and possibly Quarto).

(re)Closing this.
@schwa021 See #7151

FYI, the following works properly.

````qmd
---
title: "gt missing reference"
format: docx
---

```{r}
#| label: load-data
data(cars)

library(gt)
```

Now lets try a table in our word document. This should be @tbl-cars.

```{r}
#| label: tbl-cars
#| tbl-cap: Something about cars.
cars |>
  dplyr::slice_head(n = 5) |>
  knitr::kable()
```
````

**Closed by mcanouil** 2023-11-27 16:13 UTC
Labels: bug, crossref, tables

**Comment by mcanouil** [comment] 2023-11-27 16:43
> I'm a user, not a developer

I don't how this matter here, but let's be explicit:

- The issue right here is about the reference not the table within a Word document.
- The issue you are having is about gt table itself as you (and anyone) cannot reproduce with for example `knitr::kable()`.
- The issue is the table from gt/quarto ends up somehow malformed in the rendered Word document.
- The issue your reported here was already reported elsewhere.

Leading to:
1. This issue here is actually properly resolved as the reference works
2. Your issue is actually somewhere else, thus see/follow https://github.com/quarto-dev/quarto-cli/issues/7151
