### ISSUE TITLE
Huge memory consumption by pandoc (21 GB) while having Quarto Preview of a Quarto book project (.qmd file) open in VS Code.

### ISSUE THREAD

**Issue by walustor** [quarto-dev/quarto-cli#9315] opened 2024-04-09 12:20 UTC
### Bug description

Huge memory consumption by pandoc (21 GB) while having Quarto Preview of a Quarto book project (.qmd file) open in VS Code.

Regulary, after working for a while in VS Code with a live preview of my Quarto document running my computer slows down and I notice the huge memory consumption of the Pandoc process (~20 GB). I then kill the process. Often, after half an hour or less the same problem is there again.

### Steps to reproduce

1. Open Quarto `.qmd` (just markdown and Latex formulas) file in VS Code.
2. Click "Preview" in VS code.
3. Work (change content and save occasionally)
4. Computer slows down and huge memory consumption by Pandoc

### Expected behavior

Low memory consumption / memory consumption stays at levels that do not effect computer performance noticably.

### Actual behavior

High memory consumption of Pandoc (~20 GB).

### Your environment

- IDE: VS Code
> Version: 1.87.2
> Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
> Date: 2024-03-08T15:14:59.643Z
> Electron: 27.3.2
> ElectronBuildId: 26836302
> Chromium: 118.0.5993.159
> Node.js: 18.17.1
> V8: 11.8.172.18-electron.0
> OS: Linux x64 6.8.0-76060800daily20240311-generic

- Quarto extension for VS Code: v1.111.0

- operating system: Pop!_OS 22.04 LTS

### Quarto check output

Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/jhorak/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in micromamba. Did you forget to activate it?

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by mcanouil** [comment] 2024-04-09 14:06
Thanks for the report.

Could you elaborate on the steps to reproduce? A repository for instance. Did you try on another system?
Currently, it's not enough for us to reproduce the issue.

**Comment by jimjam-slam** [comment] 2024-04-10 03:13
Just wanted to highlight issue #2716 — not sure if @walustor is using a Docker container or an actual Linux machine, but I when I used a Docker container on my M1 Mac before there were native aarch64 containers for Quarto, it would present as x64 and I would have problems with Pandoc exhausting memory, even when I just checked its version.

**Comment by walustor** [comment] 2024-04-10 08:38
I'll try to setup a minimal repo. (Unfortunately, I don't have another system to try.)

@jimjam-slam Thank you for the comment. However, I'm running it directly on a Linux machine.

**Comment by cscheid** [comment] 2024-04-19 22:21
I'd love to have a repro to make sure we found it, but I think https://github.com/quarto-dev/quarto-cli/pull/9428 will close this.

**Comment by cscheid** [comment] 2024-04-20 17:46
I'm going to go ahead and close this because I think [quarto-dev/quarto-cli#9428](https://github.com/quarto-dev/quarto-cli/pull/9428) does actually resolve the problem. If it persists and y'all find a reproducible example, please reopen it. Thanks!

**Closed by cscheid** 2024-04-20 17:46 UTC
Labels: bug, needs-repro, books
