### ISSUE TITLE
Bug on Safari: [Error] Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by netw0rkf10w** [quarto-dev/quarto-cli#5240] opened 2023-04-19 14:12 UTC
### Bug description

I created a website locally on my Mac with Quarto, and I observed that when opening it in Safari, there are some `[Error] Failed to load resource: the server responded with a status of 404 ()`. It turns out that your official website https://quarto.org also has this issue:

<img width="1440" alt="Screen Shot 2023-04-19 at 16 09 13" src="https://user-images.githubusercontent.com/8569515/233101431-bb5ef253-4c03-4588-a21a-06eec1d970a5.png">

This seems to cause some important page load speed on Safari compared to Chrome, so please consider fixing this.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by netw0rkf10w** [comment] 2023-04-19 14:36
> > This seems to cause some important page load speed on Safari compared to Chrome, so please consider fixing this.
> 
> What makes you say one is the cause for the other?

Two observations from my side:

- Loading the page on Safari is slower than on Chrome.
- There are errors when loading the page on Safari.

Thus, the errors seem to be the cause. And it seems we cannot confirm nor deny this until we have fixed those errors.

**Comment by cscheid** [comment] 2023-04-19 14:51
Sorry, but this isn't a bug.

These also appear on Chrome:
<img width="2013" alt="image" src="https://user-images.githubusercontent.com/285675/233114027-bfaed95e-4af7-4822-9e52-1681850816ea.png">

The difference is that Chrome recognizes that these are simply source maps.

I also don't see how this is possibly the cause of slowing down, so I'm going to close this. But if you find evidence that supports your causality claim, please feel free to reopen it. Thanks!

**Closed by cscheid** 2023-04-19 14:51 UTC
Labels: websites

**Comment by netw0rkf10w** [comment] 2023-04-19 15:05
> These also appear on Chrome

Not for me, but if the errors also appear on Chrome, then doesn't it mean that the issue is even worse?

**Comment by cscheid** [comment] 2023-04-19 15:35
> > These also appear on Chrome
> 
> Not for me, but if the errors also appear on Chrome, then doesn't it mean that the issue is even worse?

No. Like I said, "The difference is that Chrome recognizes that these are simply source maps." These are not files that are actually used to render the website. They are [source maps](https://developer.chrome.com/blog/sourcemaps/).
