### ISSUE TITLE
What are the plans for MS Word support going forward?

### ISSUE THREAD

**Issue by bfordAIMS** [quarto-dev/quarto-cli#6115] opened 2023-07-06 01:26 UTC
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/6114

<div type='discussions-op-text'>

<sup>Originally posted by **bfordAIMS** July  6, 2023</sup>
### Description

👋 😄 

**Context:**

I have recently moved from RMarkdown to Quarto markdown to produce reports at work (mostly scientific/data analysis reports). Some clients insist that reports are delivered to them in Docx format and my company has fairly strict guidelines for report styling. Majority of the styles can be incorporated using the docx template as instructed in the Quarto documentation. However there are a couple things which currently limit my report writing for Docx:

* Lists of tables and figures - As far as I can tell quarto does not offer much support for these.  I often need to have separate lists for the main report and appendices. This was previously possible in RMarkdown with the Officedown package.

* Cover pages - My company has a set cover section (i.e. multiple pages) which uses roman numerals as page numbers (whereas the main text uses regular number) and includes things like the authors, date, title, etc. Some of these attributes are repeated in the main section of the document.

* Yaml attributes - It would be nice to be able to access the yaml attributes (e.g. title, authors etc) within the document, with different styles in different places (e.g. large title in cover section and repeated in header). It would also be nice to define these attributes in the yaml without having them be automatically included in the document. 

**My Question:** 

I am wondering what the plans are for MS Word support in Quarto. Do you foresee large developments going forward (e.g. implementing some of the features of Officedown, cover pages, support customisation beyond the template file)? Or is this not really a priority? I can understand if this is not a high priority for Quarto, and honestly I would never use Word documents if I could help it. However, given its pervasiveness in industry, I thought I would check if support is coming before I start to hack together a solution.

Any insights here would be greatly appreciated.

Cheers!</div>

**Comment by mcanouil** [comment] 2023-07-06 05:54
Closing as duplicate of #6114

**Closed** 2023-07-06 05:54 UTC
