### ISSUE TITLE
Incorrectly specified `{leaflet}` tile provider breaks seemingly all JS components in standalone HTML

### ISSUE THREAD

**Issue by jack-davison** [quarto-dev/quarto-cli#9897] opened 2024-06-06 11:12 UTC
### Bug description

In R, if you muck up your `{leaflet}` provider, not only does the map not render (as one would expect) but it appears to break everything interactive in the report - incl. plotly graphs. This was a particularly destructive typo that cost me a lot of time trying to debug, as the document I was rendering was very big with only a couple of maps.

I'm not sure if this is an issue with Quarto or the R leaflet package.

### Steps to reproduce

````qmd
---
title: "TEST QMD"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: wrongleaflet

library(leaflet)
leaflet() |> addProviderTiles("CartoDB.Postron") ## NB - This provider is misspelled on purpose
```

```{r}
#| label: fineplotly

library(plotly)

plot_ly(iris, x = ~Sepal.Length) |> add_histogram()
```
````

### Expected behavior

I would imagine the `{leaflet}` map would look dodgy, but everything else (other maps, plotly graphs, reactable/DT tables, etc.) would render contentedly.

### Actual behavior

The plotly graphic has not rendered at all:

![image](https://github.com/quarto-dev/quarto-cli/assets/45171616/fccd43df-bacb-4c0a-a9b9-270c45b00f9f)

### Your environment

- IDE: RStudio 2024.04.1+748
- OS: Windows 10

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.13
      Path: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python39_64/python.exe
      Jupyter: 5.1.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/JD38/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment] 2024-06-06 11:36
Could you try using Quarto 1.4 at least?

**Comment by jack-davison** [comment] 2024-06-06 11:41
Certainly - that was using my work PC that IT controls. I've tried with another device running Quarto 1.4.555 and have the same issue.

```bash
Quarto 1.4.555
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.555
      Path: C:\Users\JD38\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: C:/Users/JD38/AppData/Local/Programs/Python/Python312/python.exe
      Jupyter: 5.5.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.3
      Path: C:/PROGRA~1/R/R-43~1.3
      LibPaths:
        - C:/Users/JD38/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.3/library
      knitr: 1.46
      rmarkdown: 2.26

[>] Checking Knitr engine render......OK
```

**Comment by gadenbuie** [comment] 2024-06-06 12:19
> In R, if you muck up your `{leaflet}` provider, not only does the map not render (as one would expect) but it appears to break everything interactive in the report - incl. plotly graphs. This was a particularly destructive typo that cost me a lot of time trying to debug, as the document I was rendering was very big with only a couple of maps.

Hi @jack-davison, I think that if there's something to be done here it'd have to come from the leaflet package. The problem is that leaflet (the javascript library) throws an error with the misspelled tile provider. It's a lot like throwing an error in R, when the unhandled error happens the browser stops executing the rest of the JavaScript code.

If you run into these kinds of problems where something is wrong when you open the document in the browser, you can try right clicking on the page and selecting "Inspect" or "Inspect Element" to bring up the developer console in the browser. Then click on the Console tab, where you may find logged errors:

<img width="674" alt="Screenshot of the Console tab of Chrome's developer console, where an error from leaflet providers is shown, reading 'Uncaught No such variant of CartoDB (Postron)'" src="https://github.com/quarto-dev/quarto-cli/assets/5420529/1c49af8c-45d8-40b4-9392-95f566036989">

leaflet may be able to catch this kind of error earlier, or there may be reasons why we can't validate the tile provider names. In any case, if you want to open an issue in leaflet, we'll take a look when we can.

**Comment by gadenbuie** [comment] 2024-06-06 12:22
I missed that you already opened https://github.com/rstudio/leaflet/issues/921. I think we can close this issue and see about handling this on the R side.

**Comment by cderv** [comment] 2024-06-06 15:25
Thanks @gadenbuie !

**Closed by cderv** 2024-06-06 15:25 UTC
Labels: bug
