### ISSUE TITLE
QuartoPub API errors

### ISSUE THREAD

**Issue by elchorro** [quarto-dev/quarto-cli#6654] opened 2023-08-29 19:48 UTC
### Bug description

I have previously been able to publish with Quarto Pub (elchorro.quarto.pub)  but I am now getting API error. I don't publish that much, so I am surprised to see "Too Many Requests" error.

![image](https://github.com/quarto-dev/quarto-cli/assets/13162607/8116103c-defc-4fb8-9022-6c89a43b9e88)

**Comment by mcanouil** [comment] 2023-08-29 20:12
Duplicate of:

- #6624

**Closed** 2023-08-29 20:12 UTC
Labels: duplicate
