### ISSUE TITLE
simple plotly output not rendering for HTML output

### ISSUE THREAD

**Issue by Patrikios** [quarto-dev/quarto-cli#5936] opened 2023-06-15 06:09 UTC
### Bug description

```
Quitting from lines 101-107 [XYZ] (xyz.qmd)
Error in `add_html_caption()`:
! unbenutztes Argument (xfun::grep_sub("^[^<]*<[^>]+aria-labelledby[ ]*=[ ]*\"([^\"]+)\".*$", "\\1", x))
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 14. sew(res, options)
 15. knitr:::sew.list(x, options, ...)
 16. base::lapply(x, sew, options, ...)
 17. FUN(X[[i]], ...)
 18. knitr:::sew.knit_asis(x, options, ...)
Ausführung angehalten
Fehler in close_connection() : 
  konnte Funktion "close_connection" nicht finden
Ruft auf: <Anonymous> -> <Anonymous>
```

### Steps to reproduce

I got a simple html document with knnitr engine (under R). There is this code block that does not render:

```
{r}
#| label:  "XYZ"
#| include: true
#| echo: true

library(plotly)
plot_ly(economics, x = ~pop)
```

### Expected behavior

Should render properly.

### Your environment

```
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so;  LAPACK version 3.8.0

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8     LC_MONETARY=de_DE.UTF-8   
 [6] LC_MESSAGES=de_DE.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Berlin
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
 [1] vctrs_0.6.2       knitr_1.43        httr_1.4.6        cli_3.6.1         xfun_0.39         rlang_1.1.1       purrr_1.0.1      
 [8] renv_0.17.3       generics_0.1.3    jsonlite_1.8.5    data.table_1.14.8 glue_1.6.2        colorspace_2.1-0  htmltools_0.5.5  
[15] scales_1.2.1      fansi_1.0.4       grid_4.3.0        munsell_0.5.0     tibble_3.2.1      fastmap_1.1.1     yaml_2.3.7       
[22] lifecycle_1.0.3   compiler_4.3.0    dplyr_1.1.2       htmlwidgets_1.6.2 pkgconfig_2.0.3   tidyr_1.3.0       rstudioapi_0.14  
[29] plotly_4.10.2     digest_0.6.31     viridisLite_0.4.2 R6_2.5.1          tidyselect_1.2.0  utf8_1.2.3        pillar_1.9.0     
[36] magrittr_2.0.3    tools_4.3.0       gtable_0.3.3      lazyeval_0.2.2    ggplot2_3.4.2   
```

**Comment by mcanouil** [comment] 2023-06-15 06:21
Thanks for the report.
Pretty sure it's a duplicate of:

- #5702

Could you update your Quarto version?

**Comment by Patrikios** [comment] 2023-06-15 07:35
Downgrading to knitr@1.42 worked!

**Comment by mcanouil** [comment] 2023-06-15 07:59
So definitely a duplicate.
Note that if you install 1.4 pre-release you can keep the latest knitr version.

**Closed** 2023-06-15 07:59 UTC
Labels: duplicate

**Comment by cderv** [comment] 2023-06-15 08:04
Last quarto release v1.3.361 should not lead to this error. You should check your Quarto version too

**Comment by Patrikios** [comment] 2023-06-15 08:53
I upgraded all in the RStudio Project (quarto and knitr).  The result is that I can render with the latest versions of quarto@1.3.361 and knitr@1.43 with `quarto render` however not with the built in Render button in RStudio (the same error as above). I removed the earlier version from `/usr`.

Is there any recipe to completely uninstall older quarto version of quarto, or an official repo to update with debian's `apt`?

My RStudio version is: 2023.03.0

**Comment by mcanouil** [comment] 2023-06-15 09:20
in RStudio terminal panel, what gives you `quarto check`?

**Comment by Patrikios** [comment] 2023-06-15 09:23
`quarto check`  gives:

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /home/<user>/opt/quarto-1.3.361/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.7.3
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/lib/R
      LibPaths:
        - /home/<user>/<project>/renv/library/R-4.3/x86_64-pc-linux-gnu
        - /home/<user>/.cache/R/renv/sandbox/R-4.3/x86_64-pc-linux-gnu/9a444a72
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment] 2023-06-15 12:27
@Patrikios this works for me with Quarto 1.3.361 and **knitr** 1.43

````markdown
---
title: test
engine: knitr
---

```{r}
#| label:  "XYZ"
#| include: true
#| echo: true

library(plotly)
plot_ly(economics, x = ~pop)
```
````

I would try on Terminal on your side to be sure, and then check inside R Studio. 

If you have a quarto on PATH, it should be used by RStudio IDE instead of the built it on
