### ISSUE TITLE
Quarto Book: Crossrefs not working correctly in index.qmd

### ISSUE THREAD

**Issue by meierluk** [quarto-dev/quarto-cli#9843] opened 2024-06-02 13:07 UTC
### Bug description

When using a crossref to a chapter in  `index.qmd`, e.g., `We learn more in [Chapter @sec-intro].`, the HTML output also contains the chapter name, i.e., it is rendered as "Chapter 1  Introduction". This does not happen when using a similar crossref within the file of a chapter.

### Steps to reproduce

[This](https://github.com/meierluk/quarto-test-crossref/blob/d1cf6cc975e30daa4cb870e7e0f043307706fa6e/index.qmd#L11) crossref is not rendered correctly.

When using a [similar approach](https://github.com/meierluk/quarto-test-crossref/blob/d1cf6cc975e30daa4cb870e7e0f043307706fa6e/intro.qmd#L11) within a chapter, everything works as intended.

### Expected behavior

The crossref should be "Chapter 1".

### Actual behavior

The crossref is "Chapter 1 Introduction".

### Your environment

- IDE: RStudio 2024.04.1 Build 748
- Windows 11

### Quarto check output

```
Quarto 1.4.554
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.554
      Path: C:\Users\meierluk\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\meierluk\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.0
      Path: C:/Users/meierluk/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: 4.9.2
      Kernels: julia-1.9, python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\meierluk\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\meierluk\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
[>] Checking Jupyter engine render....OK
```

**Comment by meierluk** [comment] 2024-06-03 07:31
It looks like this might be a duplicate of #9294.

**Comment by cderv** [comment] 2024-06-03 07:52
Yes this is duplicate of 
* #9294 
* #9439

I'll close this one, and you can follow resolution in the others

thanks !

**Closed by cderv** 2024-06-03 07:52 UTC
Labels: bug
