### ISSUE TITLE
collapse in revealjs not working

### ISSUE THREAD

**Issue by gdkrmr** [quarto-dev/quarto-cli#5703] opened 2023-05-26 13:12 UTC
### Bug description

The following produces a collapsed box in html but not in revealjs:
```
::: {.callout-caution collapse="true"}
## Caution

caution!!
:::
```

Manjaro Linux
quarto version 1.3.353 installed from AUR

```
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.353
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: /usr/bin/python3
      Jupyter: 4.9.2
      Kernels: julia-1.8, julia-1.7, ir, julia-1.9, python3

(\) Checking Jupyter engine render....Exception ignored in: <function BaseEventLoop.__del__ at 0x7fa214c0e8c0>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_events.py", line 690, in __del__
    self.close()
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 87, in close
    self._close_self_pipe()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 94, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 272, in _remove_reader
    key = self._selector.get_key(fd)
  File "/usr/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /home/gkraemer/progs/R/R-4.3.0
      LibPaths:
        - /home/gkraemer/progs/R/R-4.3.0/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment] 2023-05-26 13:44
Thanks for opening an issue, unfortunately, this is not a bug.
I am closing this as a duplicate of #1328[^1], please follow-up on it.

[^1]: Also discussed in #4780 and #727.

**Closed by mcanouil** 2023-05-26 13:44 UTC
Labels: bug
